### ISSUE TITLE
Extracting Grades in each cell in a submitted assignment

### ISSUE THREAD

**Issue by JimmyTree** [jupyter/nbgrader#1007]
Hi,

Is there a way where I can extract the grade of each cell that is being marked in a submitted assignment?
Currently I am using  the following piece of code to obtain the overall score in each submitted assignment.
https://nbgrader.readthedocs.io/en/stable/user_guide/advanced.html?highlight=export#getting-information-from-the-database

However, I am unable to look at the scores in each sub part. I also noticed that there is a new export function. I tried it and it also just gives me an overall score. Please shed light on this. Thank you.

**Comment by jhamrick** [comment]
I am closing this issue because there hasn't been any activity on it in a while. However, if you (or others) continue to encounter problems, feel free to comment here or open a new issue!
