### ISSUE TITLE
Is "Student ID" equivalent to the username in a Linux system?

### ISSUE THREAD

**Issue by fishfree** [jupyter/nbgrader#1011]
In the "Add new student" dialog, should I input a valid Linux username( or JupyterHub login username) as the Student ID?

**Comment by jhamrick** [comment]
If you are using JupyterHub, then yes, the student ids should correspond to JupyterHub login usernames. If you are not using JupyterHub, then they can be any id you want to use to identify students.

**Comment by fishfree** [comment]
@jasongrout Thank you!

**Comment by jhamrick** [comment]
I am closing this issue because there hasn't been any activity on it in a while. However, if you (or others) continue to encounter problems, feel free to comment here or open a new issue!
