### ISSUE TITLE
NBGrader with cling kernel

### ISSUE THREAD

**Issue by pankajkumar229** [jupyter/nbgrader#1013]
### Operating system
Linux Debian wheezy

### `nbgrader --version`
nbgrader version 0.5.4

### `jupyter notebook --version` 
5.5.0

### Expected behavior
I am using the C++ cling kernel with NbGrader and running into some issues.
1. assert(false) or another method causes 0 points and program continues. 
2. cell execution if it throws uncaught exception, lets the kernel continue

### Actual behavior
1. using the assert function in C/C++ does not cause test to fail
   assert(false) gets full credit
   I think assert in C++ cling has no effect in production mode.  There should be another method provided
2. If the execution of a cell leads to uncaught exception, cling should not hang but continue.

Problem 2 is probably a problem with the kernel.

### Steps to reproduce the behavior
Install a cling kernel  and NbGrader .
Also I use the following nbgrader_config.py :
c = get_config()
c.Exchange.course_id = "AlgoProj1"
c.Exchange.root = "/mnt/nfs/dcdemo110@gmail.com/share"
c.ExecutePreprocessor.kernel_name = "cling-cpp17"
c.ClearSolutions.code_stub = {
    "R": "# your code here\nraise NotImplementedError",
    "python": "# your code here\nraise NotImplementedError",
    "javascript": "// your code here, make sure it compiles or no grade for the whole notebook\n return 0;",
    "C++": "// your code here\n throw NULL;"
}

**Comment by sigurdurb** [comment]
Maybe this is something you should open on the quantstack cling repo because the assert(false) is just the behaviour you would get in a normal C++ jupyter notebook cell, nbgrader works if there is an exception thrown:
For example you could set your tests up like this:
```
try{
    posPow(-1);
    throw "ExceptionNotThrownError";
} catch(std::invalid_argument){}

// BEGIN HIDDEN TESTS
if (posPow(9) != 81){
    throw "IncorrectError";
}
if (posPow(99) != 9801){
    throw "IncorrectError";
}
// END HIDDEN TESTS
```

**Comment by datacabinet** [comment]
Hi, I am using the C++ kernel integrated with root cling repo. The kernel dies if there is an uncaught exception leaving the cell. In regular C++, if exception is uncaught, it causes the process to exit. What should the behavior be for Jupyter and NBGrader? Could there be a particular type of exception that can be raised from C++ that can be caught when running under NBGrader and ignored?

**Comment by pankajkumar229** [comment]
Hi, I am using the C++ kernel integrated with root cling repo. The kernel dies if there is an uncaught exception leaving the cell. In regular C++, if exception is uncaught, it causes the process to exit. What should the behavior be for Jupyter and NBGrader? Could there be a particular type of exception that can be raised from C++ that can be caught when running under NBGrader and ignored?

**Comment by jhamrick** [comment]
This is unfortunately not something that we can handle specifically in nbgrader, which just checks whether there is an "error" output on the cell or not. The error output is put there if, when executing the kernel (which is done by nbconvert rather than nbgrader), the kernel sends an error message kernel reply. So it is up to the kernel to send this message. (It is up to the C++ kernel mainainters to decide what to do when an error occurs---but perhaps they could add an option to ignore the error rather than exiting the process to enable it to work better with nbgrader)

See related discussion here: https://github.com/jupyter/nbgrader/issues/986

**Comment by pankajkumar229** [comment]
Thanks! We will try fix and submit a patch to the cling kernel.

**Comment by sigurdurb** [comment]
@pankajkumar229 The same problem exists with the Octave kernel [https://github.com/Calysto/octave_kernel](https://github.com/Calysto/octave_kernel)
Maybe you can strike two birds with one stroke if you are looking at a fix for the cling kernel.
## Example Octave problem on the students side
```
% ngrader autograder answer cell
function retval = myfunc (arg)
  retval = arg**1
endfunction
```
```
% nbgrader autograde cell
assert (myfunc(0) == 0)
assert (myfunc(2) == 4)
```
### Unexpected behaviour when student presses Validate button -> "Success all tests pass" when clearly there are Errors:
<img width="572" alt="screen shot 2018-10-17 at 20 35 10" src="https://user-images.githubusercontent.com/10588202/47114722-30a0eb80-d24c-11e8-874e-0aa014fa0405.png">

**Comment by blink1073** [comment]
The issue we have with the Octave kernel is that we are communicating with the Octave process using a pty, which conflates stderr and stdin.  You could in theory use a regex to determine what is an "error", if someone wanted to pursue that path.

**Comment by pankajkumar229** [comment]
It seems to be a little easier for C++ kernel: https://github.com/root-project/cling/pull/272 . I will let you know if it gets accepted. We still have the infinite loop problem. If there is too much traffic with a infinite print statement, maybe Jupyter needs a method to disable that.

**Comment by SylvainCorlay** [comment]
@pankajkumar229 you may be interested in trying out the xeus-cling kernel which also supports rich display and interactive widgets!

**Comment by datacabinet** [comment]
I thought they were the same thing. Do you know what the relationship is between the two projects?

**Comment by SylvainCorlay** [comment]
@datacabinet both are based on the cling C++ interpreter.

- the kernels included in root and cling are based on `ipykernel`, the reference python implementation of the Jupyter protocol, which wraps calls to cling and composes the messages

- `xeus` is a C++ implementation of the protocol, which can be used to make kernels. xeus-cling is the C++ kernel based on xeus, xeus-python is a new Python kernel based on xeus. For the cling kernel benefits is that it can do more than just retrieving the text output. It really uses cling as a library and inspect the AST for returned expressions using cling APIs, enabling rich content (images, widgets). Another advantage is that the resulting kernel does not depend on a python runtime. It is simply an executable.

**Comment by nthiery** [comment]
I can confirm that nbgrader works very smoothly with xeus-cling. Maybe this issue can be closed? This is really a bug of the plain cling kernel.

**Comment by jhamrick** [comment]
Yes, makes sense to close I think, thanks for confirming @nthiery that it works with xeus-cling at least!
