### ISSUE TITLE
Update documentation links.

### ISSUE THREAD

**Issue by Carreau** [jupyter/nbgrader#1015]
Many links in the documentation are 404 (for example) continuum is now anaconda, and make th test fails. 

It should be easy to either update the links, or remove rephrase the corresponding sections.

**Comment by amrs-tech** [comment]
I'll try to sort out this issue. Can you please assign it to me?

**Comment by amrs-tech** [comment]
Can you please mention the file(s) which is to be updated ?

**Comment by Carreau** [comment]
If you look at some of the latest [tests of the Documentation Build](https://travis-ci.org/jupyter/nbgrader/jobs/433069483), you will see near to the end that many links are red with reason as to why. 

I see that someone submitted #1016, so check the latest tests

**Comment by mathagician** [comment]
I would like to pick some. Could please help and suggest how and which one to take.

**Comment by mddarmawan** [comment]
@Carreau me too. Would you please mention me the files which is to be updated?

**Comment by stvmachine** [comment]
@Carreau hi, i would love to help too

**Comment by jhamrick** [comment]
This has been fixed by #1016 and #1017
