### ISSUE TITLE
Document how to access the formgrader when it is a JupyterHub service

### ISSUE THREAD

**Issue by jnak12** [jupyter/nbgrader#1034]
### Operating system
FreeBSD 11.2 64 bit
### `nbgrader --version`
5.4
### `jupyterhub --version` (if used with JupyterHub)
0.9.4
### `jupyter notebook --version` 
5.7
### database
postgresql 10.5

Hi,

I have created a course account and two other user accounts.
JupyterHub has been set up as a  managed shared notebook to the course account
with the two users as part of the group.

An assignment was set up in the course account.  It has been released within the course account.

When i log into one of the two user accounts and get into formgrader tab:
1) The created assignment shows up (manage assignments), but when i click on the assignment, i get a
"File not found 404" error.
2) When i click on the manual grading, the assignment shows up and clicking on the assignment, the notebook file shows up.
3) When i click on the manage students, i can see all the students and can add and edit them.

If i try to generate or release the assignment, i get a permission error, but i thought the
idea of the shared notebook is to eliminate permission errors.
Everything works okay in the course account, just not in the other accounts set up for sharing.

Any help would be great,
cheers,
john

Here are some logfiles:
Trying to generate the assignment:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nbgrader/utils.py", line 371, in capture_log
    app.start()
  File "/usr/local/lib/python3.6/site-packages/nbgrader/converters/assign.py", line 146, in start
    super(Assign, self).start()
  File "/usr/local/lib/python3.6/site-packages/nbgrader/converters/base.py", line 72, in start
    self.convert_notebooks()
  File "/usr/local/lib/python3.6/site-packages/nbgrader/converters/base.py", line 332, in convert_notebooks
    _handle_failure(gd)
  File "/usr/local/lib/python3.6/site-packages/nbgrader/converters/base.py", line 260, in _handle_failure
    rmtree(dest)
  File "/usr/local/lib/python3.6/site-packages/nbgrader/utils.py", line 245, in rmtree
    shutil.rmtree(path)
  File "/usr/local/lib/python3.6/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/lib/python3.6/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/local/lib/python3.6/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'a1_prob.ipynb'

Permissions:
$ ls -laR /srv/nbgrader/exchange
total 24
drwxrwxrwx  3 root    wheel  512 Oct 26 15:08 .
drwxr-xr-x  3 root    wheel  512 Oct 25 16:05 ..
drwxr-xr-x  4 course  wheel  512 Oct 26 15:08 test_course

/srv/nbgrader/exchange/test_course:
total 32
drwxr-xr-x  4 course  wheel  512 Oct 26 15:08 .
drwxrwxrwx  3 root    wheel  512 Oct 26 15:08 ..
drwxr-xr-x  2 course  wheel  512 Oct 26 15:08 inbound
drwxr-xr-x  3 course  wheel  512 Oct 26 15:11 outbound

/srv/nbgrader/exchange/test_course/inbound:
total 16
drwxr-xr-x  2 course  wheel  512 Oct 26 15:08 .
drwxr-xr-x  4 course  wheel  512 Oct 26 15:08 ..

/srv/nbgrader/exchange/test_course/outbound:
total 24
drwxr-xr-x  3 course  wheel  512 Oct 26 15:11 .
drwxr-xr-x  4 course  wheel  512 Oct 26 15:08 ..
drwxr-xr-x  2 course  wheel  512 Oct 26 15:08 assg1

/srv/nbgrader/exchange/test_course/outbound/assg1:
total 24
drwxr-xr-x  2 course  wheel   512 Oct 26 15:08 .
drwxr-xr-x  3 course  wheel   512 Oct 26 15:11 ..
-rw-r--r--  1 course  wheel  2458 Oct 26 15:08 a1_prob.ipynb

Permissions in the course account:
/home/course/test_course:
total 48
drwxr-xr-x  4 course  course   512 Oct 26 14:39 .
drwxr-xr-x  6 course  course   512 Oct 26 13:41 ..
-rw-r--r--  1 course  course  5614 Oct 26 15:27 .nbgrader.log
drwxr-xr-x  3 course  course   512 Oct 26 15:08 release
drwxr-xr-x  3 course  course   512 Oct 26 13:39 source

/home/course/test_course/release:
total 24
drwxr-xr-x  3 course  course  512 Oct 26 15:08 .
drwxr-xr-x  4 course  course  512 Oct 26 14:39 ..
drwxr-xr-x  2 course  course  512 Oct 26 15:08 assg1

/home/course/test_course/release/assg1:
total 24
drwxr-xr-x  2 course  course   512 Oct 26 15:08 .
drwxr-xr-x  3 course  course   512 Oct 26 15:08 ..
-rw-r--r--  1 course  course  2458 Oct 26 15:08 a1_prob.ipynb

/home/course/test_course/source:
total 24
drwxr-xr-x  3 course  course  512 Oct 26 13:39 .
drwxr-xr-x  4 course  course  512 Oct 26 14:39 ..
drwxr-xr-x  3 course  course  512 Oct 26 14:38 assg1

/home/course/test_course/source/assg1:
total 32
drwxr-xr-x  3 course  course   512 Oct 26 14:38 .
drwxr-xr-x  3 course  course   512 Oct 26 13:39 ..
drwxr-xr-x  2 course  course   512 Oct 26 14:38 .ipynb_checkpoints
-rw-r--r--  1 course  course  2190 Oct 26 14:37 a1_prob.ipynb

/home/course/test_course/source/assg1/.ipynb_checkpoints:
total 24
drwxr-xr-x  2 course  course   512 Oct 26 14:38 .
drwxr-xr-x  3 course  course   512 Oct 26 14:38 ..
-rw-r--r--  1 course  course  2190 Oct 26 14:37 a1_prob-checkpoint.ipynb

jupyterhub_config.py:

service_name = 'shared_notebook'
service_port = 9999

c.JupyterHub.services = [
   {
      'name':'cull_idle',
      'admin' : True,
      'command':'python3 ./cull_idle_servers.py --timeout=3600'.split()
   },
   {
      'name' : service_name,
      'url' : 'http://127.0.0.1:{}'.format(service_port),
      'command' : ['jupyterhub-singleuser',
                   '--group={}'.format(grp_name),
                   '--debug'
                  ],
      'user' : 'course',
      'cwd'  : '/usr/home/course/test_course'
   }
]

nbgrader config file:
c.CourseDirectory.root = '/usr/home/course/test_course'
c.Exchange.course_id = 'test_course'

**Comment by jhamrick** [comment]
If I understand the issue correctly, I think the problem is that your files need to be owned by the user that's running the shared notebook server. The idea is that multiple users will be able to log into the nbgrader service, but the service itself owns the files. See here for an example: https://nbgrader.readthedocs.io/en/master/configuration/jupyterhub_config.html#example-use-case-one-class-multiple-graders

**Comment by jnak12** [comment]
"course" is the account that has all the course information in it.
I did an htop and there is a process owned by "course" that 
has jupyterhub-singleuser --group=shared --debug 
which matches the above jupyterhub_config.py file.
All the files are owned by "course".

I logged into another account ("stud1") that is part of the "shared" group and noticed that
when i click on the Formgrader tab, the URL is .../user/stud1/formgrader.  
Is this correct?  I'm thinking it should be .../user/course/formgrader if the service is 
associated with the "course" account.

The "File not found" error stems from this as well.  
The path is .../user/stud1/course/test_course/course/assg1
which does not exist because all of the info is in .../user/course.

**Comment by jhamrick** [comment]
Thanks for the response, that helps clarify things for me! So it sounds like you've installed the formgrader extension for the other accounts (e.g. `stud1`) and are trying to access the formgrader using the tab that appears in the notebook list---is that correct?

If so, then the reason things aren't working properly is because that's not how the formgrader is meant to be accessed in the case where it corresponds to its own user account. Specifically, the formgrader extension should only be installed for the `course` user, not other users on the system. This means that those users won't see the formgrader tab in the notebook list. Instead, to access the formgrader they will need to manually go to the url `/services/shared_notebook` which will load the notebook list for the shared notebook server, from which they can then click on the "formgrader" tab and access the formgrader.

I realize this isn't actually in the documentation I linked to, but it definitely should be.

Related: #1060

**Comment by jnak12** [comment]
SUCCESS!
Yes i did install formgrader in the stud1 account.
The key piece of info was to put  /services/<name of the service> at the end of the 
login URL (e.g. https://URL/services/shared_notebook in my case).
Once I did that, everything worked fine
Thanks.

**Comment by jhamrick** [comment]
I think with #1140, #1114, and #1113 this is now addressed.
