### ISSUE TITLE
Use Nbgrader without a DB in simplest way possible

### ISSUE THREAD

**Issue by AKuederle** [jupyter/nbgrader#1041]
I am trying to use nbgrader for a course I am supervising. However, due to logistics of the course I only need a very small subset of the available features.

Specifically, I just want to generate an assignment version of my notebooks, without any added features. Meaning, I just want to strip the solution blocks and potentially hide specific test cells.

What would be the easiest way to do this? The `assign` command has a flag to not store any information in the database, but even with this flag nbgrader assumes a certain directory structure and a config file.
Is it possible to just convert one notebook with a single command and no further setup?

Thanks in advance!

**Comment by jhamrick** [comment]
This isn't supported directly by nbgrader, but it should be possible to do with nbconvert by requesting that it use the relevant nbgrader preprocessors:

* IncludeHeaderFooter
* ClearSolutions
* LockCells
* ClearOutput
* ClearHiddenTests

I believe @choldgraf has implemented something like this?

**Comment by AKuederle** [comment]
@choldgraf @jhamrick Thank you very much for your input! `nbclean` looks exactly like the tool I was looking for!
