### ISSUE TITLE
Public side-effects of running tests

### ISSUE THREAD

**Issue by jedbrown** [jupyter/nbgrader#1046]
Running the test suite currently tries to create/modify a `sitecustomize.py` in a system path. This file is often not owned by the user and in any case, has public side-effects if other python programs run while the tests run. Instead of these manipulations in `tasks.py`, I think it would be preferable to just have a static file in the nbgrader source and add its directory to PYTHONPATH. Do you foresee any problems with this?

Cc: https://github.com/openjournals/jose-reviews/issues/32

**Comment by willingc** [comment]
Yeah, it would be good to remove the usage of `sitecustomize.py`. Probably makes sense to refactor the test runs as well. It would be nice to remove the dependency on invoke too.

**Comment by jhamrick** [comment]
Agreed, all that stuff is there back from when we were running a lot of subprocesses in the tests which weren't by default getting test coverage. But I think that shouldn't be an issue anymore, so we can remove everything having to do with sitecustomize.py.

I'm fine removing the dependency on invoke, too---it's pretty lightweight at this point and we could do everything just with standard argument parsing I think.

**Comment by willingc** [comment]
Nicely done @jhamrick :cake:
