### ISSUE TITLE
Non-Deterministic Behavior of Validate when Exceptions are Thrown

### ISSUE THREAD

**Issue by samuelmanzer** [jupyter/nbgrader#1056]
### Operating system
```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### `nbgrader --version`

```
 nbgrader --version
Python version 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:39:56)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
nbgrader version 0.5.4
```

### `jupyterhub --version` (if used with JupyterHub)
```
# jupyterhub-singleuser --version
0.9.4
```

### `jupyter notebook --version` 

```
jupyter notebook --version
5.7.0
```

### Expected behavior

`nbgrader validate` succeeds every time

### Actual behavior

`nbgrader validate` fails erroneously and non-deterministically a subset of the times that it is run. 

### Steps to reproduce the behavior

Running `nbgrader validate` on the notebook below can reproduce the behavior: 

```
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "this_variable_should_equal_two = 3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "deletable": false,
    "editable": false,
    "nbgrader": {
     "checksum": "9361fcebce88eee35b14bede71b677bd",
     "grade": false,
     "grade_id": "cell-c50796410e27c65c",
     "locked": true,
     "schema_version": 1,
     "solution": false
    },
    "tags": [
     "raises-exception"
    ]
   },
   "outputs": [],
   "source": [
    "assert this_variable_should_equal_two == 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "deletable": false,
    "nbgrader": {
     "checksum": "e10187840830d5f693cddae9ea7cb4e9",
     "grade": false,
     "grade_id": "currency-conversion",
     "locked": false,
     "schema_version": 1,
     "solution": true
    }
   },
   "outputs": [],
   "source": [
    "amount_eur = 160\n",
    "exchange_rate = 1.15\n",
    "amount_usd = amount_eur * exchange_rate"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "deletable": false,
    "editable": false,
    "nbgrader": {
     "checksum": "eb9129a1d61649cdebab68fa5269f91b",
     "grade": true,
     "grade_id": "currency-conversion-tests",
     "locked": true,
     "points": 1,
     "schema_version": 1,
     "solution": false
    }
   },
   "outputs": [],
   "source": [
    "assert amount_eur == 160\n",
    "assert exchange_rate == 1.15\n",
    "assert amount_usd == 184"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

You may need to run it repeatedly to see the non-determinism:

```
for i in {1..100}; do nbgrader validate 01_python_interpreter.ipynb 2>&1 | grep -i VALIDATION; done
```

### Followups

So I think I  may have figured out the root cause, but I do not know how to best apply the fix. This file is the culprit: 

```
/opt/conda/lib/python3.6/site-packages/jupyter_client/client.py
```

this is the offending method:

```
    def execute(self, code, silent=False, store_history=True,
                user_expressions=None, allow_stdin=None, stop_on_error=True):
```

When I manually edit the source of this module and change `stop_on_error=True` to `stop_on_error=False`, deterministic behavior is restored and `nbgrader validate` returns success every time, as it should. 

There does not seem to be any pathway by which the default `True` value of the `stop_on_error` kwarg is overridden by nbgrader - the setting `ExecutePreprocessor.allow_errors` does not seem to affect this. I think that in some subset of the runs, the ZeroMQ messages for multiple cells reside simultaneously on the execution stack, and `stop_on_error=True` results in the cell containing the assignment statements being thrown away as it is on the stack when the earlier (deliberate) `AssertionError` exception causes the stack to be discarded. The subsequent assertion which depends on that assignment statement executing successfully then fails. 

The reason this seemly arcane case matters in practice is because in introductory lessons I find it useful to deliberately trigger errors in order to train the students to debug their code; however, these errors then introduce non-determinism into the validation results via the mechanism described above. 

I would like to perform some sort of monkeypatch of `jupyter_client` to make `stop_on_error=False`, but the traitlets architecture is confusing to me. If anyone can provide an example of how to monkey-patch this method that does not throw traitlet-related exceptions, I think I could take this the rest of the way and fix this in a PR.

**Comment by samuelmanzer** [comment]
Note also that any time of exception (not just an `AssertionError`) can trigger this non-determinism, for example the following notebook is also a good test case, though again you may have to run this multiple times in order to reproduce the error - it seems to trigger more reliably when 'validate' is called from the jupyter the UI, not the command line: 

```
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "deletable": false,
    "editable": false,
    "nbgrader": {
     "checksum": "9361fcebce88eee35b14bede71b677bd",
     "grade": false,
     "grade_id": "cell-c50796410e27c65c",
     "locked": false,
     "schema_version": 1,
     "solution": false
    },
    "tags": [
     "raises-exception"
    ]
   },
   "outputs": [],
   "source": [
    "this_is_undefined"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "deletable": false,
    "nbgrader": {
     "checksum": "e10187840830d5f693cddae9ea7cb4e9",
     "grade": false,
     "grade_id": "currency-conversion",
     "locked": false,
     "schema_version": 1,
     "solution": true
    }
   },
   "outputs": [],
   "source": [
    "amount_eur = 160\n",
    "exchange_rate = 1.15\n",
    "amount_usd = amount_eur * exchange_rate"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "deletable": false,
    "editable": false,
    "nbgrader": {
     "checksum": "eb9129a1d61649cdebab68fa5269f91b",
     "grade": true,
     "grade_id": "currency-conversion-tests",
     "locked": true,
     "points": 1,
     "schema_version": 1,
     "solution": false
    }
   },
   "outputs": [],
   "source": [
    "assert amount_eur == 160\n",
    "assert exchange_rate == 1.15\n",
    "assert amount_usd == 184"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

**Comment by jhamrick** [comment]
Hmm, interesting, thanks for tracking this down! I think the right way to fix this is to actually make a change in nbconvert, rather than nbgrader itself. Specifically, the call to the kernel client happens here:

https://github.com/jupyter/nbconvert/blob/master/nbconvert/preprocessors/execute.py#L438

Which just relies on all the default arguments. However, the execute preprocessor already has an option for `allow_errors`. So probably what should happen is the line I pasted above should be:

```
msg_id = self.kc.execute(cell.source, stop_on_error=not self.allow_errors)
```

although I am not 100% sure. I think it is probably worth opening up an issue about this on the nbconvert repo and making a PR there---do you want to do this?

**Comment by jhamrick** [comment]
I have made https://github.com/jupyter/nbconvert/pull/1040 with the change I suggested, though I should note when running the notebook you provided I wasn't actually able to reproduce the error... I suspect because this is a race condition that my particular machine configuration just doesn't reveal it. Would you be able to test on your machine and see if it fixes it for you?

**Comment by samuelmanzer** [comment]
Thank you! This is a minor miracle - back around when this was filed I had made a rather horrifying hack that was unsuitable for a PR, hacked it into my docker image, and then become distracted with other things. Just today it occurred to me that I should check on this and lo and behold you fixed it yesterday. Some coincidence!  I will test on my machine tomorrow and report back.

**Comment by samuelmanzer** [comment]
So this is hard to reproduce outside of prod but I got 3 manifestations of this bug out of 5000 runs on my 2014 macbook (using `nbconvert==5.5.0`):

```
for i in {1..5000}; do nbgrader validate test.ipynb 2>&1 | grep -C 15 -i VALIDATION; done
```

```
VALIDATION FAILED ON 1 CELL(S)! If you submit your assignment as it is, you WILL NOT
...
VALIDATION FAILED ON 1 CELL(S)! If you submit your assignment as it is, you WILL NOT
...
VALIDATION FAILED ON 1 CELL(S)! If you submit your assignment as it is, you WILL NOT
...
```

I then applied your [commit](https://github.com/jupyter/nbconvert/commit/d7e71240035ee13488ae57bf2b77c5af7dd4fbab) thus:

```
pip install git+git://github.com/jupyter/nbconvert.git@d7e71240035ee13488ae57bf2b77c5af7dd4fbab
```

Looks like it works:

```
pip freeze | grep -i nbconvert
nbconvert==5.5.0.dev0
```

And now running this gives no errors whatsoever:

```
for i in {1..5000}; do nbgrader validate test.ipynb 2>&1 | grep -C 15 -i VALIDATION; done
```

Looks fixed!

**Comment by samuelmanzer** [comment]
thanks!

**Comment by jhamrick** [comment]
Awesome, glad to hear it is fixed for you. Thanks for testing!
