### ISSUE TITLE
Trying to install dev version of nbgrader in Docker

### ISSUE THREAD

**Issue by ttimbers** [jupyter/nbgrader#1062]
I am trying to install the dev version of nbgrader in a Docker image for use with Jupyterhub. I get this error when I try:

```
The directory '/home/jupyter/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/jupyter/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
```

### Operating system
This docker stack: https://github.com/UBC-DSCI/docker-stacks

And specifically, this Dokerfile:

```
FROM ubcdsci/r-dsci-100

# Install nbgrader for grading
USER root
RUN git clone https://github.com/jupyter/nbgrader
RUN cd nbgrader && pip install -r dev-requirements.txt -e .
RUN jupyter nbextension install --sys-prefix --py nbgrader --overwrite
RUN jupyter nbextension enable --sys-prefix --py nbgrader
RUN jupyter serverextension enable --sys-prefix --py nbgrader

# switch back to jupyter user
USER jupyter
```

### `nbgrader --version`
https://nbgrader.readthedocs.io/en/latest/contributor_guide/installation_developer.html (I think 0.6.0.dev)

### Steps to reproduce the behavior
Building that dockerfile....

**Comment by sigurdurb** [comment]
How are you managing nbgrader to communicate with Jupyterhub, as per the shared file system thing for example?

Maybe [this pull request on dockerspawner](https://github.com/jupyterhub/jupyterhub-deploy-teaching/pull/99) on the Jupyterhub-deploy-teaching repo could help you on your path.

**Comment by jhamrick** [comment]
Were you able to figure out the issue here? My guess is that what's happening is that the `.pip` folder is owned by the `jupyter` user but you're trying to install nbgrader under the `root` user, which causes issues. You could try:

1. `chown -R` the `.pip` folder to root before installing nbgrader, and then `chown -R` it back
2. Install nbgrader with the `jupyter` user

Probably the second option is better, but I guess you're probably not doing that because it doesn't work either?

**Comment by jhamrick** [comment]
I am closing this issue because there hasn't been any activity on it in a while. However, if you (or others) continue to encounter problems, feel free to comment here or open a new issue!
