### ISSUE TITLE
Implement support for nbgrader in JupyterLab

### ISSUE THREAD

**Issue by alirezamecheng** [jupyter/nbgrader#1063]
Hello,
I saw a video about using nbgrader, and it seems that you have done a great job. 
I was wondering if it is possible to install nbgrader extension for `JupyterLab` within the jupyterhub?
Can you please help me, how to do that?
thanks for your time.

**Comment by leonsp** [comment]
I second this question.

**Comment by jhamrick** [comment]
Unfortunately at the moment JupyterLab support is not yet available.

**Comment by jhamrick** [comment]
I am going to close this as a duplicate of #1006
