### ISSUE TITLE
Question / Taskview for grading

### ISSUE THREAD

**Issue by tmetzl** [jupyter/nbgrader#1065]
Hello,

we are working with nbgrader at our university and the graders have requested a different view for grading.
Instead of showing a whole notebook we want to only show certain cells (e.g. all with the keyword 'Task1' in the grade_id). The result should be a view where the grader only sees one specific task consisting of one cell stating the task, one cell showing the students answer and if applicable one cell with tests.

To achieve this I used a specific naming scheme when creating the assignment, where all cells belonging to the first task have the keyword Task1 in it, all cells belonging to the second task have the keyword Task2, etc.

Then I created a custom preprocessor for nbconvert that excludes all cells that don't have the keyword in the grade_id. 

    from nbconvert.preprocessors import Preprocessor

    class FilterCellsById(Preprocessor):
        
        def filter_cells(self, cells, keyword):
            new_cells = []
            for cell in cells:
                metadata = cell['metadata']
                if ('nbgrader' in metadata) and \
                   ('grade_id' in metadata['nbgrader']):
                    if keyword in metadata['nbgrader']['grade_id']:
                        new_cells.append(cell)
            return new_cells
    
        def preprocess(self, nb, resources):
            if 'keyword' in resources:
                nb.cells = self.filter_cells(nb.cells, resources['keyword'])
            return nb, resources

I added this to the config in the formgrader.py:

    def build_extra_config(self):
        extra_config = super(FormgradeExtension, self).build_extra_config()
        extra_config.HTMLExporter.template_file = 'formgrade'
        extra_config.HTMLExporter.template_path = [handlers.template_path]

        # Register the cell filter
        extra_config.HTMLExporter.preprocessors = [FilterCellsById]
        return extra_config

Now I basically copied over the SubmissionHandler from the handlers.py and exposed it at `formgrader/test_submission/<submission_id>/<filter>/`. Additionally I added the filter to the resources that are passed to the exporter.

So when I type in that URL for a certain submission it works as expected and only shows cells that have the specified filter keyword.

My problem now is that the URL is changed to `formgrader/submissions/<submission_id>/` instead of staying at the URL I typed in. This redirect is happening at the `self.write(html)` step in the handler (I tested by exchanging the html with a random string, then it stays at the first URL).

Could someone tell me how I can avoid this redirect and where it is actually happening (in the jinja templates or the javascript files?).

Eventually I want to have the same navigation view as the formgrader has now, just with an added filter that stays active when I change between submissions by clicking the next and prev buttons.

Thank you very much

EDIT: I changed the question to make it clearer what I want and what I have done so far

**Comment by jhamrick** [comment]
I think the place where the URL is getting overwritten is here: https://github.com/jupyter/nbgrader/blob/master/nbgrader/server_extensions/formgrader/static/js/formgrade.js#L126

which is called here: https://github.com/jupyter/nbgrader/blob/master/nbgrader/server_extensions/formgrader/static/js/formgrade.js#L272

This is used by the formgrader to keep track of which field is currently selected, so that you can easily navigate between submissions while staying on the same question. I think if you modify the javascript to keep track of the current filter and then update the `navigateTo` function to include the filter URL that may fix the issue.

**Comment by jhamrick** [comment]
I am closing this issue because there hasn't been any activity on it in a while. However, if you (or others) have any further questions, feel free to comment here or open a new issue!
