### ISSUE TITLE
Running nbgrader as an external service

### ISSUE THREAD

**Issue by ianalis** [jupyter/nbgrader#1068]
I want to deploy nbgrader for multiple classes with multiple graders. According to the [documentation](https://nbgrader.readthedocs.io/en/latest/configuration/jupyterhub_config.html), I should create a shared notebook server in order to do that. Since my deployment runs on top of kubernetes, I need to make it an external service rather than a managed one. 

Now, looking at the [example code](https://github.com/jupyterhub/jupyterhub/blob/master/examples/service-notebook/external/shared-notebook-service), it seems that I only have to call `jupyterhub-singleuser --group` with three environment variables (`JUPYTERHUB_API_TOKEN`, `JUPYTERHUB_SERVICE_URL`, `JUPYTERHUB_SERVICE_NAME`). However, when I run the command with the three variables, `jupyterhub-singleuser` throws a `oauth_client_id cannot be empty` error. After further investigation, I was able to make it run by specifying adding the environment variables `JUPYTERHUB_CLIENT_ID` and `JUPYTERHUB_API_URL`.

Here are my questions:
* Are the two variables that I added (`JUPYTERHUB_CLIENT_ID` and `JUPYTERHUB_API_URL`) really required?
* My understanding is that in terms of execution, the external notebook service and jupyterhub are independent so I can start them in any order. Is this correct?

**Comment by jhamrick** [comment]
Hi @ianalis , I have not been using JupyterHub as much recently so I'm unfortunately not really sure of the answers to your questions---I'd recommend asking these in the JupyterHub repo where hopefully others can be of more help!

**Comment by jhamrick** [comment]
I am going to close this since it's more a question about JupyterHub than nbgrader, but if you have any issues setting up nbgrader specifically feel free to open a new issue specific to that!
