### ISSUE TITLE
Editing test cases for grading

### ISSUE THREAD

**Issue by andrew-cui** [jupyter/nbgrader#1069]
### Operating system
Mac OS X 10.14.3, running on an AWS EC2 instance

### `nbgrader --version`
0.5.4

### `jupyterhub --version` (if used with JupyterHub)
0.9.4

### `jupyter notebook --version` 
5.7.4 

### Expected behavior
After releasing homework, decided to make the test cases more permissive (such as increasing margin of error) and changed a typo. Did this on the source directory in our EC2, which is in the same bucket as the submitted and autograded. The hope is that since we are changing hidden tests, when we autograde the assignments then it does so with the updated source files (and changed test cases).

### Actual behavior
The test cases appear to have not been changed at all. I know read-only cells are saved in db at time of nbgrader assign, but is it possible to get the test cases allowed to be changed from the admin/instructor side? We are not changing cell IDs or other metadata, just a couple values in the tests.

### Steps to reproduce the behavior
Edit a test case in source, nbgrader autograde, look at formgrader/JupyterHub test case feedback output and find test cases are different

**Comment by andrew-cui** [comment]
Workaround:

nbgrader db assignment remove
nbgrader db assignment add
nbgrader assign
nbgrader release

**Comment by jhamrick** [comment]
For future reference, I think you can do this without needing to explicitly remove the assignment from the database:

```
nbgrader assign --force
```

You also shouldn't need to re-release it (that only sends the assignments to students, and they do not see the hidden tests anyway).

**Comment by lucadealfaro** [comment]
Suppose I do nbgrader assign --force, but DO NOT give the new assignment to the students, but rather let them turn in the old one. 

When the students turn in their solutions (based on the older version of the tests) and I run nbgrader autograde, will it work?  Will it be using the new version of the tests?

**Comment by alessandrozocca** [comment]
> When the students turn in their solutions (based on the older version of the tests) and I run nbgrader autograde, will it work? Will it be using the new version of the tests?

The thumbs up to @lucadealfaro question means the answer to his question is "yes"?
