### ISSUE TITLE
The autograder does not render plots at all.

### ISSUE THREAD

**Issue by bennomeier** [jupyter/nbgrader#1070]
First of all a huge thank you for nbgrader, it is incredibly useful!

I have a problem with manually grading plots (created with matplotlib.pyplot): They don't show at all in the autograded notebooks. So I have to open each notebook, run the students' code and then put the mark in the autograded notebook. This workflow is ok for me, but the students will not see their actual plot in the feedback, which is non-ideal. Changing the notebook to trusted does not seem to help.

Can anyone help?

**Comment by bennomeier** [comment]
This is not an issue if
%matplotlib inline

is included in the notebooks. 

But note that this line is not required to show plots inline, at least not with the version of Jupyter / Anaconda the students were using.

**Comment by jaspervdh96** [comment]
Why not put '%matplotlib inline' in a Read-Only Cell, so you are sure it will be in it? Or add that in a read only cell after you already released? Then they won't see it and won't get confused.

**Comment by bennomeier** [comment]
Yes, this is a good workaround. I'll close this issue.

**Comment by mcourteaux** [comment]
Just pointing out that `%matplotlib inline` does work for me, while `%matplotlib notebook` does not. Do not be confused by the two.
