### ISSUE TITLE
Better document how to setup multiple nbgrader_config.py files in JupyterHub

### ISSUE THREAD

**Issue by rgerkin** [jupyter/nbgrader#1072]
### `nbgrader --version`
0.5.5

### `jupyterhub --version` (if used with JupyterHub)
0.9.4

### `jupyter notebook --version` 
5.7.4

### Expected behavior
Assignment listing tab should use my `nbgrader_config.py`, and not try to use the default exchange directory.  

### Actual behavior
Assignment listing tab doesn't use my `nbgrader_config.py`, and does use the default exchange directory.  Formgrader successfully uses my `nbgrader_config.py`.  Also, I can run `nbgrader list --debug` and confirm that it is able to find and list my assignments in the terminal.  So I'm not sure why the assignments tab is not able to find it (or is but isn't using it).  

### Steps to reproduce the behavior
All the ones from the documentation.  I am using JupyterHub, and my main `nbgrader_config.py` is in ~/.jupyter (same for every user), and contains a `c.CourseDirectory.root = 'path/to/my/course', and that directory in turn has the larger, shared `nbgrader_config.py` file which contains the correct exchange server path (not the default one).  

I am currently working around this by just sym-linking the correct exchange path into the default `/srv/nbgrader/exchange` one, but I don't understand why the assignments tab is not honoring the location in my actual config.

**Comment by jhamrick** [comment]
So just to clarify, the `~/.jupyter/nbgrader_config.py` does not contain the path for the exchange directory? If you add that config option to that file, does it work then? (It seems to work when I do this, but not when I have the exchange only in the course directory).

For now I hope that can fix it, but there could definitely be a bit more clever loading of configs here such that the `nbgrader_config.py` in `CourseDirectory.root` is always loaded as well.

**Comment by rgerkin** [comment]
My memory is vague on this now, but I think that is right, and I didn't put the exchange directory in each user's nbgrader_config.py, perhaps because I was trying to obfuscate it from mischievous students.  Thinking about this now, this seems like a low priority, so you can probably close this issue.

**Comment by jhamrick** [comment]
I think I'll actually keep it open as a reminder to sort out the config loading and make it more intuitive---but glad you were able to sort it out for your class this term!
