### ISSUE TITLE
quickstart help flag not implemented

### ISSUE THREAD

**Issue by kcranston** [jupyter/nbgrader#1078]
### Operating system
OS X 10.14.3

### `nbgrader --version`
nbgrader version 0.6.0.dev

### `jupyterhub --version` (if used with JupyterHub)
n/a

### `jupyter notebook --version` 
5.7.8

### Expected behavior
As shown in the [docs](https://nbgrader.readthedocs.io/en/stable/user_guide/installation.html#quick-start), `nbgrader quickstart -help` should provide help on the quickstart feature. 

### Actual behavior
nbgrader creates a new course with id "-help". Also true for `--help`. Output:

```
(nbg-env) $  ~  nbgrader quickstart –help
[QuickStartApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[QuickStartApp | INFO] Creating directory '/Users/karen/–help'...
[QuickStartApp | INFO] Copying example from the user guide...
[QuickStartApp | INFO] Generating example config file...
[QuickStartApp | INFO] Done! The course files are located in '/Users/karen/–help'.
    
    To get started, you can edit the source notebooks located in:
    
        /Users/karen/–help/source/ps1
    
    Once you have edited them to your satisfaction, you can create
    the student version by running `nbgrader assign ps1` from the
    '/Users/karen/–help' directory.

```

### Steps to reproduce the behavior
* install nbgrader version listed above
* type `nbgrader quickstart -help`

**Comment by jhamrick** [comment]
Hmm, it seems to work fine for me to type `nbgrader quickstart --help`. Is it possible your terminal is autocorrecting `--` to `–` (which is the character you pasted in the issue)?

**Comment by jhamrick** [comment]
Oh! Actually, it's the docs that have the character. Sorry about that--they should indeed be amended.

**Comment by jhamrick** [comment]
Ah, this has actually already been fixed in the version of the docs at head:

https://nbgrader.readthedocs.io/en/master/user_guide/installation.html#quick-start

**Comment by jhamrick** [comment]
Thanks for reporting---hopefully I'll get 0.6.0 released soon and then the stable docs will get updated with the fix!
