### ISSUE TITLE
Deprecate support for python 2

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#1082]
Given that official support Python 2 will be ending in 2020, I think it makes sense to remove support for Python 2 from nbgrader as well in the next major release (maybe 0.6.0?).

I am opening this issue to have a discussion about this if others disagree, and otherwise to discuss a timeline.

**Comment by perllaghu** [comment]
Jupyter stopped supporting P2 in 2018...

**Comment by jhamrick** [comment]
Well, Jupyter itself no longer supports running Python 2, but it still can run Python 2 kernels. Since that's the case, I decided to keep py2 support a bit longer with nbgrader because there are certainly instructors still using python 2 kernels. But I think it makes sense now to deprecate support if even Python doesn't officially support it.

**Comment by aliniknejad** [comment]
Hello. I am working on this.

**Comment by jhamrick** [comment]
Closed by #1082
