### ISSUE TITLE
Error when creating student version of Assignment

### ISSUE THREAD

**Issue by DerFerdi** [jupyter/nbgrader#1091]
Hi,

I'm using nbgrader Version 0.5.5, Jupyterhub 0.9.6, Jupyter Notebook 5.7.8
When trying to create a student-version of an assignment using the formgrader, I get  an error.
It looks like this:

Log Output:
>[INFO] Updating/creating assignment 'aufgabe1': {}
[INFO] Converting notebook kurs2/source/./aufgabe1/aufgabe1.ipynb
[ERROR] There was an error processing assignment: kurs2/source/./aufgabe1
[ERROR] Traceback (most recent call last):
      File "/opt/tljh/user/lib/python3.6/site-packages/nbgrader/converters/base.py", line 293, in convert_notebooks
        self.convert_single_notebook(notebook_filename)
      File "/opt/tljh/user/lib/python3.6/site-packages/nbgrader/converters/base.py", line 249, in convert_single_notebook
        output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
      File "/opt/tljh/user/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 175, in from_filename
        modified_date = datetime.datetime.fromtimestamp(os.path.getmtime(filename))
      File "/opt/tljh/user/lib/python3.6/genericpath.py", line 55, in getmtime
        return os.stat(filename).st_mtime
    FileNotFoundError: [Errno 2] No such file or directory: 'kurs2/source/./aufgabe1/aufgabe1.ipynb'
[ERROR] There was an error processing assignment 'aufgabe1' for student '.'
[ERROR] Please see the the above traceback for details on the specific errors on the above failures.

Traceback:
>Traceback (most recent call last):
  File "/opt/tljh/user/lib/python3.6/site-packages/nbgrader/utils.py", line 371, in capture_log
    app.start()
  File "/opt/tljh/user/lib/python3.6/site-packages/nbgrader/converters/assign.py", line 146, in start
    super(Assign, self).start()
  File "/opt/tljh/user/lib/python3.6/site-packages/nbgrader/converters/base.py", line 72, in start
    self.convert_notebooks()
  File "/opt/tljh/user/lib/python3.6/site-packages/nbgrader/converters/base.py", line 350, in convert_notebooks
    raise NbGraderException(msg)
nbgrader.converters.base.NbGraderException: Please see the the above traceback for details on the specific errors on the above failures.

So these are the exact steps i followed to get to this problem:  
1. I set up Jupyterhub exactly like in this tutorial https://tljh.jupyter.org/en/latest/install/amazon.html  
2. I installed nbgrader:  
    - pip install nbgrader --user  
    - jupyter nbextension install --user --py nbgrader --overwrite  
    - jupyter nbextension enable --user --py nbgrader  
    - jupyter serverextension enable --user --py nbgrader  
3. Navigate to srv in the terminal
    - sudo mkdir nbgrader
    - cd nbgrader
    - sudo mkdir exchange
    - sudo chmod ugo+rw exchange
4. Navigate to ~/.jupyter
5. Create nbgrader_config.py
>c = get_config()
c.CourseDirectory.root = 'kurs2'
6. Create an empty folder "kurs2"
7. Reboot the instance on aws
8. Open the formgrader and add new assignment "aufgabe1"
9. Go to the assignment-folder and upload a notebook that is already finished.
10. Use the formgrader to add a student "12345678", "Max", "Mustermann"
11. Also add this student to Jupyterhub using the control panel
12. Create nbgrader_config.py in ~/kurs2
>c = get_config()
c.Exchange.course_id = "kurs2"
c.Exchange.root = "/srv/nbgrader/exchange"
c.CourseDirectory.db_assignments = [dict(name="aufgabe1")]
c.CourseDirectory.db_students = [dict(id="12345678", first_name="Max", last_name="Muster")]
13. Click on the generate-assignment-button.
And this is where it fails.

Thank you for your time.

**Comment by jhamrick** [comment]
I think the issue is this line in your `nbgrader_config.py`:

```
c.CourseDirectory.root = 'kurs2'
```

This root directory needs to be an absolute path, e.g. `/home/instructor1/kurs2`. If I set it to be relative like in your example then I get the same error too. Let me know if that fixes it!

**Comment by DerFerdi** [comment]
Hey, thanks for the quick response.

I now tried these paths:
- *ip-address*/user/admin1/tree/kurs2
- user/admin1/tree/kurs2
- admin1/tree/kurs2
- admin1/kurs2
- tree/kurs2
- home/kurs2
I tried them all with '/' at the beginning also.

Now when i go to the formgrader, there is a message that says:
> The course id has not been set in nbgrader_config.py. The "release" and "collect" functionality will not be available. Please see the documentation on Setting Up The Exchange for instructions.

Also the Assignment does not show up in the formgrader anymore. 
It did show up there before, when i used 'kurs2' as the path.

Looking at my URL, the course is located in:
*http://ip-address/user/admin1/tree/kurs2*
Through the Terminal i can acces the course through:
*jupyter-admin1@ip-address:~/kurs2*

Please let me know if i am doing something wrong.
Thanks in advance.

**Comment by jhamrick** [comment]
You can find the full path by running the `pwd` command from your terminal in the `kurs2` directory. My guess is that it should be `/home/jupyter-admin1/kurs2` based on what you pasted about your terminal, but you should run `pwd` just in case to be sure.

Note that the path you have to specify in the config file is a file system path, not a URL.

**Comment by DerFerdi** [comment]
Thanks!!!
It was indeed `/home/jupyter-admin1/kurs2`.
