### ISSUE TITLE
Assignments-Tab only shows "Loading, please wait", when logged in as a student

### ISSUE THREAD

**Issue by DerFerdi** [jupyter/nbgrader#1103]
Hi,
I have a problem using nbgrader on Jupyterhub.
I guess i made a mistake installing it but can`t find it.
I am using following versions:

`Ubuntu 18.04`  

`Nbgrader 0.5.5`

`Jupyterhub 0.9.6` (tljh)

`Jupyter Notebook 5.7.8` 

When logging into Jupyterhub as a student, I should be able to see an assignment that i released using the Formgrader. 
Using `nbgrader list` in the terminal of the admin, i can see that the assignment has been released.
Also the Assignments tab works perfectly fine when i am logged in as the admin.
There i can see the released assignment.

When i log into my students account and click on the assignments tab, it looks like this:
![grafik](https://user-images.githubusercontent.com/49441882/58640331-1efee680-82f9-11e9-89c2-4a55356ec1da.png)

#### Also, using the terminal as a student the command nbgrader is not found.

So to recreate this problem:
- I set up Jupyterhub exactly like in this tutorial https://tljh.jupyter.org/en/latest/install/amazon.html
- I installed nbgrader like this:
        sudo -E pip install nbgrader --sys-prefix
        sudo -E jupyter nbextension install --sys-prefix --py nbgrader --overwrite
        sudo -E jupyter nbextension enable --sys-prefix --py nbgrader
        sudo -E jupyter serverextension enable --sys-prefix --py nbgrader
- Use the formgrader to add a student "12345678", "Max", "Mustermann"
- Also add this student to Jupyterhub using the control panel

I guess my problem is somewhere in this installation.

Thanks in advance :)

**Comment by jhamrick** [comment]
It sounds like nbgrader hasn't been installed properly for the student account. I'm not sure `--sys-prefix` is a valid flag for pip, can you try just running `sudo -E pip install -U nbgrader`?

Can you also paste here any command line output from when JupyterHub is running? It should ideally give some errors that might be diagnostic too.

**Comment by DerFerdi** [comment]
Thanks for your quick response!

When i run `sudo -E pip install -U nbgrader` as admin1 the terminal shows this:

> WARNING: The directory '/home/jupyter-admin1/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/jupyter-admin1/.cache/pip' or its parent directory is not owned by the current user and cachingwheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: nbgrader in ./.local/lib/python3.6/site-packages (0.5.5)
Requirement already satisfied, skipping upgrade: jupyter-client in /opt/tljh/user/lib/python3.6/site-packages (from nbgrader)(5.2.4)
Requirement already satisfied, skipping upgrade: jupyter-console<=5.2.0 in ./.local/lib/python3.6/site-packages (from nbgrader) (5.2.0)
Requirement already satisfied, skipping upgrade: tornado in /opt/tljh/user/lib/python3.6/site-packages (from nbgrader) (5.1.1)
Requirement already satisfied, skipping upgrade: traitlets in /opt/tljh/user/lib/python3.6/site-packages (from nbgrader) (4.3.2)
Requirement already satisfied, skipping upgrade: ipython<=6.2.1 in ./.local/lib/python3.6/site-packages (from nbgrader) (6.2.1)
Requirement already satisfied, skipping upgrade: python-dateutil in /opt/tljh/user/lib/python3.6/site-packages (from nbgrader) (2.8.0)
Requirement already satisfied, skipping upgrade: six>=1.9 in /opt/tljh/user/lib/python3.6/site-packages (from nbgrader) (1.11.0)
Requirement already satisfied, skipping upgrade: jupyter-core in /opt/tljh/user/lib/python3.6/site-packages (from nbgrader) (4.4.0)
Requirement already satisfied, skipping upgrade: jsonschema in /opt/tljh/user/lib/python3.6/site-packages (from nbgrader) (3.0.1)
Requirement already satisfied, skipping upgrade: jupyter in ./.local/lib/python3.6/site-packages (from nbgrader) (1.0.0)
Requirement already satisfied, skipping upgrade: notebook>=4.2 in /opt/tljh/user/lib/python3.6/site-packages (from nbgrader) (5.7.8)
Requirement already satisfied, skipping upgrade: sqlalchemy in /opt/tljh/user/lib/python3.6/site-packages (from nbgrader) (1.3.4)
Requirement already satisfied, skipping upgrade: requests in /opt/tljh/user/lib/python3.6/site-packages (from nbgrader) (2.18.4)
Requirement already satisfied, skipping upgrade: nbconvert>=4.2 in /opt/tljh/user/lib/python3.6/site-packages (from nbgrader)(5.5.0)
Requirement already satisfied, skipping upgrade: alembic in /opt/tljh/user/lib/python3.6/site-packages (from nbgrader) (1.0.10)
Requirement already satisfied, skipping upgrade: nbformat in /opt/tljh/user/lib/python3.6/site-packages (from nbgrader) (4.4.0)
Requirement already satisfied, skipping upgrade: pyzmq>=13 in /opt/tljh/user/lib/python3.6/site-packages (from jupyter-client->nbgrader) (18.0.1)
Requirement already satisfied, skipping upgrade: ipykernel in /opt/tljh/user/lib/python3.6/site-packages (from jupyter-console<=5.2.0->nbgrader) (5.1.1)
Requirement already satisfied, skipping upgrade: pygments in /opt/tljh/user/lib/python3.6/site-packages (from jupyter-console<=5.2.0->nbgrader) (2.4.2)
Requirement already satisfied, skipping upgrade: prompt-toolkit<2.0.0,>=1.0.0 in ./.local/lib/python3.6/site-packages (from jupyter-console<=5.2.0->nbgrader) (1.0.16)
Requirement already satisfied, skipping upgrade: ipython-genutils in /opt/tljh/user/lib/python3.6/site-packages (from traitlets->nbgrader) (0.2.0)
Requirement already satisfied, skipping upgrade: decorator in /opt/tljh/user/lib/python3.6/site-packages (from traitlets->nbgrader) (4.4.0)
Requirement already satisfied, skipping upgrade: pickleshare in /opt/tljh/user/lib/python3.6/site-packages (from ipython<=6.2.1->nbgrader) (0.7.5)
Requirement already satisfied, skipping upgrade: simplegeneric>0.8 in ./.local/lib/python3.6/site-packages (from ipython<=6.2.1->nbgrader) (0.8.1)
Requirement already satisfied, skipping upgrade: jedi>=0.10 in /opt/tljh/user/lib/python3.6/site-packages (from ipython<=6.2.1->nbgrader) (0.13.3)
Requirement already satisfied, skipping upgrade: setuptools>=18.5 in /opt/tljh/user/lib/python3.6/site-packages (from ipython<=6.2.1->nbgrader) (39.2.0)
Requirement already satisfied, skipping upgrade: pexpect; sys_platform != "win32" in /opt/tljh/user/lib/python3.6/site-packages (from ipython<=6.2.1->nbgrader) (4.7.0)
Requirement already satisfied, skipping upgrade: attrs>=17.4.0 in /opt/tljh/user/lib/python3.6/site-packages (from jsonschema->nbgrader) (19.1.0)
Requirement already satisfied, skipping upgrade: pyrsistent>=0.14.0 in /opt/tljh/user/lib/python3.6/site-packages (from jsonschema->nbgrader) (0.15.2)
Requirement already satisfied, skipping upgrade: ipywidgets in /opt/tljh/user/lib/python3.6/site-packages (from jupyter->nbgrader) (7.4.2)
Requirement already satisfied, skipping upgrade: qtconsole in ./.local/lib/python3.6/site-packages (from jupyter->nbgrader) (4.5.1)
Requirement already satisfied, skipping upgrade: prometheus-client in /opt/tljh/user/lib/python3.6/site-packages (from notebook>=4.2->nbgrader) (0.6.0)
Requirement already satisfied, skipping upgrade: jinja2 in /opt/tljh/user/lib/python3.6/site-packages (from notebook>=4.2->nbgrader) (2.10.1)
Requirement already satisfied, skipping upgrade: Send2Trash in /opt/tljh/user/lib/python3.6/site-packages (from notebook>=4.2->nbgrader) (1.5.0)
Requirement already satisfied, skipping upgrade: terminado>=0.8.1 in /opt/tljh/user/lib/python3.6/site-packages (from notebook>=4.2->nbgrader) (0.8.2)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /opt/tljh/user/lib/python3.6/site-packages (from requests->nbgrader) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.7,>=2.5 in /opt/tljh/user/lib/python3.6/site-packages (from requests->nbgrader) (2.6)
Requirement already satisfied, skipping upgrade: urllib3<1.23,>=1.21.1 in /opt/tljh/user/lib/python3.6/site-packages (from requests->nbgrader) (1.22)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /opt/tljh/user/lib/python3.6/site-packages (from requests->nbgrader) (2019.3.9)
Requirement already satisfied, skipping upgrade: defusedxml in /opt/tljh/user/lib/python3.6/site-packages (from nbconvert>=4.2->nbgrader) (0.6.0)
Requirement already satisfied, skipping upgrade: entrypoints>=0.2.2 in /opt/tljh/user/lib/python3.6/site-packages (from nbconvert>=4.2->nbgrader) (0.3)
Requirement already satisfied, skipping upgrade: bleach in /opt/tljh/user/lib/python3.6/site-packages (from nbconvert>=4.2->nbgrader) (3.1.0)
Requirement already satisfied, skipping upgrade: pandocfilters>=1.4.1 in /opt/tljh/user/lib/python3.6/site-packages (from nbconvert>=4.2->nbgrader) (1.4.2)
Requirement already satisfied, skipping upgrade: mistune>=0.8.1 in /opt/tljh/user/lib/python3.6/site-packages (from nbconvert>=4.2->nbgrader) (0.8.4)
Requirement already satisfied, skipping upgrade: testpath in /opt/tljh/user/lib/python3.6/site-packages (from nbconvert>=4.2->nbgrader) (0.4.2)
Requirement already satisfied, skipping upgrade: Mako in /opt/tljh/user/lib/python3.6/site-packages (from alembic->nbgrader) (1.0.10)
Requirement already satisfied, skipping upgrade: python-editor>=0.3 in /opt/tljh/user/lib/python3.6/site-packages (from alembic->nbgrader) (1.0.4)
Requirement already satisfied, skipping upgrade: wcwidth in /opt/tljh/user/lib/python3.6/site-packages (from prompt-toolkit<2.0.0,>=1.0.0->jupyter-console<=5.2.0->nbgrader) (0.1.7)
Requirement already satisfied, skipping upgrade: parso>=0.3.0 in /opt/tljh/user/lib/python3.6/site-packages (from jedi>=0.10->ipython<=6.2.1->nbgrader) (0.4.0)
Requirement already satisfied, skipping upgrade: ptyprocess>=0.5 in /opt/tljh/user/lib/python3.6/site-packages (from pexpect;sys_platform != "win32"->ipython<=6.2.1->nbgrader) (0.6.0)
Requirement already satisfied, skipping upgrade: widgetsnbextension~=3.4.0 in /opt/tljh/user/lib/python3.6/site-packages (from ipywidgets->jupyter->nbgrader) (3.4.2)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /opt/tljh/user/lib/python3.6/site-packages (from jinja2->notebook>=4.2->nbgrader) (1.1.1)
Requirement already satisfied, skipping upgrade: webencodings in /opt/tljh/user/lib/python3.6/site-packages (from bleach->nbconvert>=4.2->nbgrader) (0.5.1)



Can you explain where to find the command line output from jupyterhub?
I'm not sure if that is the System log on aws?

**Comment by jhamrick** [comment]
I am not totally sure, but I imagine the the littlest jupyterhub configures jupyterhub to output logs to a logfile---if you can send those along that is the equivalent to the command line output. (Unfortunately I have not used the littlest jupyterhub before though so I am not sure exactly where the logfile would be)

**Comment by jhamrick** [comment]
Ah but actually the pip output you listed is revealing:

```
Requirement already up-to-date: nbgrader in ./.local/lib/python3.6/site-packages (0.5.5)
```

it looks like your nbgrader is only installed for the local user, rather than the system. Can you try uninstalling nbgrader and then reinstalling it?

**Comment by DerFerdi** [comment]
Thank you very much. I uninstalled nbgrader, then installed it like you said:
> sudo -E pip install -U nbgrader

and now everything works as I excpected it :)
