### ISSUE TITLE
Sanitize notebook documentation output

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#1117]
Currently when building the docs, they produce a lot of outputs that involves user-specific information like username, path to the nbgrader repo, dates and times, etc. Ideally we could write some sort of postprocessing sanitizer to remove this information so it doesn't result in such large diffs when committing changes to the docs.

cc @danielmaitre @dsblank

**Comment by danielmaitre** [comment]
I made it my train journey task. Should have a PR shortly...

**Comment by jhamrick** [comment]
Closed by #1119
