### ISSUE TITLE
Assignment generation: adding: raise NotImplementedError()

### ISSUE THREAD

**Issue by psychemedia** [jupyter/nbgrader#1154]
The default behaviour of the assignment generator is to populate code cells with:

```python
# YOUR CODE HERE
raise NotImplementedError()
```

For a novice this looks intimidating, is irrelevant to the student, and may also confuse them when writing their own solutions.

Is the `raise NotImplementedError()` line required to ensure the autograder performs correctly?

If students leave this line in the code cell before or after their answer, the exception is raised and the student will lose any marks for code they correctly entered into the cell. Should there be a guard to remove the `raise NotImplementedError()` clause if it appears there is code in the cell?

To mitigate against this, when receiving an assignment, would it make more sense to check code cells to see if they are empty or if they just contain the default text, and if so then populate them with the `raise NotImplementedError()` statement before autograding, rather than adding the `raise NotImplementedError()` to each assessed code cell when the student release notebook is created ?

**Comment by psychemedia** [comment]
Just as an observation on the `NotImplementedError()`, if the automated tests include something like:

```
### BEGIN HIDDEN TESTS
import sys
tmp = sys.last_value
if isinstance(tmp,UnicodeDecodeError):
  print("some sort of hint about how to go about answering the question")
### END HIDDEN TESTS

then you can provide some feedback to students even if they don't attempt a question?

In some cases, you might even want to provide the student with an actual example answer, which speaks to https://github.com/jupyter/nbgrader/issues/1155 in the sense of this may be yet another ways of making use of the canned / example answers that were included in an original marking guide assignment notebook.

**Comment by jaspervdh96** [comment]
The `raise NotImplementedError()` is just a default replacement. You can change it, see the [documentation](https://nbgrader.readthedocs.io/en/stable/configuration/student_version.html#changing-the-defaults).

I don't use it myself, but it can make sure students don't forget a question.

**Comment by jhamrick** [comment]
Indeed, as @jaspervdh96 said the code and text stubs are fully configurable.

Though I should mention, the hidden tests are only run during the autograding step, not when the student has the assignment, so if you wanted to provide them a hint for how to solve it you probably don't want to include that in the hidden tests.

**Comment by jhamrick** [comment]
Since there hasn't been any additional activity on this and it sounds like it is perhaps resolved, I am going to go ahead and close this, but feel free to comment here again or open a new issue if there are further questions!

**Comment by mpfoster** [comment]
Hi! nbgrader newbie here. I'd like to reopen this issue. Based on what I read in the documentation and on this page, the `raise NotImplementedError()` should only appear in autograded cells. I'm seeing it in previews of cells set to be manually graded. Is this the expected result? Thanks!
