### ISSUE TITLE
Exclude students when autograding

### ISSUE THREAD

**Issue by rkdarst** [jupyter/nbgrader#1157]
Autograde has a `--student` option, which limits to autograde only one student.  Sometimes, autograde fails for unknown reasons (currently bumping against metadata updates), but it's concievable that there could be more.  It would be useful for me to have the equivalent of `--skip-students` option which skips the given student IDs (for example, comma separated list).

Right now I have a hack where, if it fails, I run `ls submitted/ | grep -v (bad usernames) | cut -d/ -f1 | xargs -i nbgrader autograde [...] [assignment_name] --student={}`, which basically re-invokes for each student explicitly using `--student` - it's not perfect because it also invokes for students who haven't submitted.

This is related to "don't stop if there is an error with one notebook", and #1083 somewhat.  There have been some recent updates to metadata handling, which may solve an immediate problem, but this could still be useful...

I'm using what was approximately master before the hackathon, Linux.

**Comment by jhamrick** [comment]
Yes, seems reasonable to add something like this. Ideally we'll find all the ways that nbgrader fails during grading and handle them a bit more gracefully, but I think this is a nice fallback option as I expect there will always be some edge cases.

**Comment by rkdarst** [comment]
done in #1179 long ago.
