### ISSUE TITLE
Unpin version of ipython in 0.5.6.dev and release 0.5.6

### ISSUE THREAD

**Issue by ocefpaf** [jupyter/nbgrader#1159]
The current release has `ipython` pinned to `<=6.2.1` and that is preventing us from installing `nbgrader` alongside modern packages. See https://github.com/jupyter/nbgrader/pull/1050

Looks like that limitation was already fixed. Can we get a new release?

**Comment by ocefpaf** [comment]
Ping @lwasser, this is one of the blocker to build a stable env from your stack of packages in teh EDS docker image.

**Comment by lwasser** [comment]
oh wow @ocefpaf thank you. Do you use a tool to trace these issues? i'm just wondering if it's something i can help troubleshoot as things come up or if it's quite complex.

 @jhamrick is wonderful and originally built and now still works on nbgrader and could probably help with a new release.

**Comment by jhamrick** [comment]
I was hoping to wait for 0.6.0 release in order to get this issue fixed but
it's taken a bit longer than I anticipated, so perhaps I can try to do a
0.5.6 release just to unpin the version of IPython. I am unfortunately
quite busy with work for the next week though so I do not know if I will be
able to get to it until next weekend. I will try though!

**Comment by lwasser** [comment]
thank you @jhamrick we know you are super busy and really appreciate your getting to it next weekend :)

**Comment by ocefpaf** [comment]
> I was hoping to wait for 0.6.0 release in order to get this issue fixed but it's taken a bit longer than I anticipated, 

We can wait :smile: 

> so perhaps I can try to do a 0.5.6 release just to unpin the version of IPython. I am unfortunately quite busy with work for the next week though so I do not know if I will be able to get to it until next weekend. I will try though!

If you point me to the PR that fixed the incompatibility I can make a "patched" released on conda-forge. (I could not find the reason for the pin nor the PR fixing it, just noticed that it is unpinned on master.)

**Comment by ocefpaf** [comment]
> oh wow @ocefpaf thank you. Do you use a tool to trace these issues?

No tool. Just the solver's error messages and lots of GH searches.

> i'm just wondering if it's something i can help troubleshoot as things come up or if it's quite complex.

conda's solver is getting better at error messaging this but bad conda-package metadata and the lack of a 'pip solver' makes it hard to trust the results.

> @jhamrick is wonderful and originally built and now still works on nbgrader and could probably help with a new release.

:+1:

**Comment by davidnero** [comment]
Seeing as it's the end of August, would you be willing to release 0.5.6? Fall classes are about to start, and having to override the requirements is not an ideal state to be stuck in.

**Comment by lwasser** [comment]
i'd love that as well +1

**Comment by jhamrick** [comment]
Yes, I will be making releases very soon. So sorry about the delay on this!

**Comment by jhamrick** [comment]
I have created a release on 0.5.6 on pypi, release on conda is pending (https://github.com/conda-forge/nbgrader-feedstock/pull/28).

I'll try to get 0.6.0 released this weekend!

**Comment by lwasser** [comment]
yay!! thank you so much, @jhamrick !!! @kcranston we will be able to update our environment now for class next week :)

**Comment by kcranston** [comment]
Thank you, @jhamrick ! (we know the challenges of maintaining open source while also maintaining a day job).
