### ISSUE TITLE
Which extensions should I enable?

### ISSUE THREAD

**Issue by mkzia** [jupyter/nbgrader#1165]
The following is a list of extensions that can be enabled:

- nbextensions
  - create_assignment/main --section=notebook
  - formgrader/main --section=notebook
  - formgrader/main --section=tree
  - assignment_list/main --section=tree
  - jupyter-js-widgets/extension --section=notebook

- serverextension 
  - nbgrader.server_extensions.formgrader
  - nbgrader.server_extensions.validate_assignment
  - nbgrader.server_extensions.assignment_list

I need to know which ones need to be enabled for an instructor and which ones for students.

**Comment by mkzia** [comment]
Answering my own question.

For an instructor user I enabled everything:
jupyter nbextension install --user --py nbgrader --overwrite
jupyter nbextension enable --user --py nbgrader
jupyter serverextension enable --user --py nbgrader

For system-wide settings I enabled the following:
jupyter nbextension install --sys-prefix --py nbgrader --overwrite
jupyter nbextension enable --sys-prefix assignment_list/main 
jupyter nbextension enable --sys-prefix assignment_list/main --section=tree
jupyter nbextension enable --sys-prefix  validate_assignment/main --section=notebook
jupyter serverextension enable --sys-prefix nbgrader.server_extensions.assignment_list
jupyter serverextension enable --sys-prefix nbgrader.server_extensions.validate_assignment
jupyter serverextension enable --sys-prefix nbgrader.server_extensions.formgrader

**Comment by jhamrick** [comment]
Glad you figured it out! For reference, there is also a table here clarifying which extensions should be enabled for instructors, students, and formgrader accounts in a JupyterHub setup: https://nbgrader.readthedocs.io/en/master/configuration/jupyterhub_config.html#example-use-case-one-class-multiple-graders
