### ISSUE TITLE
Assignment-Tab not showing when logged in as a student

### ISSUE THREAD

**Issue by DerFerdi** [jupyter/nbgrader#1167]
Hi,
I have a small problem using nbgrader on Jupyterhub.
I guess I made a mistake installing nbgrader (again).
I am using following versions:

Ubuntu 18.04

Nbgrader 0.5.5

Jupyterhub 1.0.0 (tljh)

Jupyter Notebook 5.7.8

**So the problem is, there is no assignments-tab when logged in as a student. Everything else works perfectly fine. I can fetch and submit assignments using the terminal, which is very very cool.**

I don`t know if this is related but autograding also works fine when using "nbgrader autograde" in the terminal but using the formgrader to manage the submissions only shows "loading".
![grafik](https://user-images.githubusercontent.com/49441882/62451391-7e9cc680-b76e-11e9-96f3-412bedf40fad.png)

So to recreate this problem:
I set up Jupyterhub exactly like in this tutorial: https://tljh.jupyter.org/en/latest/install/amazon.html
I installed nbgrader like this:
```
sudo -E pip install -U nbgrader
sudo -E jupyter nbextension install --py nbgrader --overwrite
sudo -E jupyter nbextension enable --py nbgrader
sudo -E jupyter serverextension enable --py nbgrader
```
The nbgrader_config.py located in ~/.jupyter looks like this:
```
c = get_config()
c.CourseDirectory.root = '/home/jupyter-admin1/course1'
```
And the nbgrader_config.py located in course1 looks like this:
```
c = get_config()
c.Exchange.course_id = "course1"
c.CourseDirectory.db_assignments = [dict(name="level1")]
c.CourseDirectory.db_students = [
    dict(id="1234567"),
    dict(id="7654321")
]
```

Also I want to point out that, fetching an assignment, I get this warning:
```
[FetchApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[FetchApp | DEBUG] Searching ['/home/jupyter-1234567', '/home/jupyter-1234567/.jupyter', '/opt/tljh/user/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[FetchApp | DEBUG] Looking for jupyter_config in /etc/jupyter
[FetchApp | DEBUG] Looking for jupyter_config in /usr/local/etc/jupyter
[FetchApp | DEBUG] Looking for jupyter_config in /opt/tljh/user/etc/jupyter
[FetchApp | DEBUG] Looking for jupyter_config in /home/jupyter-1234567/.jupyter
[FetchApp | DEBUG] Looking for jupyter_config in /home/jupyter-1234567
[FetchApp | DEBUG] Looking for nbgrader_config in /etc/jupyter
[FetchApp | DEBUG] Looking for nbgrader_config in /usr/local/etc/jupyter
[FetchApp | DEBUG] Looking for nbgrader_config in /opt/tljh/user/etc/jupyter
[FetchApp | DEBUG] Looking for nbgrader_config in /home/jupyter-1234567/.jupyter
[FetchApp | DEBUG] Looking for nbgrader_config in /home/jupyter-1234567
[FetchApp | DEBUG] Looking for nbgrader_config in /home/jupyter-1234567
```
I don't really understand if this has anything to do with my original problem, since releasing, fetching, submitting etc. works and this is "only" a warning. So I guessed that I don't necessarily need a third nbgrader_config.py, because I wouldn`t know what to specify there.
    

I am sorry if these are individual problems, but I thought they might be related. Hopefully you can still understand my problem.

Thanks in advance :)

**Comment by perllaghu** [comment]
To enable the assignment listing & fetching, you need:

    jupyter nbextension enable --sys-prefix assignment_list/main --section=tree
    jupyter serverextension enable --sys-prefix nbgrader.server_extensions.assignment_list

To enable the [student] validation, you need:

    jupyter nbextension enable --sys-prefix validate_assignment/main --section=tree
    jupyter serverextension enable --sys-prefix nbgrader.server_extensions.validate_assignment

**Comment by DerFerdi** [comment]
Thank you very much for your quick respone! Now it works.
