### ISSUE TITLE
Collected submissions not showing in form grader 

### ISSUE THREAD

**Issue by Dpananos** [jupyter/nbgrader#1170]
### Operating system

Mac OS 10.14.5

### `nbgrader --version`

 0.5.5

### `jupyter notebook --version` 

5.7.8

### Expected behavior

When clicking on `# submissions` for a particular assignment, I expect to see a list of submitted assignments as well as the option to auto mark any of the submitted assignments.

### Actual behavior

No submissions show.  Prompt saying "Loading, please wait" is shown.  Submissions are not loaded.

### Steps to reproduce the behavior

* Create assignment
* Distribute assignment
* Collect completed assignment
* Attempt to auto grade using form grader

**Comment by BertR** [comment]
@Dpananos could you share the logged output from the notebook when this happens?

**Comment by jhamrick** [comment]
I am closing this issue because there hasn't been any activity on it in a while. However, if you (or others) continue to encounter problems, feel free to comment here or open a new issue!
