### ISSUE TITLE
The exchange directory at /srv/nbgrader/exchange does not exist and could not be created.

### ISSUE THREAD

**Issue by chikaj** [jupyter/nbgrader#1212]
@jhamrick asked that this be opened as a new issue, but I do not see that it was. I have the same issue as described by @nscozzaro below.

Hi @jhamrick, I recently discovered NbGrader and it seems really cool! To test it out I just set up a JupyterHub and am using the `umsimads/education-notebook/` docker image which comes with nbgrader installed. However, I received the same error as discussed above (`The exchange directory at /srv/nbgrader/exchange does not exist...`). I read the page the error message links to (https://nbgrader.readthedocs.io/en/stable/user_guide/managing_assignment_files.html#setting-up-the-exchange), and executed the commands on that page and then refreshed my nbgrader page but I still see the same message. I also read through the nbgrader JupyterHub config page (https://nbgrader.readthedocs.io/en/stable/configuration/jupyterhub_config.html) but unfortunately I'm still confused about what to do! 

What exactly do I need to configure in order to get it the exchange to work on my JupyterHub? Thanks in advance!

![Screen Shot 2019-08-19 at 10 13 49 PM](https://user-images.githubusercontent.com/15185105/63312186-ad6a7f00-c2ce-11e9-982c-a47ee3cc08cb.png)

_Originally posted by @nscozzaro in https://github.com/jupyter/nbgrader/issues/841#issuecomment-522827593_

**Comment by perllaghu** [comment]
In your Dockerfile (I can tell you're using Docker Images, as it's `/srv/nbgrader/exchange`) add

`RUN mkdir -p /srv/nbgrader/exchange && fix-permissions /srv/nbgrader/exchange` or
`RUN mkdir -p /srv/nbgrader/exchange && chmod 777 /srv/nbgrader/exchange`

**Comment by chikaj** [comment]
Thank you! And a note to myself or future users: 

Also in your Dockerfile, make sure you add

USER root

prior to changing the permissions (probably at the top of the Dockerfile).

**Comment by ranjiGT** [comment]
Hello I am facing the same issue but I don't have a Dockerfile but instead, I use the dockerspawner and spawns a single-user server on which the server runs. What exactly should I need to do configure so that the exchange directory is accessed?

**Comment by perllaghu** [comment]
> Hello I am facing the same issue but I don't have a Dockerfile but instead, I use the dockerspawner and spawns a single-user server on which the server runs. What exactly should I need to do configure so that the exchange directory is accessed?

Your problem in a cloud environment is twofold:
1. The exchange folder is a directory within the docker image [the single-image is a docker image], so the storage needs to be volume-mounted from the host to the image
2. The exchange storage needs to exist across _all_ the nodes, because you never know which node the users docker image starts on.
