### ISSUE TITLE
Course List Extension: There are no available formgrader services.

### ISSUE THREAD

**Issue by sigurdurb** [jupyter/nbgrader#1215]
nbgrader master at 16 august 2019
jupyterhub 0.8.1

I am running a couple of courses as a managed service since the pre-multiple courses version of nbgrader. In the services I am running the formgraders I am now switching to the new version of multiple courses and I did a `nbgrader db upgrade` and some of the old courses seem to be running correctly but some had some error with the db. 

Now, for a user/teacher account I had some issue with the course list extension.
First I had a 404 for GET /user/USERNAME/formgraders? that was solved in #1175 but now I have a 404 formgrader issue for /user/USERNAME/formgrader/api/status

This is the log output:
`[W 2019-09-12 18:37:37.224 SingleUserNotebookApp log:122] 404 GET /user/USERNAME/formgrader/api/status (@130.208.243.34) 1.58ms`
`[W 2019-09-12 18:37:37.225 SingleUserNotebookApp handlers:71] Local formgrader does not seem to be running`
`[I 2019-09-12 18:37:37.227 SingleUserNotebookApp log:122] 200 GET /user/USERNAME/formgraders?_=1568312899679 (user@192.168.204.177) 18.55ms`

**Comment by andreas-h** [comment]
I'm seeing something similar.  I also have the 

`Sep 30 17:03:19 lamoslab bash[26303]: [W 2019-09-30 17:03:19.312 SingleUserLabApp handlers:72] Local formgrader does not seem to be running`

error, but I do not see any 404s around there.

After clicking the *Courses* link, it takes ~60s before I get the **There are no available formgrader services.** message in the browser, and the `Local formgrader does not seem to be running` log message.

I'm on recent JupyterHub with JupyterLab as default interface.

**Comment by sigurdurb** [comment]
Hi, @andreas-h  
I don't think nbgrader works with JupyterLab but I have not tried it. Are you running your course as a service and do you have `c.CourseDirectory.course_id` set in nbgrader_config.py ?
