### ISSUE TITLE
Fetch grades cell by cell

### ISSUE THREAD

**Issue by gabrielplicks** [jupyter/nbgrader#1226]
Hi. First of all, amazing work done by you guys. This is probably a new feature request, cause I haven't seen it anywhere in the documentation. Is there any way I can get the grades cell by cell in the python API? I am only able to fetch the total sum of the grades so far using `NbGraderAPI.autograde()`. Thanks in advance.

**Comment by elesiuta** [comment]
As far as I know it hasn't been implemented yet. I wrote a script that does exactly this by iterating over all the students' notebooks from the autograded folder. 

Just run it with --dist assignmentname and it will print a summary of the totals for each cell along with writing a csv containing each student's grade cell by cell. 

It also has the option of iterating over the feedback files with --fdist if you want the cell by cell grades after any manual adjustments.

https://github.com/elesiuta/jupyter-nbgrader-helper

**Comment by jhamrick** [comment]
This functionality exists in the `GetGrades` preprocessor, but not directly from the Python API. The problem with doing it from the API is that the database doesn't actually know anything about the order of the cells in the notebook.

If you don't care about the order, then you can get all the grades for a particular cell using the api to the database models: https://nbgrader.readthedocs.io/en/stable/api/models.html#database-models

(I will try to add an example of how to do this later!)

**Comment by jhamrick** [comment]
Here's an example:

```
from nbgrader.api import Gradebook
with Gradebook('sqlite:///gradebook.db') as gb:
    for assignment in gb.assignments:
        for notebook in assignment.notebooks:
            for cell in notebook.task_cells + notebook.grade_cells:
                print(cell)
                for grade in cell.grades:
                    print(grade.student, grade.score)
```

**Comment by gabrielplicks** [comment]
Thank you so much @elesiuta and @jhamrick ! The example helps me a lot. I might as well overcome the cells ordering issue by setting particular cell IDs to the ones I am interested in. Thanks again! Amazing work.
