### ISSUE TITLE
Creating assignments from scripts

### ISSUE THREAD

**Issue by srcolinas** [jupyter/nbgrader#1237]
Hi! The library seems amazing, but I wonder whether it is possible to create assignments from regular python script files (`.py` extension). The reason is that if I can create assignments from that then I show more complicated things. For instance, considere a class you want your students to implement for their first assignment but want to inherit from there in a later assignment. I think this flexibility at organizing code will also let us show students best practices and more complex programming patterns.

Thanks!

**Comment by BertR** [comment]
Hi, if your assignment includes a `.py` file and a `.ipynb` file,
you can import code from the first into the second, but as far
as I'm aware you cannot do it the other way around.

**Comment by srcolinas** [comment]
Thanks @BertR ! Will the library also generate homework and assignment files for `.py` files?

**Comment by BertR** [comment]
The `.py` files will be included in the assignments. They will not be converted, so things like
`### BEGIN SOLUTION` will not be stripped out. The `.py` will be a straight copy of the original.

**Comment by perllaghu** [comment]
@srcolinas - nbgrader specifically looks for, and only works with _ipython notebooks_ - or `.ipynb` files.

**Comment by srcolinas** [comment]
@BertR  and @perllaghu thanks for your answers! Do know if there are any plans to add support for `.py` files?

**Comment by perllaghu** [comment]
> @BertR and @perllaghu thanks for your answers! Do know if there are any plans to add support for `.py` files?

Personally, I'm unaware of any..... and I think it would require fairly extensive changes in other parts of the Jupyter Notebook ecosystem to make it work....

**Comment by jhamrick** [comment]
Yes, unfortunately I think it's out of scope to support tests in regular python scripts. One reason is that nbgrader is meant to be language-agnostic, so allowing tests in python scripts would also mean we'd need to support them for any other language, which would not be an easy thing to support. Additionally, as @perllaghu mentioned it would require a lot of changes to the overall infrastructure of the project.
