### ISSUE TITLE
Integrating nbgrader into jupyterhub with DockerSpawner

### ISSUE THREAD

**Issue by sampanriver** [jupyter/nbgrader#1240]
My jupyterhub was setup with docker spawner. When I was trying to setup nbgrader following "One class, Multiple graders" example, it always failed with following error message:

_[I 2019-10-08 16:05:05.538 JupyterHub service:316] Starting service 'course101': ['jupyterhub-singleuser', '--group=formgrader-course101', '--debug']
[I 2019-10-08 16:05:05.540 JupyterHub service:121] Spawning jupyterhub-singleuser --group=formgrader-course101 --debug
Failed to set groups [Errno 1] Operation not permitted_

 
Could anyone help on this?

Thanks in advance!

**Comment by sampanriver** [comment]
I run the command with sudo, the error message has gone. But the nbgrader still doesn't work.

**Comment by BertR** [comment]
Hi @sampanriver , can you give a bit more detail about your setup?
How are you running JupyterHub? Can you share your configuration?

**Comment by sampanriver** [comment]
> Hi @sampanriver , can you give a bit more detail about your setup?
> How are you running JupyterHub? Can you share your configuration?

Thanks @BertR . I have figured it out by myself. The reason of my failure was because no nbgrader was added in the docker image.
