### ISSUE TITLE
Consider adding caching to the tests so they don't need to run exhaustively

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#1252]
For example, with the pytest-cache extension.

**Comment by HanTeo** [comment]
We could explore using [pytest-testmon](https://pypi.org/project/pytest-testmon/) This is a pytest plug-in which automatically selects and re-executes only tests affected by recent changes.

It might be useful to invalidate the cache on a daily basis to avoid potential issues with stale cache giving a false positives.

We will likely have to modify the Travis workflow to enable this.

**Comment by jhamrick** [comment]
It seems at this time it's not really feasible to use pytest-testmon, see https://github.com/jupyter/nbgrader/pull/1258#issuecomment-549059879. As a result, I am closing this issue.
