### ISSUE TITLE
Google collab interactions

### ISSUE THREAD

**Issue by ashriram** [jupyter/nbgrader#1273]
Is is possible to activate the validate form button in google collab ?
Can I ask the students to complpete the assignments in google collab, export and import it for grading on nbgrader.

**Comment by jhamrick** [comment]
The nbgrader extensions are not compatible with Colab, so unfortunately this is not possible.

**Comment by gramlogic** [comment]
Is there any chance of nbgrader and Google colab working together at some point in the future? I've been running JupyterHub on my own kubernetes cluster so I can use nbgrader, but this can be expensive and Google colab offers some nice features.

**Comment by ambareeshsrja16** [comment]
If nbgrader could be made compatible with Google Colab that would be great!

**Comment by subhashsubramanian** [comment]
> If nbgrader could be made compatible with Google Colab that would be great!

Absolutely! That will be great!

**Comment by bryan-pardo** [comment]
I agree, that would be great to be able to use nbgrader with Colab! I know the issue is closed....but if it could be reopened....

**Comment by perllaghu** [comment]
Does Colab use the classic notebook interface, or the newer Jupyterlab interface?

In Google GoLab, how does one identify students as being in a common group?
Do they share any common FileStore?

..... nbgrader's origin is from a single instructor working with a single course, and all students logging into a common [*nux] server - it can be pulled in other directions, but it takes work [and complex configuration]

**Comment by mauro-cosentino** [comment]
I have a concern regarding the combination of Google Colab and nbgrader assignments. 
I have created an assignment and opened it in Colab and to my surprise all the  "read-only" cells were editable. Including the autograder test ones. This can be a very relevant issue since students can use colab to change the test values to make their flawed answers to pass the validation in a way that when the teacher gets the assignment back, the autograded tasks will be graded as correct. If you have a handful of students you could check them one by one and find the issue. But is you have dozens it will never be caught.

**Comment by rkdarst** [comment]
The notebook is just a file on some storage system, accessible to the
user.  nbgrader sets a 'read-only' metedata on cells, but it's up to
the editor (jupyter notebook server, colab) to use it or not.  For
some fun, you can edit cell metadata in normal jupyter notebook/lab
and make any read-write if you want.  Or open the notebook in a raw
text editor...

nbgrader might re-insert the original content back when it is being
re-processed, and it definitely will for hidden solutions.  If you
want some sort of assurance, it has to be at this level.  This is the
theory at least, I know it does something but upon looking a bit I
can't immediately convince myself it does for all of the cases I have
in my mind.  Has someone looked into this?

nbgrader isn't a captive editing system.

But for the original question... I have a teacher that tells students
they can download notebooks from our jupyterhub, upload to colab to
work, and transfer them back to jupyterhub to submit (they they have a
few other options).  There are ways that colab can break things, but
when you realize what goes on under the hood it works.  I also use
nbgrader on a multi-node system with a shared filesystem, it works if
you manage user IDs well (and some people manage without, but I
wouldn't recommend that).  As far as students work, the notebooks are
just notebooks.  Submitting/receiving is another matter, depending on
your needs you may be happy with the current situation or you may not
be.  Remember that original nbgrader relied on some other way of
distributing notebooks to students, if you build something that way
colab works like normal.
