### ISSUE TITLE
SQL Error when loading "Manage Students"

### ISSUE THREAD

**Issue by calvin1414** [jupyter/nbgrader#1291]
I am just starting to use nbgrader for the first time. I have attempted to go through the documentation to ensure I am configuring things correctly, and I have updated anaconda to the latest (2019.10), but I get errors when trying to load "Manage Assignments" and "Manage Students" in Formgrader.

### Operating system
Windows 10 1903
### `nbgrader --version`
Python version 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
nbgrader version 0.6.0
### `jupyterhub --version` (if used with JupyterHub)
not using jupyterhub
### `jupyter notebook --version` 
6.0.1
### Expected behavior
The list of students will load in the webpage when "Manage Students" is clicked
### Actual behavior
When I navigate to "Manage Students", I get the error (in the command prompt) that is attached. The page shows "Loading, please wait..."

I have also attempted to put in a test submission using the generated ps1 assignment and gone to "Manage Assignments" and clicked the submissions link. When I do, I get a similar error, also attached. 

[Error - Manage Students.txt](https://github.com/jupyter/nbgrader/files/3822101/Error.-.Manage.Students.txt)
[Error - Manage Assignments.txt](https://github.com/jupyter/nbgrader/files/3822100/Error.-.Manage.Assignments.txt)

### Steps to reproduce the behavior
I have been able to reproduce the error running the following steps.
- install a fresh installation of nbgrader 0.6.0
- run the quickstart to generate a new class
- add 2 test students from Formgrader
- navigate to "Manage Students"

These errors also occur in a real class that I am running this semester. The errors occur in multiple browsers. Other features appear to work fine.

**Comment by jhamrick** [comment]
Thanks---I think this is the same issue as #1246. This should be fixed in version 0.6.1 of nbgrader, which I just released earlier this evening. If you upgrade nbgrader it should fix the issue!
