### ISSUE TITLE
Validate/autograde notebook with dependencies

### ISSUE THREAD

**Issue by raphlogipro** [jupyter/nbgrader#1295]
hi. I want to validate/autograde notebook with 'pandas' dependency for parsing CSV file.
When validation/autograde is executed, the temporary kernel created by nbgrader doesnt load 'pandas' when i import it. I can see it when log level is on DEBUG (--ValidateApp.log_level='DEBUG')
In Jupyter user interface, i import 'pandas' with this following command: pip install --user pandas.
In validate/autograde, it is possible to use trainer kernel (with his dependencies), or specify all notebook dependencies?

--
validate logs:
[ValidateApp | DEBUG] Executing cell:
        import pandas as pd
    [ValidateApp | DEBUG] msg_type: status
    [ValidateApp | DEBUG] content: {u'execution_state': u'busy'}
    [ValidateApp | DEBUG] msg_type: execute_input
    [ValidateApp | DEBUG] content: {u'execution_count': 2, u'code': u'import pandas as pd'}
    [ValidateApp | DEBUG] msg_type: error
    [ValidateApp | DEBUG] content: {u'ename': u'ImportError', u'evalue': u"Unable to import required dependencies:\nnumpy: No module named 'numpy'", u'traceback': [u'\x1b[0;31m---------------------------------------------------------------------------\x1b[0m', u'\x1b[0;31mImportError\x1b[0m                               Traceback (most recent call last)', u'\x1b[0;32m<ipython-input-2-7dd3504c366f>\x1b[0m in \x1b[0;36m<module>\x1b[0;34m()\x1b[0m\n\x1b[0;32m----> 1\x1b[0;31m \x1b[0;32mimport\x1b[0m \x1b[0mpandas\x1b[0m \x1b[0;32mas\x1b[0m \x1b[0mpd\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[0m', u'\x1b[0;32m/home/jupyter-5de0fa121d635/.local/lib/python3.6/site-packages/pandas/__init__.py\x1b[0m in \x1b[0;36m<module>\x1b[0;34m()\x1b[0m\n\x1b[1;32m     15\x1b[0m \x1b[0;32mif\x1b[0m \x1b[0mmissing_dependencies\x1b[0m\x1b[0;34m:\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[1;32m

     16\x1b[0m     raise ImportError(\n\x1b[0;32m---> 17\x1b[0;31m         \x1b[0;34m"Unable to import required dependencies:\\n"\x1b[0m \x1b[0;34m+\x1b[0m \x1b[0;34m"\\n"\x1b[0m\x1b[0;34m.\x1b[0m\x1b[0mjoin\x1b[0m\x1b[0;34m(\x1b[0m\x1b[0mmissing_dependencies\x1b[0m\x1b[0;34m)\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[0m\x1b[1;32m     18\x1b[0m     )\n\x1b[1;32m     19\x1b[0m \x1b[0;32mdel\x1b[0m \x1b[0mhard_dependencies\x1b[0m\x1b[0;34m,\x1b[0m \x1b[0mdependency\x1b[0m\x1b[0;34m,\x1b[0m \x1b[0mmissing_dependencies\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n', u"\x1b[0;31mImportError\x1b[0m: Unable to import required dependencies:\nnumpy: No module named 'numpy'"]}

 Thanks in advance.

[notebook_pandas.zip](https://github.com/jupyter/nbgrader/files/3983662/notebook_pandas.zip)

**Comment by Sefriol** [comment]
Grader might use a different context (i.e. installing with --user tag is not sufficient). Have you tried to install this dependency globally and use the it then?

**Comment by raphlogipro** [comment]
thats right, thanks. I executed autograde on python virtual env, differently of jupyter execution context. So i use jupyter context using this following command: '. /opt/tljh/user/bin/activate && nbgrader autograde'
Thanks for all
