### ISSUE TITLE
Add a new type of cell that is not a grade cell but which should not be changed

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#131]
It would be really useful to have a distinction between grade/test cells (which have actual tests in them) and cells that just need to not change. For example, in many of my assignments we have people implement a function, and then call it on a particular set of data that's defined inline in the notebook; then they have to interpret their results. I don't want people to change the cells where we define that inline data, because that will make things a nightmare for the grader, but I also don't want to mark them as grade cells because (1) they're not worth any points, and (2) it will screw up `nbgrader validate --invert` (because those cells always pass).

In every other respect, these cells would act just like grade cells: `nbgrader validate` would warn students about changing these cells, and they would get overwritten from the saved version in the database when the autograder is run.

@ellisonbg what do you think? This would add more complexity, but would also make things a lot easier. I find myself on almost every assignment wishing that we had a cell type like this.

**Comment by ellisonbg** [comment]
I am fine with this and have run into this need myself.

On Fri, Mar 6, 2015 at 8:51 AM, Jessica B. Hamrick <notifications@github.com
> wrote:

> It would be really useful to have a distinction between grade/test cells
> (which have actual tests in them) and cells that just need to not change.
> For example, in many of my assignments we have people implement a function,
> and then call it on a particular set of data that's defined inline in the
> notebook; then they have to interpret their results. I don't want people to
> change the cells where we define that inline data, because that will make
> things a nightmare for the grader, but I also don't want to mark them as
> grade cells because (1) they're not worth any points, and (2) it will screw
> up nbgrader validate --invert (because those cells always pass).
>
> In every other respect, these cells would act just like grade cells: nbgrader
> validate would warn students about changing these cells, and they would
> get overwritten from the saved version in the database when the autograder
> is run.
>
> @ellisonbg <https://github.com/ellisonbg> what do you think? This would
> add more complexity, but would also make things a lot easier. I find myself
> on almost every assignment wishing that we had a cell type like this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/nbgrader/issues/131>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jhamrick** [comment]
Great, I'll add this at some point in the near future then.

**Comment by jhamrick** [comment]
Working on this. It will depend on #290.

**Comment by ellisonbg** [comment]
Great!

On Tue, Jun 9, 2015 at 9:11 AM, Jessica B. Hamrick <notifications@github.com
> wrote:

> Working on this. It will depend on #290
> <https://github.com/jupyter/nbgrader/pull/290>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/nbgrader/issues/131#issuecomment-110418151>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
