### ISSUE TITLE
nbconvert version 6.0.0 breaks nbgrader feedback

### ISSUE THREAD

**Issue by echuber2** [jupyter/nbgrader#1367]
Basically, nbconvert version 6.0.0 breaks nbgrader's `generate_feedback`. Need to pin nbconvert to 5.6.1 for now for compatibility.

### `nbgrader --version`
Python version 3.8.5 | packaged by conda-forge | (default, Aug 29 2020, 01:22:49) 
[GCC 7.5.0]
nbgrader version 0.6.1

### `jupyter notebook --version` 
6.1.3

### Expected behavior
Should be able to run `generate_feedback`

### Actual behavior
Can't run `generate_feedback` -- incompatibility with `HTMLExporter` from latest nbconvert (versions 6 and later)

Downgrading nbconvert to 5.6.1 resolves the issue.

### Steps to reproduce the behavior
Try using `generate_feedback` with nbconvert 6.0.0 or later installed. Note that these were in pre-release until just yesterday.

**Comment by echuber2** [comment]
Note: template system "completely revamped" https://nbconvert.readthedocs.io/en/latest/architecture.html#templates

**Comment by BertR** [comment]
Thanks for reporting this @echuber2
