### ISSUE TITLE
Partial credit -- assigning zero marks gives full credit

### ISSUE THREAD

**Issue by chinery** [jupyter/nbgrader#1374]
When returning zero from a cell as partial credit, this awards full marks, due to the use of `> 0.0` rather than `>= 0.0` in the code below:

https://github.com/jupyter/nbgrader/blob/ed98bc9ddffec5900f99e310434d6f3c8cedc9b7/nbgrader/utils.py#L87-L94

e.g. consider the following:
```
score = test_one(...)
score += test_two(...)
score += test_three(...)

score
```

This may output zero if all tests fail.

**Comment by chinery** [comment]
I have replicated this on actual submissions: student failed all tests for one question but their grade in the database was higher than it should be. Apologies if I've missed anything from this issue report – as you can guess I'm in the middle of grading submissions, so I wanted to post it quickly and get back to it!

**Comment by lwasser** [comment]
@chinery  @BertR  we are having the same issue and we just looking at the code to figure out what was happening! i see it tagged as a 0.6.2 milestone. is a fix on the way or can someone tell us if this is being addressed? Thank you so much!!

**Comment by kcranston** [comment]
Thanks for the report! This is my code, and we just independently discovered the same bug. If no one else gets to it sooner, I can submit a PR later this week. It would be ideal if the warning messages were more informative, including the cell id and the grade, so I'll include that too.
