### ISSUE TITLE
Student id with Space 

### ISSUE THREAD

**Issue by manoj1103** [jupyter/nbgrader#1403]
# Is this is a Bug in jupyter hub ?

 I couln't able to remove a student using `nbgrader db student remove <student name>`  command. if there is space between the letters like  **Student name**  in student ID the command is not working to remove that particular student.

It works well if there is no gap in Student ID.

Thanks !

**Comment by jhamrick** [comment]
You should be able to put quotes around the student id, like so: `nbgrader db student remove "jessica hamrick"`.
