### ISSUE TITLE
Jessica Hamrick PhD

### ISSUE THREAD

**Issue by Carreau** [jupyter/nbgrader#141]
Not that you are not doing good work, but I guess that will motivate you to work on something else than not-your-phd. 
- [x] Publish articles: 
  - [x] PhD
  - [ ] NbGrader
  - [ ] Jupyter/IPython
-  [x] Thesis Proposal 
- [x] Thesis outline
- [x] Draft
- [x] Writing
- [x] Submission
- [x] Defense
- [ ] Get wasted. 

I guess that a dependencies also to get a PostDoc :-)

**Comment by jhamrick** [comment]
I have a PhD now! 😸🎉👩‍🎓
