### ISSUE TITLE
Skip executing certain cells during grading

### ISSUE THREAD

**Issue by samarthbhargav** [jupyter/nbgrader#1415]
Is it possible to somehow skip execution of *some* cells during autograding. The issue I have is that there are a few cells (which train a NeuralNetwork) will take a long time to execute. The results of these cells are saved elsewhere (which is read by tests and graded). 

Perhaps a related discussion can be found [here](https://discourse.jupyter.org/t/is-there-a-cell-tag-convention-to-skip-execution/5445).

**Comment by rkdarst** [comment]
I recommend people to use environment variables or some such to detect
if the code is interactive or not.  Right now there is a
NBGRADER_VALIDATING environment variable for the validation step, but
I am not currently sure if it is set during autograding.  I guess a
test cell the beginning could modify a variable that controls the
long tests.  I know several people that use these methods to train
models only on the student side.

**Comment by jhamrick** [comment]
I think it is set for the validator only, but it would be feasible to add to the autograder too.

**Comment by jhamrick** [comment]
I think this should let you do what you want: https://github.com/jupyter/nbgrader/pull/1425

**Comment by samarthbhargav** [comment]
@rkdarst/ @jhamrick thanks!

**Comment by alessandrozocca** [comment]
One of the [FAQs](https://github.com/jupyter/nbgrader/blob/9c622c4e6c310ce6d571f7653e2d6621be00066c/nbgrader/docs/source/user_guide/faq.rst#can-i-modify-the-notebook-behavior-during-autograding-or-validation) mentions that the NBGRADER_EXECUTION environment variable could be used to skip executing some cells during autograding only. How exactly can this be done?
