### ISSUE TITLE
NBGrader Compatibility w/ Jupyter v1.3.0? We are getting HTTP 400 Errors

### ISSUE THREAD

**Issue by atnjqt** [jupyter/nbgrader#1416]
### Operating System & Jhub Environment
`cat /etc/os-release | grep PRETTY_NAME`
**CentOS Linux 7 (Core)**

`/usr/local/anaconda3/bin/nbgrader --version`
**Python version 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0]
nbgrader version 0.6.1**

`/usr/local/anaconda3/bin/jupyterhub --version` (if used with JupyterHub)
**1.3.0**

`/usr/local/anaconda3/bin/jupyter-notebook --version` 
**6.0.2**

### Expected behavior

Our NBGrader Services for various class jhub environments has worked really nicely for the past few years.

### Actual behavior

Ever since upgrading jupyter to v1.3.0 in January 2021, our Professor & NBGraders report that the service pages will occassionally throwing an HTTP 400 Error...

In order to resolve they need to clear browser cookies & cache &/or restart their jhub server instance. This is only a temporary fix as they will consistently get another 400 or 404 error after using the NBGrader services for a while...

### Steps to reproduce the behavior

Using NBGrader on system with latest jhub v 1.3.0 and work inside of a *service*... This is mainly on Chrome browser though I assume other browsers experience the same.

**Comment by jhamrick** [comment]
I'm not sure why that would be happening... if you can provide any error logs from the service when the 400 errors start happening, that might provide some clues. Or clearing cookies seems to help, then you could also try looking for errors in the javascript console.

**Comment by atnjqt** [comment]
We're just going to migrate to a new host... might be network related issues. I just thought there might be known incompatibility with NBGrader for newer versions of jhub.
