### ISSUE TITLE
Bug? Formgrader manage assignments fails to see student submission

### ISSUE THREAD

**Issue by Tebinski** [jupyter/nbgrader#1426]
### Operating system
Ubuntu 18.04 LS on AWS

### `nbgrader --version`
`/opt/tljh/user/lib/python3.7/site-packages/sqlalchemy/sql/coercions.py:308: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
  "implicitly coercing SELECT object to scalar subquery; "
Python version 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0]
nbgrader version 0.6.1
`

### `jupyterhub --version` (if used with JupyterHub)
1.2.2

### `jupyter notebook --version` 
6.1.5

### Expected behavior
Click on student submission and see the notebook.

### Actual behavior
The Formgrader freezes
![image](https://user-images.githubusercontent.com/27648596/112868676-9bf97380-90bc-11eb-8f4f-85acf2a3892a.png)

The student submission is in the `submitted` folder. 

nbgrader.log file
`
[SingleUserNotebookApp | INFO] course101 pruebita
[SingleUserNotebookApp | ERROR] Uncaught exception GET /user/tebinski/formgrader/api/submissions/pruebita (87.218.16.83)
    HTTPServerRequest(protocol='http', host='54.229.0.92', method='GET', uri='/user/tebinski/formgrader/api/submissions/pruebita', version='HTTP/1.1', remote_ip='87.218.16.83')
    Traceback (most recent call last):
      File "/opt/tljh/user/lib/python3.7/site-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/tljh/user/lib/python3.7/site-packages/tornado/web.py", line 3006, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/tljh/user/lib/python3.7/site-packages/nbgrader/server_extensions/formgrader/base.py", line 108, in wrapper
        return f(self, *args, **kwargs)
      File "/opt/tljh/user/lib/python3.7/site-packages/nbgrader/server_extensions/formgrader/base.py", line 117, in wrapper
        return f(self, *args, **kwargs)
      File "/opt/tljh/user/lib/python3.7/site-packages/nbgrader/server_extensions/formgrader/apihandlers.py", line 167, in get
        submissions = self.api.get_submissions(assignment_id)
      File "/opt/tljh/user/lib/python3.7/site-packages/nbgrader/apps/api.py", line 587, in get_submissions
        db_submissions = gb.submission_dicts(assignment_id)
      File "/opt/tljh/user/lib/python3.7/site-packages/nbgrader/api.py", line 3079, in submission_dicts
        .group_by(SubmittedAssignment.id)
      File "/opt/tljh/user/lib/python3.7/site-packages/sqlalchemy/orm/util.py", line 1192, in aliased
        adapt_on_names=adapt_on_names,
      File "/opt/tljh/user/lib/python3.7/site-packages/sqlalchemy/orm/util.py", line 495, in __init__
        mapper = insp.mapper
    AttributeError: 'CompoundSelect' object has no attribute 'mapper'
[SingleUserNotebookApp | ERROR] {
      "Host": "54.229.0.92",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "en,en-US;q=0.9,es-ES;q=0.8,es;q=0.7,fr-FR;q=0.6,fr;q=0.5",
      "Cookie": "jupyterhub-user-tebinski=[secret]; jupyterhub-session-id=[secret]; _xsrf=[secret]",
      "Referer": "http://54.229.0.92/user/tebinski/formgrader/manage_submissions/pruebita",
      "X-Csrftoken": "2|efb61685|6c9b4273b9375741e0ad157d569a83f7|1617031486",
      "X-Forwarded-For": "87.218.16.83",
      "X-Forwarded-Host": "54.229.0.92",
      "X-Forwarded-Port": "80",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Server": "ip-172-31-17-246",
      "X-Real-Ip": "87.218.16.83",
`

**Comment by myedibleenso** [comment]
Hi, @Tebinski.  We actually observed the same issue.  This seems to have already been fixed on `master` (Maybe in [this PR](https://github.com/jupyter/nbgrader/pull/1420)?).  Until the next release, you might consider installing from `master`.

**Comment by jhamrick** [comment]
Thanks @myedibleenso. Indeed installing from master ought to help. You might also be able to get away with installing an older version of SQLAlchemy (less than 1.4, which is the upgrade that caused issues).

**Comment by Tebinski** [comment]
Correct! Reinstalling nbggrader in my JupyterHub as  following solve the problem

```
sudo -H python -m pip install git+https://github.com/jupyter/nbgrader.git
sudo -H jupyter nbextension install --sys-prefix --py nbgrader --overwrite
sudo -H jupyter nbextension enable --sys-prefix --py nbgrader
sudo -H jupyter serverextension enable --sys-prefix --py nbgrader
``` 

Thanks a lot!
