### ISSUE TITLE
Way to limit memory used during execution of a cell

### ISSUE THREAD

**Issue by parthjoshi2007** [jupyter/nbgrader#1429]
### Operating system
Linux

### `nbgrader --version`
Python version 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 09:07:38)
[GCC 7.3.0]
nbgrader version 0.6.1

### `jupyterhub --version` (if used with JupyterHub)
1.0.0

### `jupyter notebook --version` 
5.7.8

Is there any configuration option to limit the amount of memory consumed during cell execution? For execution time, I know I can use `ExecutePreprocessor.timeout` but I did not find any such option for maximum memory consumption.

I'm asking because I recently came across a situation where a student un-familiar with generators in Python was converting the generator into a massive list causing the kernel to get killed due to OOM issues. This prevented me from being able to autograde his assignment. I finally figured this out and resolved the issue by modifying his submission manually but I've since been looking for a way to prevent this from happening again. If this is not there currently, is this something that could be implemented? I'd be happy to help in any way I can.

**Comment by perllaghu** [comment]
This seems to be more of an issue for the notebook itself, rather than nbgrader.

I suggest you look to https://github.com/jupyter/notebook for help on that

**Comment by jhamrick** [comment]
Yes, unfortunately I agree with @perllaghu that this is something that would need to be dealt with by the kernel or the notebook rather than nbgrader itself.
