### ISSUE TITLE
Please allow post-iron age versions of nbconvert and traitlets

### ISSUE THREAD

**Issue by martenwa** [jupyter/nbgrader#1447]
The newly released nbgrader-0.6.2 still enforces really old versions `nbconvert==5.6.1` and `traitlets==4.3.3` in `setup.py`. What is expected to break in newer versions of those packages?

[nbgrader-0.6.2-allow-recent-nbconvert-and-traitlets.patch.txt](https://github.com/jupyter/nbgrader/files/6451519/nbgrader-0.6.2-allow-recent-nbconvert-and-traitlets.patch.txt)

(Here, nbgrader seems to work just fine with `nbconvert==6.0.7` and `traitlets==5.0.5`)

**Comment by kno10** [comment]
By now, this makes nbgrader installation a PITA.
ipython 8.2.0 has requirement traitlets>=5, but you'll have traitlets 4.3.3 which is incompatible.
ipykernel 6.13.0 has requirement traitlets>=5.1.0, but you'll have traitlets 4.3.3 which is incompatible.

Is there any documentation on the version requirements for the last nbgrader release?
