### ISSUE TITLE
How to add a submit button directly in jupyter notebook ? 

### ISSUE THREAD

**Issue by cleliofavoccia** [jupyter/nbgrader#1453]
### Operating system
Ubuntu 20.10
### `nbgrader --version`
0.7.0.dev
### `jupyterhub --version` (if used with JupyterHub)
1.4.1
### `jupyter notebook --version` 
6.4.0
### Expected behavior
Have a submit button directly in notebook
### Actual behavior
I don't see how to add a submit button directly in notebook. Fetching will be manage by a script.

**Comment by BertR** [comment]
Maybe you could add the command you would use in the terminal as a cell in your notebook,?

**Comment by jhamrick** [comment]
Just adding a comment to clarify, as assignments are defined by a *collection* of notebooks, I think it could be confusing to add a submit button to the notebook itself. But there is a submit button in the assignment list extension that submits the entire assignment.
