### ISSUE TITLE
Nbgrader example setup + Documentation 

### ISSUE THREAD

**Issue by octavd** [jupyter/nbgrader#1454]
Hello,

First of all, thank you very much for this tool, it looks very interesting and i want to setup at work an env for future canditates to have a python quiz on it.

Secondly, i've tried to setup just a basic example on Windows or Mac or Docker container, basic example meaning the following i am an instructor, i have 1 student and i want that student to complete a python notebook where he just needs to answer to a question with a print("hey") and i find it extremely difficult using the current documentation (either it cannot create that exchange folder, either it cannot write in the /srv/nbgrader/ etc). I've tried to search on youtube or git for documentation and it felt the official one was incomplete and also looked for some examples(just like a said above because afterwards i can make real life examples) and after finding just 1-2, neither one works. :(

It's possible to have a more explained documentation or just a extremly basic working example?

Best regards,
Octavian

**Comment by BertR** [comment]
Hi @octavd,

Here's an example of how you could set up a test environment for nbgrader.
It assumes you have python 3 and pip installed.

```bash
# Create a new directory to host your file
mkdir -p /tmp/nbgrader-demo
# Create a directory for the exchange
mkdir -p /tmp/nbgrader-demo/exchange
```

Create a file called `nbgrader_config.py` in the first directory you created (/tmp/ngrader-demo in the example)
and add the following configuration:
```python
c = get_config()

c.NbGrader.course_id = "demo"  
c.Exchange.root = "/tmp/nbgrader-demo/exchange"
```

Enable the nbgrader extensions:

```bash
jupyter nbextension install --sys-prefix --py nbgrader
jupyter nbextension enable --sys-prefix create_assignment/main

jupyter nbextension enable --sys-prefix validate_assignment/main --section=tree
jupyter serverextension enable --sys-prefix nbgrader.server_extensions.validate_assignment

jupyter nbextension enable --sys-prefix formgrader/main --section=tree
jupyter serverextension enable --sys-prefix nbgrader.server_extensions.formgrader

jupyter nbextension enable --sys-prefix assignment_list/main --section=tree
jupyter serverextension enable --sys-prefix nbgrader.server_extensions.assignment_list
```

Next you can start your notebook and nbgrader should be available!

```bash
jupyter notebook
```
