### ISSUE TITLE
student is not allowed to enter a course in jupyterhub although allowed in jupyterhub and added to the course

### ISSUE THREAD

**Issue by benpolman** [jupyter/nbgrader#1479]
### jupyter notebook 6.4.3

jupyterhub is running as root to be able to run different courses as different users.
Am using c.Authenticator.plugin_class = JupyterHubAuthPlugin in nbgrader_config.py

I have created two courses as services in jupyterhub_config.py each with own user and 
formgrade and nbgrader groups
Relevant piece out of jupyterhub_config.py
```
c.JupyterHub.load_groups = {
    'formgrade-course101': [
        'instructor1'
        'grader101'
    ],
    'formgrade-course123': [
        'instructor2'
        'grader123'
    ],
    'nbgrader-course101': [],
    'nbgrader-course123': []
}

c.JupyterHub.services = [
    {
        'name': 'course101',
        'url': 'http://127.0.0.1:9999',
        'command': [
            'jupyterhub-singleuser',
            '--group=formgrade-course101',
            '--debug',
        ],
        'user': 'grader101',
        'cwd': '/vol/jupyter/grader-course101',
        'api_token': 'some secret string'  # include api token from admin user
    },
  { second entry ...
  }
]
```

As instructor I can add student1 (local unix account) to the course and  add an assignment.

The student1 account can login to jupyterhub, sees the services tab with the 2 courses but as soon as you select
the course to which I have added the account, it asks for Authorization access to the service as a jupyterhub user
and after accepting it throws an

 **Error 403: Forbidden.  user student1 is not allowed** 

Debugging info has lead me to the source of the error in
 lib/python3.8/site-packages/jupyterhub/services/auth.py
the group intersection fails:
       elif self.hub_groups and set(model['groups']).intersection(self.hub_groups):

```
[SingleUserNotebookApp | DEBUG] Received request from Hub user {'kind': 'user', 'name': 'student1', 'admin': False, 'groups': ['nbgrader-course101'], 'server': None, 'pending': None, 'created': '2021-07-15T16:03:38.081796Z', 'last_activity': '2021-08-18T10:10:47.294400Z', 'servers': None}
[SingleUserNotebookApp | INFO] Logged-in user {'kind': 'user', 'name': 'student1', 'admin': False, 'groups': ['nbgrader-course101'], 'server': None, 'pending': None, 'created': '2021-07-15T16:03:38.081796Z', 'last_activity': '2021-08-18T10:10:47.294400Z', 'servers': None}
[SingleUserNotebookApp | DEBUG] Setting oauth cookie for 131.174.139.92: service-course101, {'path': '/services/course101/', 'httponly': True, 'secure': True}
[SingleUserNotebookApp | INFO] 302 GET /services/course101/oauth_callback?code=[secret]&state=[secret] -> /services/course101/tree? (@131.174.139.92) 36.26ms
[SingleUserNotebookApp | WARNING] model groups: nbgrader-course101
[SingleUserNotebookApp | WARNING] groups: formgrade-course101
[SingleUserNotebookApp | WARNING] Not allowing Hub user student1
```

where I have added the printing of groups and model groups in auth.py

What am I missing ? Clearly student1 should be only in nbgrader-course101, which he is.

**Comment by ashriram** [comment]
I am also encountering this issue trying to set up the demo one class multiple graders. 
Setup: docker.

**Comment by sigurdurb** [comment]
If you are using Jupyterhub > v.1, I am using 1.5, then
you need to add a token and then add the same token to the 'api_token' down by the service.
Make sure the token is generated for an admin user.
But add it with the username for who is suppose to get in:
c.JupyterHub.api_tokens.update({u'jupyterhub admin token':'grader101'})
That should solve that issue.

> The student1 account can login to jupyterhub, sees the services tab with the 2 courses

I am not sure I understand your setup.
The course should have a special account on your server.
Other user accounts, like for students, should be added to the 'nbgrader-course101' variable,
and after you follow the installation for the nbgrader install nb and serverextensions, they should
see their course assignments in their assignment list. No need for them to go to the formgrader service; that is only for the teacher/grader to send out assignments.

**Comment by sigurdurb** [comment]
<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">This table should clarify which extension to enable when you have separate services for the formgraders.</p>

  | Students | Instructors | Formgraders
-- | -- | -- | --
Create Assignment | no | no | yes
Assignment List | yes | yes | no
Formgrader | no | no | yes
Course List | no | yes | no

Following the best practice above. And if this is your jupyterhub running as root (Please check the installation docs)

```
jupyter nbextension install --sys-prefix --py nbgrader --overwrite
jupyter nbextension enable --sys-prefix --py nbgrader
jupyter serverextension enable --sys-prefix --py nbgrader

jupyter nbextension disable --sys-prefix formgrader/main --section=tree
jupyter serverextension disable --sys-prefix nbgrader.server_extensions.formgrader

jupyter nbextension disable --sys-prefix course_list/main --section=tree
jupyter serverextension disable --sys-prefix nbgrader.server_extensions.course_list

jupyter nbextension disable --sys-prefix create_assignment/main
```


Then this should be run as the teacher or grading users, i.e. "su grader101"

```
jupyter nbextension enable --user course_list/main --section=tree
jupyter serverextension enable --user nbgrader.server_extensions.course_list
```

And as the course unix user:
```
jupyter nbextension disable --user assignment_list/main --section=tree
jupyter serverextension disable --user nbgrader.server_extensions.assignment_list

jupyter nbextension enable --user create_assignment/main
```
For the latest instructions follow the [nbgrader installation guide](https://nbgrader.readthedocs.io/en/latest/user_guide/installation.html)

**Comment by jhamrick** [comment]
I am closing this issue because there hasn't been any activity on it in a while. However, if you (or others) continue to encounter problems, feel free to comment here or open a new issue!
