### ISSUE TITLE
The course id has not been set in nbgrader_config.py. The "release" and "collect" functionality will not be available. Please see the documentation on Setting Up The Exchange for instructions.

### ISSUE THREAD

**Issue by yonghuming** [jupyter/nbgrader#1522]
### Operating system
ubuntu 18l08
### `nbgrader --version`
```
Python version 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0]
nbgrader version 0.6.2
```
### Expected behavior
formgrader release button avilable.
### Actual behavior
release not avilable.
### Steps to reproduce the behavior
![image](https://user-images.githubusercontent.com/435079/140929690-ac39e701-999a-4449-b7e6-f098756349fd.png)

i just do not know which nbgrader_config.py to modify. 
![image](https://user-images.githubusercontent.com/435079/140929842-ccf284e8-afa6-4b00-8ef0-bf539dffc53e.png)

i just do this as the n Setting Up The Exchange  indicate.
but it still show `The course id has not been set in nbgrader_config.py. The "release" and "collect" functionality will not be available. Please see the documentation on Setting Up The Exchange for instructions.`
 I have spent lots of time on this problme. anyone could help me?

**Comment by szazs89** [comment]
How did you start jupyter? From commandline, as `jupyter-notebook`? Then in the same directory...
(If you are using jupyter with jupyterhub then maybe in the `$HOME/.jupyter` folder.)

**Comment by jhamrick** [comment]
Yes, as suggested by @szazs89 you need to modify the config file that's in the folder where the notebook is started, or a global config file. You can see where Jupyter will look for configs by running `jupyter --paths`.

**Comment by yonghuming** [comment]
您好，邮件已经收到
