### ISSUE TITLE
Accessing gradebook and removing a submission

### ISSUE THREAD

**Issue by mmann1123** [jupyter/nbgrader#1524]
I have an issue where I collected and graded submissions but now need to update the original assignment. I can't however seem to remove the previous collected and graded submissions from the student from the database (despite removing notebook from the submitted folder) 

Hoping to figure out how to do this with someone's help. 

But would it be possible to add more examples of controlling the gradebook to the docs? For instance [this section](https://nbgrader.readthedocs.io/en/stable/user_guide/what_is_nbgrader.html?highlight=gradebook#gradebook-db-and-student-management) might have an example of the api use

**Comment by szazs89** [comment]
I guess you should remove the whole assignment from the database from the commandline:
```
nbgrader db assignment remove {assignment} --force
```
after that you can Generate, Release, etc. it again, IMHO.

**Comment by jhamrick** [comment]
I am closing this issue because there hasn't been any activity on it in a while. However, if you (or others) continue to encounter problems, feel free to comment here or open a new issue!
