### ISSUE TITLE
Proposal: remove solution cells

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#153]
I think the concept of solution cells is confusing, because you can just make the solution region (e.g. with `### BEGIN SOLUTION`), and so then it's less clear what the difference between solution cells and grade cells is. I propose getting rid of the solution cell checkbox, and just requiring people to use the solution region annotation. Then, in the cell toolbar, we can change the "grade?" checkbox to be different for markdown vs code cells:

* for markdown cells, the label should be something like "written answer?"
* for code cells, the label should be something like "tests for code answer?"

Under the hood, we'll still have the concept of solution cells and grade cells, but I think in the UI the different pieces are just confusing.

For my proposed new cell type (#131), we could add a checkbox that has a label saying "prevent edits?" or something like that. It would automatically get checked on code cells that are grade cells, and would be impossible to check on markdown cells that are grade cells.

@ellisonbg what are your thoughts on this?

**Comment by ellisonbg** [comment]
Jess,

Yes, I think this is a good idea. I have always had trouble understanding
the difference between "solution" and "grade". I like the idea of having
different labels for code/md cells. Maybe something like:

* "Grade this cell for code tests"
* "Grade written answer"

?

On Mon, Mar 16, 2015 at 1:07 PM, Jessica B. Hamrick <
notifications@github.com> wrote:

> I think the concept of solution cells is confusing, because you can just
> make the solution region (e.g. with ### BEGIN SOLUTION), and so then it's
> less clear what the difference between solution cells and grade cells is. I
> propose getting rid of the solution cell checkbox, and just requiring
> people to use the solution region annotation. Then, in the cell toolbar, we
> can change the "grade?" checkbox to be different for markdown vs code cells:
>
>    - for markdown cells, the label should be something like "written
>    answer?"
>    - for code cells, the label should be something like "tests for code
>    answer?"
>
> Under the hood, we'll still have the concept of solution cells and grade
> cells, but I think in the UI the different pieces are just confusing.
>
> For my proposed new cell type (#131
> <https://github.com/jupyter/nbgrader/issues/131>), we could add a
> checkbox that has a label saying "prevent edits?" or something like that.
> It would automatically get checked on code cells that are grade cells, and
> would be impossible to check on markdown cells that are grade cells.
>
> @ellisonbg <https://github.com/ellisonbg> what are your thoughts on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/nbgrader/issues/153>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
