### ISSUE TITLE
Adopt the Jupyter Releaser

### ISSUE THREAD

**Issue by jtpio** [jupyter/nbgrader#1570]
It would be great if we could start using the Jupyter Releaser for making new releases: https://jupyter-releaser.readthedocs.io/en/latest/

The releaser is already being used in many projects. Using it for `nbgrader` would be great for consistency and would make the setup similar to the other projects.

The checklist for adoption: https://jupyter-releaser.readthedocs.io/en/latest/how_to_guides/convert_repo.html

**Comment by jhamrick** [comment]
That's a great idea, I didn't know about Jupyter Releaser.

If you start using it could you update the releasing docs accordingly too? (They may also be helpful in ensuring all the release steps are followed when switching to Jupyter Releaser): https://nbgrader.readthedocs.io/en/stable/contributor_guide/releasing.html

**Comment by brichet** [comment]
I can start setting up the Jupyter Releaser.
I don't know if I need special permissions on this repository. I'll let you know.

**Comment by jtpio** [comment]
Thanks @brichet.

We should be able to start with a draft PR, by adding the config files and the `check-release` CI workflow like that one: https://github.com/jupyter-server/jupyter_server/blob/main/.github/workflows/check-release.yml

The check release workflow will help us know if the repo is correctly setup and ready to be released with the releaser.
