### ISSUE TITLE
Rename the default branch to `main`

### ISSUE THREAD

**Issue by jtpio** [jupyter/nbgrader#1578]
Most of the other Jupyter repositories have now switch to `main` as their default branch.

Opening this issue for visibility. If someone would like to go ahead and do the renaming feel free! Otherwise we can give it a couple of days until 0.7.0 stabilizes before doing it.

It should now be relatively straightforward using the GitHub UI, which will update the PR automatically:

![image](https://user-images.githubusercontent.com/591645/167431029-1932b291-b38b-4b98-8696-65e8d25b9fe2.png)

We can then post a quick message here to let folks know how to update their forks, similar to https://github.com/jupyter/notebook/issues/6295. And pin the issue to increase visibility and awareness about this change.

**Comment by jhamrick** [comment]
I've now renamed master to main. To update forks to have the `main` branch too:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by jtpio** [comment]
Nice, thanks!

**Comment by jtpio** [comment]
cc @brichet for awareness
