### ISSUE TITLE
Enable the ReadTheDocs PR Preview

### ISSUE THREAD

**Issue by jtpio** [jupyter/nbgrader#1580]
The ReadTheDocs PR Preview feature is really useful to automatically build the docs when a new PR is opened.

We should consider enabling it for this repo. This would make reviewing documentation changes easier without having to build the changes locally. For example for https://github.com/jupyter/nbgrader/pull/1577 which updated the way the changelog is handled.

Documentation on RTD: https://docs.readthedocs.io/en/stable/pull-requests.html

![pr-preview](https://docs.readthedocs.io/en/stable/_images/github-build-status-reporting.gif)

**Comment by jtpio** [comment]
cc @jhamrick @BertR who might have access to the project on ReadTheDocs.

This should be available under the Advanced Settings:

![image](https://user-images.githubusercontent.com/591645/168024876-aa955b26-bb01-43ee-be46-8b1d4f49990e.png)

**Comment by jhamrick** [comment]
I enabled the setting!

**Comment by jtpio** [comment]
Thanks!

Looks like the check is not visible though, for example on the recent https://github.com/jupyter/nbgrader/pull/1584:

![image](https://user-images.githubusercontent.com/591645/168989079-1f0fdd90-8731-44d0-a6df-82335d639814.png)

Not sure there is something else to enable to make it visible.

**Comment by jhamrick** [comment]
Yeah, I just tried refreshing the web hook from the github side so
hopefully it will work now?
