### ISSUE TITLE
Tests on nbextensions are broken with latest selenium version (4.3.0)

### ISSUE THREAD

**Issue by brichet** [jupyter/nbgrader#1612]
The latest version of `selenium 4.3.0` breaks the nbextensions tests with the following error :
`E           AttributeError: 'WebDriver' object has no attribute 'find_elements_by_css_selector'`

This has been fixed in `main` branch in https://github.com/jupyter/nbgrader/pull/1611 by pinning `selenium < 4.3`, as the main branch is no longer supposed to support nbextensions.

This issue should be fixed in  the branch `0.7.x`.

**Comment by jtpio** [comment]
This seems to be related to the removal of previously deprecated methods:

> * Deprecated find_element_by_* and find_elements_by_* are now removed (#10712)

https://github.com/SeleniumHQ/selenium/blob/2fbfc62f565026ba57cf700e14179012c6ebef4c/py/CHANGES#L2

Probably we can remove the pin and update the code to the new API as mentioned in the docstring:

> Please use find_element(by=By.CSS_SELECTOR, value=css_selector) instead",

**Comment by brichet** [comment]
Fixed in https://github.com/jupyter/nbgrader/pull/1677
