### ISSUE TITLE
upgrade nbclassic to version 0.4.0

### ISSUE THREAD

**Issue by brichet** [jupyter/nbgrader#1622]
`nbclassic` in version `0.4.0` breaks `nbgrader` with labextensions :
- it seems that the `mathjax-url` settings of the handler in not populated anymore.
- it break the installation of server extensions in dev mode (maybe only if `notebook<7` is also installed).

The first issue should be fixed at least, as `notebook<7` is not supposed to be supported anymore.

**Comment by goekce** [comment]
The nbclassic seems to be upgraded now:

https://github.com/jupyter/nbgrader/blob/eb1c19ab2be5e1192ee873925d5dd497f1811af9/pyproject.toml#L43

I had also Mathjax 404 problems, but after doing a fresh `pip install git+https://github.com/jupyter/nbgrader` the math symbols are rendered again.

**Comment by brichet** [comment]
Right, thanks @goekce
