### ISSUE TITLE
open github  discussions

### ISSUE THREAD

**Issue by WolfgangFahl** [jupyter/nbgrader#1627]
### Expected behavior
Github discussions should be active
### Actual behavior
not active
### Steps to reproduce the behavior
visit https://github.com/jupyter/nbgrader

**Comment by jtpio** [comment]
Thanks @WolfgangFahl.

I just checked and it looks like someone has enabled the GitHub Discussions now: https://github.com/jupyter/nbgrader/discussions

Closing as completed!
