### ISSUE TITLE
No Assignment and Courses Tab after Installation

### ISSUE THREAD

**Issue by FaustAnna** [jupyter/nbgrader#1652]
Hi there,

I use a Windows,
with the latest version of nbgrader (How do I check for the nbgrader version?)
Jupyter Notebook -- 3.9.7

I just installed nbgrader via Anaconda. After launching Jupyter Notebook I expect to see the new tabs "Formgrader", "Assignments" and "Courses".
However, I can see only the "Formgrader" tab - the "Assignments" and "Courses" tabs are missing.

Any suggestions what I can do here?
Many thanks in advance!

**Comment by slel** [comment]
Sorry I cannot help, but please change "Assingment" to "Assignment" in the issue title and description.

**Comment by brichet** [comment]
Hi,
You can get the nbgrader version with `nbgrader --version` command.
Can you copy the result of `jupyter --version` please ?

**Comment by FaustAnna** [comment]
Asking for the nbgrader version results in:
"Python version 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
nbgrader version 0.6.2"

Asking for the jupyter version results in:

"Selected Jupyter core packages...
IPython          : 7.34.0
ipykernel        : 6.4.2
ipywidgets       : 7.6.5
jupyter_client   : 6.1.12
jupyter_core     : 4.10.0
jupyter_server   : 1.18.1
jupyterlab       : 3.4.4
nbclient         : not installed
nbconvert        : 5.6.1
nbformat         : 5.3.0
notebook         : 6.4.12
qtconsole        : 5.3.1
traitlets        : 4.3.3"

**Comment by brichet** [comment]
`nbgrader` is currently in version `0.7.1`
If you don't specifically need version `0.6.2`, you can try installing the latest version. This version breaks some dependencies, you should to use a new environment to install it properly.

**Comment by FaustAnna** [comment]
If I use "conda install -c conda-forge nbgrader" to install nbgrader, I automatically end up with the verssion 0.6.2. 
Is there another way to install or update nbgrader?

**Comment by brichet** [comment]
You can specify the version in conda : `conda install nbgrader=0.7.1`

Or use pip : `pip install nbgrader==0.7.1`.

I can't test on Windows, but on Linux the default version is the last one.

**Comment by FaustAnna** [comment]
I updated nbgrader to version 0.7.1 
Unfortunately there are still no "Assignments" and "Courses" tabs.

Do you have any other ideas how to tackle this problem?

**Comment by jhamrick** [comment]
Unfortunately the Assignment List and Course List extensions are not supported on Windows, as they rely on the "exchange" functionality which is linux-only. This is why you are not seeing those extensions.

**Comment by brichet** [comment]
Closing as expected, exchange is not supported on Windows
