### ISSUE TITLE
Trouble with nbextensions on littlest jupyterhub

### ISSUE THREAD

**Issue by ebatty** [jupyter/nbgrader#1659]
nbgrader version 0.8.0
jupyterhub version 1.5.0

**Overview:** Can't get any of the nbextensions like formgrader working on littlest jupyterhub instance. Installing nbgrader seems to permanently mess up nbextensions

I set up a littlest jupyterhub instance on AWS following their instructions (https://tljh.jupyter.org/en/latest/install/amazon.html)

I opened a terminal as the admin user to install nbgrader (again, following their instructions on how to pip install packages)

First, I check that juptyer nbextension works:
`jupyter nbextension list`
Returns what I expect, the config directory and some info.

Then I install nbgrader: `sudo -E pip install nbgrader`

Formgrader tab doesn't show up even after restarting the server so I check the nbextension list:

Now `jupyter nbextension list` returns "Jupyter command `jupyter-nbextension` not found."

The only thing I did between the two calls to jupyter nbextension was install nbgrader

**Comment by brichet** [comment]
Thanks for reporting this. 
I can't reproduce it without AWS account.

As *nbgrader* is installed as *root*, can you try `sudo -E jupyter nbextension list` ?

Can you also copy/paste the return of the command `jupyter --version` before and after installation ?
