### ISSUE TITLE
Give visual feedback if grader inputs value outside of range

### ISSUE THREAD

**Issue by suchow** [jupyter/nbgrader#166]
(Right now it autocorrects, placing the value at the top of the range.)

**Comment by jhamrick** [comment]
What kind of visual feedback are you thinking of?

**Comment by suchow** [comment]
Something similar to the form validation that happens on sites where you enter in a credit card checksum. Flash a red border or something like that? The concern is that, without the visual indication, the grader might enter 0.25 instead of 0.025 for a question worth 0.1, accidentally giving full credit instead of very partial credit.

**Comment by jhamrick** [comment]
Ok, yeah, I like that idea :+1:
