### ISSUE TITLE
nbgrader+jupyterhub for multiple graders: no links to assignments in 'Manage Assignments' (formgrader)

### ISSUE THREAD

**Issue by ronligt** [jupyter/nbgrader#1660]
### Operating system

Ubuntu 20.04.05 LTS

### `nbgrader --version`

Python version 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0]

nbgrader version 0.8.0

### `jupyterhub --version` (if used with JupyterHub)

2.3.1

### `jupyter notebook --version` 

6.4.12

### Expected behavior

In the formgrader page Manage Assignments there is a list with the available assignments. When clicking on the title a new tab opens up with Notebook tree of the assignment

### Actual behavior

Although the title appears to be a link there is no `href` inside the tag and nothing happens when clicking on the title.

### Steps to reproduce the behavior

Follow instructions from the nbgrader demo: <https://nbgrader.readthedocs.io/en/stable/configuration/jupyterhub_config.html#example-use-case-one-class-multiple-graders>

### Possible cause

When turning on "Prevent cross-site tracking" in Safari (v15.6.1) the links are working correctly. This might indicate that there is a problem with cross-site linking. Maybe this is caused by the setup of the 'multiple graders' where a new service is configured in `jupyterhub_config.py`. I do not have enough experience with configuring JupyterHub to solve this issue.

**Comment by ronligt** [comment]
This issue has been solved switching over to JupyterLab.

**Comment by christina-seegers** [comment]
> This issue has been solved switching over to JupyterLab.

Could you explain what switching over to JupyterLab implies? 
I would like to do the same but just exchanging the notebook image with a JupyterLab image did not help.
