### ISSUE TITLE
Better installation of the nbextension

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#167]
@Carreau suggests adding something like `nbgrader install-nbextension` and then activate it by modifying a json config file?

**Comment by Carreau** [comment]
Partially wrote relevant docs while trying to figure it out. 

http://carreau.gitbooks.io/jupyter-book/content/Jsextensions.html

**Comment by Carreau** [comment]
Still some weird stuff in the js config :-P

**Comment by jhamrick** [comment]
Closed by #168
