### ISSUE TITLE
Installation: Enabling nbgrader server extension requires sudo?

### ISSUE THREAD

**Issue by startakovsky** [jupyter/nbgrader#1679]
Hello, Attached is an image of the error I am getting. I cannot, unfortunately, figure out how to install this tool so I can then edit assignments while I am offline. It feels a little too complicated.

<img width="571" alt="image" src="https://user-images.githubusercontent.com/689723/193621401-4916af57-cc70-41f9-bbd4-74162a835a00.png">

### Operating system

Mac OS Monterey

### `nbgrader --version`

Python version 3.7.13 (default, Sep  8 2022, 01:42:26)
[Clang 13.0.0 (clang-1300.0.29.30)]
nbgrader version 0.8.1

### `jupyter notebook --version` 

6.4.12

### Expected behavior

No sudo necessary with jupyterhub extension enabling, but is required with jupyter server

### Actual behavior

Error without sudo

### Steps to reproduce the behavior

`jupyter server extension enable --system --py nbgrader`

**Comment by martenwa** [comment]
Try with `--user` instead of `--system` (which naturally requires sudo rights), for instance:

    jupyter nbextension install --user --py nbgrader --overwrite
    jupyter nbextension enable --user --py nbgrader
    jupyter serverextension enable --user --py nbgrader
