### ISSUE TITLE
Notebooks with "raw" cells cannot be opened for manual grading

### ISSUE THREAD

**Issue by davidnero** [jupyter/nbgrader#1680]
### Operating system
Ubuntu 20.02 on WSL2

### `nbgrader --version`
0.7.1

### `jupyter notebook --version` 
6.4.12

Submissions with a "raw" cell can be autograded, but cannot be opened for manual grading, instead causing the error
    `Uncaught exception GET /formgrader/submissions/<submission id>/ (127.0.0.1)`
The traceback ends with
    `lxml.etree.ParserError: Document is empty`

Removing the "raw" cell from the notebook and autograding again allows it to be opened for manual grading as usual.

**Comment by tuncbkose** [comment]
Can't replicate on latest version

**Comment by brichet** [comment]
@davidnero can you confirm if the issue is still there on latest version ?

**Comment by davidnero** [comment]
Sorry, it's been two years since I've used nbgrader, and I don't have easy access to the student notebooks that caused the issue anymore. 

It's good news if it's fixed. I have no objections if you want to close the issue.
