### ISSUE TITLE
Installation: nbgrader menus don't show up in jupyterhub

### ISSUE THREAD

**Issue by kliegr** [jupyter/nbgrader#1681]
### Operating system
Ubuntu 20.04.5 LTS
### `nbgrader version`
0.8.1
### `jupyterhub version` (if used with JupyterHub)
1.5.0 20220918101831
### `jupyter notebook --version` 
6.4.12
### Expected behavior
after `pip install nbrader` the Jupyter hub web UI contains Formgrader, Courses and Assignment menus
### Actual behavior
Neither of the nbgrader-specific menus shows up
### Steps to reproduce the behavior
I have also tried installing with "sudo" and activating the server extensions manually as described in https://nbgrader.readthedocs.io/en/stable/user_guide/installation.html
with no result. No error is reported during the installation or activation of the extensions.

**Comment by brichet** [comment]
Thanks for reporting this issue.

Are you running it in Classic Notebook or JupyterLab ?

Can you copy the return of the following commands :
```
jupyter nbextension list
```
and 
```
jupyter labextension list
```

**Comment by kliegr** [comment]
Hi, we resolved this. It looks like this was caused by a mismatch between the version of nbgrader and the changes in configuration files between nbgrader versions 0.7.1 a 0.8.0.
