### ISSUE TITLE
Students deleting grade cells causes formgrader to report "needs manual grading" forever

### ISSUE THREAD

**Issue by trevorcampbell** [jupyter/nbgrader#1682]
Hi nbgrader team,

(I'm using nbgrader 0.7.1 on ubuntu 22.04)

I've found that students sometimes accidentally delete grade cells (yes, they're read-only; with a class of 800 students, *someone* always manages to do this, even after disabling keyboard shortcuts, educating them about the perils of changing read-only cells, etc).

If this happens, formgrader will say "needs manual grading". But the TAs cannot do anything about it, since they can't see the cell in formgrader as it was removed from the notebook. To them it looks like grading is done, even though formgrader thinks it isn't. 

Proposed solution idea:
- during autograding, check if any grade cells are missing in the notebook
- try to re-insert them if the cells are otherwise all there and in the right order (or sufficiently many around the place where that missing cell should be)
- if nbgrader can't determine where the cell should go (e.g. if the student has mangled the notebook sufficiently), then assign a score of 0 and move on. Or perhaps add the cell at the end of the notebook.

**Comment by tuncbkose** [comment]
@trevorcampbell If this is still an issue, would you mind taking a look at [this branch](https://github.com/AaltoSciComp/nbgrader/tree/missing_cells) and autograde using `nbgrader autograde {whatever} --OverwriteCells.add_missing_cells=True`?

**Comment by tuncbkose** [comment]
I've done this quick-test already, and it seems to work fine. 

One clarification: I am guessing that you are referring to the "Needs Manual Grading" check mark. I observe that the problem being that when a grade cell is missing, the notebook is always marked "Need Manual Grading", even if all the present grade cells are graded. So we want the check mark to disappear, which is the opposite of what you are describing.

Am I misunderstanding/missing something? In either case, I'll make a pr to hopefully get more feedback from others and link it to this issue.

**Comment by trevorcampbell** [comment]
> One clarification: I am guessing that you are referring to the "Needs Manual Grading" check mark. 

Yes, sorry -- that was my mistake. I haven't used it in a bit :) your description of it is correct.

**Comment by nthiery** [comment]
I have been regularly struck by this issue with my 200+ course, and #1770 
sounds very promising! I am looking forward having it in production for the
next iteration of the course in Fall.
