### ISSUE TITLE
where can I find complete list of formgrader API urls

### ISSUE THREAD

**Issue by adarshverma19** [jupyter/nbgrader#1685]
I am integrating nbgrader into my LMS. In my LMS backend, I am using formgrader URLs like 

1. formgrader/api/assignment/{assignment_name}/generate_feedback"
2. formgrader/api/assignment/{assignment_name}/release_feedback"
3. formgrader/api/assignments

to fetch details and perform some actions directly from my LMS frontend. 

These are URLs that I found out myself by using chrome debugger tools 
**I need one for auto-grading all assignments.** 
I only found the one that auto grades for a single student, like so

- /formgrader/api/submission/{assignment_name}/{student_name}/autograde

Where can I find the entire list of formgrader endpoints(URLs) and their documentation?

**Comment by brichet** [comment]
Hey @adarshverma19, I don't think the endpoints are documented yet.
You can find all the URLs in [the directory containing the server extensions](https://github.com/jupyter/nbgrader/tree/main/nbgrader/server_extensions), in the `handlers.py` files.

**Assignment list handlers**
https://github.com/jupyter/nbgrader/blob/066e793fb973b8ed03ea222a28c81950361edc94/nbgrader/server_extensions/assignment_list/handlers.py#L366-L371

**Course list handlers**
https://github.com/jupyter/nbgrader/blob/066e793fb973b8ed03ea222a28c81950361edc94/nbgrader/server_extensions/course_list/handlers.py#L224-L226

**Formgrader API handlers** - this is where you should find the one you are looking for if it exists
https://github.com/jupyter/nbgrader/blob/066e793fb973b8ed03ea222a28c81950361edc94/nbgrader/server_extensions/formgrader/apihandlers.py#L314-L348

**Formgrader handlers**
https://github.com/jupyter/nbgrader/blob/066e793fb973b8ed03ea222a28c81950361edc94/nbgrader/server_extensions/formgrader/handlers.py#L286-L305

**validate assignment handlers**
https://github.com/jupyter/nbgrader/blob/066e793fb973b8ed03ea222a28c81950361edc94/nbgrader/server_extensions/validate_assignment/handlers.py#L130-L133

When a URL matches a regular expression (first parameter of handlers), the corresponding object is instantiated (to return web content or JSON data).

It would be wonderful to improve the documentation by documenting the endpoints, if you have it after your research.
