### ISSUE TITLE
General: Configuration File Format change

### ISSUE THREAD

**Issue by liuq** [jupyter/nbgrader#1687]
This is a general issue, not related to a specific bug.

I am currently writing a package to automate the integration of nbgrader with Moodle which aims at working both as a Jupyter extension and a command line tool. In doing that I faced the problem to access the configuration file in a safe way. Unfortunately, the choice of using a Python file is far from being safe from security issues since it has to be imported and it might contain malicious code besides the configuration information. Also, the option of passing the configuration information at the command line has an impact on the usability of the tool (why should I repeat myself providing information that is already stored in the configuration file?).

Consequently, my suggestion for a future (major) release of nbgrader is to move toward a safer way to express the configuration options such as a YAML file (or even a multi-format one), which is safer to be read from third-party tools and do not have trustability/security issues.

**Comment by perllaghu** [comment]
NBGrader follows the same configuration process that Jupyter [notebook and hub] use - it does not make sense to change configuration unless/until the parent products do.

**Comment by perllaghu** [comment]
(suggest closing this issue now)
