### ISSUE TITLE
Is there any way to edit/update an assignment after it's been released and has some submissions?

### ISSUE THREAD

**Issue by tdpetrou** [jupyter/nbgrader#1699]
### Operating system

Linux

### `nbgrader --version`

0.6.1

### `jupyterhub --version` (if used with JupyterHub)

1.3

### `jupyter notebook --version` 

6.1.6

### Expected behavior

I am looking for the best practice for editing/updating an assignment. Often times, I'll need to add/remove/edit a few questions after an assignment has been released and has some submissions. I'll make the edits, unrelease it, then attempt to generate the assignment again. I am met with this error

```
RuntimeError: Cannot add or remove cells for notebook <notebook name> because there are submissions associated with it
```

Right now, I have to remove the assignment [using this solution](https://github.com/jupyter/nbgrader/issues/995#issuecomment-427574502). I lose all of the data associated with it. 

I'm curious as to what the best practice is here? Do I create a new assignment (which necessitates a new name)? Ideally, I'd like to keep the same name, just have different versions of the assignment.

**Comment by brichet** [comment]
If I'm not mistaken, there are no versions of the assignments, to ensure the integrity of the submissions.
Otherwise, it could be confusing for students who have already submitted the assignment.
Do you have any idea how this could be handled on the student side to avoid confusion?

**Comment by tdpetrou** [comment]
Thank you for the response. Maybe I can simplify my request to - how do I create a new version of an assignment? 

Right now, I cannot duplicate the notebook as the ID of each cell will be same and there will be a checksum error. I created a manual script that will replace the IDs with a unique random number, but this is tedious. I hope there is a better method.

**Comment by perllaghu** [comment]
If you create a new assignment (as in the name of the assignment), then you should be able to use the same `.ipynb` file in both assignments (I do that when I'm testing my service)

.... however @brichet 's question is a valid one: If I were a student who had submitted, or mostly completed, a piece of work, I would not expect that "homework" to change underneath me...

**Comment by perllaghu** [comment]
I came across some in-house notes I'd made a while back, relating to this:

Creating & releasing assignments is good, and one can "un-release" by clicking on the "X" in the `Release` column

* .... **until** someone has fetched it.

At this time, any newer releases will not be seen as a fetch would need to over-write the files already present (wiping out the existing work), or pre-force, move the old files into some other directory.

We push the responsibility for this action onto the recipient: _they_ need to remove the `<assignment_code>` folder by some choice, and then the assignment will not be seen locally, and can thus be fetched again.

* .... **until** you have collected & `autograded` submissions

At this point, you need to actually purge the assignment from your local `gradebook.db`

    nbgrader db assignment remove <assignment>

* *note* - you will need to force it
* *note* - you will retain the files on disk (`collected`, `autograded`, etc)... you will want to [re]move them out the way..

**Comment by brichet** [comment]
Closing as not planned.

Feel free to reopen it if this feature is required.
