### ISSUE TITLE
Unable to update css

### ISSUE THREAD

**Issue by major-project-1921** [jupyter/nbgrader#1701]
Adding custom css in nbgrader.css for manage_assignments.tpl but the css is not getting reflected.

**Comment by brichet** [comment]
Thanks @major-project-1921 for reporting this.
Did you find a way to make it work ?
Otherwise can you provide the versions of `nbgrader` and `notebook` or `jupyterlab` depending on the one you are using, and maybe some example of what you want to do ?

**Comment by perllaghu** [comment]
I have personal CSS working.... though I'm using nbgrader with notebooks in Docker Images.

I have a file called `custom.css` that I copy to `/etc/jupyter/custom/custom.css`

Examples of what I have done, that definitely work:

```
#login_widget button {
  display: none;
}

button#shutdown {
  display: none;
}
```

**Comment by major-project-1921** [comment]
> Thanks @major-project-1921 for reporting this. Did you find a way to make it work ? Otherwise can you provide the versions of `nbgrader` and `notebook` or `jupyterlab` depending on the one you are using, and maybe some example of what you want to do ?

I have added style tag in head block and implementing it correctly.
Haven't tried what you suggested @perllaghu. 

Wanted to know changing the css in nbgrader.css will not work or am I the only one facing it.

**Comment by perllaghu** [comment]
> Wanted to know changing the css in nbgrader.css will not work or am I the only one facing it.

In my case, I wanted to affect root notebook-server elements, rather than modify nbgrader & it's elements directly.... though I would take the same route: changing files from an installed libraries causes maintenance issues in the long run

**Comment by major-project-1921** [comment]
@perllaghu 
Understood. Thank you.
