### ISSUE TITLE
Invalid constraint found in nbclient dependencies

### ISSUE THREAD

**Issue by evgenytsydenov** [jupyter/nbgrader#1716]
I tried to install nbgrader via poetry and received a warning about an invalid constraint (see below).

### Operating system
Windows 10 Pro 22H2

### `nbgrader --version`
0.8.1

### `jupyter notebook --version`
6.4.12

### `poetry --version` 
Poetry (version 1.3.1)

### Expected behavior
The installation was completed without any warnings.

### Actual behavior
The installation was completed with the following warning:
`Invalid constraint (jupyter-core!=~5.0,>=4.12) found in nbclient-0.7.1 dependencies, skipping`

### Steps to reproduce the behavior
`poetry init`
`poetry add nbgrader`

**Comment by brichet** [comment]
Thanks @evgenytsydenov for reporting this.
Is it still an issue with latest version of nbgrader ?

**Comment by evgenytsydenov** [comment]
Feel free to close the issue. I'm not working on this right now and I can't check it.

**Comment by brichet** [comment]
I'm closing it as not planned.
Feel free to reopen it if it is still an issue.
