### ISSUE TITLE
Conda package incompatibility between JupyterLab 3.6 and nbgrader 8.1

### ISSUE THREAD

**Issue by nthiery** [jupyter/nbgrader#1733]
### `nbgrader --version`

0.8.1

### Expected behavior

Being able to install simultaneously JupyterLab 3.6 and nbgrader 8.1

### Actual behavior

Failure to install.

### Steps to reproduce the behavior

1. Install micromamba (or presumably any other conda installation)
2. Try to create a fresh environment:
```
> mamba create -n toto "jupyterlab>=3.6" nbgrader=0.8.1
Encountered problems while solving:
  - package jupyterlab-3.6.0-pyhd8ed1ab_0 requires jupyter_server_ydoc >=0.6.0,<0.7.0, but none of the providers can be installed
The environment can't be solved, aborting the operation
```

**Comment by brichet** [comment]
I opened https://github.com/conda-forge/nbgrader-feedstock/pull/58 which pins `jupyterlab<3.6`.
We should probably release a `0.8.2` working with jupyterlab 3.6.x.
