### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by tuncbkose** [jupyter/nbgrader#1736]
It seems to me that there are two issues causing tests to fail.
1- JupyterLab [announcements](https://jupyterlab.readthedocs.io/en/stable/user/announcements.html) pop-up is interfering with `test_formgrader.spec.ts`, and
2- `node-canvas` is requested for a version that doesn't have a build for the `node` used in the testing environment, and it can't be built. (Related?: https://github.com/jupyterlab/jupyterlab/pull/13722) 

I am writing them down in case someone else encounters them too. Maybe I can create a pr as well soon.

**Comment by brichet** [comment]
Thanks @tuncbkose for reporting this.
I think the second point should been fixed by https://github.com/jupyter/nbgrader/pull/1737

I'll take a look at the first issue.

**Comment by brichet** [comment]
I close it as fixed by https://github.com/jupyter/nbgrader/pull/1737 and https://github.com/jupyter/nbgrader/pull/1743.
Feel free to re-open it if necessary.
