### ISSUE TITLE
Add the releaser workflows to the repo

### ISSUE THREAD

**Issue by jtpio** [jupyter/nbgrader#1767]
Follow-up to #1766 

It would be great to align this repo with others in the `jupyter` organization:

- https://github.com/jupyter/nbconvert
- https://github.com/jupyter/notebook

To use the releaser workflows from the repo and make releases with the bot:

- GitHub: https://github.com/jupyter-release-bot
- PyPI: https://pypi.org/user/jupyter-release-bot/
- npm: https://www.npmjs.com/~jupyter-release-bot

For this we would need to perform several tasks:

- [x] Add `jupyter-release-bot` to the repo with `Admin` rights
- [x] Add `jupyter-release-bot` to PyPI: https://pypi.org/user/jupyter-release-bot
- [x] Add `jupyter-releaser-bot` to `npm`: https://www.npmjs.com/package/nbgrader

cc @brichet

**Comment by brichet** [comment]
Thanks @jtpio, the checklist will help :+1:

**Comment by brichet** [comment]
@blink1073 it could be nice to convert this repo to use the releaser workflow from the repo itself.

But AFAIK I can't do that, I would need ID and private key from the Github app of Jupyter organization.

Can you help with this ?
