### ISSUE TITLE
restrictions in jupyter_client and jupyter_server dependencies necessary ?

### ISSUE THREAD

**Issue by nklever** [jupyter/nbgrader#1771]
@brichet: Thanks for the 0.8.2 update! 

The dependency part of [pyproject.toml](https://github.com/jupyter/nbgrader/blob/main/pyproject.toml) restricts jupyter_client<8 and jupyter_server<2. Is this necessary, because of jupyter v2 compatibility ?

Thanks, Nik

**Comment by brichet** [comment]
I haven't had time to do any further introspection on these restrictions, but the tests fail when updating each of the packages:
- https://github.com/jupyter/nbgrader/pull/1718 fails on nbextension tests.
- https://github.com/jupyter/nbgrader/pull/1728 fails on python tests with a timeout. Probably one or more test are pending.

**Comment by tuncbkose** [comment]
For `jupyter_client>=8` and timeout tests, https://github.com/jupyter/nbconvert/issues/1964 is relevant

**Comment by luisarturopena** [comment]
The jupyter_server dependency issue breaks nbgrader when used with jupyter_server_terminals, which is needed for a lot of things. Hopefully this is fixed soon!

**Comment by brichet** [comment]
Closing as fixed by https://github.com/jupyter/nbgrader/pull/1778 (released in 0.8.3) and https://github.com/jupyter/nbgrader/pull/1684 (released in 0.9.0)
