### ISSUE TITLE
Attachment leakage in generated notebooks

### ISSUE THREAD

**Issue by mspl13** [jupyter/nbgrader#1782]
### Operating system
Linux; CentOS 7

### `nbgrader --version`
```shell
Python version 3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:46:39)
[GCC 10.4.0]
nbgrader version 0.7.0.dev
```

### `jupyterhub --version` (if used with JupyterHub)
```shell
2.2.2
```

### `jupyter notebook --version` 
```shell
6.4.4
```

### Expected behavior
When I add an image attachment in between the mark scheme, to a markdown cell that is marked as "Manually graded answer", the image attachment should be removed from the generated notebook.

### Actual behavior
When adding an image attachment in between the mark scheme to a markdown cell that is marked as "Manually graded answer", the image attachment is still present in the notebook file and accessible as encoded image. This is true after "generating" the notebook/preparing it for the release. This leads to students being able to reconstruct the image from the notebook file, effectively leading to a "leakage" of the answer.

My current workaround for this is to generate the notebook, downloading it, removing the attachment manually from the JSON code, re-uploading it and only then releasing it to the students.

### Steps to reproduce the behavior
1. Create a new assignment and a corresponding notebook.
2. Create a new markdown cell, mark it as "Manually graded answer".
3. Add the mark scheme to the cell and insert an image in-between using the "Edit > Insert image" menu option.
4. In formgrader, click on the "Generate" button for the given assignment.
5. Download the generated notebook and open it with any text editor.
6. Inspect the created markdown cell. The `source` value should say "YOUR ANSWER HERE" (expectec), but the `attachment` value should still be intact (unexpected).

---

Thank you for the awesome project and work on it! We've been using it for quite some time now and are generally very happy with it. :)

**Comment by tuncbkose** [comment]
This leakage is definitely a problem, but I think the best solution is to prevent using attachments in mark schemes. 

If we want to make attachments work, we need to remove it from source notebooks and add it back during autograding, meaning that we need to keep track of the attachment content. In the presence of a working alternative (adding images in markdown), I'd rather not keep track of it. At least, I can't think of a scenario where it is more convenient to add an image to the mark scheme as an attachment rather than markdown. Please let me know if you have an example in mind.

Out of curiosity, once you manually remove the attachment, how do you restore it to submitted notebooks in your workflow?

**Comment by mspl13** [comment]
Thank you for your quick answer!

> In the presence of a working alternative (adding images in markdown)

What exactly do you mean with "adding images in markdown"? I only see two ways that, at the moment, both seem to leak the solution without manual intervention:

1. We add the images as attachment, then reference it attachment in markdown in-between the mark scheme using something like `![image-file-name.png](attachment:image-file-name.png)`.
2. Upload the image into the notebook directory and reference it using a similar syntax as above, but providing the full path instead of `attachment:`. This would, if I'm not mistaken, also copy the image file into the release directory and, with that, publish it to the students. Please note that the image is not one that is hosted somewhere on a server, but rather one that I have locally on my machine, so there is no URL for the image as well.

Is there maybe a third way I don't know of?


> I can't think of a scenario where it is more convenient to add an image to the mark scheme as an attachment rather than markdown.

I do agree, if there is a realiable way of preventing the publication alongside the notebook.


> how do you restore it to submitted notebooks in your workflow?

Sorry, I'm not sure I fully understand. Why would I need to restore the image to the submitted notebooks? The generated feedback files don't show the solution anyway, or do they? During grading, I simply use the source version of the notebook as a reference and the same during presenting solutions to the class.

**Comment by tuncbkose** [comment]
I'm working on a PR that
1. Adds an option to raise an error when an attachment in a marking scheme is detected (enabled by default),
2. Changes `nbconvert.exporters.HTMLExporter` configuration to embed images during `generate_feedback`,
because this seems to me like the most sensible way forward currently.

Please let me know if you think there is a better option and/or this proposed solution fails to take something into account.

**Comment by mspl13** [comment]
I think that keeping track of the attachment would still be the most robust solution at the moment. However, I also see that this might not be very relevant in the future, as JupyterLab does seem to support attachments in cells anymore (at least I couldn't find an option to attach an image to a cell locally). It only seems to work with file paths there. And since the new Jupyter Notebook 7 UI will also be based on the JupyterLab code, I don't see it being an option there.

That said, I agree that the relative path solution seems to be somewhat reasonable given the current limitations. But I also see the danger of this breaking when, at some point, the structure changes again (or is this something that is supposed to be set in stone for the forseeable future?).

Maybe, for the short term, we could also think of a dirty workaround? In cases like ours, where we don't really have control over the update process of the JupyterHub instance and the nbgrader plugin, this might be nice to have.

So what I'm thinking right now: I could just use a relative path for the image. For the feedback, it's not necessary to include the image (since I present the solution in person anyway). Would this work without breaking the feedback generation process? Would the process then simply insert a link to an image that does not exist?

**Comment by tuncbkose** [comment]
I'm under the impression that JupyterLab still supports attachments, at least when pasting images to markdown cells, but maybe there is no button for it. But I didn't know there was one in Notebook either, so maybe I just missed it.

> I think that keeping track of the attachment would still be the most robust solution at the moment.

Maybe, I am just reluctant to propose any changes to the database myself, especially those that might inflate its size. It is possible that my hesitance is unwarranted, and the change would end up not mattering.

> Would this work without breaking the feedback generation process?

The process is broken only if:
1. The release version of the notebook (one where marking schemes and thus references to the attachment are removed) is opened in Jupyter Notebook/Lab and saved. Presumably, students will do this. At save time, the Jupyter frontend detects that the attachment is not used, so it is deleted.
2. `nbgrader generate_feedback` (or the corresponding button in the Notebook/Lab extensions) is used. These notebooks will contain references to missing attachments, and `nbconvert` will complain about it during conversion to html.

Thus, you only need to worry about it if you intend on publishing html feedback files to students. 


> Maybe, for the short term, we could also think of a dirty workaround?

I was looking into this a bit, but I wasn't as organized as I probably should be. So with the caveat that you should test it before using, I think the following will work:

1. Add the following to `nbgrader_config.py` (if jupyter notebook/lab was already launched, restart it afterward):
```
c.HTMLExporter.embed_images = True
```
2. Before calling `generate_assignment` on the `source` notebook, change the image path to this: `![alt text](../../../resources/image.png)`. This doesn't actually have to point to the image.
3. Create the folder `<course_dir>/resources` and put the image file there.

In case it is not clear, what this is doing is putting the image files to a place where it will be accessible for the notebooks in the `autograded` and `feedback` folders. We are also telling `nbconvert` to embed images into the file when converting to html, which is what happens during manual grading and feedback files.

I initially thought this workaround should work without the first step, but I was encountering `302 Found` responses for the HTTP requests for images and they didn't display, not sure why.
