### ISSUE TITLE
Use nbgrader with Jupyterhub Authenticator "NativeAuthenticator" possible?

### ISSUE THREAD

**Issue by cablesky** [jupyter/nbgrader#1793]
Is there a way to run nbgrader with jupyterhub authenticator "NativeAuthenticator" too?
The NativeAuthenticator creates a directory for each registered student in a /home directory, e.g. /home/student1 or /home/student2.
Can nbgrader use this directory structure, e.g. to fill the student directory?

**Comment by tuncbkose** [comment]
I am not sure what you have in mind. Shouldn't the student servers launched by JupyterHub have `/home/student-x` as the base directory? (I have never configured Hub, so maybe this is not the case by default, but then I don't see why those directories are created). So I would expect nbgrader should just work as you want it to.

**Comment by brichet** [comment]
I'm closing it as solved.

Feel free to reopen it if it is still an issue.
