### ISSUE TITLE
Disabling Jupyter Labextensions not working

### ISSUE THREAD

**Issue by milandeepbassi** [jupyter/nbgrader#1810]
### Operating system 
Ubuntu 22.04

### `nbgrader --version` 
0.9.0a1

### `jupyterhub --version` (if used with JupyterHub) 
JupyterHub 4.0.2 20230810214238

### `jupyter notebook --version` 
7.0.2

### Expected behavior
Should be able to disable individual components for Users and Indviduals

### Actual behavior
Can only disable Server Extensions not lab

### Steps to reproduce the behavior
Use any of the folllowing

The labextensions are all enabled by default, but can be disabled individually by running:
jupyter labextension disable nbgrader/formgrader
jupyter labextension disable nbgrader/assignment-list
jupyter labextension disable nbgrader/course-list
jupyter labextension disable nbgrader/create-assignment
jupyter labextension disable nbgrader/validate-assignment

**Comment by milandeepbassi** [comment]
I see the docs in Version 9 need to be updated. The keys have changed.

const pluginIDs = {
  menus: 'nbgrader:menu',
  assignmentsList: 'nbgrader:assignment-list',
  coursesList: 'nbgrader:course-list',
  formgrader: 'nbgrader:formgrader',
  createAssignment: 'nbgrader:create-assignment',
  validateAssignment: 'nbgrader:validate-assignment'
}

^ from the index.ts inside src.

using the : instead of / solved my issue.

**Comment by brichet** [comment]
Closed by https://github.com/jupyter/nbgrader/pull/1811
