### ISSUE TITLE
Header not Compatible with Kernel Language

### ISSUE THREAD

**Issue by swissarthurfreeman** [jupyter/nbgrader#1820]
### Operating system
```
Ubuntu 22.04 LTS on Docker
```

### `nbgrader --version`
```
Python version 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
nbgrader version 0.8.4
```

### `jupyterhub --version` (if used with JupyterHub)
```
4.0.2
```
### `jupyter lab --version` 
```
3.6.5
```

### Expected behavior
When an instructor generates the student version of an assignement, the generated version should not have an additional useless cell with python syntax based variable definitions,
```
NAME = ""
COLLABORATORS = ""
```

### Actual behavior

When instructor generates student version via formgrader, even without having such a cell, nbgrader's pipeline adds that cell at some point.

### Steps to reproduce the behavior

Create example scala notebook using the deployment at [this link](https://github.com/swissarthurfreeman/jupyhubgrascala/) :
Accessing grader shared notebook server to create assignement,
![Example Scala Notebook](https://github.com/jupyter/nbgrader/assets/53379583/8beb32bf-3572-4104-8564-782ca765e35b)

![Output of Generation](https://github.com/jupyter/nbgrader/assets/53379583/117a264e-f65b-4a5f-8320-f72886534b63)

When the user fetches it, the cell is there, 
![User Fetched Notebook](https://github.com/jupyter/nbgrader/assets/53379583/4b208451-ff0e-46d3-8cca-092ce949ebdc)
It of course does not compile as it is not valid scala code. 

When user submits it and instructor autogrades, we get a compilation error. Same when student validates his notebook. 
![Screenshot from 2023-08-28 12-58-48](https://github.com/jupyter/nbgrader/assets/53379583/4cf9d7a2-7e5f-4807-a04e-4dff6def4a88)

How can we modify / remove the appending of that header cell for it to work with Scala ? Note that I would also like to keep this
behavior for Python kernels. 

Many thanks,

Gordon

**Comment by brichet** [comment]
The header shouldn't be include automatically.
Did you generate the example from the `nbgrader quickstart` command ?

This command includes the following line in *nbgrader_config.py*:
`c.IncludeHeaderFooter.header = "source/header.ipynb"`
It also adds *source/header.ipynb* file, containing the cells you mentioned.

You can either comment/remove the config line in *nbgrader_config.py* file, or change the header file to something working with Scala.

**Comment by swissarthurfreeman** [comment]
Dear @brichet, 

Thank you for your swift reply, it was indeed my mistake, I hadn't realised that nbrader quickstart was generating it's own config file which was overriding the one I had provided. The issue is now solved. 

Many thanks !
