### ISSUE TITLE
Release 0.9.0 breaks nbextensions

### ISSUE THREAD

**Issue by Adamtaranto** [jupyter/nbgrader#1828]
### Operating system
Ubuntu
### Python
3.11
### `nbgrader --version`
=>0.9.0
### `jupyter notebook --version` 
6.5.5
### Expected behaviour
Trying to activate nbgrader extension with command: `jupyter nbextension install --sys-prefix --py nbgrader`

Expect this to call `jupyter-nbextension` and install nbgrader extension

### Actual behaviour

When nbgrader =>v0.9.0 is installed `jupyter-nbextension` is missing and calling the command above generates the following error:

> Available subcommands: console dejavu events execute fileid kernel kernelspec lab labextension labhub migrate nbclassic nbconvert notebook qtconsole
> run server troubleshoot trust
> 
> Jupyter command `jupyter-nbextension` not found.

### Steps to reproduce the behaviour
Install nbgrader v0.9.0
jupyter-nbextension will be removed even if you previously had it installed from an earlier version.

Reverting to nbgrader v0.8.5 resolves the issue.

**Comment by lahwaacz** [comment]
nbgrader v0.9.0 requires Jupyter Notebook 7: https://github.com/jupyter/nbgrader/blob/main/pyproject.toml#L45

Are you sure you have notebook 6.5.5? How did you install nbgrader?

**Comment by Adamtaranto** [comment]
Installed with `pip3 install -r requirements.txt`

Which installs:
> nbgrader
> jupyter
> numpy
> pandas
> matplotlib
> biopython
> networkx
> regex

If I do this in a clean env notebook is 6.5.5
> notebook                  6.5.5                    pypi_0    pypi

**Comment by brichet** [comment]
Thanks @Adamtaranto for reporting this.
I can't reproduce it locally, `pip3 install -r requirements.txt` installs *Jupyterlab 4* and *Notebook 7* (which is expected).
Notebook 7 is using labextensions system, and not nbextensions.

If you want to run nbgrader on Notebook<7 you should use the `0.8.5` version.

These are not dependencies of *nbgrader*:

> numpy
> pandas
> matplotlib
> biopython
> networkx
> regex

I suppose you did not only install the *requirement.txt* of *nbgrader*.

Can you see the same issue when pulling *nbgrader* from github and running `pip3 install -r requirements.txt` again ?

**Comment by brichet** [comment]
Feel free to reopen it if there are any update.
