### ISSUE TITLE
Pin to ipython 3.x

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/nbgrader#183]
IPython 4.0-dev is becoming a mess. Is it possible to pin nbgrader to 3.x for now or *not* specify a version dependency for it? I am deploying 3.x for my class and I don't want to have to try to work around all of the breakage that is going to happen in the 4.0-dev space.

**Comment by jhamrick** [comment]
Now that ipython/ipython#8073 has been backported to 3.x, I think we can change travis to use 3.x as well. I would say that the requirements.txt should use ipython>3.0 though, rather than >=3.0.
