### ISSUE TITLE
Formgrader is not showing

### ISSUE THREAD

**Issue by dipsav** [jupyter/nbgrader#1919]
I have installed nbgrader on jupyterhub (TLJH) with JupyterLab.

**nbgrader --version**
Python version 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0]
nbgrader version 0.9.3
**jupyterhub --version**  
4.1.4
**jupyter lab --version** 
4.2.2
**jupyter notebook --version**  
7.2.1

When I try to open the formgrader through the menu, it opens an empty tab. No errors or warnings. 
The only message I could find in the log files is: "Formgrader config is not serializable"

Any advise how to trace the issue?

**Comment by jeflem** [comment]
Could this be related to #1870 ?

Are there errors in the browser console?

**Comment by dipsav** [comment]
The error in the consol is:
Failed to load resource: the server responded with a status of 404 ()Refused to load http://xxxxx/user/yyyyyy/formgrader/manage_assignments because it does not appear in the frame-ancestors directive of the Content Security Policy.Sandbox access violation: Blocked a frame at "http://XXXXX" from accessing a frame at 

BTW, I managed to open the indicated link directly (by copying it to the address bar), and the formgrader works. 
Tested in safary and chrome, mac and iPad
JupyterHub is running on  Ubuntu 22.04.4

**Comment by dipsav** [comment]
Looks like it's indeed related to #1870 
I will follow that one.
This one can be closed

**Comment by dipsav** [comment]
Closed as related to related to #1870
