### ISSUE TITLE
Make grading plots less horrible

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#197]
Grading plots is a huge pain. Partially, they just need to be done manually, but there are also some things that could be autograded. However, if the plots are done with matplotlib at least, this is difficult, as the underlying data model doesn't necessarily correspond one-to-one with what the plot looks like. For example:

1. `plot` and `scatter` can produce nearly identical plots, but one is accessed through lines and one is accessed through collections.
2. It's possible to use `scatter` within a for loop for just a single point but with an array of colors, meaning that when we check the point colors they seem correct, but they're actually not because the points all just use the first color of the color array.
3. How to check things like a dendrogram plot?

This might not actually be something nbgrader wants to handle, especially if it wants to be language agnostic, but I'd really like a better way to do this so I'm opening an issue here for now anyway.

**Comment by ischurov** [comment]
Maybe, this can help us: https://github.com/jhamrick/plotchecker ?

**Comment by jhamrick** [comment]
Yep, I wrote that with this exactly kind of stuff in mind :smile:
