### ISSUE TITLE
Configurable plugins for late penalties

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#233]
Every class is going to want to institute late penalties differently, so we shouldn't actually include anything in nbgrader itself that calculates the late penalties. However, it would be nice to for example have the ability to write your own plugin to calculate late penalties, which could then be displayed in the formgrader and also when generating feedback.

**Comment by mandli** [comment]
Seconded.

**Comment by jhamrick** [comment]
Closed by #512
