### ISSUE TITLE
Make nbgrader install a real subcommand

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/nbgrader#239]
Now that the install command is a proper app, we might as well make it a proper subcommand of nbgrader so users can see it in the command line documentation and run it like the other commands.

**Comment by jhamrick** [comment]
@Carreau and I discussed this a bit and decided that because you only need to ever run it once, it might clutter up the list of subcommands. There probably is something to be said, though, about having `nbgrader install-nbextension` to mirror `ipython install-nbextension`?

**Comment by Carreau** [comment]
I **think** that IPython one is mostly used for non-python kernels to shell-out. 
also we should probably think of that in the jupyter echosystem where we coulf have a jupyter-install-nbextension executable
