### ISSUE TITLE
Allow solution+grade cells for free response coding

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/nbgrader#242]
I often find myself wanting students to freely code and write their own tests in a cell. In the current version I have to create two cells:

1. A solution cell that has my version of the code.
2. A grade cell with `assert True` as a placeholder to grade the students work.

The problem is that I have to create two cells *and* the comments in the formgrader go with the placeholder cell, not the student's code.

If we allow a code cell (like a markdown cell) to be solution+grade, it would be become much nicer to do this type of thing. Also, our current UI allows users to have a solution+grade code cell, so the fact that is doesn't work is some manner of bug.

**Comment by jhamrick** [comment]
Part of my worry with this is that you *really* don't want to be able to do this for normal code solutions and tests -- which happened a few times when creating our assignments, which is why I disabled it. I definitely think we should be able to do this, but probably it should wait until #153 is fixed, so that we can make the distinction between (1) normal code solutions and tests and (2) free-response code solutions extra clear.

**Comment by ellisonbg** [comment]
Hmm, but the more I use it, the more I think that keeping solution cells is
a good idea - when I have a sequence of multiple solution cells where the
entire cell is a solution, having to put in the `###` markers is pretty
tedious. Let's try to talk about all of this later, I am sure we can figure
something good out. I would like to understand better what removing
solution cells buys us.

On Mon, Apr 13, 2015 at 11:03 AM, Jessica B. Hamrick <
notifications@github.com> wrote:

> Part of my worry with this is that you *really* don't want to be able to
> do this for normal code solutions and tests -- which happened a few times
> when creating our assignments, which is why I disabled it. I definitely
> think we should be able to do this, but probably it should wait until #153
> <https://github.com/jupyter/nbgrader/issues/153> is fixed, so that we can
> make the distinction between (1) normal code solutions and tests and (2)
> free-response code solutions extra clear.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/nbgrader/issues/242#issuecomment-92447244>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
