### ISSUE TITLE
Previous and next arrows are unclickable

### ISSUE THREAD

**Issue by suchow** [jupyter/nbgrader#250]
![screenshot 2015-04-17 10 08 15](https://cloud.githubusercontent.com/assets/613981/7206807/e37eedbe-e4e9-11e4-9b01-4fcf639d3a5e.jpg)

**Comment by jhamrick** [comment]
Sigh. At least, every time there is a formgrader bug I can now add a test for it, so it will be stable eventually :stuck_out_tongue_winking_eye:
