### ISSUE TITLE
Improve UX of switching views

### ISSUE THREAD

**Issue by suchow** [jupyter/nbgrader#256]
I'm consistently surprised when I navigate in Assignment View to a specific problem set, and then flip to Student View. It returns me to the root, but I'm expecting it to show me a list of students with links to that specific problem set.

**Comment by jhamrick** [comment]
I tried tackling this at some point, but I think it needs some careful thought put into it to get the right design. For the moment I am going to mark this as wishlist, but I would like to do this redesign at some point.

**Comment by jhamrick** [comment]
I think with #782 this will be more obvious. It doesn't flip to viewing the same assignment but as a list of students, but it does make it clearer that clicking on "Manage Students" will bring you to a new page, not show you the same data a different way.
