### ISSUE TITLE
Document nbgrader list/release/fetch/submit/collect

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#283]
These currently aren't documented anywhere. It might be nice to add `nbgrader validate` in there as well.

**Comment by jhamrick** [comment]
Started in #294

**Comment by jhamrick** [comment]
@willingc is working on this and other docs.

**Comment by willingc** [comment]
@jhamrick It looks like the command line tools documentation has documentation of nbgrader's list, release, fetch, submit, and collect commands. Was there additional documentation that you would like in another location. If not, this can be closed :)

**Comment by jhamrick** [comment]
I think there is still plenty to do on the docs, but I think what we have is good enough for the upcoming release.

**Comment by willingc** [comment]
Agreed :D I really like the doc changes and installation improvements that you made the past few days. Awesome job on the release :sunflower:
