### ISSUE TITLE
Behavior of nbgrader list

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#295]
@ellisonbg I have a question about the behavior of `nbgrader list`. I was working on trying to document the transfer apps a bit, and ran into some unexpected behavior if you use a different user. For example, let's say I (`jhamrick`) am the instructor and there is a student (`nobody`) on the same system. I can release the assignment and list it as expected:

```
$ whoami
jhamrick
$ nbgrader list
[ListApp | INFO] Released assignments:
[ListApp | INFO] example_course Problem Set 1
```

And I can use `nbgrader list` from the student's perspective to see the released assignments:

```
$ sudo -u nobody whoami
nobody
$ sudo -u nobody nbgrader list example_course
[ListApp | INFO] Released assignments:
[ListApp | INFO] example_course Problem Set 1
```

Fetching and submitting works fine:

```
$ sudo -u nobody nbgrader fetch example_course "Problem Set 1"
[FetchApp | INFO] Source: /tmp/exchange/example_course/outbound/Problem Set 1
[FetchApp | INFO] Destination: /private/tmp/student_home/Problem Set 1
[FetchApp | INFO] Fetched as: example_course Problem Set 1
$ sudo -u nobody nbgrader submit "Problem Set 1" example_course
[SubmitApp | INFO] Source: /private/tmp/student_home/Problem Set 1
[SubmitApp | INFO] Destination: /tmp/exchange/example_course/inbound/nobody+Problem Set 1+2015-06-12 17:35:09 UTC
[SubmitApp | INFO] Submitted as: example_course Problem Set 1 2015-06-12 17:35:09 UTC
```

But then when I use `nbgrader list --inbound`, the student can't see their submitted assignments:

```
$ sudo -u nobody nbgrader list example_course --inbound
[ListApp | INFO] Submitted assignments:
```

The instructor, however, can:

```
$ whoami
jhamrick
$ nbgrader list --inbound
[ListApp | INFO] Submitted assignments:
[ListApp | INFO] example_course nobody Problem Set 1 2015-06-12 17:35:09 UTC
```

Is this a bug, or is this expected behavior? I was under the impression that students could use `nbgrader list` to view what they had submitted.

**Comment by ellisonbg** [comment]
When I wrote this I was thinking that all users would be treated
symmetrically - that this was really just a way for any user to send file
to another set of users. From this perspective `--inbound` from a student's
perspective would refer to file that are being sent to them. From this
perspective, I don't think it is broken. The difficulty is that this
doesn't allow students to see what they have submitted and this does turn
out to be a problem in practice (my students kept asking). I am not sure
how to resolve this, but we should definitely think a bit more about it.

On Fri, Jun 12, 2015 at 10:39 AM, Jessica B. Hamrick <
notifications@github.com> wrote:

> @ellisonbg <https://github.com/ellisonbg> I have a question about the
> behavior of nbgrader list. I was working on trying to document the
> transfer apps a bit, and ran into some unexpected behavior if you use a
> different user. For example, let's say I (jhamrick) am the instructor and
> there is a student (nobody) on the same system. I can release the
> assignment and list it as expected:
>
> $ whoami
> jhamrick
> $ nbgrader list
> [ListApp | INFO] Released assignments:
> [ListApp | INFO] example_course Problem Set 1
>
> And I can use nbgrader list from the student's perspective to see the
> released assignments:
>
> $ sudo -u nobody whoami
> nobody
> $ sudo -u nobody nbgrader list example_course
> [ListApp | INFO] Released assignments:
> [ListApp | INFO] example_course Problem Set 1
>
> Fetching and submitting works fine:
>
> $ sudo -u nobody nbgrader fetch example_course "Problem Set 1"
> [FetchApp | INFO] Source: /tmp/exchange/example_course/outbound/Problem Set 1
> [FetchApp | INFO] Destination: /private/tmp/student_home/Problem Set 1
> [FetchApp | INFO] Fetched as: example_course Problem Set 1
> $ sudo -u nobody nbgrader submit "Problem Set 1" example_course
> [SubmitApp | INFO] Source: /private/tmp/student_home/Problem Set 1
> [SubmitApp | INFO] Destination: /tmp/exchange/example_course/inbound/nobody+Problem Set 1+2015-06-12 17:35:09 UTC
> [SubmitApp | INFO] Submitted as: example_course Problem Set 1 2015-06-12 17:35:09 UTC
>
> But then when I use nbgrader list --inbound, the student can't see their
> submitted assignments:
>
> $ sudo -u nobody nbgrader list example_course --inbound
> [ListApp | INFO] Submitted assignments:
>
> The instructor, however, can:
>
> $ whoami
> jhamrick
> $ nbgrader list --inbound
> [ListApp | INFO] Submitted assignments:
> [ListApp | INFO] example_course nobody Problem Set 1 2015-06-12 17:35:09 UTC
>
> Is this a bug, or is this expected behavior? I was under the impression
> that students could use nbgrader list to view what they had submitted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/nbgrader/issues/295>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jhamrick** [comment]
Yeah, I definitely think it would be useful for students to be able to verify they have submitted, both for them and instructors -- otherwise students have to ask the instructor to confirm they've received it.

Would it work to have an additional level of directories in the inbound/outbound folders, so that you'd have something like:

**Comment by jhamrick** [comment]
Yeah, I definitely think it would be useful for students to be able to verify they have submitted, both for them and instructors -- otherwise students have to ask the instructor to confirm they've received it.

Let's definitely think a bit more about this; I'm sure there's something we can figure out.

**Comment by jhamrick** [comment]
Ok, what do you think about this idea:

1. Instructor creates a GPG key on the system. The public key for this gets copied to the exchange the first time something is released. Assignments that are released are released normally (not encrypted).
2. The first time students try to access the exchange, nbgrader imports the public key.
3. When students submit something, nbgrader automatically imports the public key and encrypts their submission to that key.
4. The `inbound` directory is readable by everyone. Encrypted submissions get copied to the inbound directory in the same way that they are currently, except that permissions are set such that they cannot be modified/removed by other students. So, other students can see who has submitted stuff, but can't actually see the contents of the submission.
5. When collecting submissions, nbgrader will automatically decrypt them using the secret key that only the instructor has.

**Comment by jhamrick** [comment]
Also, if you wanted to configure the class so that students could send stuff to each other, you could set up each student account with it's own GPG key and then add a flag to nbgrader to tell it to encrypt to another student rather than to the instructor. It might be a bit tricky to do this in a way that is easy for students to use while still secure, but I don't think it would be *too* hard to do.

**Comment by ellisonbg** [comment]
Perhaps of the biggest deficiencies that I see with nbgrader right now is that all of the `list/release/collect/etc` commands only work with a centrally deployed jupyterhub instance. There are many teaching and tutorial contexts where that isn't realistic. 

I have been thinking a bit about how we could get these parts of nbgrader working as a separate service the project can run for students and teachers to exchange materials. It could be that GPG keys would help in this, but we also may be able to piggyback on top of GitHub OAuth or something similar.

I am a bit hestinant to expose the details of GPG keys to users and teachers though. 

Let's try to talk about this on skype this week.

**Comment by jhamrick** [comment]
Hmm, yeah. Perhaps it would be worthwhile to think about something like that. I'm not sure it would be in scope for the upcoming release, though. So perhaps for now we should just leaving things as they are, and plan to do an overhaul of this machinery for the following release.

**Comment by jhamrick** [comment]
We have decided to leave the current as it is for the upcoming release and try to revisit this issue later.

**Comment by jhamrick** [comment]
Closing this, as I think through the combination of the upcoming JupyterHub file publishing service, plus the "cache" directory, that this is addressed well enough.
