### ISSUE TITLE
Inconsistent requirement of course id

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#296]
`nbgrader fetch` and `nbgrader submit` both require that you specify the course id on the command line, and will throw an error if it is no. `nbgrader list`, however, does not require that the course id is specified on the command line, and if you forget to provide it, will just tell you there are no submissions/assignments without telling you that you forgot to give a course id. It would be nice if `nbgrader fetch` and `nbgrader submit` could optionally look for the course id in a config file (like `nbgrader list` does) and then not require students to type out the whole thing. I especially think this would be desirable on a system that only has one class -- in which case, it won't make sense to students why they have to type the name of the course as well as the name of the assignment.

Also, `nbgrader list` should probably check if the course id is empty, and if it is, give an error, rather than just saying nothing has been submitted/released.

**Comment by jhamrick** [comment]
@ellisonbg After talking with people here in DC, they've decided they'd like to use JupyterHub (yay!) since they were already using a hosted system. I showed them these commands and how they integrate with a shared server setup, and there was consensus that the way these commands take arguments is confusing. I'd like to modify the existing behavior such that:

* All transfer commands have only a single positional argument, which is the name of the assignment
* All transfer commands additionally take a `--course` flag
* If the course is not specified either in a config file or with the `--course` flag, an error is thrown

I think this behavior would make `nbgrader fetch` and `nbgrader submit` more consistent with the rest of the nbgrader commands, will remove confusion about the argument order, and will allow less typing as the course id will be able to be provided in a config file.

What do you think?

cc @jonathanmorgan (I would cc Christina and Josh too but I don't know their GitHub usernames -- do you?)

**Comment by ellisonbg** [comment]
I think that sounds great.

On Thursday, June 25, 2015, Jessica B. Hamrick <notifications@github.com>
wrote:

> @ellisonbg <https://github.com/ellisonbg> After talking with people here
> in DC, they've decided they'd like to use JupyterHub (yay!) since they were
> already using a hosted system. I showed them these commands and how they
> integrate with a shared server setup, and there was consensus that the way
> these commands take arguments is confusing. I'd like to modify the existing
> behavior such that:
>
>    - All transfer commands have only a single positional argument, which
>    is the name of the assignment
>    - All transfer commands additionally take a --course flag
>    - If the course is not specified either in a config file or with the
>    --course flag, an error is thrown
>
> I think this behavior would make nbgrader fetch and nbgrader submit more
> consistent with the rest of the nbgrader commands, will remove confusion
> about the argument order, and will allow less typing as the course id will
> be able to be provided in a config file.
>
> What do you think?
>
> cc @jonathanmorgan <https://github.com/jonathanmorgan> (I would cc
> Christina and Josh too but I don't know their GitHub usernames -- do you?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/nbgrader/issues/296#issuecomment-115412914>.
>


-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jhamrick** [comment]
Fixed by #330
