### ISSUE TITLE
sqlite database does not refresh

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#315]
If you have the formgrader running and then e.g. re-run nbgrader autograde, the formgrader does not always reflect the updates to the database. I think this is due to a cached connection to the database in the flask app, so this caching probably should be disabled.

**Comment by jhamrick** [comment]
@alope107 is working on this

**Comment by alope107** [comment]
Could not reproduce. Attempted to reproduce on local machine and demo server.  All values properly refreshed upon webpage refresh when adding new students, new assignments, and new submissions and re-running autograder. Attempted under Chromium browser.
