### ISSUE TITLE
Depend on a stable version of JupyterHub

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#316]
Currently nbgrader depends on the development version, but this should not be the case when 0.1.0 is released. I want to investigate whether I can use the released version of JupyterHub or whether I need to wait until the next release of JupyterHub.

**Comment by minrk** [comment]
We can decide if it's appropriate to do a release of JupyterHub now. I'm not sure whether to do it before or after all the 4.0 stuff ships.

**Comment by jhamrick** [comment]
I think it depends on the timeline. I definitely think there should be a JupyterHub release before the semester starts for everyone that wants to use it for classes, and ideally sooner rather than later as a lot of people are already starting to get stuff set up. If they have stable versions of nbgrader and JupyterHub to work from I think that's going to make things a lot easier. Maybe there could be a 0.2.0 release of JupyterHub before 4.0, and then 0.3.0 for 4.0?

**Comment by minrk** [comment]
Sure. If that's the case, I can do 0.2 today. I'll just do a bit of testing to see if there's any known issues when the notebook server is 4.0 that are simple to address, and then cut 0.2 in the next couple of days.

**Comment by jhamrick** [comment]
Fantastic, thanks!
