### ISSUE TITLE
Add support for late assignments

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#32]
Currently, there is no way to track when assignments are turned in, whether they are late, and if so, what late penalty should be applied.

**Comment by tasilb** [comment]
I'm trying to add a timestamp property to the API, but I can't figure out how submission is related to the database. Any tips? Am I headed in the wrong direction with this?

**Comment by jhamrick** [comment]
Hi @tasilb , I'm actually in the process right now of making some pretty big changes to how things work, including some code that will resolve this issue, so I'd hold off on trying to work on this right now. I'm teaching this semester so things are changing really quickly as new stuff comes up -- sorry about that!

**Comment by jhamrick** [comment]
@tasilb I have a PR that fixes this issue, but if you'd like to help out with some other stuff, I'm unlikely to be able to get to any of the "wishlist" items myself anytime soon. Alternately, there's a ton of tests that need to be written, so if you wanted to try helping with those, that would be very much appreciated! (There's a few issues open already that indicate specific things that need tests still)
