### ISSUE TITLE
Add example "boilerplate" notebooks for use by instructors

### ISSUE THREAD

**Issue by willingc** [jupyter/nbgrader#338]
It may be helpful to add notebooks for instructors to use as a baseline example for setting up and grading assignments. For example, take the examples that are spread out across the user guide and make them into "boilerplate" notebooks without all the additional documentation for instructors. The benefit would be that the instructor would have a quick start to setting up a demo.

**Comment by jhamrick** [comment]
Yeah, I was thinking about something similar like adding a command `nbgrader --quickstart` that would set up a skeleton course directory for assignments. There actually are boilerplate notebooks in `docs/source/user_guide/source` but they are kind of hard to find if you don't know where to look.
