### ISSUE TITLE
Support IPython 4.0

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#344]
After all of the various components for IPython/Jupyter 4.0 are released, nbgrader will need to update everything as well. I don't want to do this though until everything has been released, though, because it will make installation a pain.

**Comment by maartenmarx** [comment]
I updated to IPython 4.0 and lost the "Create assignment" cell option. Running `nbgrader extension activate` again doesn't help.

**Comment by jhamrick** [comment]
Yes, I wouldn't expect extensions to still work because they have changed
locations in the new version of Jupyter. For the time being if you want to
use nbgrader you need to use IPython 3.x. I am working on 4.0 support
though and should have a PR for that soon.

On Thursday, August 13, 2015, maartenmarx <notifications@github.com> wrote:

> I updated to IPython 4.0 and lost the "Create assignment" cell option.
> Running nbgrader extension activate again doesn't help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/nbgrader/issues/344#issuecomment-130637687>.
>


-- 
Cheers,
Jess
