### ISSUE TITLE
Create Assignment not available

### ISSUE THREAD

**Issue by jzmiller1** [jupyter/nbgrader#350]
I set up a new Jupyterhub server on Ubuntu 14.04 and installed and activated nbgrader.  When I log in on my Jupyterhub admin user and create a new notebook the Create Assignment option is not available.  Any tips on where to begin troubleshooting?

Also, where should nbgrader_config.py be located?

**Comment by Carreau** [comment]
Are you on IPython master ? Or 3.x ?

**Comment by jzmiller1** [comment]
Whatever version pip3 pulls at the moment.

**Comment by Carreau** [comment]
Check that

```
$ cat ~/.ipython/profile_default/nbconfig/notebook.json
{
  "load_extensions": {
    "nbgrader/create_assignment": true
  }
}
```

and 

```
$ ls /usr/local/share/jupyter/nbextensions/nbgrader/
create_assignment.js nbgrader.css
```

Do you have errors in the Browser JS console ?

**Comment by jhamrick** [comment]
Hmm, that's odd. When you run the `nbgrader extension` commands, could you add a `--debug` flag and paste the output here, e.g.:

```
nbgrader extension install --debug
nbgrader extension activate --debug
```

**Comment by jzmiller1** [comment]
Several questions to answer so I'm going to break them into individual responses.

Versions first.  I installed IPython via pip3 and got 3.2.1.  nbgrader uninstalls 3.2.1 and installs 3.2.0 instead.

**Comment by jzmiller1** [comment]
I checked 

$ cat ~/.ipython/profile_default/nbconfig/notebook.json
{
  "load_extensions": {
    "nbgrader/create_assignment": true
  }
}


was there and it was.  I created this file in the nbconfig folder of my jupyterhub user named jp.  I've never been able to figure out how to log into Jupyterhub using the root system account.  Once I created this file I was able to access the create_assignment option.

There was an error in the JS console:

API request failed (500): Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/base/handlers.py", line 394, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/services/config/handlers.py", line 21, in get
    self.finish(json.dumps(self.config_manager.get(section_name)))
  File "/usr/local/lib/python3.4/dist-packages/IPython/config/manager.py", line 74, in get
    return json.load(f)
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)

**Comment by jzmiller1** [comment]
I ran the nbgrader commands with --debug but I lost the results from my notepad.  I'll post it when I rebuild the vm from scratch tomorrow.

**Comment by jhamrick** [comment]
You probably don't want to create the JSON file by hand as it's easy to introduce a syntax error, which is probably what you're seeing in the javascript console. What I'd recommend doing instead is, after running JupyterHub and starting your server, open up a terminal (through the browser, it is in the same menu where you create a new notebook) and type the `nbgrader extension enable` command there.

**Comment by jhamrick** [comment]
Alternately, you can run:

```
nbgrader extension activate --ipython-dir=/home/jp/.ipython
```

where `/home/jp/.ipython` is the `.ipython` directory in the homedir of your jp user.

**Comment by jhamrick** [comment]
@jzmiller1 Were you able to get this working? I'm going to go ahead and close the issue, but if you're still having troubles please let me know and I'll try to help you debug some more.
