### ISSUE TITLE
Allow linking to other files from the formgrader

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#376]
If an instructor wants to be able to have students write code in a file next to the notebook, for example, and provide a link to it in the notebook, then that link should be openable from the formgrader.

cc @joschu

**Comment by jhamrick** [comment]
@joschu Just verified that this does in fact work, so if you include links in your notebooks to python files that are next to the notebook, you should be able to open them from the formgrader.

**Comment by joschu** [comment]
Cool--thanks!
