### ISSUE TITLE
[Idea] Do a quick sweep of documentation from the end user perspective

### ISSUE THREAD

**Issue by willingc** [jupyter/nbgrader#392]
@jhamrick I have a bunch of travel coming up which makes some good time for me to work on docs. Any interest in iterating some docs to help end users get up and using nbgrader?

I mocked up a new README for the repo. I will submit a WIP PR. Feel free to question, comment, or circular file as desired :frog:

I also have some ideas from coaching new users at OpenHatch on adjusting the table of contents in the User Guide to be more user friendly.

**Comment by jhamrick** [comment]
That would be awesome! (Though I should mention I'll be doing some travel myself in a week, but won't be responding much to email or issues while I'm away).

**Comment by willingc** [comment]
Excellent. I tend to do best when iterating concepts via GitHub issues, and then smaller PRs over time. I will create a draft TOC in a new issue and we can iterate from there. Ideally, it would be great to have the doc reader be able to be guided from install to usage like we discussed at SciPy. The requests project does a pretty good job of this in their docs: lots of examples. 

What did you use to make the gif?

**Comment by jhamrick** [comment]
Yes, definitely :smile: 

I used a program called licecap to make the gif. I'll have a go at making a gif for the create assignment extension now and post it in the PR.

**Comment by willingc** [comment]
Here's my general plan:

- [ ] Create Contributor Guide so there is separation of end user technical info and developer info
- [ ] Revise the User Guide Table of Contents with the goal of guiding a first time instructor through the install, configuration, and use of nbgrader
- [ ] Edit doc pages and prefer 'instructor' or 'student' to the more generic term 'user' where 'instructor' includes instructors, IT personnel working on behalf of instructor, TAs, etc.

**Comment by jhamrick** [comment]
:+1:

**Comment by willingc** [comment]
@jhamrick With all the good work the past two days, I think it is reasonable to close this issue.

**Comment by jhamrick** [comment]
Ok, cool!
