### ISSUE TITLE
In Assignments tab, in Downloaded assignments, drop-down triangle doesn't do anything

### ISSUE THREAD

**Issue by jonathanmorgan** [jupyter/nbgrader#398]
In the Assignments tab, when you click the little triangle next to an assignment, the triangle rotates from pointing to the right to pointing down, implying something should happen, but it isn't doing anything.  For the assignment I am using to test, it just has one ipython notebook associated, I expected the notebook to appear there.  Not sure what that is supposed to do, but for me, it isn't doing anything.  Image attached is of the single assignment we have, with the triangle down and nothing under it.  Let me know if there is anything else I can do to help troubleshoot, or if you have an idea of how I'd fix this.

![screen shot 2015-08-30 at 10 16 04 am](https://cloud.githubusercontent.com/assets/490745/9567610/56b9faf0-4f00-11e5-9d64-0dd62d38fb3e.png)

**Comment by jhamrick** [comment]
Hmm, I can't seem to reproduce this. Have you tried it on multiple browsers? Are there any errors in the javascript console?

**Comment by jonathanmorgan** [comment]
Tried it on chrome and firefox, no javascript errors.  It looks like clicking it and switching it to dropped down invokes the following URL:

http://54.85.16.34:8000/user/jmorgan/api/contents?type=directory&_=1441040218033

and gets the following response body back (appears to be a listing of the contents of my user's home directory, sans things whose names start with a period?):

{"created": "2015-08-31T12:57:14.020159+00:00", "type": "directory", "name": "", "writable": true, "content": [{"created": "2015-08-29T23:33:16.080159+00:00", "type": "directory", "name": "06. Networks", "writable": true, "content": null, "last_modified": "2015-08-29T23:33:16.080159+00:00", "mimetype": null, "path": "06. Networks", "format": null}, {"created": "2015-08-29T22:57:16.280159+00:00", "type": "directory", "name": "Downloads", "writable": true, "content": null, "last_modified": "2015-08-29T22:57:16.280159+00:00", "mimetype": null, "path": "Downloads", "format": null}, {"created": "2015-08-29T19:50:43.172159+00:00", "type": "directory", "name": "nbgrader", "writable": true, "content": null, "last_modified": "2015-08-29T19:50:16.252159+00:00", "mimetype": null, "path": "nbgrader", "format": null}, {"created": "2015-08-27T18:01:09.016372+00:00", "type": "notebook", "name": "Data_and_databases.ipynb", "writable": true, "content": null, "last_modified": "2015-08-27T18:01:09.016372+00:00", "mimetype": null, "path": "Data_and_databases.ipynb", "format": null}, {"created": "2015-08-27T18:00:00.780373+00:00", "type": "file", "name": "lahman2013.sqlite", "writable": true, "content": null, "last_modified": "2015-08-27T18:00:00.780373+00:00", "mimetype": null, "path": "lahman2013.sqlite", "format": null}], "last_modified": "2015-08-31T12:57:14.020159+00:00", "mimetype": null, "path": "", "format": "json"}

Does that look right?

**Comment by jhamrick** [comment]
Ohh, I bet it is because you have a dot in your assignment name. Let me try try renaming my assignment and see...

I think probably that listing of the directory is from the "Files" tab, which sends periodic requests -- it may have just been a coincidence that you saw it when you tried to expand the problem set...

**Comment by jhamrick** [comment]
Yep, that's the issue. Fix incoming soon.

**Comment by jonathanmorgan** [comment]
works fine in0.2.2.
