### ISSUE TITLE
Create a Contributor Guide

### ISSUE THREAD

**Issue by willingc** [jupyter/nbgrader#401]
A Contributor Guide would collect details related to installation of a development environment, pull requests, testing, and documentation.

A benefit of the Contributor would be greater separation of 'end user/instructor' configuration and use of nbgrader from the 'developer' tasks of building, improving, and maintaining nbgrader.

**Comment by jhamrick** [comment]
:+1:

I also think it would be nice to split the current "user guide" into an "instructor guide" and a "student guide" or something along those lines.

**Comment by jhamrick** [comment]
Closed by #402
