### ISSUE TITLE
Releasing an assignment: why do I need to use the python API?

### ISSUE THREAD

**Issue by joschu** [jupyter/nbgrader#415]
Just commenting that it's a little peculiar that most of the workflow is through command line scripts but step 2 of [generating_assignments](http://nbgrader.readthedocs.org/en/latest/user_guide/03_generating_assignments.html) requires jumping into the python interpreter.

**Comment by jhamrick** [comment]
Yeah, that's a good point. Maybe I could add a configuration option that lets you specify the assignments as a dictionary or something so you can put them in your config file rather than having to run separate python code.
