### ISSUE TITLE
Preserve kernel information

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#417]
For example, if the notebook is expected to be python 3, but students turn it in as python 2, the kernel should be updated in the notebook metadata so that it is python 3 (and presumably also this notebook shouldn't validate properly unless students are using the right kernel).

cc @joschu

**Comment by jhamrick** [comment]
I am actually not sure if there is a super good way to do this, because kernels can have different names. Python kernels, regardless of whether they are Python 2 or Python 3, have language "python" but have different display names. So you can't tell based on the language name alone, but I also don't want to enforce that the display name is the same because this might be different for different people (e.g. "IPython 3" vs. "Python 3").

For the time being, I am going to close this issue, but if a good solution to this comes up in the future then I may reopen it.

**Comment by lgpage** [comment]
I would like to re-visit this issue. I have the following case that is annoying, grading with a kernel name `python3` but some student submissions are failing because their kernel name is `Python [root]`... stupid Anaconda

**Comment by jhamrick** [comment]
Perhaps one way to do it would be to store the kernel information in the database, and then rewrite the kernel name during autograding (i.e. when the cell contents are replaced)?

**Comment by lgpage** [comment]
That was my thinking.

**Comment by lgpage** [comment]
xref:
- https://github.com/jupyter/nbformat/issues/81
- https://github.com/jupyter/nbconvert/issues/515

**Comment by lgpage** [comment]
closed by #714
