### ISSUE TITLE
Contributor Guide link is broken

### ISSUE THREAD

**Issue by vinaykola** [jupyter/nbgrader#420]
The current link in https://github.com/jupyter/nbgrader/blob/master/CONTRIBUTING.md points to http://nbgrader.readthedocs.org/contributor_guide/index.html which doesn't exist in the stable version.

Should it point to http://nbgrader.readthedocs.org/en/latest/contributor_guide/index.html instead? I can make a PR to fix it.

**Comment by jhamrick** [comment]
Thanks for catching that! This should be fixed next time we do a release and the stable docs are updated, but I think it makes sense for it to point at the "latest" docs for contributors since they will most likely be working off of master anyway. If you wanted to make a PR that would be great!
