### ISSUE TITLE
Permissions conflict

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/nbgrader#429]
In the setup of formgrade, I have run into a permissions problem. Usually I run formgrade as the instructor for the course. This is because they are the one whose directory those files are usually in.

But, if you set the following option to have the HubAuth obtain a token automatically:

```
c.HubAuth.generate_hubapi_token = True
c.HubAuth.hub_db = "/srv/jupyterhub/jupyterhub.sqlite"
```

Then the instructor user doesn't have access to the directory where the sqlite directory is. Thus, I don't see how to use this approach without:

A) Opening  up the permissions to the jupyterhub db to all users.
B) Running the formgrade app as root.

Both seem like bad tradeoffs from a security standpoint. I think for now I will try to generate it manually as before...

**Comment by jhamrick** [comment]
Hmm, that's a good point. I think this is a feature that probably should be removed -- it's easy enough to generate the token manually, I think.
