### ISSUE TITLE
fetch and submit commands do not allow specifying assignment using --assignment option

### ISSUE THREAD

**Issue by mikebolt** [jupyter/nbgrader#433]
The following commands do not work:

    nbgrader fetch --assignment=assignment01 --course=data301a
    nbgrader fetch --assignment assignment01 --course data301a
    nbgrader fetch --course data301a --assignment=assignment01
    nbgrader fetch --course data301a --assignment assignment01

They all give the error:

    [FetchApp | ERROR] Must provide assignment name:
        nbgrader <command> ASSIGNMENT [ --course COURSE ]

The following two commands do work:

    nbgrader fetch --course data301a assignment01
    nbgrader fetch assignment01 --course data301a

Also, these two commands work by accident:

    nbgrader fetch --assignment = assignment01 --course data301a
    nbgrader fetch --course data301a --assignment = assignment01

All of the above also applies to the submit command. If this is the intended behavior then the command line help should make that more clear. It just says this:

    --assignment=<Unicode> (NbGrader.assignment_id)
        Default:
        The assignment name. This MUST be specified, either by setting the config
        option, passing an argument on the command line, or using the --assignment
        option on the command line

Discovered while submitting the first assignment in @ellisonbg 's data science course.

**Comment by jhamrick** [comment]
Thanks for reporting! This is definitely a behavior that should be allowed. For now, you'll need to just use one of the following syntaxes that you pointed out works:

```
nbgrader fetch --course data301a assignment01
nbgrader fetch assignment01 --course data301a
```

**Comment by mikebolt** [comment]
It would also be nice to be able to fetch multiple assignments with one command:

    nbgrader fetch --course data301a exampleA exampleB

This isn't supported right now. Perhaps specifying `--assignment exampleC` would just add to the set of assignments to fetch, and you could also use commas with the assignment flag like this:

    nbgrader fetch --assignment=exampleA,exampleB,exampleC --course data301a

**Comment by willingc** [comment]
@mikebolt Nice meeting you at Startup Weekend. I'm going to open your last comment as a wishlist item for future nbgrader development.

cc @jhamrick
