### ISSUE TITLE
Grading assignments in other language/kernels

### ISSUE THREAD

**Issue by sansary** [jupyter/nbgrader#434]
I would like to use nbgrader to grade nodejs assignments.
Is that possible? 
Well, anyhow, I went ahead and checked if it works out of the box with  the nodejs jupyter kernel, all went fine until I tried to autograde an assignment where I got "Need a JSON config object" and the tool blocked.

/S

**Comment by jhamrick** [comment]
nbgrader *should* be able to work with any Jupyter kernel. Can you paste the entire command line output when you try to run the command?

**Comment by sansary** [comment]
I get this line back:
        ```Need a JSON config object```
and nbgrader blocks I get this upon running validate or autograde, e.g.
      ```nbgrader validate submitted/Hacker/ProblemSetB/ProblemSetB.ipynb```

**Comment by jhamrick** [comment]
Can you run the autograde command with the `--debug` flag, and then paste the full output (everything that is printed out to the terminal, not just the `Need a JSON config object` line)?

**Comment by sansary** [comment]
AutogradeApp | DEBUG] Config changed:
[AutogradeApp | DEBUG] {'Application': {'log_level': 'DEBUG'}, 'Exporter': {'default_preprocessors': []}}
[AutogradeApp | DEBUG] Searching [u'/Users/sameh/src/jupyter_notebook', '/Users/sameh/.jupyter', '/Users/sameh/src/jupy/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[AutogradeApp | DEBUG] Attempting to load config file jupyter_config.py in path /etc/jupyter
[AutogradeApp | DEBUG] Attempting to load config file jupyter_config.json in path /etc/jupyter
[AutogradeApp | DEBUG] Attempting to load config file jupyter_config.py in path /usr/local/etc/jupyter
[AutogradeApp | DEBUG] Attempting to load config file jupyter_config.json in path /usr/local/etc/jupyter
[AutogradeApp | DEBUG] Attempting to load config file jupyter_config.py in path /Users/sameh/src/jupy/etc/jupyter
[AutogradeApp | DEBUG] Attempting to load config file jupyter_config.json in path /Users/sameh/src/jupy/etc/jupyter
[AutogradeApp | DEBUG] Attempting to load config file jupyter_config.py in path /Users/sameh/.jupyter
[AutogradeApp | DEBUG] Attempting to load config file jupyter_config.json in path /Users/sameh/.jupyter
[AutogradeApp | DEBUG] Attempting to load config file jupyter_config.py in path /Users/sameh/src/jupyter_notebook
[AutogradeApp | DEBUG] Attempting to load config file jupyter_config.json in path /Users/sameh/src/jupyter_notebook
[AutogradeApp | DEBUG] Attempting to load config file nbgrader_config.py in path /etc/jupyter
[AutogradeApp | DEBUG] Attempting to load config file nbgrader_config.json in path /etc/jupyter
[AutogradeApp | DEBUG] Attempting to load config file nbgrader_config.py in path /usr/local/etc/jupyter
[AutogradeApp | DEBUG] Attempting to load config file nbgrader_config.json in path /usr/local/etc/jupyter
[AutogradeApp | DEBUG] Attempting to load config file nbgrader_config.py in path /Users/sameh/src/jupy/etc/jupyter
[AutogradeApp | DEBUG] Attempting to load config file nbgrader_config.json in path /Users/sameh/src/jupy/etc/jupyter
[AutogradeApp | DEBUG] Attempting to load config file nbgrader_config.py in path /Users/sameh/.jupyter
[AutogradeApp | DEBUG] Attempting to load config file nbgrader_config.json in path /Users/sameh/.jupyter
[AutogradeApp | DEBUG] Attempting to load config file nbgrader_config.py in path /Users/sameh/src/jupyter_notebook
[AutogradeApp | DEBUG] Attempting to load config file nbgrader_config.json in path /Users/sameh/src/jupyter_notebook
[AutogradeApp | DEBUG] Loaded config file: /Users/sameh/src/jupyter_notebook/nbgrader_config.py
[AutogradeApp | DEBUG] Config changed:
[AutogradeApp | DEBUG] {'Application': {'log_level': 'DEBUG'}, 'Exporter': {'default_preprocessors': []}}
[AutogradeApp | INFO] Overwriting files with master versions from the source directory
[AutogradeApp | INFO] Sanitizing submitted/Bitdiddle/ProblemSetB/ProblemSetB.ipynb
[AutogradeApp | INFO] Converting notebook submitted/Bitdiddle/ProblemSetB/ProblemSetB.ipynb to notebook
[AutogradeApp | DEBUG] Student: Bitdiddle
[AutogradeApp | DEBUG] Assignment: ProblemSetB
[AutogradeApp | DEBUG] Notebook: ProblemSetB
[AutogradeApp | DEBUG] Applying preprocessor: ClearOutput
[AutogradeApp | DEBUG] Applying preprocessor: DeduplicateIds
[AutogradeApp | DEBUG] Applying preprocessor: OverwriteCells
[AutogradeApp | INFO] Writing 1850 bytes to autograded/Bitdiddle/ProblemSetB/ProblemSetB.ipynb
[AutogradeApp | INFO] Autograding autograded/Bitdiddle/ProblemSetB/ProblemSetB.ipynb
[AutogradeApp | INFO] Converting notebook autograded/Bitdiddle/ProblemSetB/ProblemSetB.ipynb to notebook
[AutogradeApp | DEBUG] Student: Bitdiddle
[AutogradeApp | DEBUG] Assignment: ProblemSetB
[AutogradeApp | DEBUG] Notebook: ProblemSetB
[AutogradeApp | DEBUG] Applying preprocessor: Execute
[AutogradeApp | INFO] Executing notebook with kernel: nodejs
[AutogradeApp | DEBUG] Found kernel nodejs in /Users/sameh/.ipython/kernels
[AutogradeApp | DEBUG] Native kernel (python2) available from /Users/sameh/src/jupy/lib/python2.7/site-packages/ipykernel/resources
[AutogradeApp | DEBUG] Starting kernel: [u'node', u'/Users/sameh/src/jupy/package/build/run.js', u'/var/folders/4d/drh_smbj7kl1lwtn3y8q18gh0000gn/T/tmpHKYmxx.json', '--HistoryManager.hist_file=:memory:']
[AutogradeApp | DEBUG] Connecting to: tcp://127.0.0.1:54109
[AutogradeApp | DEBUG] connecting shell channel to tcp://127.0.0.1:54106
[AutogradeApp | DEBUG] Connecting to: tcp://127.0.0.1:54106
[AutogradeApp | DEBUG] connecting iopub channel to tcp://127.0.0.1:54107
[AutogradeApp | DEBUG] Connecting to: tcp://127.0.0.1:54107
[AutogradeApp | DEBUG] connecting stdin channel to tcp://127.0.0.1:54108
[AutogradeApp | DEBUG] Connecting to: tcp://127.0.0.1:54108
[AutogradeApp | DEBUG] connecting heartbeat channel to tcp://127.0.0.1:54110
Need a JSON config object

**Comment by jhamrick** [comment]
Ah, hmm, I wonder if the issue could be from this line:

```
[AutogradeApp | DEBUG] Starting kernel: [u'node', u'/Users/sameh/src/jupy/package/build/run.js', u'/var/folders/4d/drh_smbj7kl1lwtn3y8q18gh0000gn/T/tmpHKYmxx.json', '--HistoryManager.hist_file=:memory:']
```

That argument for the history manager is probably specific to the ipython kernel. If you comment out the following line in the nbgrader source, does the error go away https://github.com/jupyter/nbgrader/blob/master/nbgrader/preprocessors/execute.py#L10

You can find out where the file is by opening a python interpreter and running:

```
import nbgrader.preprocessors.execute; nbgrader.preprocessors.execute.__file__
```

**Comment by jhamrick** [comment]
Just tested this, and it is indeed a problem with the `HistFile` argument. I will push a fix that only adds this when the python kernel is being used.

However, I also noticed while doing this that there is currently a bug in the ijavascript kernel that prevents the outputs from being saved into the notebook, just FYI: https://github.com/n-riesco/ijavascript/issues/62 So at the moment you won't be able to use nbgrader with the ijavascript kernel.
