### ISSUE TITLE
Add override for submitting work as another user (guest accounts).

### ISSUE THREAD

**Issue by davis68** [jupyter/nbgrader#437]
It would be occasionally convenient to have a flag to override the default submission id for students using guest accounts.  I.e.,

```
nbgrader submit <asst> --id=<xxx>
```

Can this be implemented without being a security liability?  One possibility is to tag the actual submitter's account id (and/or hostname) and flag something in the metadata if it differs from the override.

@jhamrick commented:

<blockquote>Hmm, I’m not sure how this would work from a security standpoint. Currently it always submits assignments as the username of the user submitting the assignment, so the instructor can always be sure who submitted what. But if you allow students to specify an id, then what’s to stop one student from submitting a blank assignment using another student’s id?</blockquote>

**Comment by jhamrick** [comment]
Another possibility is to have the instructor create a whitelist specifying which users are allowed to submit with which ids. The whitelist gets stored in the exchange directory and then the submit command would look at the whitelist to determine whether the student was allowed to submit with the id they gave.

Any thoughts on this, @ellisonbg ?

**Comment by jhamrick** [comment]
This was addressed by #1098
