### ISSUE TITLE
Add stability to RTD builds

### ISSUE THREAD

**Issue by willingc** [jupyter/nbgrader#450]
Let's look at migrating what we learned from JupyterHub and Notebook docs to improve the builds on RTD.

Example of build error:
http://readthedocs.org/projects/nbgrader/builds/3782854/

**Comment by jhamrick** [comment]
Let me know if you think #451 addresses this well enough. If there are other things you've learned from the other Jupyter projects that we're not doing here, I'd definitely like to incorporate those things, too!

**Comment by willingc** [comment]
@jhamrick #451 is an excellent for now. A few things that we may wish to do going forward:

- [ ] Make sure when a release is tagged in GitHub that the documentation corresponding to the release is in the release before tagging. RTD is a pain since it will only allow you to build versions (with the exception of master) of docs that correspond to a tag.
- [ ] Look into using YAML files for RTD as we have on JupyterHub
- [ ] We can, if desired, add captions in the TOC to break things up more neatly in the left hand sidebar of the docs
- [ ] We can add linkcheck and spelling if they are not already enabled

That's all I can think of now. None is urgent before the next release with the exception of the tag (though I think you have already been doing this).

**Comment by jhamrick** [comment]
Yeah, I have already been doing the first one. I just opened a PR to add the yaml file and linkcheck and spelling. How do you propose adding captions? I don't think I know exactly what that means -- could you link to an example or something that does it so I have a better idea?

**Comment by willingc** [comment]
@jhamrick Love the stuff already done. Yay spelling ;)

The captions are completely optional and are displayed in the left hand sidebar. You set the captions in index.rst under the toctree. Example https://raw.githubusercontent.com/jupyter/notebook/master/docs/source/index.rst

**Comment by jhamrick** [comment]
Ahhh, I see, cool. Yes, that totally seems like a worthwhile thing to have :+1:  I'll update that shortly as well :-)
