### ISSUE TITLE
Contributor Guide link broken

### ISSUE THREAD

**Issue by alchemyst** [jupyter/nbgrader#468]
The link to the Contributor Guide in `CONTRIBUTING.md` is broken.

**Comment by jhamrick** [comment]
Sorry about that. Thanks for catching this and #469! Should be fixed soon.

**Comment by alchemyst** [comment]
No problem. I'm a big documentation reader, so I'm sure I'll be throwing some additional stuff in there as I go through the process of learning the system. It's often useful to have a naive user try to follow the instructions and report where they tripped up. I would have fixed it myself if I knew where the links were supposed to be pointing to.

**Comment by jhamrick** [comment]
Yes, I definitely agree. Thanks, having new users point out where the docs are unclear is a huge help!
