### ISSUE TITLE
Fix failing windows tests

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#479]
Just so I remember to do so before the release...

**Comment by willingc** [comment]
@jhamrick If you send me a link to Jenkins, I'll take a look at the logs.

**Comment by jhamrick** [comment]
Here's the jenkins page: https://jenkins.jupyter.org/job/nbgrader/

The tests pass on my local windows computer, so there's something different about the two machines. I'm not really sure what to do about the failures -- they seem to be spurious, but happen with a high enough probability that across all tests the likelihood of one of them failing is pretty high. If you have any insight, that would be awesome.

Typical examples of failures:

* This one is spurious and sometimes happens, sometimes not: https://jenkins.jupyter.org/job/nbgrader/52/_mark=not%20formgrader%20and%20not%20nbextensions,_pyversion=3.5,label=windows/testReport/nbgrader.tests.apps.test_nbgrader_quickstart/TestNbGraderQuickStart/test_quickstart/
* This one always happens on Jenkins, but never locally: https://jenkins.jupyter.org/job/nbgrader/52/_mark=nbextensions,_pyversion=3.5,label=windows/testReport/nbgrader.tests.nbextensions/test_create_assignment/test_tests_cell/

**Comment by willingc** [comment]
I haven't looked at the logs yet. But if the tests use Selenium, it would make sense if they don't pass on Jenkins since the browser window acts differently locally vs. on jenkins.

**Comment by jhamrick** [comment]
Hmm, really? Even with phantomjs (which is headless)? Do you know in what ways the behavior is different?

**Comment by willingc** [comment]
http://chimera.labs.oreilly.com/books/1234000000754/apg.html#_run_your_tests_against_different_browsers

I thought I remembered something from `TA`ing Harry's tutorial a few times. Selenium can be very tempermental when its not given time to wait for a system to execute.

**Comment by willingc** [comment]
May also be helpful from Harry's ebook: http://chimera.labs.oreilly.com/books/1234000000754/apf.html#_selenium_functional_testing_best_practices
