### ISSUE TITLE
No documentation on db_students and db_assignments

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/nbgrader#480]
Just rain into a pain point with a faculty member - a recent commit deprecated the `--create` flag in the create and autograde apps in favor of the db_students and db_assignments config values. But these are not documented anywhere that I could see in the documentation. Are these the recommended way of doing these things? Is there a better approach for adding students and assignments?

@dlsun

**Comment by jhamrick** [comment]
Yes, they are now the recommended way of doing things as the previous way essentially required writing a separate script to add assignments and students to the database, or using the `--create` flag (which was actually not recommended in general, as it doesn't add things like assignment due dates or student names/emails).

The `db_students` and `db_assignments` are definitely in the documentation -- but not on the stable branch, which is maybe where you were looking? There are several places that they show up in the "latest" documentation:

* http://nbgrader.readthedocs.org/en/latest/user_guide/philosophy.html?highlight=db_assignments#configuration-files
* http://nbgrader.readthedocs.org/en/latest/user_guide/creating_and_grading_assignments.html?highlight=db_assignments#configure-assignments-and-students-in-the-config-file
* http://nbgrader.readthedocs.org/en/latest/configuration/config_options.html

**Comment by jhamrick** [comment]
I will close this for now as no action, but let me know if you think the documentation isn't sufficient.

**Comment by ellisonbg** [comment]
Perfect, those docs will do fine! Thanks!

On Tue, Apr 5, 2016 at 11:36 PM, Jessica B. Hamrick <
notifications@github.com> wrote:

> Closed #480 <https://github.com/jupyter/nbgrader/issues/480>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/nbgrader/issues/480#event-616264890>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
