### ISSUE TITLE
Next/Prev links have stopped working in formgrader

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/nbgrader#487]
In our deployment the Next/Prev links in the formgrader have stopped working. We get a 404. This is currently slowing the graders down a lot - any ideas on how to fix?  @dlsun

**Comment by jhamrick** [comment]
Hmm, that's definitely a problem. Are you running off of master? I can't seem to reproduce the problem. What URLs does it try to go to when you click on the prev/next buttons?

**Comment by dlsun** [comment]
The URL should have "/nbgrader/dlsun" as part of its path. This part is
missing from the Next and Prev links, resulting in a 404: Not Found error.
The URL is correct otherwise.

**Comment by ellisonbg** [comment]
I am running off master from about 3 weeks ago.

On Tue, Apr 19, 2016 at 12:53 PM, Jessica B. Hamrick <
notifications@github.com> wrote:

> Hmm, that's definitely a problem. Are you running off of master? I can't
> seem to reproduce the problem. What URLs does it try to go to when you
> click on the prev/next buttons?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/nbgrader/issues/487#issuecomment-212098488>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jhamrick** [comment]
If you click the other "breadcrumbs" links (the ones in between the next and prev links), are those broken, too?

**Comment by jhamrick** [comment]
Ok, I think I've found the bug! I will make a PR shortly...

**Comment by jhamrick** [comment]
#489 should fix the issue. If you can test it out and verify that it works that would be awesome. If not, that's ok; I'm pretty confident this fixes it.

**Comment by dlsun** [comment]
Hi Jess,

The "Next" button is now working, but now the "Prev" button is missing
entirely. I forked your baseurl branch. Do you know what's going on?

Thanks,
Dennis

**Comment by jhamrick** [comment]
Hrm, no, and I can't reproduce it. Could it perhaps be a browser cache issue -- if you try disabling/clearing the cache does it go away?

**Comment by dlsun** [comment]
The problem seems to have resolved itself -- thanks!

By the way, the base_url problem seems to have been fixed for the "Next"
and "Prev" links, but not for the "Submission #" link.
