### ISSUE TITLE
Allow the assignment of extra credit on a notebook or assignment

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/nbgrader#488]
Right now nbgrader enforces the students score to be less than or equal to the max possible. This make it impossible to give extra credit to students on a problem. What would be the best way of allowing that?

In the past, I have kept a separate text file with that information and put it into the grades at the end of the term.  @dlsun

**Comment by jhamrick** [comment]
There's not a good way of allowing this currently, unfortunately. In my class we had separate "extra credit" assignments that students could optionally complete but there was no extra credit in the regular assignments. How exactly do you want to do the extra credit? Is it actually that you want to assign extra points to regular grade cells, or that you want to have a part of the problem that is optional and gives extra credit?

**Comment by ellisonbg** [comment]
I will let @dlsun describe here how he is wanting to use extra credit...

On Tue, Apr 19, 2016 at 12:57 PM, Jessica B. Hamrick <
notifications@github.com> wrote:

> There's not a good way of allowing this currently, unfortunately. In my
> class we had separate "extra credit" assignments that students could
> optionally complete but there was no extra credit in the regular
> assignments. How exactly do you want to do the extra credit? Is it actually
> that you want to assign extra points to regular grade cells, or that you
> want to have a part of the problem that is optional and gives extra credit?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/nbgrader/issues/488#issuecomment-212100763>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by dlsun** [comment]
I would like to be able to assign extra points to regular grade cells. The
other use case seems like it would be easily handled if we had this
feature, since we could just make a grade cell worth 0 points.

**Comment by jhamrick** [comment]
Hmm, ok. There are two ways that I think you could get around this, though I haven't tested them. There's no "official" way to do it but it's certainly something I can try to add in a future release.

1. You can hack the javascript in the formgrader, specifically this line: https://github.com/jupyter/nbgrader/blob/master/nbgrader/formgrader/static/js/models.js#L44 I think it would involve changing `max_score` there to `val`, and then restarting the formgrader. This will allow you to assign scores that are greater than the max score.
2. You can create an extra grade cell when you create the assignment that is "extra credit" with points equal to the maximum amount of extra credit you think you will assign. nbgrader will then report the max points for the assignment as being the true max points plus the max extra credit, but that should be ok as long as you remember what the "true" maximum score should be.

**Comment by dlsun** [comment]
Great, thanks! I opened up the developer console in Chrome and manually
edited the Javascript. I can verify that this one change to the Javascript
works.

If you'd like, I can make a pull request. I think that the instructor just
needs to be warned that they're giving more than the
max points in a cell. This seems like functionality that would be generally
very useful.

-- Dennis

**Comment by jhamrick** [comment]
I'm a bit hesitant to just remove the functionality that prevents you from assigning too many points... I know I definitely rely on that to catch my own mistakes while I am grading. I wonder if we could instead add something like a checkbox to the create assignment extension that says something like "allow extra credit", and then when the assignment is being graded if that flag is set it won't complain about putting in more points than it's worth. So that way you can definitely enable that if you want, but you have to do so explicitly. What do you think?
