### ISSUE TITLE
Document how to get late submission times from assignments

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#502]

**Comment by willingc** [comment]
@jhamrick You beat me to filing an issue on this. Also, consider documenting parts of [mailing list response](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jupyter/NRB9CQNBMfo/sNWz1DwZBgAJ) in a FAQ of some sort for nbgrader.

**Comment by jhamrick** [comment]
Great idea!
