### ISSUE TITLE
Getting nbgrader to work with jupyterhub

### ISSUE THREAD

**Issue by Sullivanstatistics** [jupyter/nbgrader#514]
I have a working version of jupyterhub on my server and I stop the jupyterhub server, then I run:

nbgrader extension activate

It shows me that it is working. I restart the server and when I go to create a graded assignment I cannot find  a way to do it. All that shows is the typical:

- code
- markdown
- Raw NBconvert
- Heading

I am not sure if I missed something with the install or what is going on.

**Comment by jhamrick** [comment]
The nbgrader cell types are different from the regular cell types, so you won't find them there. To get access to them, you need to activate the "Create Assignment" celltoolbar, which you can find I think in "View -> Cell Toolbar" (I don't have the notebook in front of me, so I might be wrong about the exact menu name). If you don't see the "Create Assignment" celltoolbar then the extension isn't being loaded properly (it should be in a list with other celltoolbars like "Edit Metadata" and "Slideshow").

**Comment by jhamrick** [comment]
I am going to close this for now since there hasn't been activity, but if you are still having problems feel free to reopen!
