### ISSUE TITLE
Uncaught exception GET /assignments?_=1464647188091 (::1)

### ISSUE THREAD

**Issue by magsol** [jupyter/nbgrader#515]
I'm seeing some strange errors after installing nbgrader and firing up a Jupyter notebook.

(Aside: I installed nbgrader through conda, so it's version 0.3.0-dev; I'm running Python 3.5.1; Jupyter 4.2.0, notebook **4.1.0**)

Everything seems to install just fine, until I execute `jupyter notebook`:

```
Apollo:notebookdir user$ jupyter notebook
[W 15:26:27.133 NotebookApp] Unrecognized JSON config file version, assuming version 1
[I 15:26:27.510 NotebookApp] Serving notebooks from local directory: /home/user/notebookdir
[I 15:26:27.510 NotebookApp] 0 active kernels 
[I 15:26:27.510 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 15:26:27.510 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[E 15:26:29.134 NotebookApp] Uncaught exception GET /assignments?_=1464647188091 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/assignments?_=1464647188091', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'en-US,en;q=0.8', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/tree', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'Accept-Encoding': 'gzip, deflate, sdch', 'Cookie': '_ga=GA1.1.1283186454.1454350702', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36', 'Host': 'localhost:8888', 'X-Requested-With': 'XMLHttpRequest'})
    Traceback (most recent call last):
      File "/opt/python/lib/python3.5/site-packages/tornado/web.py", line 1443, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/python/lib/python3.5/site-packages/tornado/web.py", line 2800, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/python/lib/python3.5/site-packages/nbgrader/nbextensions/assignment_list/handlers.py", line 99, in get
        self.finish(json.dumps(self.manager.list_assignments()))
      File "/opt/python/lib/python3.5/site-packages/nbgrader/nbextensions/assignment_list/handlers.py", line 48, in list_assignments
        assignments.extend(self.list_released_assignments())
      File "/opt/python/lib/python3.5/site-packages/nbgrader/nbextensions/assignment_list/handlers.py", line 28, in list_released_assignments
        raise RuntimeError('nbgrader list exited with code {}'.format(retcode))
    RuntimeError: nbgrader list exited with code 1
[E 15:26:29.141 NotebookApp] {
      "Accept-Language": "en-US,en;q=0.8",
      "Connection": "keep-alive",
      "Referer": "http://localhost:8888/tree",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Accept-Encoding": "gzip, deflate, sdch",
      "Cookie": "_ga=GA1.1.1283186454.1454350702",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36",
      "Host": "localhost:8888",
      "X-Requested-With": "XMLHttpRequest"
    }
[E 15:26:29.141 NotebookApp] 500 GET /assignments?_=1464647188091 (::1) 792.78ms referer=http://localhost:8888/tree
```

In the webpage itself, I have an "Assignments" tab, but it's empty, and I have no cell toolbar for specifying a notebook as an Assignment.

I'm hoping this isn't another [version clash](https://github.com/jupyter/nbgrader/issues/497)...or something else I'm doing that's stupid :P Thank you!

**Comment by magsol** [comment]
I don't know if this is related at all, but I'm finding some inconsistencies in the documentation vs what my nbgrader has available. For instance:

```
Apollo:notebookdir user$ nbgrader quickstart
[NbGraderApp | ERROR] No command given (run with --help for options)
```

Furthermore, the `quickstart` subcommand does not show up in the list of available subcommands (`nbgrader --help | grep quickstart` is empty).

**Comment by jhamrick** [comment]
You are probably running an older version of nbgrader that doesn't have the quickstart command yet (the quickstart command is not in a released version, yet, only the development version). Can you paste the output of `nbgrader --version`?

The reason the assignment list is blank is probably related to `RuntimeError: nbgrader list exited with code 1`. Can you paste the output of `nbgrader list`?

**Comment by magsol** [comment]
nbgrader version:

```Apollo:~ user$ nbgrader --version
Python version 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:24:55) 
[GCC 4.2.1 (Apple Inc. build 5577)]
nbgrader version 0.3.0.dev
```

nbgrader list:
```
Apollo:~ user$ nbgrader list
[ListApp | ERROR] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
```

Yikes; not sure what's going on there?

**Comment by magsol** [comment]
With respect to the `nbgrader list` output--I generated a configuration file and filled in some of the defaults. That aspect at least appears to work now, and I don't get the 500 errors anymore when I start up a `jupyter notebook`.

That said, it's still strange that I'm not seeing a quickstart subcommand. Unless I'm somehow not getting the latest version?

**Comment by magsol** [comment]
Installed on a different system--both `pip install nbgrader` and `conda install -c jhamrick nbgrader` install the nbgrader package version 0.3.0.dev. In both cases, there was no `quickstart` subcommand, and running `nbgrader quickstart` returned an error:

```
[NbGraderApp | ERROR] No command given (run with --help for options)
```

Should I run a different version?

**Comment by jhamrick** [comment]
Argh, so this is partially my fault, I think. The quickstart command is only available in the dev version, but the package installed by conda isn't the most recent dev version and so it doesn't have it. The documentation is misleading in this regard because I only anticipated it would be wrong for a few days (rather than the few weeks it's turned into 😞 ) I've been trying to get nbgrader v0.3.0 released for the last few weeks but have been really swamped and am behind on that -- but as soon as that's released I will update both packages on pip and conda and both should be up to date.

In the meantime, if you want the quickstart command you will need to install it from source: http://nbgrader.readthedocs.io/en/latest/contributor_guide/installation_developer.html
