### ISSUE TITLE
The code snippet for answer should be kernel sensitive.

### ISSUE THREAD

**Issue by randy3k** [jupyter/nbgrader#517]
For instance, for R kernel, it should be just `stop(...)`.

https://github.com/jupyter/nbgrader/blob/7fd3a62852b784486b7e27f88150736ce422b4e1/nbgrader/preprocessors/clearsolutions.py#L11

**Comment by Carreau** [comment]
I'm confused by what you are asking. 

All the `somethin = Unicode(...)`  are configurable option with default values, so you can change them to whatever you desire, whether you want to change the kernel language, or whether you teach in a non-english environment.

**Comment by randy3k** [comment]
I see, so I could change them in the `metadata` of a notebook. Thanks for pointing it out.

**Comment by randy3k** [comment]
I guess I have misunderstood what you meant. If I am correct, the configuration has to be done statically in [here](https://github.com/jupyter/nbgrader/blob/7fd3a62852b784486b7e27f88150736ce422b4e1/nbgrader/apps/assignapp.py#L38) , how could I specify the changes dynamically for each of the notebooks? Assume that there are python and r notebooks.

**Comment by jhamrick** [comment]
Ah, hmm, that isn't something that can be handled super cleanly at the moment. I have been assuming that all the notebooks for a class are in the same language.

A way to fix this I think would be to make the code snippet stub configurable option actually be a dictionary, with keys being the language name.
