### ISSUE TITLE
Getting 404 error on Dockerspawner container

### ISSUE THREAD

**Issue by huwf** [jupyter/nbgrader#519]
I'm trying to set up nbgrader with jupyterhub for use with Canvas or an online course.  I have set up jupyterhub okay, and have a Docker image of nbgrader (below) which works fine as a single notebook.  

If I use the `jupyterhub/singleuser` with the jupyterhub dockerspawner, it works no problem.  However, with the nbgrader image, I get a 404 when I try and access it at the address the jupyterhub sends to (:8000/user/e7ce0ad264).  It seems to have installed fine though, because if I go to http://127.0.0.1:32802 then I can access the notebook (though the mount doesn't seem to work properly).  Note I'm using notebook==0.4.1 as a 

It might not be an nbgrader issue, but I can't figure it, and it seems to be the a reasonable guess.  Any thoughts?

Cheers

## Log
	oauth_consumer_key=XXXX&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1466014882&oauth_nonce=a7LjTH70hxzMRB5CzzgPlAZE7QyqqG72qA40QzXdfs&oauth_version=1.0&context_id=d03513557d&context_title=Lesson+272&launch_presentation_return_url=https%3A%2F%2Flearn-lti.herokuapp.com%2Ftool_return%2Fsignature_check%2F0%2F3632&lis_person_name_full=Wei+Hansen&lti_message_type=basic-lti-launch-request&lti_version=LTI-1p0&resource_link_id=b037ea430d&roles=&tool_consumer_instance_name=Hippo+534&user_id=e7ce0ad264&oauth_signature=IYwU6tWGlmqJby57h4yc0hniJHY%3D

	Authenticated? True
	[I 2016-06-15 19:21:22.436 JupyterHub dockerspawner:333] Container 'jupyter-e7ce0ad264' is gone
	[W 2016-06-15 19:21:22.436 JupyterHub dockerspawner:304] container not found
	[I 2016-06-15 19:21:22.491 JupyterHub dockerspawner:333] Container 'jupyter-e7ce0ad264' is gone
	[I 2016-06-15 19:21:22.588 JupyterHub dockerspawner:395] Created container 'jupyter-e7ce0ad264' (id: bb01840) from image huwf/nbgrader
	[I 2016-06-15 19:21:22.588 JupyterHub dockerspawner:405] Starting container 'jupyter-e7ce0ad264' (id: bb01840)
	[I 2016-06-15 19:21:23.715 JupyterHub base:306] User e7ce0ad264 server took 1.279 seconds to start
	[I 2016-06-15 19:21:23.715 JupyterHub orm:159] Adding user e7ce0ad264 to proxy /user/e7ce0ad264 => http://127.0.0.1:32802
	[I 2016-06-15 19:21:23.740 JupyterHub log:100] 302 POST /hub/login (@::ffff:127.0.0.1) 1366.05ms
	[I 2016-06-15 19:21:23.741 JupyterHub login:86] User logged in: e7ce0ad264
	[I 2016-06-15 19:21:23.771 JupyterHub log:100] 302 GET /hub/ (e7ce0ad264@::ffff:127.0.0.1) 20.36ms
	[I 2016-06-15 19:21:23.915 JupyterHub log:100] 302 GET /static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=9b2c8d3489227115310662a343fce11c (@::ffff:127.0.0.1) 1.37ms
	[I 2016-06-15 19:21:23.977 JupyterHub log:100] 302 GET /custom/custom.css (@::ffff:127.0.0.1) 0.96ms
	[I 2016-06-15 19:21:23.994 JupyterHub log:100] 302 GET /static/components/jquery-typeahead/dist/jquery.typeahead.min.css?v=7afb461de36accb1aa133a1710f5bc56 (@::ffff:127.0.0.1) 3.26ms
	[I 2016-06-15 19:21:24.001 JupyterHub log:100] 302 GET /static/style/style.min.css?v=807166c81ded9672f91872a576572dcd (@::ffff:127.0.0.1) 1.37ms
	[W 2016-06-15 19:21:24.048 JupyterHub log:100] 404 GET /hub/custom/custom.css (e7ce0ad264@::ffff:127.0.0.1) 40.81ms
	[W 2016-06-15 19:21:24.049 JupyterHub log:100] 404 GET /hub/static/components/jquery-typeahead/dist/jquery.typeahead.min.css?v=7afb461de36accb1aa133a1710f5bc56 (@::ffff:127.0.0.1) 0.60ms
	[W 2016-06-15 19:21:24.051 JupyterHub log:100] 404 GET /hub/static/style/style.min.css?v=807166c81ded9672f91872a576572dcd (@::ffff:127.0.0.1) 0.93ms
	[W 2016-06-15 19:21:24.053 JupyterHub log:100] 404 GET /hub/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=9b2c8d3489227115310662a343fce11c (@::ffff:127.0.0.1) 1.00ms
	[I 2016-06-15 19:21:24.059 JupyterHub log:100] 302 GET /static/components/es6-promise/promise.min.js?v=f004a16cb856e0ff11781d01ec5ca8fe (@::ffff:127.0.0.1) 1.19ms
	[I 2016-06-15 19:21:24.068 JupyterHub log:100] 302 GET /static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce (@::ffff:127.0.0.1) 1.21ms
	[W 2016-06-15 19:21:24.077 JupyterHub log:100] 404 GET /hub/static/components/es6-promise/promise.min.js?v=f004a16cb856e0ff11781d01ec5ca8fe (@::ffff:127.0.0.1) 4.43ms
	[I 2016-06-15 19:21:24.108 JupyterHub log:100] 302 GET /static/base/images/logo.png?v=7c4597ba713d804995e8f8dad448a397 (@::ffff:127.0.0.1) 1.38ms
	[W 2016-06-15 19:21:24.115 JupyterHub log:100] 404 GET /hub/static/base/images/logo.png?v=7c4597ba713d804995e8f8dad448a397 (@::ffff:127.0.0.1) 1.01ms

## Config

    import os
    import sys
	c = get_config()

	c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'

	c.DockerSpawner.container_image = "huwf/nbgrader"
	c.DockerSpawner.args = ['-it', '-v' '$(pwd):/home/jovyan/assignments']
	c.DockerSpawner.debug = True

	c.JupyterHub.hub_ip = << My IP Address >>
	c.JupyterHub.port = 8000

	c.JupyterHub.log_level = 'DEBUG'
	c.JupyterHub.authenticator_class = 'ltiauthenticator.LTIAuthenticator'

	join = os.path.join

	here = os.path.dirname(__file__)
	# root = os.environ.get('OAUTHENTICATOR_DIR', here)
	sys.path.insert(0, here)

	# ssl config
	ssl = join(here, 'ssl')

	keyfile = join(ssl, 'key.pem')
	certfile = join(ssl, 'cert.pem')
	if os.path.exists(keyfile):
	    c.JupyterHub.ssl_key = keyfile
	if os.path.exists(certfile):
	    c.JupyterHub.ssl_cert = certfile

## Dockerfile 

    # Still in development
    FROM jupyterhub/singleuser

    USER root
    RUN python3 -m pip install notebook==4.1
    RUN python3 -m pip install nbgrader

    RUN python3 -m pip install pymongo

    # Where the assignments will live (these need to be mounted on runtime)
    RUN mkdir /home/jovyan/assignments
    WORKDIR /home/jovyan/assignments

    RUN nbgrader extension install --symlink
    RUN nbgrader extension activate

    CMD ["jupyter", "notebook", "--no-browser", "--ip=0.0.0.0"]

**Comment by huwf** [comment]
Well that's embarrassing.  Turns out that after two days searching through the config, and then 3 hours after I post a question that my `CMD` in the `Dockerfile` was the problem.  I removed it and then everything worked.  Nothing to do with nbgrader after all! :)

**Comment by jhamrick** [comment]
Glad you were able to figure it out! 😄
