### ISSUE TITLE
Validation fails for `assignment_list/main`

### ISSUE THREAD

**Issue by davis68** [jupyter/nbgrader#532]
In preparation for courses next week, I'm upgrading and testing our jupyter/nbgrader installation.  The following error occurs:
```
$ nbgrader extension activate assignment_list
Unrecognized JSON config file version, assuming version 1
Unrecognized JSON config file version, assuming version 1
Activating assignment_list server extension
Unrecognized JSON config file version, assuming version 1
Enabling tree extension assignment_list/main...
      - Validating: problems found:
        - require?  X assignment_list/main
Done. You may need to restart the Jupyter notebook server for changes to take effect.
```

Symptoms:  The command-line `nbgrader` works, but the browser extension doesn't appear.  (I'm not worried about the unrecognized JSON version lines—those have always been there without affecting behavior.)

This seems similar to issues #497, #501, and *maybe* #515.

I am using versions:
```
jupyter==1.0.0
jupyter-client==4.3.0
jupyter-console==5.0.0
jupyter-core==4.1.1
nbgrader==0.3.0
notebook==4.2.2
```

Any idea what's gone wrong here?

**Comment by davis68** [comment]
I'm going to think out loud here as I work on this.  The code raising the error is in [`notebook/nbextensions.py`](https://github.com/jupyter/notebook/blob/025f753c7d92dd2875d5ca7591238e459a29df59/notebook/nbextensions.py#L497), lines 497–524; in particular:
```
    warnings = []
    infos = []

    js_exists = False
    for exts in _nbextension_dirs():
        # Does the Javascript entrypoint actually exist on disk?
        js = u"{}.js".format(os.path.join(exts, *require.split("/")))
        js_exists = os.path.exists(js)
        if js_exists:
            break

    require_tmpl = u"        - require? {} {}"
    if js_exists:
        infos.append(require_tmpl.format(GREEN_OK, require))
    else:
        warnings.append(require_tmpl.format(RED_X, require))
    
    if logger:
        if warnings:
            logger.warning(u"      - Validating: problems found:")
            for msg in warnings:
                logger.warning(msg)
```

This implies that `notebook` isn't finding the JS where it expects to.  Now to chase that down...

**Comment by davis68** [comment]
Looks like `notebook` expects `assignment_list/main.js` to be located in my virtual environment under `share/jupyter/nbextensions/`, but there's nothing there.  *Those* are actually in `etc/jupyter/nbextensions`, so something's changed in directory structure expectations or I did something fiddly when I installed one or the other.  I'll try symlinking the `etc/` JS files to `share/` and report back.

**Comment by lgpage** [comment]
What is in your config files?
- `~/.jupyter/jupyter_notebook_config.json`
- `~/.jupyter/nbconfig/notebook.json`

**Comment by davis68** [comment]
OK, that fixes it.  Within the context of my virtual environment:
```
ln -s etc/jupyter/assignment_list/ share/jupyter/nbextensions/assignment_list
ln -s etc/jupyter/create_assignment/ share/jupyter/nbextensions/create_assignment
```
did the trick.

**Comment by davis68** [comment]
For my primary (system) user:
```
$ cat ~/.jupyter/jupyter_notebook_config.json 
{
  "NotebookApp": {
    "server_extensions": []
  }
```

For my student users, they have no `.jupyter/` directory being created.

**Comment by jhamrick** [comment]
Hmm, this doesn't seem like something that should happen, so I'm going to reopen this and try to investigate.

I wonder how those files ended up in `/etc`. Perhaps you had an older version of the nbgrader extensions? I think they used to live somewhere else, though I don't know if they ever lived in etc. When you ran `nbgrader extension install`, what got printed out? For me, it says they're getting printed out to `/usr/local/share`, not `/etc`:

```
$ nbgrader extension install assignment_list
Unrecognized JSON config file version, assuming version 1
Installing assignment_list extension
Making directory: /usr/local/share/jupyter/nbextensions/assignment_list/
Copying: /Users/jhamrick/project/tools/nbgrader/nbgrader/nbextensions/static/assignment_list/assignment_list.css -> /usr/local/share/jupyter/nbextensions/assignment_list/assignment_list.css
Copying: /Users/jhamrick/project/tools/nbgrader/nbgrader/nbextensions/static/assignment_list/assignment_list.js -> /usr/local/share/jupyter/nbextensions/assignment_list/assignment_list.js
Copying: /Users/jhamrick/project/tools/nbgrader/nbgrader/nbextensions/static/assignment_list/main.js -> /usr/local/share/jupyter/nbextensions/assignment_list/main.js
```

Also, are you on mac?

**Comment by davis68** [comment]
It's a sitewide Scientific Linux installation.  I've now located the
offending line, used because I'm in a virtual environment:

    nbgrader extension install
--nbextensions=/class/cs101/etc/venv/cs101-fa16/etc/jupyter --symlink
--debug

From `cs101-fa16/` on is the relevant portion of that path.  This was, as I
recall, a way of sidestepping difficulties with using local .jupyter
directories.  (I don't have root access to the system so I've contrived
ways around that limitation.)

**Comment by jhamrick** [comment]
Ah, so the issue is that you are installing to a custom nbextensions folder and then Jupyter doesn't know where to find that folder?

Just to verify I'm understanding the issue correctly, does it work then if you use `nbgrader extension install --nbextensions=/class/cs101/etc/venv/cs101-fa16/share/jupyter/nbextensions --symlink --debug` instead?

**Comment by davis68** [comment]
It should—there's certainly not a perms problem, and that's where Jupyter
is *trying* to find it.  (I'm not going to try since the system goes live
first thing tomorrow morning.)

I don't recall if there was a specific reason for using a .../etc/...
folder instead of share.

**Comment by jhamrick** [comment]
Ah, ok, no worries about not wanting to test it then 😄 

I am satisfied that this isn't a deeper problem, so am going to mark this as resolved. Thanks for the report!
