### ISSUE TITLE
extension Assignment_list does not install using windows 10

### ISSUE THREAD

**Issue by MrMikeWolf** [jupyter/nbgrader#537]
After installing upgrade of nbgrader using pip, installing and activating the extensions the assignment_list extension did not install

`Enabling notebook extension create_assignment/main...`
`      - Validating: OK`
`Done. You may need to restart the Jupyter notebook server for changes to take effect.

**Comment by jhamrick** [comment]
That's correct -- the assignment list extension isn't supported on Windows, unfortunately. Documenting this is on my todo list (see #525 )
