### ISSUE TITLE
Cannot get nbgrader extenstion to show in jupyterhub

### ISSUE THREAD

**Issue by whositwhatnow** [jupyter/nbgrader#541]
i've gone through the instal procedures pip install, nbgraderinstall --system, then activate.

It shows plugin ok, but i cannot see it in my web interface.  Im stumped, having a heck of a time with extensions.

**Comment by jhamrick** [comment]
Which user are you running `nbgrader extension install` and `nbgrader extension activate` for? If you're using JupyterHub, you need to run those commands for *each* user of JupyterHub if you haven't, and then restart those users' servers. Can you please paste the output of running those commands? If you just run the notebook independent of JupyterHub, does the plugin appear or not? (I'm trying to determine whether this is an issue with JupyterHub configuration, or the plugin installation)

**Comment by whositwhatnow** [comment]
How would this work if I have over 40 users?  Is there no systemwide install/activation.  Sorry for my silly questions, im just starting to learn all this

**Comment by jhamrick** [comment]
You can do a systemwide install, but not a systemwide activate.

One option is to create a [skeleton directory](http://linuxg.net/the-unix-and-linux-skeleton-directory-etcskel/) where the extension is activated, before creating your users. If you've already created your users, I'd recommend writing a script to install and activate the plugin for each user, something like:

```bash
nbgrader extension install
for user in $USERS; do
    cd $HOME/$user
    sudo -U $user nbgrader extension activate
done
```

**Comment by whositwhatnow** [comment]
Thank you Jessica, appreciate the help!!

**Comment by whositwhatnow** [comment]
Jessica,

I got the extension loaded but when I log in I noticed these errors in the log.  The extension seems to be working but im not 100% sure.

[I 2016-09-08 09:26:00.918 JupyterHub log:100] 200 GET /hub/api/authorizations/cookie/jupyter-hub-token-novograd/[secret] (user@127.0.0.1) 9.48ms
[W 2016-09-08 09:26:01.781 novograd log:47] 404 GET /user/user/nbextensions/nbextensions_configurator/tree_tab/main.js?v=20160908083933 (127.0.0.1) 1.51ms referer=https://jupyterhub.com:8000/user/user/tree
[E 2016-09-08 09:26:02.589 user web:1548] Uncaught exception GET /user/user/assignments?_=1473341144546 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='jupyterhub.com:8000', method='GET', uri='/user/user/assignments?_=1473341144546', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Referer': 'https://jupyterhub.com:8000/user/user/tree', 'X-Requested-With': 'XMLHttpRequest', 'Host': 'jupyterhub.com:8000', 'Cookie': 'jupyter-hub-token-user="2|1:0|10:1473341160|26:jupyter-hub-token-user|44:MDVkNzViNjAxMzQ3NDFmNmJhZjFhMWI3NTdmNGNiYmU=|1e0e4bb96903d7eff46190e398811cf84591911e2632af52f4bdf317f769dbd3"; _ga=GA1.2.240688201.1473109162', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36', 'Accept-Encoding': 'gzip, deflate, sdch, br', 'Connection': 'close', 'Accept-Language': 'en-US,en;q=0.8'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.5/site-packages/tornado/web.py", line 2829, in wrapper
        return method(self, *args, **kwargs)
      File "/usr/local/lib/python3.5/site-packages/nbgrader/nbextensions/assignment_list/handlers.py", line 99, in get
        self.finish(json.dumps(self.manager.list_assignments()))
      File "/usr/local/lib/python3.5/site-packages/nbgrader/nbextensions/assignment_list/handlers.py", line 48, in list_assignments
        assignments.extend(self.list_released_assignments())
      File "/usr/local/lib/python3.5/site-packages/nbgrader/nbextensions/assignment_list/handlers.py", line 28, in list_released_assignments
        raise RuntimeError('nbgrader list exited with code {}'.format(retcode))
    RuntimeError: nbgrader list exited with code 1
[E 2016-09-08 09:26:02.591 user log:46] {
      "Referer": "https://jupyterhub.com:8000/user/user/tree",
      "X-Requested-With": "XMLHttpRequest",
      "Host": "jupyterhub.com:8000",
      "Cookie": "jupyter-hub-token-user=\"2|1:0|10:1473341160|26:jupyter-hub-token-user|44:MDVkNzViNjAxMzQ3NDFmNmJhZjFhMWI3NTdmNGNiYmU=|1e0e4bb96903d7eff46190e398811cf84591911e2632af52f4bdf317f769dbd3\"; _ga=GA1.2.240688201.1473109162",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36",
      "Accept-Encoding": "gzip, deflate, sdch, br",
      "Connection": "close",
      "Accept-Language": "en-US,en;q=0.8"
    }

**Comment by jhamrick** [comment]
What happens if you run `nbgrader list` from the same directory that the notebook server is running in?

**Comment by whositwhatnow** [comment]
bah [ListApp | ERROR] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange

**Comment by jhamrick** [comment]
The exchange directory must be readable and writable by all users -- there is an example of how to do this here: http://nbgrader.readthedocs.io/en/latest/user_guide/managing_assignment_files.html#releasing-assignments

**Comment by dsblank** [comment]
Your script:

```
nbgrader extension install
for user in $USERS; do
    cd $HOME/$user
    sudo -U $user nbgrader extension activate
done
```
should be in the docs, or instructions on what each student needs to do. I've been wrestling with trouble-shooting for the last week. My check list:

1. Is the "Assignments" tab showing up? No, then they need to "nbgrader extension activate". Student may need to shutdown server and restart.
2. Are the Assignments list showing up? No, then they might need to edit nbgrader_config.py. I have seen that file: with the wrong name, typos (case, missing quotes).
3. Still don't see Assignments list? Have they been added to the gradebook?

**Comment by jhamrick** [comment]
> Your script... should be in the docs

Good call, I will document this.

**Comment by randy3k** [comment]
If you are using `LocalGitHubOAuthenticator` and have `create_system_users` set to `true`, the following `CustomAuthenticator` will activate `nbgrader` automatically when a user is created.


*jupyterhub_config.py*
```python
c.LocalGitHubOAuthenticator.create_system_users = True

import oauthenticator
from subprocess import check_call
class CustomAuthenticator(oauthenticator.LocalGitHubOAuthenticator):
    def add_user(self, user):
        oauthenticator.LocalGitHubOAuthenticator.add_user(self, user)
        user_name = user.name
        try:
            check_call("su - %s bash -l -c 'nbgrader extension activate'" % user_name, shell=True)
        except:
            pass

c.JupyterHub.authenticator_class = CustomAuthenticator
```

**Comment by dsblank** [comment]
@randy3k Oh, thank you for this! I wish there was better methods to enable nbgrader Assignment List on jupyterhub. I had a rough beginning this semester because of all of the issues I had in getting the students going quickly. 

This does suggest a "system" approach to handling enrollments. I could see that the students course_id could come from a centralized location. But course_id should really be a list, so that students don't have to keep editing that file to see assignments from another course. However, when enrollments change, this won't be reflected in their nbgrader_config.py. Seems like there should be a systems approach to manage which student is in which courses.
