### ISSUE TITLE
Be more flexible in finding solution delimeters

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#551]
See the discussion in #542

This would essentially revert #523, which is unfortunate in that it will result in yet another API change, but I think it will ultimately make things simpler as @dsblank suggests.

**Comment by jhamrick** [comment]
Probably whatever PR implements this should also tackle #422 too.

**Comment by dsblank** [comment]
You could probably still allow the old delimiters to work too, and slowly deprecate them.

**Comment by jhamrick** [comment]
Yes, though the way the current delimeters work hasn't been in an official release yet, so I'm more ok with breaking those.
