### ISSUE TITLE
Assignments need a Preview to see student view

### ISSUE THREAD

**Issue by dsblank** [jupyter/nbgrader#552]
Currently (as far as I understand), seeing what the student will see requires:
1. editing nbgrader_config.py, c.NbGrader.db_assignments
2. assigned
3. released
4. possibly switching course_id by editing nbgrader_config.py
5. fetched
6. open up copied notebook
7. save and close

If a mistake is found, then you have to repeat the steps (using --force) to re-release them. There are lots of mistakes I often make:
- wrong cell type (markdown vs code) for autograded cell
- wrong number of points
- mistyped delimiter
- unused/duplicated name of autograded cell
- missing section (Reflections, for example)
- general typo
- due date

It would be easier if there were a "Preview" button that went directly to step 6.

**Comment by jhamrick** [comment]
To see what the student will see in terms of the entire workflow, then yes, you'd need to do all that -- but what it sounds like your asking for is just to see the version of the notebook that students see. If that's what you want, you can remove steps 3-7 -- the student version *is* the release version, so if you open up the notebooks in the release folder, you'll see the version that students see.

**Comment by jhamrick** [comment]
I think this is actually implemented now in the formgrader interface, as there is a "preview" button you can click (though you still have to go through the "assign" step).
