### ISSUE TITLE
Fetching assignments should use ~/course_id/assignment

### ISSUE THREAD

**Issue by dsblank** [jupyter/nbgrader#554]
Currently, if a student is in two (or more) courses, they can switch back and forth between by editing their nbgrader_config.py file. However, if two courses both have "Assignment1" then that causes problems when fetching because they both try to copy the files into ~/Assignment1.

A better solution would be for fetched assignments to go to ~/course_id/Assignment1

**Comment by jhamrick** [comment]
Yes, this would probably make more sense. Maybe to preserve backwards compatibility we can have a "single course only" option that will keep the current behavior too.
