### ISSUE TITLE
Extracting grades

### ISSUE THREAD

**Issue by bretmarshall16** [jupyter/nbgrader#557]
How does one easily extract grades of students for a particular assignment in mass rather than having to go on to formgrader and manually look at each student and each grade?

**Comment by jhamrick** [comment]
You can use the nbgrader API to do this, see: http://nbgrader.readthedocs.io/en/latest/user_guide/advanced.html#getting-information-from-db

If you are using the development version of nbgrader, it also now includes a `nbgrader export` command that will export all the grades in the database to CSV.

**Comment by jhamrick** [comment]
I am going to close this for now, but let me know if you have any additional questions regarding this!
