### ISSUE TITLE
Hide Released Assignments from Students

### ISSUE THREAD

**Issue by fcurrin** [jupyter/nbgrader#558]
When we create directories for multiple classes inside of a singular nbgrader account, students enrolled in any one class automatically see all of the assignments released for every class tied to the account.  Is there a way to hide assignments for classes that a student is not enrolled in without creating a separate account for each class, potentially by doing something with the gradebook database?

Additionally, is there a way to hide assignments from students that were released for a previous year but won't be assigned again for a while -- essentially un-releasing them?

**Comment by kthyng** [comment]
I have this problem too. I have two classes, each with their own directory and associated `nbgrader_config.py` file, but everyone can see all homework assignments. I made it less confusing by giving the assignments all really specific names including the course number, but I'd prefer if a student could only see the assignments given permissions by being in the `nbgrader_config` file.

**Comment by jhamrick** [comment]
Yes, this is a known problem, see #544 . Hopefully I will have time to try to address it soon!
