### ISSUE TITLE
docker jupyterhub/jupyterhub-onbuild deploy

### ISSUE THREAD

**Issue by jujes** [jupyter/nbgrader#572]
Hi, someone know/have a **Dockerfile** (jupyterhub/jupyterhub-onbuild) for running **nbgrader**

I'm successful deploying whit:
jupyterhub-deploy-docker

thanks in advance,

**Comment by jhamrick** [comment]
There's not anything officially supported as a nbgrader Dockerfile, but there are a few Dockerfiles out there that I've created that you might find useful:

* The nbgrader binder demo: https://github.com/jhamrick/nbgrader-demo
* The compmodels systemuser docker image, which installs nbgrader: https://github.com/compmodels/systemuser
* The compmodels formgrader docker image, which runs `nbgrader formgrade`: https://github.com/compmodels/formgrader

**Comment by jujes** [comment]
Hi @jhamrick I know, actually all what I can find abut docker nbgrader come from this repo:
https://github.com/compmodels/formgrader

but here use jupyter/scipy-notebook and jupyterhub-deploy-docker use jupyterhub/jupyterhub-onbuild

**Comment by jhamrick** [comment]
I don't know of any Dockerfiles based off of `jupyterhub-onbuild` that install nbgrader, but I don't think that's where you want to install nbgrader anyway -- JupyterHub doesn't need access to nbgrader, it's the singleuser servers that do. It looks like you should be able to specify the singleuser image here: https://github.com/jupyterhub/jupyterhub-deploy-docker#prepare-the-jupyter-notebook-image

(Also, it does look like `jupyterhub-deploy-docker` uses `jupyter/scipy-notebook`, at least for the singleuser servers -- it is only using `jupyterhub-onbuild` for the JupyterHub container, not for the singleuser server containers)

**Comment by jhamrick** [comment]
I am going to close this since the issue seems to be inactive, but feel free to reopen or ask any addition questions!
