### ISSUE TITLE
formgrader should show student name

### ISSUE THREAD

**Issue by randy3k** [jupyter/nbgrader#575]
Right now, formgrader only shows a submission number, it is almost useless.

![screen shot 2016-11-17 at 1 01 42 pm](https://cloud.githubusercontent.com/assets/1690993/20401258/016f3676-acc6-11e6-9882-d9a99740de3f.png)

![screen shot 2016-11-17 at 1 09 56 pm](https://cloud.githubusercontent.com/assets/1690993/20401516/2a4e5698-acc7-11e6-8acc-65c75fb5be63.png)

It would be more informative to show the name of the student. It is even more useful to link the student name to the student view of the assignments.

**Comment by jhamrick** [comment]
This is a purposeful feature to avoid bias while grading. It would certainly also be possible to add a feature disabling this functionality, but I definitely don't want to get rid of it entirely.

Another possibility would be to list students in order here (and link to the student view), but to also have a button that says for example "start grading", which would then randomly order and anonymize submissions during the grading process itself to still avoid bias.

**Comment by randy3k** [comment]
I agree that randomization is a nice feature to avoid bias. However, when I am grading, I may need to contact specific students to address their issues, for example, a student may completely misunderstand a question, or to identify potential plagiarism activities.

It will be nice at least there is a button to reveal the actual student name.

**Comment by jhamrick** [comment]
> Perhaps, the name is hidden in default, it is only revealed if a button is clicked?

I like that idea a lot! Definitely seems like a reasonable thing to have.

Would it be fine to include this in the actual grading view (the view of the notebook), or do you want it in the list of submissions as well?

**Comment by jhamrick** [comment]
FYI, for now as a hacky workaround, if you hover over the link for the notebook name in the notebook/grading view, the URL will include the student's username.

**Comment by randy3k** [comment]
The hack definitely serves my purpose, thanks.
