### ISSUE TITLE
Travis and local tests fail with notebook v4.3

### ISSUE THREAD

**Issue by lgpage** [jupyter/nbgrader#582]
### Formgrader:
> tests/formgrader/test_gradebook_navigation.py::TestGradebook::test_load_live_notebook[DefaultManager] FAILED

Gets stuck at a login page:
![selenium screenshot](https://cloud.githubusercontent.com/assets/1577821/21182085/e6816240-c209-11e6-8128-ff6d78836fbc.png)

### Nbextensions:
> tests/nbextensions/test_assignment_list.py::test_show_assignments_list FAILED
Also gets stuck at a login page

Need to update to handle token authenticaiton:
xref: https://github.com/jupyter/notebook/pull/1831

**Comment by lgpage** [comment]
Ignoring token auth for the nbextension tests is easy, but I have no idea what needs updating for the formgrader

**Comment by jhamrick** [comment]
Hmm, ok, I will investigate further to figure out what needs updating for formgrader. Thanks!

**Comment by lgpage** [comment]
For the nbextension tests adding `"--NotebookApp.token="` option to [`sys.executable`](https://github.com/jupyter/nbgrader/blob/master/nbgrader/tests/nbextensions/conftest.py#L150) work.
