### ISSUE TITLE
Install extensions on conda install

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#595]
From @lgpage in #589 : I have post-link and pre-unlink scripts for the conda recipe if you want them.

**Comment by lgpage** [comment]
@jhamrick out of interest what do you think about getting `nbgrader` onto [conda-forge](https://conda-forge.github.io) and using there build bots?

**Comment by jhamrick** [comment]
Yes, I'd be on board with that. How often does conda-forge build? Does it just build releases or does it also do continuous builds?

**Comment by lgpage** [comment]
Just releases. Saves you the trouble of building releases for multiple python versions for multiple platforms. With their build tools its as simple as bump the version in a PR to the feedstock and the CI does the rest.

I will start a recipe on conda-forge later this evening and cc you on it.

**Comment by jhamrick** [comment]
Awesome, thanks!

Just as a heads up -- I know the recipe is currently set up to run *all* the tests. I did this originally to make sure that the conda recipe for nbgrader is correct, and it would be nice to keep it, but it's not essential. But I don't know if maybe conda forge builds have a timeout or something -- if they do, we're probably reaching it already 😜

**Comment by lgpage** [comment]
It should be possible to run the full test suite. I know the conda forge guys were able to get the time limit bumped to 90min on appveyor I think, not sure about travis and circleci. Easiest way to know is try add the recipe and see what happens :P 

The only issue I foresee is probably not being able to build the docs as `pyenchent` and `sphinxcontrib-spelling` are not available on conda.

`nodejs` is available on conda, so `phantomjs-prebuilt` can easily be install with `npm`

**Comment by jhamrick** [comment]
> Easiest way to know is try add the recipe and see what happens :P

Ok, sounds good :)

> The only issue I foresee is probably not being able to build the docs as pyenchent and sphinxcontrib-spelling are not available on conda.

Ok, that's fine since docs aren't essential for running nbgrader itself.
