### ISSUE TITLE
Fix running of invoke on windows

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#599]
cf https://github.com/conda-forge/staged-recipes/pull/2125

We can try this fix of adding an invoke configuration file: https://github.com/pyinvoke/invoke/issues/345#issuecomment-225557831

This should probably be fixed in a patch release, i.e. 0.3.2

**Comment by lgpage** [comment]
I will try verify this first with a rudimentary `echo` config stuff to file hack in staged recipes.

**Comment by lgpage** [comment]
@jhamrick I tested the patch in PR #601 on a local branch for the staged recipe [here](https://github.com/lgpage/staged-recipes/blob/nbgrader-patch/recipes/nbgrader/tasks.patch).

The only problem now is Python 2.7 (x86) on windows regularly times out in the `AssignApp`. Appveyor logs [here](https://ci.appveyor.com/project/lgpage/staged-recipes/build/1.0.2). Any ideas on fixing this?

Also if you would prefer to target this change to the `0.4.0` milestone instead of a patch release we can simply leave the patch in the staged recipe until then.

**Comment by jhamrick** [comment]
Hmm, I am not totally sure, but it's possible it is just a fluke -- sometimes the tests randomly time out :-/ When you say they regularly time out, does that mean you've tried restarting them and they still fail?

If so, then I don't really know without being able to look at it more closely. The error `RuntimeError: Timeout waiting for IOPub output` usually means that it has successfully execute the cell and is waiting for the cell outputs (see https://github.com/jupyter/nbconvert/blob/master/nbconvert/preprocessors/execute.py#L282 ). I don't know why that would be an issue for this particular test, though, especially when the previous ones seem to have run successfully. And it's particularly puzzling because that's not the sort of thing I would expect to differ between python versions 😕 

> Also if you would prefer to target this change to the 0.4.0 milestone instead of a patch release we can simply leave the patch in the staged recipe until then.

Sure, that sounds fine to me.

**Comment by lgpage** [comment]
Regularly might be overstating it. There were 2 jobs where both failed only for Python2.7 (x86) within 5min into the tests.

Ill re-run the jobs a few times and see if "regularly" is indeed the case.

**Comment by lgpage** [comment]
This is somewhat of a certainty. I re-ran the AppVeyor job another 5 times and for all runs Python2.7 (x86) failed, yet Python2.7 (x64) passed :confused:

**Comment by lgpage** [comment]
I am reasonably sure the Python 2.7 test failures on AppVeyor (x86) are related to @minrk's comment in https://github.com/jupyter/nbconvert/pull/235:
> CI VMs, which can have super weird, crazy-slow network behaviour

But this is hard to verify as the 4s timeout for collecting iopub messages is hard-coded and we can't use a `nbconvert` version pre `v4.2`.

**Comment by jhamrick** [comment]
I am home now and will look into why this is happening today.

**Comment by jhamrick** [comment]
Hmm, so I am able to run the tests successfully locally, but am seeing similar errors on the Jenkins build server as well (not on the same test, though): https://jenkins.jupyter.org/job/nbgrader/_mark=python,_pyversion=3.5,label=windows/83/console

When you re-ran the tests, did they always break on the same test? Or was it random?

**Comment by lgpage** [comment]
@jhamrick the test was random, but it was always a test that used the `execute` preprocessor.

**Comment by jhamrick** [comment]
Ok, then I'm fairly confident #608 will address the problem -- it won't technically address the underlying issue, but it seems that the issue is due to the "super weird, crazy-slow network behaviour" you referenced earlier. I think the best we can do for now is just try to rerun the test if it fails.
