### ISSUE TITLE
Simplify formgrade

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/nbgrader#604]
After looking through formgrade with the goal of updating it to be a JupyterHub 0.7.0 service. I have been trying to think through ways of simplifying formgrade. Some thoughts:

* Remove the ability of formgrade users to access live single user notebook servers. @minrk is working on an example of running a single user notebook server as a JupyterHub service with group level access (https://github.com/jupyterhub/jupyterhub/issues/921).
* This change would make it *much* easier to migrate formgrade to being a pretty stock JupyterHub service.
* I am also starting to explore replacing formgrade entirely by a live notebook server/jupyterlab with additional nbextensions/labextensions. Some initial ideas below...

The core client UI of formgrade could be replace in many situation by a live notebook with the following:

* An nbextension that allow human grading and commenting and stores the results in nbgrader metadata.
* A new nbgrader command line phase that takes that metadata and stores it in the db. We already have nbconvert preprocessors that essentially do this, so this would be super simple.
* Some sort of additional frontend UI that makes it easy to navigate through notebooks for grading.

In JupyterLab, offering additional UIs is relatively easy. I don't have a ton of time right now to work on this stuff, but I may pick away at it.

**Comment by jhamrick** [comment]
If possible, I'd really prefer to not remove the functionality of having access to a live notebook server as I know that people find that feature useful. I am not sure why that would prevent it from working as a service, though, as it assumes the server is already running under a different user and just requests access to it. I haven't looked deeply yet into how to migrate it to the services framework.

Let's keep discussion of doing grading in the live notebook in #67 to keep that stuff all in one place.

**Comment by jhamrick** [comment]
Actually this really seems to cover both stuff in #67 and #568 so I am going to close this issue and we can discuss the relevant things in those other issues!
