### ISSUE TITLE
create-assignment nbextension doesn't work with notebook master

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/nbgrader#609]
I have confirmed that the create-assignment nbextension works on notebook 4.3.1 but not on notebook master. Pinging @minrk and @gnestor as they may have an idea of what the issue it. I will dive into it now and try to debug it.

**Comment by jhamrick** [comment]
Adding this to 0.5.0 for now, but happy to move it to 0.4.0 depending on when the notebook is next released and whether the fix is backwards compatible or not.

**Comment by ellisonbg** [comment]
I think it is a bug with notebook master related to webpack: see https://github.com/jupyter/notebook/issues/2024 and https://github.com/jupyter/notebook/pull/2011

**Comment by gnestor** [comment]
I was about to chime that my next project is to switch the notebook from webpack back to pure require.js, but it looks like Min beat me to it! As soon as https://github.com/jupyter/notebook/pull/2011 is merged, it should fix this issue, many other broken extensions, and allow us to ship notebook 5.0.

**Comment by jhamrick** [comment]
I am going to close this since it is not an issue with nbgrader itself. Feel free to reopen though (or open a new issue) if there are further issues on notebook master.
