### ISSUE TITLE
v1.json missing from package data and install

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/nbgrader#626]
I found that when I installed nbgrader from github using pip, the `nbgrader/nbformat/v1.json` file was missing from the install. It needs to be listed in the package_data for `setup.py` and if we want to cut an sdist in a MANIFEST.in. We should double check to make sure there are not other things missing...

**Comment by jhamrick** [comment]
Oops, forgot to include that. Fixing that right now. (Note there is no MANIFEST.in to begin with, so I just need to add it to setup.py).
