### ISSUE TITLE
Fix nbgrader db tests on windows

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#631]
Apparently they are broken, sigh:

https://jenkins.jupyter.org/job/nbgrader/_mark=python,_pyversion=3.5,label=windows/96/console

**Comment by lgpage** [comment]
:cry: 
Although it seems unrelated to the timeout error?

**Comment by jhamrick** [comment]
Yeah, I think the failures are due to #625.

I should really figure out how to set up continuous integration with windows tests...

**Comment by lgpage** [comment]
Once I have the conda force recipe working I will take a look at adding CI with AppVeyor for here. It should be more or less a copy and paste exercise then.

**Comment by jhamrick** [comment]
That would be super awesome, thank you!

The current setup is that there is a Jupyter server running Jenkins, which runs windows tests I think every hour assuming there are new commits. So, better than nothing, but it does mean that errors aren't necessarily caught right away.
