### ISSUE TITLE
Remove conda recipe and document conda forge management

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#634]
@lgpage since you set this up, can I assign this issue to you?

I assume that now that we have a conda forge package, we can remove the conda recipe stuff from this repo and just point people to the conda forge recipe. This should also involve updating the existing documentation about how to build a conda package to explain how to update the conda forge package (i.e. is it just submitting another PR to the conda forge repo?) when a new version of nbgrader is released.

- [x] remove conda forge recipe
- [x] update docs with installation instructions from conda forge rather than from the jhamrick channel
- [x] update release docs with instructions on how to update the conda forge package

**Comment by lgpage** [comment]
@jhamrick sounds good. Just with
> update release docs with instructions on how to update the conda forge package

I think it would be better just to point people to the feedstock as it is explained there: https://github.com/conda-forge/nbgrader-feedstock#updating-nbgrader-feedstock

**Comment by jhamrick** [comment]
Sure, I am fine with just having a link to that rather than writing them explicitly in the nbgrader docs -- I am more concerned with it being discoverable rather than where it is in particular 😄
