### ISSUE TITLE
Unable to fetch assignments

### ISSUE THREAD

**Issue by hetland** [jupyter/nbgrader#636]
I am setting up nbgrader for a class this semester. I am able to release an assignment, and see it both for me (the instructor) and for a test student. However, I am not able to fetch the assignment in the assignments tab of the notebook. I could use the command line 'nbgrader fetch' to get the assignment.  The javascript console suggests there is an error, but I am unable to trace it beyond that:

    jquery.min.js:6 POST https://copano.tamu.edu:8000/user/test_pgs_spring2017/assignments/fetch 500 (Internal Server Error)

I'm not sure how to proceed.

**Comment by jhamrick** [comment]
1. What version of nbgrader do you have installed?
2. Can you try running the notebook manually from the user's directory (rather than through JupyterHub), fetch the assignment, and then check the logs of the notebook server to see what the error is?

**Comment by hetland** [comment]
1. nbgrader version 0.3.2

2. When I run it as a standalone jupyter notebook, fetch appears to work
(so no errors to report). Just not in jupyterhub.



On Fri, Jan 13, 2017 at 1:35 PM, Jessica B. Hamrick <
notifications@github.com> wrote:

>
>    1. What version of nbgrader do you have installed?
>    2. Can you try running the notebook manually from the user's directory
>    (rather than through JupyterHub), fetch the assignment, and then check the
>    logs of the notebook server to see what the error is?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jupyter_nbgrader_issues_636-23issuecomment-2D272527397&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=FPERNJ38ToEXgd8OyE4aew&m=eMISakvvJRLmJeGMrQsMNiM2IROirRqK2t62D4Dj7wY&s=Y0fUL9EINJsTMTPfzs9um2usTvQDoKQR94AGcja-9IM&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACesFup5ZOCy3qas2mRXW0TF3lQkY5OZks5rR9IKgaJpZM4LjN7I&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=FPERNJ38ToEXgd8OyE4aew&m=eMISakvvJRLmJeGMrQsMNiM2IROirRqK2t62D4Dj7wY&s=zq7usqbi9PfHEYcD3nQIpW0l_h3HiXyel545wC2lc-k&e=>
> .
>



-- 
Prof. Rob Hetland
Texas A&M Univ.  –  Dept. of Oceanography
http://pong.tamu.edu/~rob

**Comment by jhamrick** [comment]
Can you post your `jupyterhub_config.py`?

**Comment by hetland** [comment]
# Configuration file for jupyterhub.

#------------------------------------------------------------------------------
# Configurable configuration
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# LoggingConfigurable configuration
#------------------------------------------------------------------------------

# A parent class for Configurables that log.
#
# Subclasses have a log trait, and the default behavior is to get the logger
# from the currently running Application.

#------------------------------------------------------------------------------
# SingletonConfigurable configuration
#------------------------------------------------------------------------------

# A configurable that only allows one instance.
#
# This class is for classes that should only have one instance of itself or
# *any* subclass. To create and retrieve such a class use the
# :meth:`SingletonConfigurable.instance` method.

#------------------------------------------------------------------------------
# Application configuration
#------------------------------------------------------------------------------

# This is an application.

# The date format used by logging formatters for %(asctime)s
# c.Application.log_datefmt = '%Y-%m-%d %H:%M:%S'

# The Logging format template
# c.Application.log_format = '[%(name)s]%(highlevel)s %(message)s'

# Set the log level by value or name.
# c.Application.log_level = 30

#------------------------------------------------------------------------------
# JupyterHub configuration
#------------------------------------------------------------------------------

c.SudoSpawner.sudospawner_path = '/opt/anaconda3/bin/sudospawner'

# An Application for starting a Multi-User Jupyter Notebook server.

# Grant admin users permission to access single-user servers.
#
# Users should be properly informed if this is enabled.
# c.JupyterHub.admin_access = False

# DEPRECATED, use Authenticator.admin_users instead.
# c.JupyterHub.admin_users = set()

# Answer yes to any questions (e.g. confirm overwrite)
# c.JupyterHub.answer_yes = False

# Dict of token:username to be loaded into the database.
#
# Allows ahead-of-time generation of API tokens for use by services.
# c.JupyterHub.api_tokens = {}

# Class for authenticating users.
#
# This should be a class with the following form:
#
# - constructor takes one kwarg: `config`, the IPython config object.
#
# - is a tornado.gen.coroutine
# - returns username on success, None on failure
# - takes two arguments: (handler, data),
#   where `handler` is the calling web.RequestHandler,
#   and `data` is the POST form data from the login page.
# c.JupyterHub.authenticator_class = 'jupyterhub.auth.PAMAuthenticator'

# The base URL of the entire application
# c.JupyterHub.base_url = '/'

# Whether to shutdown the proxy when the Hub shuts down.
#
# Disable if you want to be able to teardown the Hub while leaving the proxy
# running.
#
# Only valid if the proxy was starting by the Hub process.
#
# If both this and cleanup_servers are False, sending SIGINT to the Hub will
# only shutdown the Hub, leaving everything else running.
#
# The Hub should be able to resume from database state.
# c.JupyterHub.cleanup_proxy = True

# Whether to shutdown single-user servers when the Hub shuts down.
#
# Disable if you want to be able to teardown the Hub while leaving the
single-
# user servers running.
#
# If both this and cleanup_proxy are False, sending SIGINT to the Hub will
only
# shutdown the Hub, leaving everything else running.
#
# The Hub should be able to resume from database state.
# c.JupyterHub.cleanup_servers = True

# The config file to load
# c.JupyterHub.config_file = 'jupyterhub_config.py'

# Confirm that JupyterHub should be run without SSL. This is **NOT
RECOMMENDED**
# unless SSL termination is being handled by another layer.
# c.JupyterHub.confirm_no_ssl = False

# Number of days for a login cookie to be valid. Default is two weeks.
# c.JupyterHub.cookie_max_age_days = 14

# The cookie secret to use to encrypt cookies.
#
# Loaded from the JPY_COOKIE_SECRET env variable by default.
# c.JupyterHub.cookie_secret = b''

# File in which to store the cookie secret.
c.JupyterHub.cookie_secret_file = '/srv/jupyterhub/cookie_secret'

# The location of jupyterhub data files (e.g. /usr/local/share/jupyter/hub)
# c.JupyterHub.data_files_path = '/opt/anaconda3/share/jupyter/hub'

# Include any kwargs to pass to the database connection. See
# sqlalchemy.create_engine for details.
# c.JupyterHub.db_kwargs = {}

# url for the database. e.g. `sqlite:///jupyterhub.sqlite`
# c.JupyterHub.db_url = 'sqlite:///jupyterhub.sqlite'

# log all database transactions. This has A LOT of output
# c.JupyterHub.debug_db = False

# show debug output in configurable-http-proxy
# c.JupyterHub.debug_proxy = False

# Send JupyterHub's logs to this file.
#
# This will *only* include the logs of the Hub itself, not the logs of the
proxy
# or any single-user servers.
c.JupyterHub.extra_log_file = '/var/log/jupyterhub'

# Extra log handlers to set on JupyterHub logger
# c.JupyterHub.extra_log_handlers = []

# Generate default config file
# c.JupyterHub.generate_config = False

# The ip for this process
#c.JupyterHub.hub_ip = '10.0.0.1'

# The port for this process
#c.JupyterHub.hub_port = 443

# The prefix for the hub server. Must not be '/'
# c.JupyterHub.hub_prefix = '/hub/'

# The public facing ip of the whole application (the proxy)
# c.JupyterHub.ip = ''

# Supply extra arguments that will be passed to Jinja environment.
# c.JupyterHub.jinja_environment_options = {}

# Interval (in seconds) at which to update last-activity timestamps.
# c.JupyterHub.last_activity_interval = 300

# Specify path to a logo image to override the Jupyter logo in the banner.
# c.JupyterHub.logo_file = ''

# File to write PID Useful for daemonizing jupyterhub.
# c.JupyterHub.pid_file = ''

# The public facing port of the proxy
# c.JupyterHub.port = 8000

# The ip for the proxy API handlers
# c.JupyterHub.proxy_api_ip = '127.0.0.1'

# The port for the proxy API handlers
# c.JupyterHub.proxy_api_port = 0

# The Proxy Auth token.
#
# Loaded from the CONFIGPROXY_AUTH_TOKEN env variable by default.
# Created via openssl rand -hex 32
c.JupyterHub.proxy_auth_token =
'afd911ac81b51a45f8ae81cce6c274fb3185e4d0f00b5c777fd36bcfd971decc'

# Interval (in seconds) at which to check if the proxy is running.
# c.JupyterHub.proxy_check_interval = 30

# The command to start the http proxy.
#
# Only override if configurable-http-proxy is not on your PATH
# c.JupyterHub.proxy_cmd = ['configurable-http-proxy']

# Purge and reset the database.
# c.JupyterHub.reset_db = False

# The class to use for spawning single-user servers.
#
# Should be a subclass of Spawner.
# c.JupyterHub.spawner_class = 'jupyterhub.spawner.LocalProcessSpawner'

# Path to SSL certificate file for the public facing interface of the proxy
#
# Use with ssl_key
c.JupyterHub.ssl_cert = '/etc/pki/tls/certs/copano_tamu_edu_cert.cer'

# Path to SSL key file for the public facing interface of the proxy
#
# Use with ssl_cert
c.JupyterHub.ssl_key = '/etc/pki/tls/private/copano.tamu.edu.key'

# Host to send statds metrics to
# c.JupyterHub.statsd_host = ''

# Port on which to send statsd metrics about the hub
# c.JupyterHub.statsd_port = 8125

# Prefix to use for all metrics sent by jupyterhub to statsd
# c.JupyterHub.statsd_prefix = 'jupyterhub'

# Run single-user servers on subdomains of this host.
#
# This should be the full https://hub.domain.tld[:port]
#
# Provides additional cross-site protections for javascript served by
single-
# user servers.
#
# Requires <username>.hub.domain.tld to resolve to the same host as
# hub.domain.tld.
#
# In general, this is most easily achieved with wildcard DNS.
#
# When using SSL (i.e. always) this also requires a wildcard SSL
certificate.
# c.JupyterHub.subdomain_host = ''

# Paths to search for jinja templates.
# c.JupyterHub.template_paths = []

# Extra settings overrides to pass to the tornado application.
# c.JupyterHub.tornado_settings = {}

#------------------------------------------------------------------------------
# Spawner configuration
#------------------------------------------------------------------------------

# Base class for spawning single-user notebook servers.
#
# Subclass this, and override the following methods:
#
# - load_state - get_state - start - stop - poll

# Extra arguments to be passed to the single-user server
# c.Spawner.args = []

# The command used for starting notebooks.
# c.Spawner.cmd = ['jupyterhub-singleuser']

# Enable debug-logging of the single-user server
# c.Spawner.debug = False

# The default URL for the single-user server.
#
# Can be used in conjunction with --notebook-dir=/ to enable  full
filesystem
# traversal, while preserving user's homedir as landing page for notebook
#
# `%U` will be expanded to the user's username
# c.Spawner.default_url = ''

# Disable per-user configuration of single-user servers.
#
# This prevents any config in users' $HOME directories from having an
effect on
# their server.
c.Spawner.disable_user_config = False

# Whitelist of environment variables for the subprocess to inherit
# c.Spawner.env_keep = ['PATH', 'PYTHONPATH', 'CONDA_ROOT',
'CONDA_DEFAULT_ENV', 'VIRTUAL_ENV', 'LANG', 'LC_ALL']

# Environment variables to load for the Spawner.
#
# Value could be a string or a callable. If it is a callable, it will be
called
# with one parameter, which will be the instance of the spawner in use. It
# should quickly (without doing much blocking operations) return a string
that
# will be used as the value for the environment variable.
# c.Spawner.environment = {}

# Timeout (in seconds) before giving up on a spawned HTTP server
#
# Once a server has successfully been spawned, this is the amount of time we
# wait before assuming that the server is unable to accept connections.
# c.Spawner.http_timeout = 30

# The IP address (or hostname) the single-user server should listen on
# c.Spawner.ip = '127.0.0.1'

# The notebook directory for the single-user server
#
# `~` will be expanded to the user's home directory `%U` will be expanded
to the
# user's username
c.Spawner.notebook_dir = '~/notebooks'

# An HTML form for options a user can specify on launching their server. The
# surrounding `<form>` element and the submit button are already provided.
#
# For example:
#
#     Set your key:
#     <input name="key" val="default_key"></input>
#     <br>
#     Choose a letter:
#     <select name="letter" multiple="true">
#       <option value="A">The letter A</option>
#       <option value="B">The letter B</option>
#     </select>
# c.Spawner.options_form = ''

# Interval (in seconds) on which to poll the spawner.
# c.Spawner.poll_interval = 30

# Timeout (in seconds) before giving up on the spawner.
#
# This is the timeout for start to return, not the timeout for the server to
# respond. Callers of spawner.start will assume that startup has failed if
it
# takes longer than this. start should return when the server process is
started
# and its location is known.
# c.Spawner.start_timeout = 60

#------------------------------------------------------------------------------
# LocalProcessSpawner configuration
#------------------------------------------------------------------------------

# A Spawner that just uses Popen to start local processes as users.
#
# Requires users to exist on the local system.
#
# This is the default spawner for JupyterHub.

# Seconds to wait for process to halt after SIGINT before proceeding to
SIGTERM
# c.LocalProcessSpawner.INTERRUPT_TIMEOUT = 10

# Seconds to wait for process to halt after SIGKILL before giving up
# c.LocalProcessSpawner.KILL_TIMEOUT = 5

# Seconds to wait for process to halt after SIGTERM before proceeding to
SIGKILL
# c.LocalProcessSpawner.TERM_TIMEOUT = 5

#------------------------------------------------------------------------------
# Authenticator configuration
#------------------------------------------------------------------------------

# A class for authentication.
#
# The primary API is one method, `authenticate`, a tornado coroutine for
# authenticating users.

# set of usernames of admin users
#
# If unspecified, only the user that launches the server will be admin.
c.Authenticator.admin_users = {'baum','kthyng','rob'}

# Dictionary mapping authenticator usernames to JupyterHub users.
#
# Can be used to map OAuth service names to local users, for instance.
#
# Used in normalize_username.
# c.Authenticator.username_map = {}

# Regular expression pattern for validating usernames.
#
# If not defined: allow any username.
# c.Authenticator.username_pattern = ''

# Username whitelist.
#
# Use this to restrict which users can login. If empty, allow any user to
# attempt login.
# c.Authenticator.whitelist = {'baum','testy','rob','kthyng'}

#------------------------------------------------------------------------------
# LocalAuthenticator configuration
#------------------------------------------------------------------------------

# Base class for Authenticators that work with local Linux/UNIX users
#
# Checks for local users, and can attempt to create them if they exist.

# The command to use for creating users as a list of strings.
#
# For each element in the list, the string USERNAME will be replaced with
the
# user's username. The username will also be appended as the final argument.
#
# For Linux, the default value is:
#
#     ['adduser', '-q', '--gecos', '""', '--disabled-password']
#
# To specify a custom home directory, set this to:
#
#     ['adduser', '-q', '--gecos', '""', '--home', '/customhome/USERNAME',
'--
# disabled-password']
#
# This will run the command:
#
# adduser -q --gecos "" --home /customhome/river --disabled-password river
#
# when the user 'river' is created.
# c.LocalAuthenticator.add_user_cmd = []

# If a user is added that doesn't exist on the system, should I try to
create
# the system user?
# c.LocalAuthenticator.create_system_users = False

# Automatically whitelist anyone in this group.
c.LocalAuthenticator.group_whitelist =
{'baum','pythonfall2016','jupyter','pythonspring2017'}


#------------------------------------------------------------------------------
# PAMAuthenticator configuration
#------------------------------------------------------------------------------

# Authenticate local Linux/UNIX users with PAM

# The encoding to use for PAM
# c.PAMAuthenticator.encoding = 'utf8'

# Whether to open PAM sessions when spawners are started.
#
# This may trigger things like mounting shared filsystems, loading
credentials,
# etc. depending on system configuration, but it does not always work.
#
# It can be disabled with::
#
#     c.PAMAuthenticator.open_sessions = False
# c.PAMAuthenticator.open_sessions = True

# The PAM service to use for authentication.
# c.PAMAuthenticator.service = 'login'

On Fri, Jan 13, 2017 at 1:50 PM, Jessica B. Hamrick <
notifications@github.com> wrote:

> Can you post your jupyterhub_config.py?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jupyter_nbgrader_issues_636-23issuecomment-2D272531138&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=FPERNJ38ToEXgd8OyE4aew&m=bl00PNcJpPM1FY94BE48AtLHy7j8oDnK6UvgNVAPUFA&s=k_bbHLIzLl4mv21U0dLXBeFTy07JYzWRrIIb_bt8szQ&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACesFiMyiTd5GNCYyvlap5y81P5zBoTxks5rR9WdgaJpZM4LjN7I&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=FPERNJ38ToEXgd8OyE4aew&m=bl00PNcJpPM1FY94BE48AtLHy7j8oDnK6UvgNVAPUFA&s=lRFw0FFA_HfGCBqLDbBQG96qkc5LIbTYQTbwunSN4ks&e=>
> .
>



-- 
Prof. Rob Hetland
Texas A&M Univ.  –  Dept. of Oceanography
http://pong.tamu.edu/~rob

**Comment by jhamrick** [comment]
Hmm, that looks like it should be fine to me...

Just to double check, as I noticed you set a custom directory for the single user servers to start: when you ran `nbgrader fetch` from the command line, and when you ran the standalone notebook, you rand them from this `~/notebooks` directory?

Can you also post the user's `nbgrader_config.py`?

Finally, it looks like you're using `JupyterHub.extra_log_file`, which apparently will *only* log the JupyterHub output. Can you modify your setup to redirect all output to a logfile, e.g.:

https://groups.google.com/forum/#!topic/jupyter/xWZvSQQ3g6Q

or, alternately, just remove that option for now and run JupyterHub from the command line, Which will hopefully reveal what the error is?

**Comment by hetland** [comment]
The test student does not have an nbgrader_config.py file in their
directory.

And, yes, I ran fetch and jupyter notebook in the ~/notebooks directory.

I will remove the extra_log_file option, and post anything interesting in
the log.

On Fri, Jan 13, 2017 at 2:13 PM, Jessica B. Hamrick <
notifications@github.com> wrote:

> Hmm, that looks like it should be fine to me...
>
> Just to double check, as I noticed you set a custom directory for the
> single user servers to start: when you ran nbgrader fetch from the
> command line, and when you ran the standalone notebook, you rand them from
> this ~/notebooks directory?
>
> Can you also post the user's nbgrader_config.py?
>
> Finally, it looks like you're using JupyterHub.extra_log_file, which
> apparently will *only* log the JupyterHub output. Can you modify your
> setup to redirect all output to a logfile, e.g.:
>
> https://groups.google.com/forum/#!topic/jupyter/xWZvSQQ3g6Q
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__groups.google.com_forum_-23-21topic_jupyter_xWZvSQQ3g6Q&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=FPERNJ38ToEXgd8OyE4aew&m=uj5zaQ3tQfethBua3dOFL-J3O5pvUYJnpg-dISC_MFc&s=Htwa6zXFbMGFQwTEOU-fmSiExSG9ZA15JK_Pf57PeDA&e=>
>
> or, alternately, just remove that option for now and run JupyterHub from
> the command line, Which will hopefully reveal what the error is?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jupyter_nbgrader_issues_636-23issuecomment-2D272536492&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=FPERNJ38ToEXgd8OyE4aew&m=uj5zaQ3tQfethBua3dOFL-J3O5pvUYJnpg-dISC_MFc&s=VUa6BQrCxR9J7dSFM_ZqTmGRT3IHlEj1D5oJzfBxIHM&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACesFqVrLbL806nGjWBlmN2PB4W1-2Dtskks5rR9r4gaJpZM4LjN7I&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=FPERNJ38ToEXgd8OyE4aew&m=uj5zaQ3tQfethBua3dOFL-J3O5pvUYJnpg-dISC_MFc&s=WG1UlwYbXpzi0VBLm4mAj7_WGGrdTQxWdngH1ACOn7k&e=>
> .
>



-- 
Prof. Rob Hetland
Texas A&M Univ.  –  Dept. of Oceanography
http://pong.tamu.edu/~rob

**Comment by hetland** [comment]
There is more, but this seems to be the most relevant section of the logs:


HTTPServerRequest(protocol='http', host='copano.tamu.edu:8000',
method='POST', uri='/user/test_pgs_spring2017/assignments/fetch',
version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Cookie':
'jupyter-hub-token-test_pgs_spring2017="2|1:0|10:1484338421|37:jupyter-hub-token-test_pgs_spring2017|44:MTY0MDVkNWQ5MTZkNDRiODk1MjY1MDFmYTgyYmIxMTM=|696972bab74347c3f921da7d6985caa3eec1c1d9f6500a2021ef946ccd01e1dd"',
'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
'Connection': 'close', 'Host': 'copano.tamu.edu:8000', 'X-Requested-With':
'XMLHttpRequest', 'Accept-Encoding': 'gzip, deflate, br', 'Content-Length':
'43', 'Accept-Language': 'en-US,en;q=0.8', 'Origin': '
https://copano.tamu.edu:8000', 'Referer': '
https://copano.tamu.edu:8000/user/test_pgs_spring2017/tree', 'User-Agent':
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML,
like Gecko) Chrome/55.0.2883.95 Safari/537.36', 'Accept':
'application/json, text/javascript, */*; q=0.01'})
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.5/site-packages/tornado/web.py",
line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/anaconda3/lib/python3.5/site-packages/tornado/web.py",
line 2829, in wrapper
        return method(self, *args, **kwargs)
      File
"/opt/anaconda3/lib/python3.5/site-packages/nbgrader/nbextensions/assignment_list/handlers.py",
line 110, in post
        self.manager.fetch_assignment(course_id, assignment_id)
      File
"/opt/anaconda3/lib/python3.5/site-packages/nbgrader/nbextensions/assignment_list/handlers.py",
line 57, in fetch_assignment
        ], stdout=sp.PIPE, stderr=sp.STDOUT, cwd=self.assignment_dir)
      File "/opt/anaconda3/lib/python3.5/subprocess.py", line 947, in
__init__
        restore_signals, start_new_session)
      File "/opt/anaconda3/lib/python3.5/subprocess.py", line 1551, in
_execute_child
        raise child_exception_type(errno_num, err_msg)
    PermissionError: [Errno 13] Permission denied

On Fri, Jan 13, 2017 at 2:13 PM, Jessica B. Hamrick <
notifications@github.com> wrote:

> Hmm, that looks like it should be fine to me...
>
> Just to double check, as I noticed you set a custom directory for the
> single user servers to start: when you ran nbgrader fetch from the
> command line, and when you ran the standalone notebook, you rand them from
> this ~/notebooks directory?
>
> Can you also post the user's nbgrader_config.py?
>
> Finally, it looks like you're using JupyterHub.extra_log_file, which
> apparently will *only* log the JupyterHub output. Can you modify your
> setup to redirect all output to a logfile, e.g.:
>
> https://groups.google.com/forum/#!topic/jupyter/xWZvSQQ3g6Q
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__groups.google.com_forum_-23-21topic_jupyter_xWZvSQQ3g6Q&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=FPERNJ38ToEXgd8OyE4aew&m=uj5zaQ3tQfethBua3dOFL-J3O5pvUYJnpg-dISC_MFc&s=Htwa6zXFbMGFQwTEOU-fmSiExSG9ZA15JK_Pf57PeDA&e=>
>
> or, alternately, just remove that option for now and run JupyterHub from
> the command line, Which will hopefully reveal what the error is?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jupyter_nbgrader_issues_636-23issuecomment-2D272536492&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=FPERNJ38ToEXgd8OyE4aew&m=uj5zaQ3tQfethBua3dOFL-J3O5pvUYJnpg-dISC_MFc&s=VUa6BQrCxR9J7dSFM_ZqTmGRT3IHlEj1D5oJzfBxIHM&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACesFqVrLbL806nGjWBlmN2PB4W1-2Dtskks5rR9r4gaJpZM4LjN7I&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=FPERNJ38ToEXgd8OyE4aew&m=uj5zaQ3tQfethBua3dOFL-J3O5pvUYJnpg-dISC_MFc&s=WG1UlwYbXpzi0VBLm4mAj7_WGGrdTQxWdngH1ACOn7k&e=>
> .
>



-- 
Prof. Rob Hetland
Texas A&M Univ.  –  Dept. of Oceanography
http://pong.tamu.edu/~rob

**Comment by jhamrick** [comment]
Hmm, interesting. It seems to be failing on *executing* the subprocess, rather than the subprocess itself failing (i.e. it can't run the `subprocess.Popen` function...). But running the list command obviously works, or you couldn't get to the step of trying to fetch the assignment.

...I wonder if this is because this line isn't using `sys.executable`: https://github.com/jupyter/nbgrader/blob/0.3.x/nbgrader/nbextensions/assignment_list/handlers.py#L54
Maybe it's finding a version of nbgrader that it doesn't have permission to access. This was fixed on master in #600 but I didn't think to backport it for 3.2.

Can you try editing line 65 of the file `/opt/anaconda3/lib/python3.5/site-packages/nbgrader/nbextensions/assignment_list/handlers.py` to be:

```
            sys.executable, "-m", "nbgrader", "fetch",
```

And see if that fixes it?

**Comment by jhamrick** [comment]
(You might need to restart the singleuser server after doing that)

**Comment by hetland** [comment]
That fixed it!

Note, I had to edit a slightly different line.. Just for posterity, the
relevant code block is:

    def fetch_assignment(self, course_id, assignment_id):
         p = sp.Popen([
             sys.executable, "-m", "nbgrader", "fetch",      #### this line
was edited
             "--course", course_id,
             assignment_id
         ], stdout=sp.PIPE, stderr=sp.STDOUT, cwd=self.assignment_dir)

I would never have found that on my own. Thanks for fixing this problem so
quickly for me. This will be a big help when I want to have students
actually work on assignments. :)


On Fri, Jan 13, 2017 at 2:42 PM, Jessica B. Hamrick <
notifications@github.com> wrote:

> (You might need to restart the singleuser server after doing that)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jupyter_nbgrader_issues_636-23issuecomment-2D272542789&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=FPERNJ38ToEXgd8OyE4aew&m=ZZMGNUp0ddfh5-Ze5a16QNh-fbZ7RsE6mvWUKu5nNxY&s=hpVgkZXJQ842y9krwPysi8dGlIjnDatyNaCndYDgiRM&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACesFteCIJ-5FHuoMTImW556fQrnQgxUoBks5rR-2DGogaJpZM4LjN7I&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=FPERNJ38ToEXgd8OyE4aew&m=ZZMGNUp0ddfh5-Ze5a16QNh-fbZ7RsE6mvWUKu5nNxY&s=rib9cw7bvTRA-VrVQNlcyga5vtSvia47oGm53hEF3hY&e=>
> .
>



-- 
Prof. Rob Hetland
Texas A&M Univ.  –  Dept. of Oceanography
http://pong.tamu.edu/~rob

**Comment by jhamrick** [comment]
No problem, glad I was able to help 😄 

I am about to release 0.4.0 (probably this weekend), but I think I will backport #600 to a 0.3.3 release anyway since this seems like an important enough thing to fix for people who might want to remain on 0.3.x for the upcoming semester. And once I do that you won't have to worry about fixing this manually, you can just pip install.

**Comment by jhamrick** [comment]
Closed by #638
