### ISSUE TITLE
Developer install instructions use old method of installing extensions

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#653]
They should be updated to use `jupyter nbextension install`, etc. See the regular installation instructions for what should be put in the developer installation instructions.

**Comment by lgpage** [comment]
Maybe also update to use the ``--symlink`` flag instead of ``--sys-prefix`` for developer install

**Comment by lgpage** [comment]
I'll quickly update these docs

**Comment by jhamrick** [comment]
Yes, definitely to use `--symlink`. Thanks!
