### ISSUE TITLE
Complexity costs

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/nbgrader#66]
The nbgrader system is complex enough that when something goes wrong, the average instructor won't have any idea how to recover without writing lots of custom python code. I found myself doing this time and time again, and that isn't sustainable over the long run. I think we really need to figure out how to make it simpler and also more bullet proof.

**Comment by jhamrick** [comment]
I definitely agree. I think part of that is that we don't have a 100% clear picture of what all the necessary components are, but there is certainly a lot of complexity especially in understanding how the different apps work. Partially this is related to just the fact that the code is kind of complicated/messy (I already opened #57 to address this) but there is probably also conceptual complexity.

It would be good if we could try to document where we feel things are confusing or too complex in this issue -- I'll try to do that as I'm grading stuff this semester.

**Comment by ellisonbg** [comment]
Yes, your experience this quarter is going to be sooo helpful. My own
experience last quarter was at a much smaller scale, but I still learned a
ton about what the pain points were. Here are a few more thoughts:

* The biggest pain point by far was simply getting a good workflow of
creating my assignments, distributing them to students, having them turned
in, moving them to the right place for grading, etc.
* The realities of students turning in late work, getting sick, sending the
wrong notebook etc. made all of this enough that I wanted to jump off a
cliff.
* Once a given set of notebooks was in place and ready to grade, things
were glorious! The actual grading probably took only 10-20% of the time -
the rest was file/workflow management.

I think we can both develop things to help us manage the workflow (nbgrade
submit) as well as simplify things so when things are weird or go wrong, it
is easy to recover.


On Tue, Jan 20, 2015 at 4:50 PM, Jessica B. Hamrick <
notifications@github.com> wrote:

> I definitely agree. I think part of that is that we don't have a 100%
> clear picture of what all the necessary components are, but there is
> certainly a lot of complexity especially in understanding how the different
> apps work. Partially this is related to just the fact that the code is kind
> of complicated/messy (I already opened #57
> <https://github.com/jupyter/nbgrader/issues/57> to address this) but
> there is probably also conceptual complexity.
>
> It would be good if we could try to document where we feel things are
> confusing or too complex in this issue -- I'll try to do that as I'm
> grading stuff this semester.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/nbgrader/issues/66#issuecomment-70765195>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jhamrick** [comment]
I think we talked a lot of these things during the dev meeting and now have a plan for addressing them (e.g. #144), so I'm going to close this issue.
