### ISSUE TITLE
Allow autograding to skip usage of the database

### ISSUE THREAD

**Issue by choldgraf** [jupyter/nbgrader#661]
It could be useful to partially autograde student assignments without using the full database stack. Currently it's not possible to autograde without connecting with the database, but this requirement could be loosened by having something like a `no-db` flag as a part of the preprocessor. In this way, instructors could use the auto-running etc functionality of autograder even if they weren't using the nbgrader database. What do you think?

**Comment by jhamrick** [comment]
Do you envision this being essentially an alias for just using nbconvert to execute the notebook? Or would you also want it to do some grading (e.g. put in the cell metadata what the autograded score is?)

**Comment by choldgraf** [comment]
I think right now #1 is fine since it requires pretty minimal code. #2 could be a longer-term project if it seems like users had a use for it. WDYT? I can throw together a quick PR if you don't think #1 will be too much work

**Comment by jhamrick** [comment]
Yeah doing the first would be pretty straightforward. I *think* it would be enough just to create a flat that disables the `DeduplicateIds`,  `OverwriteCells`, `CheckCellMetadata`, `SaveAutoGrades`, and `AssignLatePenalties` preprocessors, and then to add a few if statements in the autograde app itself having it not check the database for things.

**Comment by choldgraf** [comment]
ok cool - I'll take a look at it and will try a PR...I feel bad asking you to implement things that I technically could do myself :)

**Comment by choldgraf** [comment]
Actually, looking at the code I wonder if this would also be better as a high-level function within `connectortools` as well. As you say, basically all you're doing in this case is executing the notebook and saving the output to another folder, right?

In that case I could just write something that wraps the `Execute` preprocessor and we wouldn't have to worry about changing the autograder code, which I'm hesitant to change since adding a `no-db` flag right now would basically make it not autograde anything. WDYT?

**Comment by jhamrick** [comment]
Yes, you could definitely do something that just wraps the Execute preprocessor (though I'd suggest using at least one or two others, like the LimitOutput preprocessor as well, which truncates long cell outputs).

> since adding a no-db flag right now would basically make it not autograde anything

Why would it make it not autograde anything? Do you mean it would execute, but not assign grades? I think that's true, but I also think that's probably fine. We could have it put grades in the notebook metadata, but maybe that should be left for a larger PR anyway...

**Comment by choldgraf** [comment]
> though I'd suggest using at least one or two others

That's a good idea - I'll plan on chaining together a few useful ones for this

> We could have it put grades in the notebook metadata, but maybe that should be left for a larger PR anyway...

Yeah I just meant that if we're only executing the notebooks then it doesn't make sense to do this with an object called `Autograde`. If there were some kind of metadata modification w/ grades then I think it would make more sense to be a part of the `Autograde`, but as you say I think that's a longer term PR.

**Comment by jhamrick** [comment]
After discussing with @choldgraf we determined he was able to handle this stuff with his own solution, so I am closing this issue.
