### ISSUE TITLE
Add a 3rd-party resources page to the documentation

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#662]
This could maybe be combined with the existing "autograding resources" page. But I'm thinking it would be useful to keep a list of 3rd party packages that could be used in conjunction with nbgrader (or even just instead of -- I'm more of the mind that people should be able to easily find the tool that suits their needs, rather than hoping everybody ever uses nbgrader :-)

Existing things that could be added to this list, just off the top of my head:

* nbtutor -- https://github.com/lgpage/nbtutor
* nbautoeval -- https://github.com/parmentelat/nbautoeval
* interact service for JupyterHub -- https://github.com/data-8/interact
* plotchecker -- https://github.com/jhamrick/plotchecker
* activity magic -- https://athena.brynmawr.edu/jupyter/hub/dblank/public//Activity%20Magic.ipynb

**Comment by lgpage** [comment]
Just a note for people reading this.
``nbtutor`` at the moment does not play well with the ``nbgrader`` ``create_assignment`` extension, see https://github.com/lgpage/nbtutor/issues/30

**Comment by jhamrick** [comment]
Also nbscan: https://github.com/conery/nbscan

**Comment by jhamrick** [comment]
Extension to hide code cells: https://github.com/kirbs-/hide_code

**Comment by jhamrick** [comment]
Ordo: https://github.com/nbgallery/ordo

**Comment by jhamrick** [comment]
zesje: https://gitlab.kwant-project.org/zesje/zesje

**Comment by jhamrick** [comment]
Jupyter in the Classroom: https://github.com/lucentdan/JupyterInTheClassroom
