### ISSUE TITLE
ExportApp does not work with custom exporter

### ISSUE THREAD

**Issue by lgpage** [jupyter/nbgrader#664]
@jhamrick could you please check if this works for you, when I try:
```shell
nbgrader export --exporter=plugin.Blarg
````
I get the following error (same error if set via ``nbgrader_config.py``):
```shell
[ExportApp | CRITICAL] Bad config encountered during initialization:
[ExportApp | CRITICAL] The 'plugin_class' trait of <nbgrader.apps.exportapp.ExportApp object at 0x7f2137acc0f0> instance must be a type, but 'plugin.Blarg' could not be imported
```

This however works:
```shell
nbgrader export --exporter=nbgrader.plugins.CsvExportPlugin
````

And to make thing even more strange:
```shell
python -c "from traitlets.utils.importstring import import_item; print(import_item('plugin.Blarg'))"
<class 'plugin.Blarg'>
```

**Comment by lgpage** [comment]
I think I figured out why this doesn't work and yet a custom plugin class for the ``latesubmission`` preprocessor did. ``nbconvert`` adds the ``cwd`` to the path (https://github.com/jupyter/nbconvert/blob/master/nbconvert/nbconvertapp.py#L248), which is also needed for this app.

**Comment by jhamrick** [comment]
Ah, I see. Yeah, adding the cwd to the path would be a reasonable thing to do for nbgrader as well.
