### ISSUE TITLE
Default ps1 example, created with ``quickstart``, needs updated schema data.

### ISSUE THREAD

**Issue by lgpage** [jupyter/nbgrader#674]
jsonschema error with ``quickstart`` + ``assign`` on master, steps to reproduce:
- fresh env
- ``nbgrader quickstart``
- ``nbgrader assign ps1``

**Comment by jhamrick** [comment]
Hmm, I can't reproduce. Are you using a conda env or virtualenv? Can you paste the full error?

**Comment by jhamrick** [comment]
If you install the release candidate, does it also happen?

**Comment by lgpage** [comment]
Using a conda env. Double checking now to see if maybe I didn't screw something up :wink:

**Comment by lgpage** [comment]
Hmm can't reproduce either, seems I must have messed something up somewhere earlier.
