### ISSUE TITLE
nbgrader lists commands

### ISSUE THREAD

**Issue by hetland** [jupyter/nbgrader#675]
It would be nice if 

    $ nbgrader 

(the command alone without any options) returned a list of commands with short descriptions (i.e., one command and short description per line). I keep forgetting the commands, and while the information is in --help, I need to scroll up to see it.

I would be happy to write the output text.

**Comment by jhamrick** [comment]
Sure, that seems reasonable. I think rather than writing the output text manually it would be better to pull the list of commands automatically from the ones it has (that way it always stays in sync, even if we add new subcommands), but this shouldn't be too hard to do I think.
