### ISSUE TITLE
Formgrader as an external service getting 404

### ISSUE THREAD

**Issue by huwf** [jupyter/nbgrader#677]
Hi,

I have managed to configure the formgrader in 0.4.0rc1 as a Jupyterhub run service which works very nicely.  I intend to run Formgrader in a Docker container, and then use Jupyterhub to authenticate from there.  I seem to have managed to get the authentication to work, but I'm getting a 404 for everything in /static/, as well as the assignments and students handlers.  

The main difference I can tell between my config on Docker and as a Jupyterhub service is the `base_url` which is set as `'/services/formgrader'` as a Jupyterhub service, and as `'http://127.0.0.1:8000/services/formgrader/'` in Docker, but I haven't figured out where I can change `base_url`.  Is this likely to be causing the problem, or have I missed something because that doesn't seem to quite add up?  Error message is of the form

`[FormgradeApp | WARNING] 404 GET /services/formgrader/static/components/jquery/jquery.min.js (127.0.0.1) 0.91ms`

My config is as follows:

Docker command: 

	docker run -it -v /home/huwf/data_science:/home/jovyan/work/data_science \
	-p 5000:5000 \
	-e JUPYTERHUB_SERVICE_NAME=formgrader \
	-e JUPYTERHUB_API_TOKEN=super-secret \
	-e JUPYTERHUB_API_URL=http://127.0.0.1:8081/hub/api \
	-e JUPYTERHUB_BASE_URL=http://127.0.0.1:8000 \
	-e JUPYTERHUB_SERVICE_PREFIX=/services/formgrader/ \
	-e JUPYTERHUB_SERVICE_URL=http://127.0.0.1:5000 \
	--net=host \
	#nbgrader-container inherits from jupyterhub/singleuser.
	# Start with /bin/bash so I can try different things with the config
	nbgrader-container /bin/bash 

nbgrader_config.py:

    ....
    c.NbGrader.db_students = student_list
    c.NbGrader.course_id = "data_science"
    c.FormgradeApp.ip = "127.0.0.1"
    c.FormgradeApp.port = 5000
    c.FormgradeApp.authenticator_class = "nbgrader.auth.hubauth.HubAuth"
    c.FormgradeApp.authenticator_instance.base_url = '/services/formgrader'
    # Change this to be the path to the user guide folder in your clone of
    # nbgrader, or just wherever you have your class files. This is relative
    # to the root of the notebook server launched by JupyterHub, which is
    # probably your home directory.
    c.HubAuth.notebook_url_prefix = 'data_science'#os.path.join(here)#, "data_science")
    c.HubAuth.notebook_server_user = "huwf"
    c.HubAuth.grader_group = 'data_science'

jupyterhub_config.py

	c = get_config()

	# Add users here that are allowed admin access to JupyterHub.
	c.Authenticator.admin_users = ["huwf", "instructor"]

	# Add users here that are allowed to login to JupyterHub.
	c.Authenticator.whitelist = [
	    "huwf"
	]
	c.JupyterHub.load_groups = {
	    'data_science': ['instructor', 'huwf']
	}

	# start the notebook server as an external service
	c.JupyterHub.services = [
	    {
	        'name': 'formgrader',
	        'url': 'http://127.0.0.1:5000',
	        'api_token': 'super-secret',
	    }
	]

	# Uncomment for Jupyterhub service
	# c.JupyterHub.services = [
	#     {
	#         'name': 'formgrader',
	#         'admin': True,
	#         'command': ['nbgrader', 'formgrade', '--log-level=DEBUG'],
	#         'url': 'http://127.0.0.1:5000'
	#     }
	# ]

**Comment by minrk** [comment]
Try setting

    JUPYTERHUB_BASE_URL=/

instead. I think there's some confusion about what JUPYTERHUB_BASE_URL is.

**Comment by minrk** [comment]
#678 should fix it, I think.

**Comment by huwf** [comment]
Thanks for the response @minrk.  I switched to `JUPYTERHUB_BASE_URL=/`, and also the removing the trailing `/` on `JUPYTERHUB_SERVICE_PREFIX`.  Together the two fixed that problem and it works nicely.   #679 looks like it will fix the other issue I had with upgrading from 0.3.0 too which was a bonus!

Final setup for `docker run` is as follows:

	docker run -it -v /home/huwf/data_science:/home/jovyan/work/data_science \
	-p 5000:5000 \
	-e JUPYTERHUB_BASE_URL=/ \
	-e JUPYTERHUB_SERVICE_NAME=formgrader \
	-e JUPYTERHUB_API_TOKEN=super-secret \
	-e JUPYTERHUB_SERVICE_URL=http://127.0.0.1:5000 \
	-e JUPYTERHUB_API_URL=http://127.0.0.1:8081/hub/api \
	-e JUPYTERHUB_SERVICE_PREFIX=/services/formgrader \
	--net=host \
	nbgrader-container /bin/bash

**Comment by jhamrick** [comment]
Thanks for sorting this out, @minrk !
