### ISSUE TITLE
Use SQLAlchemy for DB layer

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/nbgrader#68]
Originally, it was not clear what the database would end up looking like, so mongodb made a lot of sense. However, seeing how the db tables/collections have evolved, I think it will really help to use sqlalchemy's ORM layer. This would remove the need for us to write and maintain our own custom ORM layer for MongoDB and would allow a much larger set of DB engines, most importantly file based ones that are easier to manage such as sqlite.

**Comment by jhamrick** [comment]
I definitely think we should do this. Then, people can have the option too of having a sqlite database (which is a significantly lower startup cost, and is sufficient if they're the only one doing the grading) or setting up a full sql/postgres/etc. database if there are multiple graders.

**Comment by ellisonbg** [comment]
Awesome!

On Mon, Mar 2, 2015 at 7:12 PM, Jessica B. Hamrick <notifications@github.com
> wrote:

> Closed #68 <https://github.com/jupyter/nbgrader/issues/68> via #98
> <https://github.com/jupyter/nbgrader/pull/98>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/nbgrader/issues/68#event-244924528>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
