### ISSUE TITLE
No assignments to fetch.

### ISSUE THREAD

**Issue by apano** [jupyter/nbgrader#699]
The students and the professors do not see any assignments on the assignments menu. From terminal for both I can see the assignments, fetch them, submit and collect. The student side nbgrader_config.py is empty. 

```
$ nbgrader list
[ListApp | INFO] Released assignments:
[ListApp | INFO] cs-course1617 assignment1
[ListApp | INFO] cs-course1617 assignment2
[ListApp | INFO] cs-course1617 assignment3
```

jupyterhub (0.7.1)
nbgrader (0.4.0)

configuration jupyterhub_config.py 
```
from subprocess import check_call
import os
import sys
c.JupyterHub.config_file = '/etc/jupyterhub/jupyterhub_config.py'
c.JupyterHub.cookie_max_age_days = 1
c.JupyterHub.cookie_secret_file = '/srv/jupyterhub/cookie_secret'
c.JupyterHub.db_url = 'sqlite:////srv/jupyterhub/jupyterhub.sqlite'
c.JupyterHub.extra_log_file = '/var/log/jupyterhub.log'
c.JupyterHub.ip = '10.x.x.x'
c.JupyterHub.port = 443
c.JupyterHub.ssl_cert = '/etc/ssl/jupyterhub2017.crt'
c.JupyterHub.ssl_key = '/etc/ssl/private/jupyterhub2017.key'
c.JupyterHub.logo_file = '/srv/jupyterhub/logo.png'
c.Authenticator.admin_users = {'user1', 'user2','user3', 'user4'}
c.Spawner.mem_limit = '500M'

```
trainer nbgrader_config.py 

```c = get_config()
c.NbGrader.course_id = "course1617"
c.NbGrader.db_assignments = [dict(name="assignment1")]
c.NbGrader.db_assignments = [dict(name="assignment2")]
c.NbGrader.db_assignments = [dict(name="assignment3")]
c.NbGrader.db_students = [
    dict(id="student1", first_name="Ben", last_name="Bitdiddle"),
    dict(id="student2", first_name="Alyssa", last_name="Hacker"),
    dict(id="student3", first_name="Louis", last_name="Reasoner")
]```

**Comment by jhamrick** [comment]
First, are there any errors in the javascript console when you look at the Assignment List extension in the browser?

Second, are there any error messages in the server-side log? It looks like you're using JupyterHub.extra_log_file, which apparently will only log the JupyterHub output rather than output from the single user servers as well. Can you modify your setup to redirect all output to a logfile, e.g.:

https://groups.google.com/forum/#!topic/jupyter/xWZvSQQ3g6Q

or, alternately, just remove that option for now and run JupyterHub from the command line, which will hopefully reveal what the error is?

**Comment by jhamrick** [comment]
Additionally, it looks like the name of the course in the output from `nbgrader list` is different from the one you have specified in `nbgrader_config.py` ("cs-course1617" vs "course1617"). It is possible that could be causing problems, too -- if you have the course id set in the nbgrader config then it will only show those courses in the Assignment List extension. So if the ids are different that could explain why they can't see the assignments.

**Comment by apano** [comment]
Hello Jessica,
thank you for your reply.

I edited the name of the course when I published the post so as it was
easier to identify but in my config it all matches.
I checked the javascript errors and I get two error messages: (1) Missing
argument course_id & (2) Jupyter Notebook requires JavaScript Please enable
it to proceed.

(1) The course_id is set on instructor side
on: ~/notebooks/cs-course1617/nbgrader_config.py  Should I place it in
another location?
(2) I read I can create a ipython_notebook_config.py and specify
c.NotebookApp.open_browser
= False. I created for this a file in
~/.ipython/profile_default/startup/ipython_notebook_config.py
but yet it is not being loaded

I think I am missing something on the location of the files.

Kind regards,
Amantia



On Tue, Feb 7, 2017 at 2:59 AM, Jessica B. Hamrick <notifications@github.com

**Comment by apano** [comment]
I think perhaps I understood what is happening. 

My users home is /home/students/apano 
The proxy users is created for /home/apano so I assume it does not find the nbgrader conf.

Amantia Pano

**Comment by jhamrick** [comment]
Hi Amantia,

> Missing argument course_id

Could you post a screenshot of the full error message in the javascript console?

> Jupyter Notebook requires JavaScript Please enable it to proceed.

This could definitely cause problems as well -- you can enable JavaScript by going into your browser settings (the exact location is different depending on the browser, but if you google for "enable javascript <your browser>" you should be able to find instructions).

> The proxy users is created for /home/apano so I assume it does not find the nbgrader conf.

Yes that might be an issue. If you run nbgrader with the `--debug` flag you should see what config it's finding -- try running `nbgrader list --debug` from the command line in both `/home/students/apano` and `/home/apano`. If you post the full output from both commands I can try to help you figure out if that is indeed the problem.

**Comment by apano** [comment]
Hello,

I managed to fix everything.
Our users are in an LDAP server, the homes mounted by nfs, and users are
authenticated via sssd. I would like to keep that for having
persistency/backup of files.

I now run switched to SudoSpawner. JupyterHub has to create home folders
locally & also it needs to generate the .jupyter folder in the nfs user
home (done only if you have rights to) so to solve this:

I run Jupyterhub as root for the first time so the /home/students/student1
user folder is created and the .jupyter too. I receive a 500 cannot start
spawner. I stop the server and rerun it with my JupyterHub dedicated user.

I have then the professors create the dirs for the courses and release
assignments.

I have a few doubts on this configuration because if I open a terminal from
student1 I can browse the contents of
/home/professors/professor1/course1617. Precisely:

student1@cs-jupyter:/home/professors/professor1$ ls -lrt
drwxr-xr-x 4 professor1 domain users 4096 Feb  8 15:31 course1617

and subfolders of course1617 are:
drwxr-sr-x 3 professor1 domain users  4096 Feb  8 00:38 source
drwxr-xr-x 3 professor1 domain users  4096 Feb  8 15:27 release
-rw-r--r-- 1 professor1 domain users 39936 Feb  8 15:27 gradebook.db
-rw-r--r-- 1 professor1 domain users 27885 Feb  8 15:31 nbgrader_config.py

Should I ask the professors to modify the access rights on the folders of
the courses each time? If yes, is there any directory I should keep
readable by all? I currently have set /srv/nbgrader/exchange as readable by
all.

Thank you for your time.

Kind regards,
Amantia

On Tue, Feb 7, 2017 at 6:35 PM, Jessica B. Hamrick <notifications@github.com

**Comment by jhamrick** [comment]
For my course, I used [restuser](https://github.com/minrk/restuser) in conjunction with the [authenticator](https://github.com/compmodels/jupyterhub/blob/master/docker_oauth.py) to create users on the fly the first time they log in. I am not sure if that is feasible for you to use if you're using SudoSpawner (I believe restuser needs to run as root) but I figured I'd point you to it anyway in case it is useful 😄 

> Should I ask the professors to modify the access rights on the folders of the courses each time?

Yes, that is one way you can do it. Another way is to set the [umask](https://en.wikipedia.org/wiki/Umask) of all users to 0077, which will make all files created by that user by default to be only readable by the user.

> If yes, is there any directory I should keep readable by all? I currently have set /srv/nbgrader/exchange as readable by all.

The exchange directory is the only directory that needs to be readable by everybody.

**Comment by jhamrick** [comment]
Closing this as the issue seems to be resolved but feel free to open a new issue with any further questions!
