### ISSUE TITLE
Assignment List extension is slow

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#705]
The reason is because it actually has to shell out to the command line apps rather than running them in the same python session, and the reason it can't run them in the same python session is because the `NotebookApp` and `NbGrader` both inherit from `JupyterApp` which is a singleton, so it raises an error if you try to instantiate `NbGrader` within the `NotebookApp`. Fixing this would require a fair bit of refactoring: moving the bulk of the transfer apps into separate classes that are not subclasses of `JupyterApp`, and then having the apps themselves create those classes and call them (similarly to how the preprocessors work in nbconvert).

**Comment by jhamrick** [comment]
It is also complicated by the fact that the transfer apps rely on a lot of the config machinery that `JupyterApp` provides, and it would be annoying to replicate this machinery in new classes. Maybe it's necessary, though... I think it will require some investigation as to what exactly is the right way to do this.

**Comment by lgpage** [comment]
Would it not be better to tie the assignment list in with #659

**Comment by jhamrick** [comment]
Yes, though #659 will also require having a library (rather than a REST api). The JupyterHub file sharing service will be a REST api, which nbgrader will have library functions built on top of which will then replace the existing functionality of the transfer apps. So I think the issue is still there -- but certainly we could probably address both issues at once (by building the library to not be part of `JupyterApp` itself, and then pulling in that functionality into the transfer apps).
