### ISSUE TITLE
Open ListApp tab on Jupyter tree load

### ISSUE THREAD

**Issue by huwf** [jupyter/nbgrader#715]
Is it possible to load the assignment list page as the first tab the user would see rather than the directory tree?  If this is out of scope for nbgrader, can you point to any documentation to help me out in another library?

Note: At present I'm using 0.3.3 because I had difficulties with 0.4.0.  If it's only possible on 0.4.0 then I'll jump to that.  Hopefully I will anyway, but sadly I have more immediate priorities before the current version of my course, like finishing the content so I'm not sure if I'll have time.

**Comment by lgpage** [comment]
This is possible, but I am not so sure about making this the default behaviour.

I have no idea if this will work, but this is how I would attempt it:
```
diff --git a/nbgrader/nbextensions/static/assignment_list/main.js b/nbgrader/nbextensions/static/assignment_list/main.js
index cf1b878..4e0adc3 100644
--- a/nbgrader/nbextensions/static/assignment_list/main.js
+++ b/nbgrader/nbextensions/static/assignment_list/main.js
@@ -70,6 +70,7 @@ define(function(require) {
             $('<li>')
             .append(
                 $('<a>')
+                .attr('id', 'assignments-list')
                 .attr('href', '#assignments')
                 .attr('data-toggle', 'tab')
                 .text('Assignments')
@@ -88,6 +89,7 @@ define(function(require) {
             }
         );
         assignment_list.load_list();
+        $('#assignments-list').trigger('click');
     }
     return {
         load_ipython_extension: load
```

**Comment by huwf** [comment]
That's pretty neat, I'll give it a go at some point and see if it works! :)  The title of the issue is misleading, I wasn't intending to suggest that become default behaviour, not sure why I put it like that.  It would be nice to have an option to switch this behaviour on and off though, if it could be done easily.  I'll update the title.

**Comment by lgpage** [comment]
Also keep in mind you may need to re-install the extensions for JavaScript changes to apply (depending on your current installation)

**Comment by jhamrick** [comment]
It certainly seems reasonable to me to add the HTML `id` tag to the tab element, and then it shouldn't be to hard to have a `custom.js` that does the `$('#assignments-list').trigger('click');`. What might be trickier is making sure all your students are using the same `custom.js`... I am not sure if you can have a global `custom.js` or not.

**Comment by huwf** [comment]
I'm now thinking this is probably not a good idea, because it renders in the client.  If you have a slow connection, you'll get the tree view and then a second (or more) later will jump to a different page which probably wouldn't be such a great experience.

Where is the `custom.js` file stored?  Is it in the `.jupyter` folder?

**Comment by jhamrick** [comment]
Yes, I believe it is `~/.jupyter/custom/custom.js`.

**Comment by huwf** [comment]
Thanks guys for answering my questions.  I don't think I'll use it for now since it renders on the client, though it's useful to know.  I will close this ticket.
