### ISSUE TITLE
Cannot define solution_delimiters for multiple languages

### ISSUE THREAD

**Issue by AnotherCodeArtist** [jupyter/nbgrader#716]
Hi!

According to the doc (http://nbgrader.readthedocs.io/en/stable/configuration/student_version.html) it should be possible to define solution_delimiters for multiple languages.
If I try this, I get the following error:
```traitlets.traitlets.TraitError: The 'begin_solution_delimeter' trait of a ClearSolutions instance must be a unicode string, but a value of {'scala': '// BEGIN SOLUTION', 'python': '### BEGIN SOLUTION'} <class 'dict'> was specified.```
In the code (https://github.com/jupyter/nbgrader/blob/master/nbgrader/preprocessors/clearsolutions.py) `begin_solution_delimiter` and `end_solution_delimiter` are defined as `Unicode`.
So what's wrong here??

**Comment by lgpage** [comment]
Hi

Yes, the documentation is wrong in this regard.
The solution delimiters must be specified as strings.
Only the ``code_stub`` option needs to be given in a dictionary for different languages.

The comment character/s (`scala`: `//` and `python`: `#`) are not needed when specifying the solution delimiters in the nbgrader config file, so the following should be sufficient:
```
c.ClearSolutions.begin_solution_delimeter = 'BEGIN SOLUTION'
c.ClearSolutions.end_solution_delimeter = 'END SOLUTION'
```
