### ISSUE TITLE
Updates to db schema invalidate old databases

### ISSUE THREAD

**Issue by whitead** [jupyter/nbgrader#720]
Just FYI, it appears that the new requirement to have kernelspecs in the DB invalidates old gradebooks. The error when assigning is:

```python
  sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: notebook.kernelspec [SQL: 'SELECT notebook.id AS notebook_id, notebook.name AS notebook_name, notebook.assignment_id AS notebook_assignment_id, notebook.kernelspec AS notebook_kernelspec \nFROM notebook \nWHERE ? = notebook.assignment_id ORDER BY notebook.name'] [parameters: ('dd7f27919f4949f086e975671d05579d',)]
```

For me, I had to modify the gradebook in sqlite3 to get it to work. These are the commands that worked:
```sql
ALTER TABLE notebook ADD COLUMN kernelspec VARCHAR(1024);
UPDATE notebook SET kernelspec='{"display_name": "Python 3", "name": "python3", "language": "python"}';
```

where `Python 3` or `Python 2` is used as appropriate. Just wanted to pass this info on in case anyone else had this issue.

**Comment by jhamrick** [comment]
Ah, yes, sorry about that. I perhaps should have sent an email to the mailing list.

It would be nice if we could provide a way to have a database schema version and then update old databases with newer versions of the schema, that way these sorts of changes are less disruptive.
