### ISSUE TITLE
Jupyterhub formgrader returning error 404

### ISSUE THREAD

**Issue by maxrudolph** [jupyter/nbgrader#725]
I am trying to deploy jupyterhub with nbgrader for teaching, running within a docker container. I am using github oauth through oauthenticator. Everything seems to be working except formgrader. I think that when formgrader starts as a managed service, it is unable to find nbgrader_config.py. I say this because if I change the formgrader port in nbgrader_config.py, it has no effect on the port used when formgrader is started. What do I need to do to ensure that nbgrader_config can be found? Thank you for your help.

**Comment by jhamrick** [comment]
Could you please provide the output from the docker container when you run JupyterHub?

**Comment by maxrudolph** [comment]
[D 2017-03-15 06:19:53.294 JupyterHub application:555] Looking for /srv/jupyterhub_config/jupyterhub_config in /srv/nbgrader/g326-2017
[D 2017-03-15 06:19:53.294 JupyterHub application:577] Loaded config file: /srv/jupyterhub_config/jupyterhub_config.py
[D 2017-03-15 06:19:53.305 JupyterHub app:781] Generating new cookie_secret
[I 2017-03-15 06:19:53.305 JupyterHub app:786] Writing cookie_secret to /srv/nbgrader/g326-2017/jupyterhub_cookie_secret
[D 2017-03-15 06:19:53.305 JupyterHub app:839] Connecting to db: sqlite:///jupyterhub.sqlite
[W 2017-03-15 06:19:54.603 JupyterHub app:375] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[I 2017-03-15 06:19:54.676 JupyterHub app:935] Not using whitelist. Any authenticated user will be allowed.
[D 2017-03-15 06:19:55.004 JupyterHub app:1142] Loading state for maxrudolph from db
[D 2017-03-15 06:19:55.008 JupyterHub app:1154] maxrudolph not running.
[D 2017-03-15 06:19:55.020 JupyterHub app:1142] Loading state for jupyter from db
[D 2017-03-15 06:19:55.021 JupyterHub app:1154] jupyter not running.
[D 2017-03-15 06:19:55.025 JupyterHub app:1162] Loaded users: 
    maxrudolph admin
     jupyter
[I 2017-03-15 06:19:55.037 JupyterHub app:1515] Hub API listening on http://127.0.0.1:8081/hub/
[I 2017-03-15 06:19:55.042 JupyterHub app:1236] Starting proxy @ http://0.0.0.0:443/
[D 2017-03-15 06:19:55.042 JupyterHub app:1237] Proxy cmd: ['configurable-http-proxy', '--ip', '0.0.0.0', '--port', '443', '--api-ip', '127.0.0.1', '--api-port', '444', '--default-target', 'http://127.0.0.1:8081', '--error-target', 'http://127.0.0.1:8081/hub/error', '--ssl-key', '/etc/ssl/private/private.key', '--ssl-cert', '/etc/ssl/certs/cert.crt']
06:19:55.344 - info: [ConfigProxy] Proxying https://0.0.0.0:443 to http://127.0.0.1:8081
06:19:55.349 - info: [ConfigProxy] Proxy API at http://127.0.0.1:444/api/routes
[D 2017-03-15 06:19:55.451 JupyterHub app:1266] Proxy started and appears to be up
[I 2017-03-15 06:19:55.451 JupyterHub app:1528] Starting managed service formgrader-g326 at http://127.0.0.1:5000
[I 2017-03-15 06:19:55.453 JupyterHub service:229] Starting service 'formgrader-g326': ['nbgrader', 'formgrade']
[I 2017-03-15 06:19:55.462 JupyterHub service:90] Spawning nbgrader formgrade
[D 2017-03-15 06:19:55.467 JupyterHub spawner:586] Polling subprocess every 30s
[FormgradeApp | INFO] Serving MathJax from /opt/conda/lib/python3.5/site-packages/notebook/static/components/MathJax/MathJax.js
[FormgradeApp | INFO] Notebook server is running at http://localhost:39345/notebooks/
[FormgradeApp | INFO] The formgrader is running at http://localhost:5000/
[FormgradeApp | INFO] --> Go to http://localhost:5000/ to access the formgrader
[FormgradeApp | INFO] Use Control-C to stop this server
[FormgradeApp | WARNING] 404 GET /services/formgrader-g326/ (127.0.0.1) 0.65ms
[D 2017-03-15 06:19:56.706 JupyterHub utils:87] Server at http://127.0.0.1:5000/services/formgrader-g326/ responded with 404
[I 2017-03-15 06:19:56.706 JupyterHub app:1571] JupyterHub is now running at http://127.0.0.1:443/
[I 2017-03-15 06:19:56.712 JupyterHub orm:170] Adding service formgrader-g326 to proxy /services/formgrader-g326/ => http://127.0.0.1:5000
[D 2017-03-15 06:19:56.712 JupyterHub orm:153] Fetching POST http://127.0.0.1:444/api/routes/services/formgrader-g326/
[FormgradeApp | WARNING] 404 GET /services/formgrader-g326 (127.0.0.1) 1.12ms
[D 2017-03-15 06:20:27.757 JupyterHub log:100] 304 GET /favicon.ico (@131.252.192.53) 6.85ms

**Comment by maxrudolph** [comment]
Progress - this problem only exists when using jupyterhub 0.8.0, which is the default version in the docker container that I used as a starting point.

**Comment by sigurdurb** [comment]
@maxrudolph, @jhamrick  I had the same problem, fixed it by modifying file permission on the .jupyter/nbgrader_config.py file, it was not executable. Fixed it by running.
```
chmod 700 .jupyter/nbgrader_config.py
```
I am running Jupyterhub version 0.8.1

Maybe could add to the logs to say something like: "nbgrader_config not executable" ??
