### ISSUE TITLE
autograde does not work when assignments have pyspark as dependency

### ISSUE THREAD

**Issue by sriniavireddy** [jupyter/nbgrader#729]
When running autograde on notebooks which have dependency on pyspark library, it shows "no module named pyspark", even though pyspark is installed in the system and verified as well.

**Comment by jhamrick** [comment]
It's possible that the kernel nbgrader is using to grade the notebooks is different from the version of python with which you have pyspark installed. Can you paste the output of the following commands to help me debug the problem further?

1. `nbgrader --version`
2. `which nbgrader`
3. `python --version`
4. `which python`
5. `python -c "import pyspark"`
6. `nbgrader autograde --log-level=DEBUG <your_assignment_id>`

**Comment by jhamrick** [comment]
Closing as this issue is over a month old, but let me know if this is still an issue.

**Comment by mhwasil** [comment]
I got the same problem with [xlrd](https://pypi.org/project/xlrd/), pandas and matplotlib
* nbgrader --version
```
Python version 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516]
nbgrader version 0.5.4
```
* which nbgrader
```
/usr/local/bin/nbgrader
```
* python3 --version (we are using python 3)
```
/usr/bin/python3
```
* python3 -c "import xlrd" works in terminal
* python3 -c "import pandas" also works in terminal 
* nbgrader autograde --log-level=DEBUG --student student --assignment assignment01 
```
[AutogradeApp | DEBUG] Searching ['/home/wus-course/Wahrscheinlichkeitstheorie/WuS-Course', '/home/wus-course/.jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[AutogradeApp | DEBUG] Looking for jupyter_config in /etc/jupyter
[AutogradeApp | DEBUG] Looking for jupyter_config in /usr/local/etc/jupyter
[AutogradeApp | DEBUG] Looking for jupyter_config in /usr/etc/jupyter
[AutogradeApp | DEBUG] Looking for jupyter_config in /home/wus-course/.jupyter
[AutogradeApp | DEBUG] Looking for jupyter_config in /home/wus-course/Wahrscheinlichkeitstheorie/WuS-Course
[AutogradeApp | DEBUG] Looking for nbgrader_config in /etc/jupyter
[AutogradeApp | DEBUG] Loaded config file: /etc/jupyter/nbgrader_config.py
[AutogradeApp | DEBUG] Looking for nbgrader_config in /usr/local/etc/jupyter
[AutogradeApp | DEBUG] Looking for nbgrader_config in /usr/etc/jupyter
[AutogradeApp | DEBUG] Looking for nbgrader_config in /home/wus-course/.jupyter
[AutogradeApp | DEBUG] Loaded config file: /home/wus-ploeger/.jupyter/nbgrader_config.py
[AutogradeApp | DEBUG] Looking for nbgrader_config in /home/wus-course/Wahrscheinlichkeitstheorie/WuS-Course
[AutogradeApp | DEBUG] Looking for nbgrader_config in /home/wus-course/Wahrscheinlichkeitstheorie/WuS-Course
[AutogradeApp | INFO] Skipping existing assignment: /home/wus-course/Wahrscheinlichkeitstheorie/WuS-Course/autograded/student_id01/ assignment01
```

We got this error in the notebook:
```
----> 1 import pandas as pd
      2 import random
      3 import numpy as np
      4 from scipy import stats
      5 import matplotlib.pyplot as plt

ImportError: No module named 'pandas'
```
and we got the same error for xlrd.

**Comment by mhwasil** [comment]
Great,
It works with --force.
nbgrader autograde --log-level=DEBUG --student student --assignment assignment01 --force

Thanks @jhamrick.
