### ISSUE TITLE
make nbgrader zip_collect reporting more informative

### ISSUE THREAD

**Issue by Szepi** [jupyter/nbgrader#739]
When running nbgrader zip_collect and the archives submitted by students have unexpected content, the warnings/errors generated by nbgrader should be more informative. In particular, it would be great if information about the offending submission was printed/logged. I tried to change the log level, but it did not seem to have an effect. 
The particular warnings and errors I got are:
```
[ZipCollectApp | WARNING] Invalid submission notebook name 'practice.ipynb'
[ZipCollectApp | WARNING] Invalid submission notebook name 'practice.ipynb'
[ZipCollectApp | ERROR] Duplicate submission file. No timestamps for comparison
```

I cannot include examples, sorry.

**Comment by Szepi** [comment]
I guess I was wrong. Further tinkering with nbgrader, --log_level=DEBUG gives me the file information.
However, the error messages are quite uninformative. After removing many of the submissions, now I am getting:
```Skipped submission with no match information provided```

What information was matched to what remains unclear.

**Comment by lgpage** [comment]
You should be able to get debug information by adding the ``--debug`` flag to the ``zip_collect`` command

**Comment by lgpage** [comment]
Warnings or errors follow on from a "Parsing file: " line indicating which file is being considered, for example:

```bash
[ZipCollectApp | INFO] Parsing file: /home/user/Desktop/Foo/assignments/downloaded/ps1/extracted/gradebook_foo_s1_2017_Problem20Set201_2017-02-17-17-09-00/Problem Set 1_uxxxxxxxx_attempt_2017-02-13-13-27-47.txt
[ZipCollectApp | DEBUG] Invalid file extension .txt
[ZipCollectApp | WARNING] Skipped submission with no match information provided.
```

**Comment by Szepi** [comment]
Thanks. Looking at the source made me discover that my regexp was incorrectly parsing the filename. Perhaps in debug mode in case of no match, the outcome of the parse could be shown and the user told to check their regexp (bad regexps must be a common problem for newbies?).

**Comment by jhamrick** [comment]
> Perhaps in debug mode in case of no match, the outcome of the parse could be shown and the user told to check their regexp (bad regexps must be a common problem for newbies?).

Seems like a reasonable suggestion to me.

**Comment by jhamrick** [comment]
Looking back into this, I think there should already be a debug statement if the regex isn't matching:

https://github.com/jupyter/nbgrader/blob/master/nbgrader/plugins/zipcollect.py#L147

So I'm not sure why that wouldn't be printing in your case? If you could provide a more detailed example, that would be helpful.

Regardless, I will make a PR making some of the warnings a little more explicit.
