### ISSUE TITLE
Use tornado instead of flask

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#74]
The rest of IPython/Jupyter stuff uses tornado, so it might be better to switch to that from Flask in order to be a bit more consistent. Though, if we end up switching to live notebook grading, we wouldn't need to worry about this anyway. I'm creating this as an issue anyway just as a reminder in case the HTML grader does stick around.

**Comment by jhamrick** [comment]
@jdfreder I am assigning this to you, but this is lower priority than the other things, so up to you if you want to go ahead and do this now when you're adding auth to the formgrader, or I can just do it later (probably after my course is finished).

**Comment by yarko** [comment]
Just was digging into the question of flask vs. tornado for teaching on a separate topic (runestone flask).

I am putting this here for completeness, fyi:  [deploying flask with tornado](http://flask.pocoo.org/docs/0.10/deploying/wsgi-standalone/#tornado)

**Comment by jhamrick** [comment]
Oh, that's great to know. Thanks!

**Comment by jhamrick** [comment]
I am going to push this to 2.0 because I don't think it's a blocker for 1.0.
