### ISSUE TITLE
nbgrader serverextension creates gradebook.db

### ISSUE THREAD

**Issue by Szepi** [jupyter/nbgrader#741]
I installed the server extensions and since then whenever I start jupyter notebook in a directory without a config file, some of these extensions will create an empty gradebook.db in the directory I started jupyter from.
These extensions are installed:
```bash
$ jupyter serverextension list
config dir: /opt/local/Library/Frameworks/Python.framework/Versions/3.5/etc/jupyter
    nbgrader.server_extensions.formgrader  enabled
    - Validating...
      nbgrader.server_extensions.formgrader  OK
    nbgrader.server_extensions.assignment_list  enabled
    - Validating...
      nbgrader.server_extensions.assignment_list  OK
```
I am using nbgrader 0.5.0

**Comment by lgpage** [comment]
Thanks for reporting this. I have noticed the same behaviour, but kept forgetting to post an issue.
