### ISSUE TITLE
Release version 0.5.0

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#757]
I would like to get version 0.5.0 out the door before SciPy, and am planning on doing the bulk of the work on it this week (I already have PRs for about 1/3rd of open issues marked for 0.5.0!)

This issue is just to give everybody a heads up, and to give people a chance to request that particular issues get addressed specifically for this upcoming release.

cc @lgpage @willingc @ellisonbg

**Comment by elhele** [comment]
Hello Ms Hamrick,

thank you for developing such a useful tool!
At my university we are working on a project focused on autograding and we were thinking about using the nbgrader. However, now it is a bit hard to use it because everything, like creating the assignments, adding students, etc., should be done using console. So, the question is if you are going to add some GUI in this release. If not, probably we could think about doing it by ourselves and contributing it to the project.

**Comment by jhamrick** [comment]
Hi @elhele yes this is definitely an issue on the agenda (see #555 ). I do not think we will be able to add *all* the functionality that nbgrader has to the webapp for the upcoming release (as that is really a massive amount of work -- I would estimate several weeks if not a month's worth of work, doing it full time). But I do intend to add basic functionality for e.g. running `nbgrader assign` and `nbgrader autograde` through the web interface.

**Comment by elhele** [comment]
Hello @jhamrick thank you for the reply! It is important for me to know the approximate dates.

**Comment by jhamrick** [comment]
@elhele I am aiming to have 0.5.0 released before SciPy, which is mid-July. I can't make any hard promises though, unfortunately (I am juggling trying to get this release out while also finishing my dissertation).

**Comment by willingc** [comment]
@jhamrick Let me know if you need anything for wrapping up 0.5.0.

**Comment by jhamrick** [comment]
@willingc Thanks! I am just wrapping up an implementation of #555 that I will push hopefully by the end of today... once I do that if you have a chance to give any feedback that would be awesome. That is the biggest blocker right now :)

**Comment by willingc** [comment]
Getting closer to release 🎉

**Comment by jhamrick** [comment]
@elhele I'm not sure if you saw #782 but the GUI functionality you requested now exists!

**Comment by jhamrick** [comment]
Ok, now all the major things are done for 0.5.0! 🎉  I plan to make the release either tonight or tomorrow. My guess is there will be a stream of bugs then but we can do a patch release soon if necessary.

**Comment by elhele** [comment]
@jhamrick , thank you very much for the information! :)
I'll test it as soon as I have time.
