### ISSUE TITLE
Disable 'delete cells' option in the notebook after running 'nbgrader assign'

### ISSUE THREAD

**Issue by kiranvasudev** [jupyter/nbgrader#773]
Hi !
  I would like to disable the usage of 'delete cells' and the 'insert cell above/below' buttons in the notebook after i run the 'nbgrader assign' command. Any leads to complete this would be appreciated.

Thank you !

**Comment by jhamrick** [comment]
You can disable the deletion of cells by marking them as "locked" in the Create Assignment extension. Unfortunately, there is no way to disable cell insertion through nbgrader -- this would require a custom extension to the notebook that you then have students install themselves.

**Comment by jhamrick** [comment]
I am going to close this since there hasn't been any activity on this for over a month. Feel free to open more issues if you have further questions!
