### ISSUE TITLE
Investigate slow loading times in formgrader extension

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#785]
c.f. discussion in #782

**Comment by jhamrick** [comment]
Copying what @lgpage said for reference:

Just thought I would add some load time info on my machine:

* Manage Assignments - Assignments / ps1 - 1125 records - 28s
* Manual Grading - Manual Grading / ps1 / problem1 - 1125 records - 10s
* Manage Students - 1262 records - 6s

Before:

* No comparison for Manage Submissions
* Assignments / ps1 / problem1 - 1125 records - 7s
* Students - 1262 records - 3s

**Comment by jhamrick** [comment]
For me, with 1126 records, I get:

* Manage Submissions - Assignments / ps1 (before autograding): 12.06s
* Manage Submissions - Assignments / ps1 (after autograding): 12.85s
* Manual Grading - Manual Grading / ps1 / problem1: 4.04s
* Manage Students: 1s

(Also, wow, I didn't realize you had so many students @lgpage !! 😮 )

I wrote a little script to test the time of the API calls:

```python
from datetime import datetime
from nbgrader.apps import NbGraderAPI


def time(f, n=3):
    times = []
    for _ in range(n):
        now = datetime.now()
        f()
        times.append((datetime.now() - now).total_seconds())
    best = max(times)
    print("{}s, best of {}".format(best, n))


api = NbGraderAPI()

print("--")
print("api.get_submissions('ps1')")
time(lambda: api.get_submissions("ps1"))

print("--")
print("api.get_notebook_submissions('ps1', 'problem1')")
time(lambda: api.get_notebook_submissions("ps1", "problem1"))

print("--")
print("api.get_students()")
time(lambda: api.get_students())
```

which gives:

```
$ python test_timing.py
--
api.get_submissions('ps1')
10.596381s, best of 3
--
api.get_notebook_submissions('ps1', 'problem1')
2.035762s, best of 3
--
api.get_students()
0.212093s, best of 3
```

This suggests there is a 1-2 second overhead on the client side (javascript) with the majority of the time being spent in the API call. @lgpage would you mind running this script too so I can get a comparison from you?

**Comment by jhamrick** [comment]
Ok, so I tracked down the slowness to `NbGraderAPI.get_autograded_students`. Replacing the logic in there with a more efficient database query yields the following times from my timing script:

```
--
api.get_submissions('ps1')
1.392538s, best of 3
--
api.get_notebook_submissions('ps1', 'problem1')
2.902919s, best of 3
--
api.get_students()
0.170954s, best of 3
```

(this only affects `api.get_submissions`, so the others are essentially unchanged)

**Comment by jhamrick** [comment]
Found a few other places where slowness was occurring in `NbGraderAPI.get_students` and `NbGraderAPI.get_submission` when the assignments were not yet autograded. I am going to make a PR with what I have so far.

**Comment by lgpage** [comment]
@jhamrick yeah too many students :P - I added my timings to #787 - this was tested on the full gradebook for my course. To give an idea of the number of total records (of the large tables) in the database:
- `submitted_notebook` table - 21205
- `submitted_assignment` table - 7449
- `grade` and `comment` tables - 51344
- ` student` table - 1262

**Comment by jhamrick** [comment]
I with github would let me make the 😮 emoji as a reaction to your comment!

Well, I'm really glad though that you have so many students---nbgrader definitely needs someone using it heavily to find all the areas of sluggishness that would otherwise be overlooked! (Though I also imagine it must be a ton of grading work...)

**Comment by lgpage** [comment]
Nbgrader worked so smoothly for the assignments, it was wonderful.

The real downside of so many students is that I can only have auto-graded answers and no free-response type questions and I have to incorporate more useful info in test failures as adding comments is not practically possible.

The run time of the auto-grading is quite long, but that is at least something you can start and leave to run semi unattended.
