### ISSUE TITLE
Allow the exporting of grades per assignment id

### ISSUE THREAD

**Issue by lgpage** [jupyter/nbgrader#799]
The main issue I have with the exporting of grades (csv export) is that it is extremely sluggish exporting the entire gradebook (5min+), especially in cases where there may only be one or two grade changes for a given assignment.

My suggestion is to allow the exporting of grades to individual files per assignment id, if an assignment id is specified, otherwise export the entire gradebook.

A custom plugin can be created to achieve this, but I think it may be better to support this.
@jhamrick what do you think?

This is also something that is specific to the use case of a large number of students.

**Comment by jhamrick** [comment]
I think that seems reasonable. We I think it makes sense for there to be two dimensions along which we can limit grades: both assignments (with `--assignment`) and students (with `--student`).

**Comment by dkirkby** [comment]
In addition to saving time, this feature would be convenient with my course management software which expects a separate CSV per assignment.
