### ISSUE TITLE
Formgrader assignment navigation (source and release)

### ISSUE THREAD

**Issue by lgpage** [jupyter/nbgrader#807]
This is more of a nitpick than an issue, but non-the-less.

On Windows the navigation to the source and/or release notebooks has a backslash (making the navigation up just one directory not possible):

![2017-07-13 09_17_39-source_ps1_](https://user-images.githubusercontent.com/1577821/28157242-23b6d6f2-67b6-11e7-96d4-69c27f98bdee.png)

On Linux a forward slash:

![selection_083](https://user-images.githubusercontent.com/1577821/28157303-559af0e0-67b6-11e7-9f60-b8aa1b0dc119.jpg)

**Comment by jhamrick** [comment]
I'm looking into this but can't seem to reproduce it... is it still a problem for you? If so, is this with the default setup generated by `nbgrader quickstart`?

**Comment by jhamrick** [comment]
I am closing this issue because there hasn't been any activity on it in a while. However, if you (or others) continue to encounter problems, feel free to comment here or open a new issue!
