### ISSUE TITLE
Add expected .csv columns to the db import help

### ISSUE THREAD

**Issue by lgpage** [jupyter/nbgrader#808]
It would be useful to have an indication of what `.csv` columns are expected in the respective `db` `import` commands help information (`nbgrader db assignment import -h` and `nbgrader db student import -h`).

**Comment by jhamrick** [comment]
For reference, the expected columns correspond to the column names of the database tables: http://nbgrader.readthedocs.io/en/stable/api/models.html

These correspond to:

* assignments
    * name
    * duedate

* students
    * id
    * last_name
    * first_name
    * email

**Comment by jhamrick** [comment]
@mpacer this is something you could probably do now too, now that you figured out how to get the column names!
