### ISSUE TITLE
Allow nbgrader quickstart to work on an existing directory

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#818]
Rather than refusing to run if the directory exists, quickstart should check if it is going to overwrite any files and if it is only then throw an error.

cc @ncclementi

**Comment by dudu84** [comment]
Hi! Can I take this one?

**Comment by jhamrick** [comment]
Go for it!

**Comment by dudu84** [comment]
Hi Jessica!

One question so far: As I can't simply check if the directory is not empty,
where can I get the list of files that it will be created?
I need ti know them, right? This way I can compare with the existing ones.
Thanks!

2017-10-30 11:26 GMT+01:00 Jessica B. Hamrick <notifications@github.com>:

> Go for it!
>
> On Mon, Oct 30, 2017 at 9:45 AM Luiz Eduardo de Christo <

**Comment by jhamrick** [comment]
Hmm, good point. There isn't anywhere that lists the files that will be created before creating them, but you can look in `nbgrader/apps/quickstartapp.py` to see what is created by inspecting the code. At a quick glance it looks like it creates:

* A directory called `source` containing the contents of `nbgrader/docs/source/user_guide/source`
* `nbgrader_config.py`

Since it really only creates these two things I think it's just reasonable to add some code at the beginning of `quickstartapp.py` to check them explicitly. It's a little bit of code duplication, and we'll need to remember to add more checks if we ever add more files, but I think that's fine for now.

**Comment by dechristo** [comment]
@jhamrick Hi! So sorry for long delay.
I opened a pull request for this: [https://github.com/jupyter/nbgrader/pull/1019](https://github.com/jupyter/nbgrader/pull/1019)
Thanks a lot for your  support and once again sorry that it took so long.
