### ISSUE TITLE
Tabbing should bring you to the top of the answer key, not the student's answer

### ISSUE THREAD

**Issue by suchow** [jupyter/nbgrader#83]
![screenshot 2015-02-17 17 02 18](https://cloud.githubusercontent.com/assets/613981/6240693/c4698f2a-b6c6-11e4-861e-820f4b99a459.jpg)

**Comment by jhamrick** [comment]
The hard part about this is that not all questions have answer keys right above them (though maybe that would be a good thing to have, at least for written answers!). I could have it go to the *cell* above, but that's not necessarily what you want.

**Comment by suchow** [comment]
Maybe there's a way then to have the default position of a tab-highlighted element a bit low, closer to the middle of the screen?

**Comment by jhamrick** [comment]
Yeah, that's how I had it initially. The issue there is then sometimes the answer itself gets cut off, and you have to scroll every time, which is also annoying.
