### ISSUE TITLE
Incorrect path for assignments in formgrader, if Jupyterhub notebook_dir is not home directory

### ISSUE THREAD

**Issue by misolietavec** [jupyter/nbgrader#855]
I have the subdirectory ~/notebooks for all my notebooks, so in my ```jupyterhub_config.py``` I have:
```c.LocalProcessSpawner.notebook_dir = '~/notebooks'```
(without that, default path to notebooks is the user's home directory).

After login to Jupyterhub, my base path for notebooks tree is ```/user/mike/tree``` (in fact, this is the subdirectory ```notebooks``` in my home directory.  My course is `sps_martin`, the base path for this course is  ```/user/mike/tree/sps_martin```. I have the assignment directory ```ps1```,  so the correct path to it should be  ```/user/mike/tree/sps_martin/source/ps1```.
In formgrader (Manage Assignments) I see

```/user/mike/tree/notebooks/sps_martin/source/ps1```

which is incorrect (should not contain ```notebooks```) and results in ```Error 404 - Not found.```
Commandline nbgrader works OK (from the course root directory), but I like to show nbgrader to another teachers, not accustomed to commandline, they probably would like formgrader ...

**Comment by jhamrick** [comment]
I can confirm this bug. My guess is the issue is due to this line: https://github.com/jupyter/nbgrader/blob/master/nbgrader/server_extensions/formgrader/formgrader.py#L36 though I need to investigate a bit further to know for sure.
