### ISSUE TITLE
Manual grading interface fails to load Mathjax (returns 404)

### ISSUE THREAD

**Issue by reckoner** [jupyter/nbgrader#856]
Returns 404  when navigating to manual-grading interface

`http://localhost:8888/static/components/MathJax/jax/output/HTML-CSS/fonts/TeX/fontdata.js?rev=2.6.0`

Does this mean I'm supposed to have MathJax installed locally?

**Comment by lgpage** [comment]
@reckoner you should not need to install MathJax separately.
What version of Notebook and nbgrader do you have installed?
Also, do you see a 404 page when navigating to the manual-grading interface or do you see the formgrader but get this 404 error for MathJax only?

**Comment by reckoner** [comment]
Here's the version:

   `nbgrader                  0.5.2                    py36_0    conda-forge`


![image](https://user-images.githubusercontent.com/173637/29229699-add0bfc0-7e94-11e7-9101-0f8ee1440337.png)

![image](https://user-images.githubusercontent.com/173637/29233773-b9cf6dcc-7ea7-11e7-8c99-de7077898a5a.png)

That's what I see. I get a complaint about not being able to load MathJaX as I mentioned earlier.

**Comment by jhamrick** [comment]
The particular error of `:8888/static/components/MathJax/jax/output/HTML-CSS/fonts/STIX/fontdata.js?rev=2.6.0 Failed to load resource: the server responded with a status of 404 (Not Found)` should be fine ( I see this error as well, and it doesn't seem to affect the display of MathJax`.

In terms of where to provide feedback, there should be comment regions below cells that were marked as "solution cells" when you created the assignment, that look like this:

![image](https://user-images.githubusercontent.com/83444/29234824-9a22c6e8-7eae-11e7-819d-dee1091e82b3.png)

From the screenshot you sent, it does not seem the first two cells are marked as solution or test cells. Are there other cells in the notebook that were marked as solution or test cells?

**Comment by reckoner** [comment]
OK. That helps with the MathJax issue. Let me close this ticket and open another one if I cannot get the grading cells resolved.

**Comment by cortner** [comment]
@jhamrick -- what you see is not proper MathJax formatting. It will not work correctly for complex equations. I'm desparately trying to figure this out but can't seem to find anything on this anywhere.
