### ISSUE TITLE
404 on Formgrader when course directory on a separate file system then nbgrader

### ISSUE THREAD

**Issue by rdpratti** [jupyter/nbgrader#859]
Installation : Windows standalone install (no JupyterHub).
                    Anaconda install on C:\Aanaconda3

Jupyter Config Notebook Directory: c.NotebookApp.notebook_dir = 'F:\\Jupyter\\Notebooks'
nbgrader Config Course Directory : c.CourseDirectory.root = 'F:\\Jupyter\\Notebooks\\courses\\CSC343'

jupyter brings up notebook directory without issue.
clicking on formgrader produces a 404 (attached)
![formgrader-404](https://user-images.githubusercontent.com/4406671/29127083-10066d0a-7cee-11e7-91d0-630e0928122e.JPG)

There is an error message on the server screen that I have attached.

When I changed both config files to C:, the problem goes away and formgrader comes up fine.

I apologize if this is a config problem on my part, but I can't find anything in the doc that jumps out at me (base_url?).
[nbgrader_server_emsg.txt](https://github.com/jupyter/nbgrader/files/1211768/nbgrader_server_emsg.txt)

rd

**Comment by jhamrick** [comment]
I *think* this will likely be fixed by #866 but I will double check.

**Comment by jhamrick** [comment]
Yep, #866 seems to fix it! 😄
