### ISSUE TITLE
For Markdown cells, allow double click or hover to show non-rendered source

### ISSUE THREAD

**Issue by suchow** [jupyter/nbgrader#86]
You can get the source through the context menu, but it would be nice to have a way to quickly toggle between the rendering and the source – it helps diagnose what errors were made.

**Comment by jhamrick** [comment]
I think this, along with #89, will be covered by #67. Unfortunately, that's probably a ways off, as it depends on the live notebook being able to load faster. I definitely don't want to reimplement all of the notebook interface in nbgrader independently of the notebook, so I think this will have to wait until we can do #67.
