### ISSUE TITLE
prevent formgrader access from students

### ISSUE THREAD

**Issue by randy3k** [jupyter/nbgrader#860]
I roughly searched over the issues, but not sure if it has been asked before.

I am running a Jupyterhub server and using nbgrader 0.5.2. Currently, the formgrader tab is shown in a student view:
<img width="695" alt="screen shot 2017-08-10 at 1 01 09 am" src="https://user-images.githubusercontent.com/1690993/29155123-c8a15d74-7d67-11e7-8318-88973bde39cc.png">

I wonder if it is my setup issues or anything else, but we should prevent students from accessing the formgrader (though they don't have the access of the gradebook database).

**Comment by randy3k** [comment]
sorry for the noise, found it: http://nbgrader.readthedocs.io/en/stable/user_guide/installation.html#disabling-extensions

**Comment by jhamrick** [comment]
Glad you were able to figure it out!
