### ISSUE TITLE
Release and Collect Buttons don't show up if running with jupyterhub in docker container

### ISSUE THREAD

**Issue by tedeler** [jupyter/nbgrader#863]
Hi.
I'd like to put Jupyterhub with nbgrader into a docker container. Formgrader is installed and running. Nevertheless I'm not able to "Release" or "Collect" from the GUI. 

Might be a configuration problem. 

Kind regards,
Torsten

**Steps to reproduce:**
Clone https://github.com/tedeler/jupyterhub_with_nbgrader
Type "make" on commandline

Go to "localhost:8000"
Login as "john" with no password
Go to Tab "Formgrader"
Add Assignment
Fill with at least one Document
Generate

**Expected behavior:**
Buttons for "Release" and "Collect" should appear

**Observed behavior:**
Buttons do not show up

**Comment by tedeler** [comment]
Hi.

I found the solution by myself. As stated in the documentation I had to set Exchange.course_id in the nbgrader_config.py.

Now the buttons appear.

regards,
Torsten

**Comment by jhamrick** [comment]
Great! I was just about to suggest that. I have also made a PR which will tell people if they need to do this, so hopefully it should be easier to fix in the future: #865
