### ISSUE TITLE
Match horizontal position of answer key and student's answers

### ISSUE THREAD

**Issue by suchow** [jupyter/nbgrader#87]
Alignment cuts down on eye movements and speeds grading.
![screenshot 2015-02-17 20 12 19](https://cloud.githubusercontent.com/assets/613981/6242316/521f126c-b6e1-11e4-8f50-040b202f3eb5.jpg)

**Comment by jhamrick** [comment]
I don't think there is much we can do about this, because this is how markdown gets rendered by default. This is kind of specific to this notebook in particular, so I'm not sure it's appropriate to fix this in nbgrader itself (the fix would probably be something like, make images left-aligned).
