### ISSUE TITLE
Make tabbing after final comment cell focus on "Next →"

### ISSUE THREAD

**Issue by suchow** [jupyter/nbgrader#88]
(I hope these aren't nitpicking. This is a pretty awesome system and the tweaks would make it even better.)

**Comment by jhamrick** [comment]
I tried to do this, but couldn't get it to work for some reason. I'll have another look at it and try to figure it out.

**Comment by jhamrick** [comment]
Also, nope, these aren't nitpicky! This is all great feedback to have -- keep 'em coming :smile:
