### ISSUE TITLE
Using nbgrader and jupyterhub for multiple classes

### ISSUE THREAD

**Issue by kthyng** [jupyter/nbgrader#881]
I am under the impression that I need to edit the jupyterhub_config.py file in order to use nbgrader in multiple classes at once. I can't figure out how to do this. I see wordage in the jupyterhub_config.py itself, like:

List of service specification dictionaries.
  
  A service
  
  For instance::
  
      services = [
          {
              'name': 'cull_idle',
              'command': ['/path/to/cull_idle_servers.py'],
          },
          {
              'name': 'formgrader',
              'url': 'http://127.0.0.1:1234',
              'token': 'super-secret',
              'environment': 
          }
      ]

but my attempts to use the formgrader example have not worked out. 

Does anyone have an example for how to set this up for multiple courses? I'll ping @minrk since from what I've seen you are the one who might know how to do this. Thanks very much.

**Comment by yao2001626** [comment]
Edit this file:`~/.jupyter/nbgrader_config.py` 
add the following lines
```
c = get_config()
c.CourseDirectory.root = 'path/to/course/files'
```

**Comment by kthyng** [comment]
Ah, thank you for that. I wasn't clear when I wrote this. I got that part done, but I need to be able to use formgrader for both classes too. Jess has said that to do this I need to run multiple instances of the formgrader (via multiple single user server services). This part I cannot figure out.

**Comment by yao2001626** [comment]
If you need multiple courses, why don't you create a different user account for each course. 
For example, 
User one creates the first course and the user two creates the second course. Then, modify the .jupyter/nbgrader_config.py to link to the courses, respectively.

As far as I know, jupyterhub service can be used for multiple graders for one course, rather than one grader to multiple courses.

**Comment by kthyng** [comment]
That is a good point. Ok, that is what I have done. New user account on the system which controls the second class. This is a reasonable workaround for now.

**Comment by dsblank** [comment]
Interesting workaround. I copy and paste boilerplate text between classes, so this would not be very convenient for me. If there was a "reload nbgrader_config.py files" refresh button that also regenerated the GUI, that would solve this issue, too. (Especially if you could change c.CourseDirectory.root from formgrader too).

**Comment by jhamrick** [comment]
[Catching up on issues and PRs as I've been away for the last two months]

Apologies that it is so confusing getting multiple classes to work---I will try to write up some more comprehensive documentation on the various ways that people might want to use the formgrader (without JupyterHub, different root directories, with JupyterHub, multiple classes, etc.)

**Comment by sigurdurb** [comment]
@jhamrick : is there a way for two people to be in two to more classes without seeing every class in the Assignments tab. This would have to include setting the course_id variable in nbgrader_config.py as a list or what might be better idk, to have it both as a int and list and then just have the Assignments tab show the courses from the list if it is a list. Then other people who already deployed nbgrader would not have to upgrade everything to a list.
