### ISSUE TITLE
Release 0.6.0 or a patch release 0.5.4

### ISSUE THREAD

**Issue by mlmcitdesk** [jupyter/nbgrader#885]
@jhamrick Please update the conda-forge nbgrader to have latest 0.6.0 fixes. Thanks

**Comment by lgpage** [comment]
@mlmcitdesk unfortunately you will have to be patient for the next release.
In the mean time if you need the latest version of `nbgrader` you can install the master version using pip:
```bash
pip install git+https://github.com/jupyter/nbgrader
```
And follow the install instructions in the documentation for installing and enabling the extensions (http://nbgrader.readthedocs.io/en/stable/user_guide/installation.html)

**Comment by jhamrick** [comment]
0.6.0 won't be released until the semester is over, but it might be possible to make another patch release.

**Comment by jhamrick** [comment]
Closed by #896
