### ISSUE TITLE
Directory issue in "Validate" if notebook_dir is not home directory

### ISSUE THREAD

**Issue by misolietavec** [jupyter/nbgrader#891]
### Operating system
Debian/stretch
### `nbgrader --version`
0.6.0.dev0 (github version with PR #880 merged)
### `jupyterhub --version` (used with JupyterHub)
0.8.0b5 
### Notebook version info
5.1.0
### Expected behavior
Successful or unsuccesful validation of notebook instead of error message
### Actual behavior
Teachers and students have notebooks not in home directory, but in $HOME/notebooks. This is specified in jupyterhub config file as:
`c.Spawner.notebook_dir = '~/notebooks'`  (we use LocalProcessSpawner).
For example, as a teacher (mike) I have this course root directory:
`/home/mike/notebooks/uvp17_mike` and the assignment subdirectory `mojtest` with notebook `Zadanie.ipynb` which I like to validate. Opening this notebook in jupyterhub ad trying "Validate" button results in error message.  This is what I get as part of traceback:
`File "/usr/local/lib/python3.5/dist-packages/nbgrader/utils.py", line 234, in chdir
    os.chdir(dirname)
FileNotFoundError: [Errno 2] No such file or directory: 'uvp17_mike/source/mojtest'`

I can confirm that after copying course files to home directory, the validation is successful.
So this issue can be related to #855 which @jhamrick fixed by PR #866 (`Set nbgrader url prefix to be relative to notebook_dir`).  Before formgrader, the `nbgrader` commands for generating, releasing, validating and collecting assignments were  executed in the course root directory, so those problems with paths were hidden. Now it is necessary for all the formgrader-related activities  to be aware of the change from PR #866. I suspect, this is not the curent situation, which can give raise to many path-related issues.   

### Steps to reproduce the behavior
Try `nbgrader quickstart` to generate course in a subdirectory of home directory (e.g. `$HOME/notebooks`) using jupyterhub configured with that subdirectory as `notebook_dir`. After that, try to validate test notebook in `ps1` assignment directory by `Validate` button.

**Comment by lgpage** [comment]
>  Now it is necessary for all the formgrader-related activities to be aware of the change from PR #866.

Let me first say that I have only just started messing around with JupyterHub, but from my understanding all formgrader-related activities need to be aware of the path to the course root directory. When [using formgrader with Jupyterhub](http://nbgrader.readthedocs.io/en/stable/configuration/jupyterhub_config.html) the path to the course root directory is set in the `~/.jupyter/nbgrader_config.py` file of the user that runs Jupyterhub, for example:
```python
c = get_config()
c.CourseDirectory.root = '/home/mike/notebooks/uvp17_mike'
```

**Comment by misolietavec** [comment]
@lgpage  Yes, my `nbgrader_config.py` is in `~/.jupyter` and has exactly the content you mentioned (with one more line for `c.Exchange.course_id` added).
 
I think, @jhamrick can have some ideas about the cause of this issue. I am only nbgrader user, reporting issues I really met in my practice.

**Comment by randy3k** [comment]
Changing this [line](https://github.com/jupyter/nbgrader/blob/cc8a93847e704cf2057dc9c890a9b2f4cce8c5d7/nbgrader/server_extensions/validate_assignment/handlers.py#L44)
to
```
            notebook_dir = self.session_manager.parent.notebook_dir
            result = validator.validate(os.path.join(notebook_dir, path))
```

should fix the issue. I guess...

**Comment by misolietavec** [comment]
@randy3k: This change fixed the issue for me. Thanks, maybe you can now make PR? With some explanation, how you come to the above idea about getting notebook_dir :-)

**Comment by randy3k** [comment]
I don't actually know if it is the recommended way to get notebook directory, but it works. @lgpage or @jhamrick should know better.

**Comment by jhamrick** [comment]
[Catching up on issues and PRs as I've been away for the last two months]

Great, thanks for reporting @misolietavec and thanks for figuring out the fix, @randy3k ! Hopefully there aren't too many more of these edge cases...

I am not totally sure if getting the notebook directory in that way is the best way to do it; looks like it will involve probably some code diving into the notebook code... but I'll investigate further and see what I can find.
