### ISSUE TITLE
Feedback from formgrader interface

### ISSUE THREAD

**Issue by 51cde5bd8c** [jupyter/nbgrader#903]
nbgrader has [feedback](https://nbgrader.readthedocs.io/en/stable/user_guide/creating_and_grading_assignments.html#feedback-on-assignments) mechanism which only work from terminal. It would be great to have feedback available from formgrader.

**Comment by jhamrick** [comment]
Thanks for opening this issue! We're already tracking this though in #795 so I am going to close this as a duplicate.
