### ISSUE TITLE
Deprecate or better document db_students and db_assignments

### ISSUE THREAD

**Issue by bbhopesh** [jupyter/nbgrader#904]
### Operating system
Fedora 26
### `nbgrader --version`
Python version 3.6.2 |Anaconda, Inc.| (default, Oct  4 2017, 19:36:51) 
[GCC 7.2.0]
nbgrader version 0.5.3
### `jupyter notebook --version` 
5.0.0
### Issue
I assume that once I start Jupyter notebook and it loads `nbgrader_config.py`, it will make appropriate changes to database as specified in the configuration file. It is reading some of the things from config file like the exchange directory but not updating students list. `nbgrader db student list` returns 0 students. My config file is generated by `nbgrader quickstart` and has the default list of students.

Do I have to do something more to add the students from the config file?

## Relevant part of config file.
```python
# Change the students in this list with that actual students in
# your course
c.CourseDirectory.db_students = [ 
    dict(id="bitdiddle", first_name="Ben", last_name="Bitdiddle"),
    dict(id="hacker", first_name="Alyssa", last_name="Hacker"),
    dict(id="reasoner", first_name="Louis", last_name="Reasoner")
]
```

**Comment by bbhopesh** [comment]
@jhamrick I am not sure if you'd get notified without the mention :)

Thanks in advance.

**Comment by jhamrick** [comment]
Yes, nbgrader will only add the students from `db_students` when `nbgrader autograde` is run---if you want to add students before then, I recommend doing so through the formgrader interface or by using `nbgrader db student add`.

I agree this is counterintuitive, and wonder if we should really just deprecate `db_students` and `db_assignments`. At the very least, it should be documented better that these values won't be imported into the database until `nbgrader assign` (for `db_assignments`) and `nbgrader autograde` (for `db_students`) are run.

**Comment by bbhopesh** [comment]
Thank you :)

**Comment by b-stone** [comment]
I was also confused by this, glad to know it is being worked on.
