### ISSUE TITLE
Autofill non-reponse feedback.

### ISSUE THREAD

**Issue by suchow** [jupyter/nbgrader#91]
It might be nice to automatically fill in some standard text as feedback for when a student's response is blank, e.g., ("No credit assigned because you did not provide a response.")

**Comment by jhamrick** [comment]
Yeah, this would be nice to have. Though, sometimes students do edit the cells -- e.g. I saw one student who removed the "raise  NotImplementedError" but didn't replace it with anything. Edge cases like that would be a lot harder to detect, I think.
