### ISSUE TITLE
nbgrader autograde raising KeyboardInterrupt

### ISSUE THREAD

**Issue by chapmanbe** [jupyter/nbgrader#915]
### Expected behavior
I have an autograded notebook where the students have written a simulation of a patient population. The students create a patient class and then instantiates a list of patient objects and follows them until they are all deceased. The resulting data are then analyzed. This works fine with the students run the notebooks on their own.
 
### Actual behavior
When running nbgrader autograde the simulation step always raises a KeyboardInterrupt exception, which I assume is occurring because of some sort of timeout with the kernel.

I'm wondering if there is a way to specify the timeout time. 

### Steps to reproduce the behavior

KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-51-336584b9564f> in <module>()
      6     if not living:
      7         break
----> 8     increment_study(living, mortality)
      9

**Comment by jhamrick** [comment]
Yes, you should be able to configure this using the `c.ExecutePreprocessor.timeout` config option (see http://nbgrader.readthedocs.io/en/stable/configuration/config_options.html ). It looks like the default is 30 seconds, which might be a bit slower than you want.

Let me know if that doesn't actually solve the problem!

**Comment by jhamrick** [comment]
@chapmanbe I am going to close this issue as there hasn't been any activity on it for a while, but if you still need any help please feel free to open a new issue!
