### ISSUE TITLE
Student nbgrader install question

### ISSUE THREAD

**Issue by rdpratti** [jupyter/nbgrader#918]
I will be using nbgrader in stand-alone mode without JupyterHub.
My notebooks include autograded cells with both visible and hidden tests.
I want the students to be able to use validate to check their answers against the visible tests.
Freq asked questions mentions that a student's install should include validate.
Is that as simple as executing 'jupyter nbextension install --sys-prefix --py validate'?

Are there no other install steps I need to complete to make this work?

Thanks

rd

**Comment by rdpratti** [comment]
I think I found my answer reading the doc closer.

Basic install talks about install all of nbgrader and then disabling modules not wanted.
I will try that. But there is also a 2015 problem ticket that talks about different versions of nbgrader validation for instructor vs student. I am not sure if this was ever implemented.

**Comment by lgpage** [comment]
@rdpratti did you come right with this? Can you link to the other issue you mention above?

**Comment by jhamrick** [comment]
I am going to close this issue as there hasn't been any activity on it in several months, but feel free to comment here or open a new issue if there are any further questions!
