### ISSUE TITLE
Assignment List extension w/o JupyterHub

### ISSUE THREAD

**Issue by gtolomei** [jupyter/nbgrader#922]
Hi everyone,

I have successfully installed nbgrader version 0.5.4 on mac OS High Sierra (version 10.13.2) in combination with jupyter notebook 5.2.2 using conda 4.4.7.
AFAIK, all nbgrader and server extensions are fully installed and enabled when nbgrader is installed using conda. This is indeed my case, and I can easily verify it by typing the following command:

> jupyter nbextension list
> jupyter serverextension list

Now, the thing is that I won't be using nbgrader in combination with JupyterHub; in fact, I'm gonna distribute assignments created with nbgrader **without** using the <code>nbgrader release</code> command yet using my institution's internal learning management system (i.e., Moodle), according to what is described in the [user documentation](http://nbgrader.readthedocs.io/en/stable/user_guide/managing_assignment_files_manually.html).

Because of that, I haven't setup any exchange directory at all; in particular, I didn't create any <code>/srv/nbgrader/exchange</code> directory on my local filesystem (assuming to keep the default setting for that). Of course, when I click on the _Assignments_ tab on my Jupyter Notebook dashboard I get the following error message (please, see the image attached below), which basically complains about the fact that the (default) exchange directory above cannot be found.

<img width="1164" alt="screen shot 2018-01-19 at 2 43 11 pm" src="https://user-images.githubusercontent.com/9001735/35153799-44fbc6d0-fd28-11e7-8557-e92f3025851a.png">

Thus, my question is: even though I won't be using any exchange directory to distribute my assignments, should I anyway create that directory in my local filesystem **or** should I instead disable the assignment list extension? If the latter, am I still guaranteed everything keeps working given that - here I'm quoting from user documentation - "_To work properly, the assignment list, formgrader, and validate extensions require both the nbextension and serverextension_"?

Any help will be much appreciated.

Thanks,
G.

**Comment by jhamrick** [comment]
Hi Gabriele,

The assignment list extension is only for when you are
distributing/collecting assignments from your students using nbgrader, so
in your case you wouldn't want to use it. The best option here would be to
disable the assignment list extension.

> If the latter, am I still guaranteed everything keeps working given that
- here I'm quoting from user documentation - "*To work properly, the
assignment list, formgrader, and validate extensions require both the
nbextension and serverextension*"?

Yes, everything will still work correctly. The wording of the documentation
is perhaps a bit confusing---what it means is that each of the assignment
list, formgrader, and validate extensions have two parts to them: a
nbextension and a serverextension. So to make sure each of the assignment
list/formgrader/validate extensions work, you have to make sure both the
corresponding nbextension and serverextension are enabled (so there are 6
separate pieces you could enable/disable total). If you want to disable an
extension (for example the assignment list extension) you should disable
both the nbextension and serverextension parts for it.

Hope that helps to clear things up!

Cheers,
Jess

**Comment by gtolomei** [comment]
Hi Jess,

Thanks for your reply.
Now everything is indeed much clearer!

Cheers,
G.

P.S.: Thanks for the effort you've been putting through this; nbgrader is such a great piece of tool!
