### ISSUE TITLE
Validation fails - possible timeout issue

### ISSUE THREAD

**Issue by t-davidson** [jupyter/nbgrader#923]
### Operating system
Mac 10.11.6

### `nbgrader --version`
0.5.4

### `jupyter notebook --version` 
5.30

### Expected behavior
I am trying to run a notebook which requires loading text data and running code to process it. Overall it takes around 2 minutes to run on my machine. It works fine when I run all the cells in the notebook and the grading also works. I therefore expect it to validate.

### Actual behavior
Validation fails.  I get an eror message, reproduced below.

```
(test-env) Tom$ nbgrader validate source/A0/*.ipynb
[ValidateApp | INFO] Validating 'PATH_TO_NOTEBOOK/source/A0/a0notebook.ipynb'
[ValidateApp | INFO] Executing notebook with kernel: python3
[ValidateApp | ERROR] Timeout waiting for execute reply (30s).
[ValidateApp | ERROR] Interrupting kernel
```
When I run this in the notebook I get the same error, along with the message that tests have failed. I have tried editing `nbgrader_config.py` to suppress any timeouts but to no avail.

Does anyone know why a notebook that otherwise runs fine would be failing the validation step?

**Comment by lgpage** [comment]
Can you try changing the `c.ExecutePreprocessor.timeout` config option (see http://nbgrader.readthedocs.io/en/stable/configuration/config_options.html). It looks like the default is 30 seconds, which might be a bit slower than you want.

**Comment by jhamrick** [comment]
It might be worth adding another entry to the FAQ about this sort of question, as it is asked relatively frequently. The answer is implied [here](http://nbgrader.readthedocs.io/en/stable/user_guide/faq.html#does-nbgrader-protect-against-infinite-loops) but it's not really explictly addressing the issue of the timeout not being long enough.

**Comment by t-davidson** [comment]
Thanks for getting back to me about this. I did experiment with changing the timeout parameters, I set the configuration about to `None`. I was still unable to fix the issue. I went back just now and tried to validate the notebook and it worked, so I cannot reproduce the issue. I have not experienced the same problem with other assignments so perhaps it was simply a problem with my configuration.

One thing it might be worth to note in the FAQ is to encourage users to modify the timeout if the assignments involve large datasets or complex datasets that must be loaded or manipulated. The course I'm helping to teach involves loading and parsing text data, which can make autograding quite slow and can possibly cause these timeouts, particularly if students have inefficient solutions.

**Comment by ocanevet** [comment]
I cannot make the `c.ExecutePreprocessor.timeout` work. My `/home/jovyan/.jupyter/nbgrader_config.py` contains

```
c = get_config()
c.CourseDirectory.course_id = "maths"
c.ExecutePreprocessor.timeout = -1
```

and running the following cell:

```python
x = 3
for i in range(45):
    print(i)
    time.sleep(1)
# Set x = 10
### BEGIN SOLUTION
x = 10
### END SOLUTION
```

followed by a test:

```python
assert x == 10, f"should be 10 and i is {i}"
```

produce the following validation output

```
The following cell failed:

assert x == 10, f"should be 10 and i is {i}"
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-5-d2ec54bfcf63> in <module>
----> 1 assert x == 10, f"should be 10 and i is {i}"

AssertionError: should be 10 and i is 29
```

showing that my timeout it still 30 seconds. Could you help? Thanks.

**Comment by MC-program** [comment]
Dear all,

I experience the same problem. The last statement was that the timeout cannot be set, which I do observe as well.
Can anyone help? Any news on this issue? :)
Thanks for any hints!
MCP

I use nbgrader in a setup with Docker images for the hub and notebooks in a Kubernetes cloud.
nbgrader --version
Python version 3.9.7 | packaged by conda-forge | (default, Sep 23 2021, 07:28:37)
[GCC 9.4.0]
nbgrader version 0.6.2

In the jupyterhub web interface, I go to the Courses tab, from where the formgrader is started
Available formgraders -> lecture jupyterhub (click)
It opens the formgrader / nbgrader from jupyterurl/services/lecture/formgrader
I click on an assignment, in jupyterurl/services/lecture/tree/lecture/source/assignment1 I start a “Terminal”.
In the terminal, I just say
nbgrader validate ~/lecture/source/task_3/exercise_1.ipynb

A timeout as below occurs in about 30 secs in total, even I try to set all timeout variables in nbgrader_config.py, and the file is read in by the command. The timeout variables are
c.ExecutePreprocessor.timeout = 300
c.ExecutePreprocessor.iopub_timeout=300
c.ExecutePreprocessor.iopub_timeoutInt=300
c.ExecutePreprocessor.shell_timeout_interval=60   # default 5
c.ExecutePreprocessor.startup_timeout = 300  #default 60

No matter these variables, the error message is

Wait for pending objects to be closed.............[ValidateApp | ERROR] Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 589, inrun_cell
        msg = self.kc.iopub_channel.get_msg(timeout=timeout)
      File "/opt/conda/lib/python3.9/site-packages/jupyter_client/blocking/channels.py", line 54, inget_msg
        raise Empty
    _queue.Empty

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/nbgrader/apps/validateapp.py", line 72, in start
        validator.validate_and_print(filename)
      File "/opt/conda/lib/python3.9/site-packages/nbgrader/validator.py", line 340, in validate_and_print
        results = self.validate(filename)
      File "/opt/conda/lib/python3.9/site-packages/nbgrader/validator.py", line 311, in validate
        nb = self._preprocess(nb)
      File "/opt/conda/lib/python3.9/site-packages/nbgrader/validator.py", line 290, in _preprocess
        nb, resources = pp.preprocess(nb, resources)
      File "/opt/conda/lib/python3.9/site-packages/nbgrader/preprocessors/execute.py", line 41, in preprocess
        output = super(Execute, self).preprocess(nb, resources)
      File "/opt/conda/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 405, inpreprocess
        nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
      File "/opt/conda/lib/python3.9/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
        nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
      File "/opt/conda/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 438, inpreprocess_cell
        reply, outputs = self.run_cell(cell, cell_index, store_history)
      File "/opt/conda/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 597, inrun_cell
        raise TimeoutError("Timeout waiting for IOPub output")
    TimeoutError: Timeout waiting for IOPub output

[ValidateApp | ERROR] nbgrader encountered a fatal error while trying to validate '/home/formgrader/lecture/source/task_3/exercise_1.ipynb'

**Comment by ocanevet** [comment]
Hi, to circumvent that (I still cannot setup the time limit properly in the config file), I autograde in the terminal with the following command:

```
nbgrader autograde "name-of-lab" -f --ExecutePreprocessor.timeout=-1
```

or for a specific student:

```
nbgrader autograde "name-of-lab" -f --ExecutePreprocessor.timeout=-1 --student "username"
```

I also ask the student not to click on "Validate" before submitting.

**Comment by MC-program** [comment]
Thank you! This would be a workaround. But does not work. 
--ExecutePreprocessor.timeout=-1 does not alternate anything I can observe.
-f is not recognized, btw.
