### ISSUE TITLE
Entering space infront of assignment name unfetchable

### ISSUE THREAD

**Issue by sigurdurb** [jupyter/nbgrader#924]
* Ubuntu 16.04
* jupyterhub --version 0.8.1
* jupyter --version 4.4.0
* nbgrader version 0.6.0.dev (Also referred to as Formgrader)

Replicate:
Create an assignment with a name with space in front, like: " V1-T1"
Generate and release works as expected and all the foldernames have "\ " in the foldernames infront(like in the source/ and srv/nbgrader/exchange/) but the Formgrader does not show the space in front.
Then when a student tries to Fetch the assignment basicly nothing happens, not even a log window with an error.

The TA that made this assignment did not realize that he made this error when writing the assignment name in the dialog. But the nbgrader database had the assignment name with the space in front but the list in the Formgrader did not show the space.

Possible solution / easy fix:
This could be fixed just by using pythons strip() when validating the string when the user makes the assignment because probably no one wants to have a space there anyways.

**Comment by jhamrick** [comment]
Ooh, yeah, that's annoying---thanks for tracking this down!

For reference, you can work around this on the command line if you explicitly provide the name in quotes, e.g. `nbgrader fetch " V1-T1"`. But I can confirm this is also an issue when trying to fetch using the Assignment List extension. So there are really two bugs here it seems---the assignment list extension should use the correct assignment id regardless of spaces, but there is also a UI bug in that this sort of thing should be prevented in the first place.

**Comment by jhamrick** [comment]
So I tracked the issue in assignment list down to the fact that tornado's `get_argument` function strips whitespace by default: http://www.tornadoweb.org/en/stable/web.html#tornado.web.RequestHandler.get_argument

Rather than modifying all the places where this is used to have strip=False, I am just going to have nbgrader by default strip whitespace from assignment ids (and course ids).
