### ISSUE TITLE
problem with nbgrader and docker

### ISSUE THREAD

**Issue by sam0hack** [jupyter/nbgrader#925]
Hi there,

First, I want to thank you for building the nbgrader tool. @jhamrick @minrk 

I'm using root account on my main system. and jupyterhub server working fine I also installed nbgrader
So my question is: Suppose i have two accounts  teacher1 and  studentone. How can studentone submit an assignment to teacher1? I'm also using Docker as you can see in my config by using docker every user is completely separated from each other 
even all accounts after login in jupyterhub become jovyan  

MySetup config
Jupyterhub 0.8.1
jupyterhub_config.py 

```
# - Use SSL
c.JupyterHub.ssl_key = '/etc/letsencrypt/live/mydomain/privkey.pem'
c.JupyterHub.ssl_cert = '/etc/letsencrypt/live/mydomain/fullchain.pem'
c.Jupyterhub.port =443

#Set Users allowed to use hub
c.Authenticator.whitelist = ({'sam0hack','studentone','teacher1','grwheeler'})

#set of users who can administer the Hub itself
c.Authenticator.admin_users = {'sam0hack','grwheeler'}

from dockerspawner import DockerSpawner

c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'

c.DockerSpawner.container_image = 'jupyterhub/singleuser:0.8'

#The Hub API listen on localhost by default
#but docker containers can't see that
#Tell the Hub to listen on its docker network
import netifaces
docker0 = netifaces.ifaddresses('docker0')
docker0_ipv4 = docker0[netifaces.AF_INET][0]
c.JupyterHub.hub_ip = docker0_ipv4['addr']      

```

nbgrader_config.py
```
c = get_config()

c.Exchange.course_id = "example_course"
c.Exchange.root = "/tmp/exchange"
```

**Comment by sam0hack** [comment]
I've solved the issue by adding  `DockerSpawner.volumes`

**Comment by jhamrick** [comment]
Glad you were able to figure it out!
