### ISSUE TITLE
Assignment names with a '+' character break autograding

### ISSUE THREAD

**Issue by amellinger** [jupyter/nbgrader#928]
I (perhaps foolishly) created an assignment with a '+' character in its name (the web interface did not complain). Now nbgrader will not autograde submitted assignments. From the log file, I gather that the + character is used as a separator between student id and assignment name.

Does anyone know of a workaround that lets me autograde assignments that have already been submitted?

Regards,
Axel

### Operating system
Kubuntu Linux 16.04.3 LTS

### `nbgrader --version`
Python version 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
nbgrader version 0.5.4

### `jupyterhub --version` (if used with JupyterHub)
0.8.1

### `jupyter notebook --version` 
5.4.0

### Expected behavior
`nbgrader autograde PHY332-08-Charge+Plate_Free_Fall`should autograde submitted assignments

### Actual behavior
Autograding fails; .nbgrader.log says

```
[AutogradeApp | INFO] Copying /home/axel/PHY332/submitted/doe1j+PHY332-08-Charge/PHY332-08-Charge+Plate_Free_Fall/timestamp.txt -> /home/axel/PHY332/autograded/doe1j+PHY332-08-Charge/PHY332-08-Charge+Plate_Free_Fall/timestamp.txt
[AutogradeApp | INFO] Copying /home/axel/PHY332/submitted/doe1j+PHY332-08-Charge/PHY332-08-Charge+Plate_Free_Fall/image_charge.png -> /home/axel/PHY332/autograded/doe1j+PHY332-08-Charge/PHY332-08-Charge+Plate_Free_Fall/image_charge.png
[AutogradeApp | ERROR] No student with ID 'doe1j+PHY332-08-Charge' exists in the database
[AutogradeApp | ERROR] There was an error processing assignment: /home/axel/PHY332/submitted/doe1j+PHY332-08-Charge/PHY332-08-Charge+Plate_Free_Fall
[AutogradeApp | ERROR] Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/nbgrader/api.py", line 1122, in find_student
        .filter(Student.id == student_id)\
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2843, in one
        raise orm_exc.NoResultFound("No row was found for one()")
    sqlalchemy.orm.exc.NoResultFound: No row was found for one()
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/nbgrader/converters/autograde.py", line 78, in init_assignment
        gb.find_student(student_id)
      File "/usr/local/lib/python3.5/dist-packages/nbgrader/api.py", line 1125, in find_student
        raise MissingEntry("No such student: {}".format(student_id))
    nbgrader.api.MissingEntry: No such student: doe1j+PHY332-08-Charge
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/nbgrader/converters/base.py", line 289, in convert_notebooks
        self.init_assignment(gd['assignment_id'], gd['student_id'])
      File "/usr/local/lib/python3.5/dist-packages/nbgrader/converters/autograde.py", line 82, in init_assignment
        raise NbGraderException(msg)
    nbgrader.converters.base.NbGraderException: No student with ID 'doe1j+PHY332-08-Charge' exists in the database



```

### Steps to reproduce the behavior
1. Create assignment with `+` in its name, e.g. `PHY332-08-Charge+Plate_Free_Fall`
2. Collect submitted assignments using `nbgrader collect PHY332-08-Charge+Plate_Free_Fall --update`
3. Attempt to autograde with `nbgrader autograde PHY332-08-Charge+Plate_Free_Fall`

**Comment by jhamrick** [comment]
Yeah, probably we should disallow `+` symbols from being in assignment names going forward.

In your case as a work around, you should be able to rename the folders in the `submitted` directory which I think should fix the problem. Here is a little script that should do what you want:

```
import os
import shutil
for filename in os.listdir('submitted'):
    if '+' not in filename:
        continue
    student, _ = filename.split('+', 1)
    if not os.path.exists(os.path.join('submitted', student)):
        os.makedirs(os.path.join('submitted', student))
    for assignment in os.listdir(os.path.join('submitted', filename)):
        shutil.move(os.path.join('submitted', filename, assignment), os.path.join('submitted', student, assignment))
    os.removedirs(os.path.join('submitted', filename))
```

**Comment by jhamrick** [comment]
Also, it is probably a good idea just to back up your submitted folder before doing this just in case something goes wrong---but I think just doing the renaming like this should be sufficient to fix the problem!
