### ISSUE TITLE
Add instructions for increasing autograde timeout in the FAQ

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#931]
cf https://github.com/jupyter/nbgrader/issues/923#issuecomment-366457887

**Comment by jhamrick** [comment]
The solution for this issue is to add a note to the FAQ describing the error (that the kernel gets interrupted either during validation or during autograding), and then describing the solution, which is to put something like the following in `nbgrader_config.py`:

```
# increase timeout to 60 seconds
c.ExecutePreprocessor.timeout = 60
```

**Comment by mozebdi** [comment]
Making a fork and PR'ing this 😄
