### ISSUE TITLE
Manual grading failing for one of the instructors with 404

### ISSUE THREAD

**Issue by bbhopesh** [jupyter/nbgrader#939]
### `nbgrader --version`
0.5.4
### `jupyterhub --version` (if used with JupyterHub)
0.8.1
### `jupyter notebook --version` 
5.2.2

We are two instructors for a course and nbgrader home is shared directory between us. Both instructors are part of same linux group and we manage file permissions under nbgrader home at this group level. Everything works fine for us, we are both able to create/release/autograde assignments. However, manual grading is creating problems for one of us. When one of us try to manually grade an assignment, we get a 404 error while the same thing works for the other.

Here are two lines from the log of each of us
```
[I 2018-03-12 05:28:47.551 SingleUserNotebookApp log:122] 200 GET /jupyter/user/bbassi2/formgrader/submissions/0698f5bc29574c09b81ab50fee6dc46e/ (bbassi2@127.0.0.1) 682.25ms
```

```
[D 2018-03-08 00:37:27.196 SingleUserNotebookApp auth:729] Allowing whitelisted Hub user yiyunyc2
[W 2018-03-08 00:37:27.198 SingleUserNotebookApp web:1588] 404 GET /jupyter/user/yiyunyc2/formgrader/submissions/0698f5bc29574c09b81ab50fee6dc46e (127.0.0.1): Invalid submission: 0698f5bc29574c09b81ab50fee6dc46e
[D 2018-03-08 00:37:27.199 SingleUserNotebookApp handlers:231] Using contents: services/contents
[W 2018-03-08 00:37:27.201 SingleUserNotebookApp log:122] 404 GET /jupyter/user/yiyunyc2/formgrader/submissions/0698f5bc29574c09b81ab50fee6dc46e (yiyunyc2@127.0.0.1) 6.71ms
```

The second instructor is getting 404 while trying to access submitted notebook with id `0698f5bc29574c09b81ab50fee6dc46e` while it is succeeding for first instructor. 

I tried going through code and saw that this error is generated when submission is not found in database but submission is there. It's not that the second instructor is not able to access database as all other database operations are succeeding for her both from formgrader app and from command line using `nbgrader db` utility. It's just that manual grading is failing.

Can you please take a look at this? Thanks

**Comment by bbhopesh** [comment]
@jhamrick

**Comment by jhamrick** [comment]
Could you please post the `nbgrader_config.py` files for both instructors (the one who it works for and the one who it doesn't work for)?

**Comment by bbhopesh** [comment]
The nbgrader directory is shared between us, and this is the `nbgader_config.py` for both of us

```
c = get_config()

import os

c.Exchange.course_id = os.environ['COURSE_NAME']

c.IncludeHeaderFooter.header = "source/header.ipynb"

c.ClearSolutions.code_stub = {'python': ''}
```

To point to the directory which contains above `nbgrader_config.py`, we have another `nbgrader_config.py` in `/etc/jupyter`. This is also present for both of us.
```
c = get_config()
import os

# This file is copied to /etc/jupyter in the docker image.
# This file just needs to point jupyter to the right course directory. You can have one more config file in the course home directory with other configuration.
c.CourseDirectory.root = os.environ['COURSE_HOME_ON_CONTAINER']
```

**Comment by bbhopesh** [comment]
I should have tried this earlier but just restarting the jupyterhub fixed the issue.

**Comment by jhamrick** [comment]
Glad to hear it. Feel free to comment here again or open a new issue if you encounter the issue again!
