### ISSUE TITLE
Have submitted notebooks import from local directory

### ISSUE THREAD

**Issue by yangkky** [jupyter/nbgrader#940]
I had students edit a python file and then submit it along with the notebooks. However, when I run the autograder, nbgrader imports the python file from my source directory instead of the submitted one. This, of course, leads to the test cells that test their implementation always passing no matter what they do (and also makes it so that, if they added and rely on any further functionality that's not in my solution, then those blocks fail!). Is there any way to have the submitted notebooks import from the submitted .py file?

**Comment by jhamrick** [comment]
Another way to do this which would be slightly more flexible would be to allow you to specify in the config file a list of files per assignment that shouldn't be overwritten by the source version.
