### ISSUE TITLE
Changing the Exchange back-end?

### ISSUE THREAD

**Issue by perllaghu** [jupyter/nbgrader#944]
We are running a campus-wide Notebook service as multiple Docker containers across a swarm*.... with a VLE authentication client (aka an LTI "provider") front-ending jupyterhub .

Our next interest is implementing NBGrader in notebooks, however as we are running in a swarm the Exchange suite writing to local-filestore is problematic for us.

Rather than just fork NBGrader and hack our own code in, we'd like to create (and push back) a solution that is extensible and enables others to do similar things.

Do you have any conceptual plan for allowing alternative functionality for the `Exchange` code (similar to `ContentsManager` in Notebooks themselves: http://jupyter-notebook.readthedocs.io/en/latest/extending/contents.html)

Issues #530(ish) #659 #841 seem partially relevant

[*] Tip: Go Kubenetes rather than Docker Swarm.

**Comment by jhamrick** [comment]
Yes, this is definitely something that's planned and the most thorough discussion of it is in #659 (which I see you've commented on too---but I'm just leaving a note here about that in case others come along this issue too). Unfortunately there's not currently a timeline for getting this implemented but it's definitely something we're intending to do, hopefully soon.

I'm going to close this issue and write a comment on #659 with more thoughts just to keep the discussion in one place if that's alright!
