### ISSUE TITLE
Conducting an online exam using nbgrader

### ISSUE THREAD

**Issue by vinayakumarr** [jupyter/nbgrader#945]
We have 25 students. We have to conduct an online exam. For this, we are using an ipython notebook. Each user shouldn't be accessible to other user ipython notebook. we have ubuntu operating system. Could you please tell us how to install nbgrader in step by step procedure.

**Comment by jhamrick** [comment]
The best way to do this would be to run nbgrader with JupyterHub. I'd recommend having a look at the reference deployment for using JupyterHub with nbgrader here, which includes steps for getting everything installed and running: https://github.com/jupyterhub/jupyterhub-deploy-teaching

**Comment by jhamrick** [comment]
I'm going to close this since there hasn't been any activity on this issue in a while, but feel free to open a new issue if you have further questions.
