### ISSUE TITLE
Ability to show/toggle all student names in formgrader

### ISSUE THREAD

**Issue by janmaltel** [jupyter/nbgrader#951]
Follow up on:
https://github.com/jupyter/nbgrader/issues/575 
... which led to:
https://github.com/jupyter/nbgrader/pull/617

I would highly appreciate the possibility to **toggle the visibility of all student names--with one click**. We do grading anonymously and I think it's a good default.

However, when students want to discuss individual issues **after they've received their grades/feedback**, I currently have to toggle up to 200 submission names to find the formgrader version of their submission. 
Thanks for any suggestions!

**Comment by jhamrick** [comment]
This should be possible, though it requires going through a different route:

* Click "Manage Students" on the left navigation bar
* Click on name of the relevant student
* Click on the name of the relevant assignment
* Click on the name of the relevant notebook
* You should now be viewing their submitted notebook in the formgrader

Let me know if that doesn't answer your question!

**Comment by bogaaak** [comment]
Oh, that is great! Thank you very much for your answer. 

I still would advocate for a general toggle/option for anonymization. At our university, the student submissions we receive are already anonymized through the "Moodle" system. 

The "double-anonymization" makes things slower in cases where students submit, for example, supplementary .pdf files / figures or when somehow there is an issue with a notebook.

In any case, thanks again for the great work!

**Comment by jhamrick** [comment]
Sure, I think it's reasonable to have the anonymization be a config option.

**Comment by nthiery** [comment]
For the record: Jérémie Neveu from Paris Sud mentioned to me that the "toggle visibility of all student names with one click" would be helpful in his workflow.
