### ISSUE TITLE
Unexpected behaviour of utils.find_all_files

### ISSUE THREAD

**Issue by hcastilho** [jupyter/nbgrader#952]
### Operating system
Ubunto 16.04

### `nbgrader --version`
nbgrader version 0.5.4

### `jupyterhub --version` (if used with JupyterHub)
0.8.1

### `jupyter notebook --version` 
5.4.1

### Expected behavior
By including '.git' or '.git/**' in CourseDirectory.ignore anything under the git directory to be ignored.

### Actual behavior
Anything in subdirectories of '.git' is included.

### Steps to reproduce the behavior
$ mkdir -p foo/bar/qwe
$ touch foo/bar/qwe/file.py
$ /opt/conda/bin/python -c "from nbgrader.utils import find_all_files;print(find_all_files('foo', ['bar']))"
['foo/bar/qwe/file.py']

I'm sorry if this is expected behaviour but I found it surprising.

**Comment by jhamrick** [comment]
Thanks for catching this! This is indeed a bug; the logic in `find_all_files` isn't quite right. In fact, it does exclude files in directories that are passed into the exclude argument, but not *subdirectories*:

```
$ mkdir -p foo/bar
$ touch foo/bar/file.py
$ python -c "from nbgrader.utils import find_all_files;print(find_all_files('foo', ['bar']))"
```
