### ISSUE TITLE
Fix warning with timezones

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#956]
Somewhere in the tests the following warning is being raised:

```
  /home/jhamrick/miniconda3/lib/python3.6/site-packages/dateutil/parser/_parser.py:1165: UnknownTimezoneWarning: tzname PST identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this raise an exception.
    category=UnknownTimezoneWarning)
```

This should be addressed before it turns into an exception.

**Comment by davidnero** [comment]
Since codes like "PST" don't work, how are we to enter time zones?

What I'd really like is for it to be a global configuration option (defaulting to local timezone).

**Comment by fm75** [comment]
One problem with "PST" is that it is not local time during the summer.  I would suggest 'America/Los_Angeles' as the alternative. 

I just saw this issue tonight (JupyterCon 2018 starting tomorrow). From the `nbgrader` folder, "PST" shows up 77 times in 13 files (.rst and .py)

```bash
(jupyterlab) Fred-MacBookPro:nbgrader fred$ grep -r PST * | grep -v pyc | wc -l
      77
(jupyterlab) Fred-MacBookPro:nbgrader fred$ grep -lr PST * | grep -v pyc | wc -l
      13
```
Is this only a **testing** issue?

**Comment by jhamrick** [comment]
Mostly it occurs in tests, but also a few cases in the docs so those should be changed as well.
