### ISSUE TITLE
Extend nbgrader.db to cope with multiple courses (and think beyond that)

### ISSUE THREAD

**Issue by perllaghu** [jupyter/nbgrader#960]
The current `nbgrader.db` database has no concept of a course: each course has to have it's own database (configured in the config file)

In our environment, we have

- multiple instructors on a course, and 
- one instructor doing multiple courses

We also want to consider how to move to an external database (postgresql/mysql/etc).... but we are also very conscious that the notebook-servers themselves should *not* have access to create databases in our server (that could be horribly abused :chuckle: )

Our initial thought is to add a `courses` table, and link assignments to that

Keen to hear who else has been down this route, and what solutions have been tried.

**Comment by jhamrick** [comment]
>multiple instructors on a course

nbgrader does support multiple graders for a single course and there are two ways you would configure this depending on whether you're using JupyterHub or not:

1. Using JupyterHub: see http://nbgrader.readthedocs.io/en/master/configuration/jupyterhub_config.html#example-use-case-one-class-multiple-graders
2. Not using JupyterHub: you will still need access to a shared server, but then you can run the notebook on an open port (using password protection) and give all the graders the link to the notebook server, from which they can access the formgrader.

> one instructor doing multiple courses
> Our initial thought is to add a courses table, and link assignments to that

Can you describe your use case a bit further here? It is not immediately clear to me what the benefit of having a shared database would be... in particular, even if there was support for multiple classes within the same database, you would still need to have a separate course directory for each class (and a separate config file), and separate instances of the formgrader.

> We also want to consider how to move to an external database (postgresql/mysql/etc)

nbgrader does support postgres and likely mysql, so this shouldn't be a problem: http://nbgrader.readthedocs.io/en/master/user_guide/faq.html#do-i-have-to-use-sqlite-for-the-nbgrader-database

**Comment by perllaghu** [comment]
Our environment is an LTI connection into a JupyterHub instance (so we get the userID, Course, and Role from that, not pre-configured), with the Notebooks spawned into a cloud (currently Docker Swarm, hopefully kubenetes shortly)

Persistent storage is held centrally, and mounted over /home/joyvan

..... but that docs page is very useful.

**Comment by jhamrick** [comment]
Sorry, I think maybe I wasn't quite clear in my question: what do you see as being the benefit of having a shared database for all courses when you still need separate course directories and nbgrader_config.py files?

**Comment by jhamrick** [comment]
It sounds to me like this is something that would be better served by a JupyterHub service which knows how to talk to LTI, rather than adjustments to nbgrader. As I mentioned above, even if you created a shared database for the different courses, you would still need to manually configure the separate course directories and nbgrader_config.py files. So it sounds like what you want is actually a set of scripts on top of nbgrader that perhaps form a JupyterHub service which can do that synchronization for you. I am not really familiar with LTI though, so I could still be misunderstanding.

**Comment by perllaghu** [comment]
So what we're currently working on is thus:

- User "logs into jupyterhub": this is an OAuth connection from a Blackboard/Moodle/whatever service, using an LTI connection
- The OAuth connection supplies `username`, `course`, and `role` (plus some other stuff, not relevant here)
- We have a module that defines various `volumes` for the user, and asks jupyterhub to spawn a Notebook Server for the user
- Jupyterhub creates a session for them in it's database, sets a bunch of environment variables, and launches a notebook server

So there are some implications for this:

1. The users persistent storage is volume-mounted, and is the same irrespective of the course they happen to come in from
1. The volumes mounted may appear to be the same when seen from within the notebook servers (ie `/srv/nbgrader/exchange/inbound`), but can be mapped to different bits of filestore (ie `/var/data/nbgrader/informatics/course_abc/student_23/inbound`)
1. Whilst every username appears to be different, in practice very notebook [server] is running as the `joyvan` user

(LTI is awesome, but it needs that _eureka_ moment to wrap your head around it.....)

**Comment by jhamrick** [comment]
Closed by #1099
