### ISSUE TITLE
404 when accessing the formgrader

### ISSUE THREAD

**Issue by knagas** [jupyter/nbgrader#968]
After the installation of nbgrader,  I am not able to open formgrader. It shows 404 not found.

I did the step in thereaddocument.

**Comment by jhamrick** [comment]
Unfortunately, it's difficult for me to help debug as I don't have enough information to know what might be the problem. Can you please let me know:

1. What is the output of `jupyter troubleshoot`?
1. What is the output of `nbgrader --version`?
1. Exactly which commands you ran to install nbgrader?
1. What URL gives you the 404?
1. Any command line output when you try to access the formgrader?

The more information you can provide the more likely I'll be able to help!

**Comment by knagas** [comment]
I figured it out! Thanks! it was all about sys-prefix to user
