### ISSUE TITLE
Can't use formgrader for release and collect assignment.

### ISSUE THREAD

**Issue by s6007493** [jupyter/nbgrader#971]
### Operating system
Fedora 27 x64 (jupyterhub and nbgrader on docker)
### `nbgrader --version`
0.5.4
### `jupyterhub --version` (if used with JupyterHub)
0.9.0-dev
### `jupyter notebook --version` 
5.5.0
### Expected behavior
Formgrader should be able to release and collect assignment
### Actual behavior
I already set the course id in nbgrader_config.py but formgrader have an error message "The course id has not been set in nbgrader_config.py. The "release" and "collect" functionality will not be available. Please see the documentation on Setting Up The Exchange for instructions." and it cannot release and collect assignment
[nbgrader_config.txt](https://github.com/jupyter/nbgrader/files/2047664/nbgrader_config.txt)

**Comment by jhamrick** [comment]
@s6007493 Did you close this because you were able to figure out the issue?

**Comment by i02momuj** [comment]
I have the same error, I create a course in Jupyter, but it says to me that "The course id has not been set in nbgrader_config.py. The "release" and "collect" functionality will not be available.".

I have checked the nbgrader_config.py file but it has the course id, so I have no idea how to fix the problem.

I attach snapshots of the browser with the error, and the configuration file.
![browser](https://user-images.githubusercontent.com/9946198/43308572-4cfddd7a-9182-11e8-98a2-5075a145294b.JPG)
![console](https://user-images.githubusercontent.com/9946198/43308573-4d17b4f2-9182-11e8-8f99-19fa053571a9.JPG)




Thanks for all your time.

**Comment by isaurssaurav** [comment]
@i02momuj  ,
I had a same error while back. It just happens to be that `nbgrader_config.py` file should be in its destination (in your case `/home/curso5`) **before a user is spawned**.
So either you can place `nbgrader_config.py` file at _pre_spwan hook_ , or attached into singleuser's image file.

**Comment by billzhonggz** [comment]
> 
> 
> I have the same error, I create a course in Jupyter, but it says to me that "The course id has not been set in nbgrader_config.py. The "release" and "collect" functionality will not be available.".
> 
> I have checked the nbgrader_config.py file but it has the course id, so I have no idea how to fix the problem.
> 
> I attach snapshots of the browser with the error, and the configuration file.
> ![browser](https://user-images.githubusercontent.com/9946198/43308572-4cfddd7a-9182-11e8-98a2-5075a145294b.JPG)
> ![console](https://user-images.githubusercontent.com/9946198/43308573-4d17b4f2-9182-11e8-8f99-19fa053571a9.JPG)
> 
> Thanks for all your time.

I just solved this problem by following the official document [here](https://nbgrader.readthedocs.io/en/stable/configuration/jupyterhub_config.html). The instruction comes from the following text:

> Starting in version 0.5.0 of nbgrader, the formgrader is no longer a standalone command. Rather, it is an extension of the Jupyter notebook. This means that the formgrader will work out-of-the-box with JupyterHub if you only have a single grader for your class: all you need to do is make sure that you have installed and enabled the nbgrader extensions (see Installation) and then make sure the path to your course directory is properly set in `~/.jupyter/nbgrader_config.py`:
> ```python
> c = get_config()
> c.CourseDirectory.root = 'path/to/course/files'
> ```

You can try this. It work fine for me after I point the course path locates in my home directory, e.g. `/home/user_name/course_id`.

**Comment by i02momuj** [comment]
Thank you very much for your responses.

Finally, as I read in other thread of people with similar problems, it was a problem of permissions. I was able to solve it by adding permissions to the log file `.nbgrader.log` inside a course.

For example in my case, I was creating a linux user for each different course in nbgrader. So, let be `course` the name of the user and also the name of the given course. So, what I did was the following (inside the folder of the course):
```
chown -R course:course source
chown course:course .nbgrader.log
```

I hope it will help more people with this problem.

**Comment by mrios22** [comment]
Changing permissions on the course did not solve this problem for me.
NBgrader still does not think that I have any courses available, even though the path is set correctly in the configuration file.

**Comment by mrios22** [comment]
There is something slightly confusing here: the file ``nbgrader_config.py`` will appear in your course directory, but editing it there will not help. The file ``nbgrader_config.py`` has to be in the ``~/.jupyter`` directory of the user that is operating the server.

**Comment by jhamrick** [comment]
Yes, I agree the nbgrader_config.py file is a bit confusing. I actually just added some documentation on this which should hopefully help: https://nbgrader.readthedocs.io/en/master/configuration/nbgrader_config.html

**Comment by mrios22** [comment]
Wow, thanks! I'll take a look.
