### ISSUE TITLE
Move third_party.rst to new repo

### ISSUE THREAD

**Issue by dsblank** [jupyter/nbgrader#976]
I didn't know about this file in nbgrader's documentation:

```
nbgrader/nbgrader/docs/source/user_guide/third_party.rst
```

The page of links to resources is a great idea, but it is in the wrong place. These so-called "third party" links should be kept outside of nbgrader as many don't have much (or anything) to do with nbgrader.

Suggestions:

1. Create a new repo under the jupyter project called jupyter-in-education.
2. This could be a documentation-only repo
3. The existing page could be broken up into many subsections (extensions, cloud-based services, etc)
4. The term "third party" makes a distinction that is not that useful here (most jupyter-in-education resources don't come from the jupyter project itself)
5. link to this new repo from nbgrader

**Comment by jhamrick** [comment]
Yeah, I put it in the nbgrader repo for now so that it exists somewhere, but there's a tentative plan to create a new space for stuff like that which @willingc and @lheagy have been thinking about!

**Comment by dsblank** [comment]
@willingc and @lheagy : what have you been thinking about related to this issue? Would love to help to get something moving!

**Comment by jhamrick** [comment]
Oh, I hadn't realized https://github.com/jupyter4edu/ideas/pull/9 happened! Cool. I will remove the third party docs then and replace with a link to that page.
