### ISSUE TITLE
Global tasks

### ISSUE THREAD

**Issue by danielmaitre** [jupyter/nbgrader#977]
Hi all,

I've used nbgrader last year and I plan to use it more in the future. One functionality I am missing is what I will call "tasks", they would be exercises/objectives that span multiple cells. For example the task "Illustrate this aspect of the course with a plot!" would probably require students to create a plot in a code cell and comment on it in a markdown cell. Other tasks might involve multiple code/markdown cells. I think it would be beneficial because students could use more of the notebook features to organise an answer rather than being limited to filling specific parts of single cells. Another possibility is to have global grades for an entire notebook, for example for using good coding practices or awarding points for well structured narrative in the notebook. 

I think it is hard to achieve with what is currently available in nbgrader (if I'm wrong that would be great!) and I'm willing to have a go at implementing it, but before I do I might need some guidance. 

I'm thinking of implementing a new type of cells, task_cell that would be manually graded and could be commented on during the manual marking. It looks like there would be quite a lot of changes to do and before I try to implement it I wanted to make sure that it is a feature that others would find useful and that could be incorporated in nbgrader.

**Comment by jhamrick** [comment]
> One functionality I am missing is what I will call "tasks", they would be exercises/objectives that span multiple cells.

There's nothing technically preventing this from being done in nbgrader---students can certainly provide code/comments in other cells beyond the cell which has the grade in it. I suppose there is a drawback here which is that then you can't provide comments during the feedback phase on other cells, though. But you could get around that too by having those cells be marked as graded but be worth zero points, something like this:

![image](https://user-images.githubusercontent.com/83444/41191427-3ebe0a70-6be7-11e8-87a3-8aa34d2aab38.png)

> have global grades for an entire notebook, for example for using good coding practices or awarding points for well structured narrative in the notebook.

I think that's a reasonable suggestion, though it would require a lot of nontrivial UI changes 🙁

> I'm thinking of implementing a new type of cells, task_cell that would be manually graded and could be commented on during the manual marking.

Can you elaborate a little further about how task_cell would work beyond regular manually graded cells?

**Comment by danielmaitre** [comment]
Thank you for the comment!  I realise that this would introduce quite a bit of changes, that's why I'm asking if it is of interest before trying to implement it.

Thank you for the suggestion with the manually graded cell with 0 points suggestion, I might use it in the interim. The drawback is that I would need to decide on how many cells the students would need while I'd rather them develop their own notebook style. 

The way I was envisaging the task_cell was another option in the create_assignment dropdown, here called "Manually graded task",  
![image](https://user-images.githubusercontent.com/17708761/41198644-9a7a200e-6c7a-11e8-8177-5f8c7677ebd7.png)
that cell would be markdown and read-only (unlike the manually graded cells that can -and must- be edited). I've added some styling to make the tasks easily identifiable by the students. 

The assign stage would leave it untouched (unlike the manually graded cells that are replaced by "Your answer here" ).
![image](https://user-images.githubusercontent.com/17708761/41198734-83f08236-6c7c-11e8-89c9-ec6c725f7c8b.png)

In the grading stage that cell would be unaffected but it can be graded and there could be comments. 

![image](https://user-images.githubusercontent.com/17708761/41198638-67967fd4-6c7a-11e8-8864-8bbd1464f631.png)

The screenshot doesn't have the comment box yet...

**Comment by danielmaitre** [comment]
Hi, 
I have worked some more on this feature and I think it is mostly complete (there is a few tests that fail that I need to look into). The code is at 

https://github.com/danielmaitre/nbgrader

I'd like to it to be considered for inclusion in nbgrader, should I do a pull request?
