### ISSUE TITLE
Students able to access others' submissions?

### ISSUE THREAD

**Issue by liffiton** [jupyter/nbgrader#978]
### Operating system
Linux (CentOS 6)

### `nbgrader --version`
`nbgrader version 0.5.4`

### `jupyterhub --version` (if used with JupyterHub)
`0.8.1`

### `jupyter notebook --version` 
`5.5.0`

### Issue

I'm just starting to explore nbgrader, so I may be missing an important detail, but in my testing it looks like a student could access another's submissions.  Submissions appear to be created in `coursedir/inbound` in a directory with a standard name: `USER+ASSIGNMENT+TIMESTAMP`.  The permissions on `inbound` are set such that users other than the creator (whoever runs formgrader, I believe?) cannot list its contents.  However, the permissions of the submission directories are world-readable and -writable.  Given the standard format for submission directory names, couldn't anyone write a simple script or program to search for valid directory names and access whatever submission directories they find?

Now, this isn't a huge issue, because the inclusion of microseconds makes for a fairly large search space.  But on my system, a simple Python program can search a range of one second (one million different directory names) in about six seconds.  If one student knows another has just submitted something (if they work in a shared lab, say), then it wouldn't be too hard to search through a range of a few minutes to find it.  Then they could read and/or alter the other student's work.

(Then there's the fact that if a student figures all of this out and implements it well, they're probably doing fine in the course anyway.  I'm mostly just opening the issue to check my understanding.)

If this is an accurate description of the issue, then I think a simple fix would be to add a random string to each submission directory name.

**Comment by jhamrick** [comment]
Yes, I just tested it and this is in fact correct. This problem will be alleviated when we switch to HubShare (see #659 ) but I think for now it's a reasonable workaround to add a random string to the submission names.

**Comment by rgerkin** [comment]
@jhamrick To have even this level of security, the inbound directory should have 773 permissions (no regular users listing files; submissions that need to be shown in the assignments tab can be read from the database) and the outbound should have 775 (regular users shouldn't be writing random new assignments).  Is that right?

**Comment by rkdarst** [comment]
Exactly.  It should done automatically if nbgrader creates the exchange dirs.  (But it also makes it 733 and 755 by default I think, assuming groups are not for instructors).

**Comment by jhamrick** [comment]
Yes, exactly--and this is indeed something that's set by nbgrader automatically.
