### ISSUE TITLE
Command-line autograde assignments don't appear in formgrade web app

### ISSUE THREAD

**Issue by magsol** [jupyter/nbgrader#979]
I've been using nbgrader + JupyterHub for an introductory course the past couple of years, and in that time both platforms have seen extensive and backwards-incompatible architectural changes; I think I've stumbled upon another one.

Over the past few days, I've gone through the process of releasing, collecting, and autograding my first assignment, all via the command line:

```
nbgrader release A1
nbgrader collect A1
nbgrader autograde A1
```

However, when I click the "Formgrader" tab, I don't see any assignments listed. Furthermore, none of my students appear there, either (I manually entered both them and the assignments into the `nbgrader_config.py` file at the start of the course). I feel like I may have missed a step in the configuration process.

### Operating system

Ubuntu 16.04

### `nbgrader --version`

0.5.4

### `jupyterhub --version` (if used with JupyterHub)

0.8.1

### `jupyter notebook --version` 

5.5.0

### Expected behavior

I'd expected to see the assignments (at least the autograded one, after running the aforementioned sequence of command-line options) listed in the formgrader web app.

### Actual behavior

No assignments (or students) are listed.

### Steps to reproduce the behavior

The `nbgrader` commands I listed out before were not done seconds after the other; the assignment was released last week, and I just collected and autograded them this morning (via command-line). Then, intent on fixing some grades manually, I went to the Formgrader tab and discovered it was empty.

**Comment by magsol** [comment]
So I seem to have an idea of what's going on--

In testing something else, I used the formgrader app to stub out a skeleton assignment, and in clicking it (and getting a 404 error), I saw the URL that it was trying to reference: I realized the formgrader seemed to be looking in my user's _home directory_, rather than the _course directory_.

Using that bit of information, I `cp -r`'d over the `source`, `release`, `submitted`, and `autograded` directories from the course directory over to the home directory, and automagically the formgrader app now fully populates everything.

To amend my original question, then: why am I having this disparity? I can't find a reason in either the nbgrader or JupyterHub configs (I assume it has to be somewhere in nbgrader, but I checked JupyterHub anyway because I gave up on the former). Would love some help, thanks!

**Comment by magsol** [comment]
Ok, definitely still missing information beyond just copying directories over--likely stuff that should be in the `gradebook.db`. Manual grading doesn't show anything when I click on a specific notebook file for a given assignment ("No data available in table"), and under Manage Students, none of them show as having submitted anything. What am I missing?

**Comment by magsol** [comment]
Ensuring the root directory was specified in the config was my first thought, but it didn't seem to have any effect, unless the config file just wasn't in the right place. If this was the case, the behavior would be consistent with what was effectively two separate independent instances of nbgrader (one command-line, one through the formgrader).

None of the results from `jupyter --paths` under the config option specify a path where I have an nbgrader_config.py file. However, I'm unsure how I would verify the directory where, as you said, notebook servers are "launched", i.e. the "current directory" you specified. I have a config file in the main course directory, and that's where the root option points, but how can I check that's also where the notebooks are launched?

In the meantime, I've _somehow_ fixed things. I _think_ it was because I went ahead and copied over the `gradebook.db` file to the home user directory (that the formgrader seemed to want to point to), then suddenly it seemed aware of the main course directory. I could even delete all the course-specific folders I mentioned hard-copying over from the course directory to the home user directory, as well as the `gradebook.db` file itself (the one I'd copied), and the formgrader is still clearly pointing to the right course folder.

I'll need to try and replicate this behavior later.

**Comment by hkarl** [comment]
Seems related: https://github.com/jupyter/nbgrader/issues/578 (last comment tries to update)

**Comment by magsol** [comment]
It's possible.

I can go ahead and close this issue for now, as I don't seem to be encountering this behavior anymore. I started teaching a new class this fall and did not encounter any problems with the assignment listings. That said, it seems unlikely that this problem magically disappeared; I have not updated nbgrader since before these problems started happening, so I'll need to go back and try to replicate them later.

**Comment by ttimbers** [comment]
> In the meantime, I've somehow fixed things. I think it was because I went ahead and copied over the gradebook.db file to the home user directory (that the formgrader seemed to want to point to), then suddenly it seemed aware of the main course directory. I could even delete all the course-specific folders I mentioned hard-copying over from the course directory to the home user directory, as well as the gradebook.db file itself (the one I'd copied), and the formgrader is still clearly pointing to the right course folder.

> I'll need to try and replicate this behavior later.

I can confirm that I just replicated a similar behaviour. On my laptop, `gradebook.db` needs to be in the root of the nbgrader directory (that has `source`, `release`, etc) but on the JupyterHub server, it needs to be one directory above that...
