### ISSUE TITLE
Using the REST API outside the nbgrader webapp

### ISSUE THREAD

**Issue by sondr3** [jupyter/nbgrader#992]
Hello, I'm currently in the process of evaluating nbgrader and JupyterHub for a course at our university and we want to implement some extra functionality on top of nbgrader but as a separate webapp. Thus I went looking for an API and though it's only mentioned in the documentation that there's a Python API I managed to find the commit where nbgrader was turned into a webapp and from there managed to figure out how to talk to the REST API! Even though it's not actually documented it's actually really easy to use 😃 

However, authentication is a bit of a pain since it uses a cooke and a XSRF token, so currently for testing I'm having to do something like this to access a specific student:

```python
import requests
import json
import jsonpickle

api_url = 'http://localhost:8888/formgrader/api'
xsrf = '[...]'
cookie = '[...]'

r = requests.get(f'{api_url}/students',
                headers = {
                    'X-CSRFToken': xsrf,
                    'Cookie': cookie
                })

r.raise_for_status()
students = r.json()
```

I was wondering whether I've overlooked a better way to authenticate via the REST API? The JupyterHub API is really simple since the only authentication required is a token generated on the website, but from looking at the code I can't really see any authentication method besides using the above.

Hope this was easy enough to understand and thanks for the project(s)! They are super useful and saved us a _TON_ of time since we didn't have to write something like this on our own.

**Comment by jhamrick** [comment]
Hmm, I have not tried before to use the nbgrader REST API from a separate application, so I'm not 100% sure. nbgrader itself doesn't handle any authentication---any auth that is required comes either from the notebook server or from JupyterHub. For example, if I run the notebook server (`--NotebookApp.token=''`, not recommended!) then it is totally fine for me to just to do the GET request without authentication.

I would *think* if you're using nbgrader with JupyterHub, then you would be able to send an authorization token as described here: https://jupyterhub.readthedocs.io/en/stable/reference/rest.html but I haven't tried it.

If you're using nbgrader with just a regular notebook server, then you can pass along the token that's automatically generated when you start the server, like `requests.get("http://localhost:8889/formgrader/api/assignments?token={}".format(token))`

I'm not sure if that helps, but let me know if you have further questions!

**Comment by sondr3** [comment]
This was for a trial run of an application we were developing but we ended up using the Python API directly instead, but thanks for taking your time to respond.
