### ISSUE TITLE
nbgrader feedback question

### ISSUE THREAD

**Issue by kxiluri** [jupyter/nbgrader#996]
### Operating system
Ubuntu 16.04.4

### `nbgrader --version`
0.5.3
### `jupyterhub --version` (if used with JupyterHub)
0.7.2
### `jupyter notebook --version` 
5.0.0
### Expected behavior
nbgrader feedback "hwk1" creates under the course directory the feedback directory
### Actual behavior
indeed this happens however, i am not sure how the students can view the generated .html files
### Steps to reproduce the behavior
If memory serves me right, in the previous version of nbgrader i would run nbgrader feedback and then give port 5000 and the students would view the feedback there, however, it is not clear to me now what do i have to do for the students to see the feedback directory

**Comment by maryamdev** [comment]
Hello! Please check this: [https://github.com/jupyter/nbgrader/issues/987](https://github.com/jupyter/nbgrader/issues/987)

**Comment by sigurdurb** [comment]
What LMS system are you using @kxiluri ?
I developed a python script that sends nbgrader grades and feedback to CanvasLMS if you need but it has to have the mapping to the canvas login_id's to the student.id in gradebook.students

**Comment by jhamrick** [comment]
Indeed, as the issue @maryamdev linked to explains there is currently not functionality within nbgrader to *return* feedback (and there never has been, unfortunately).

I am going to close this as a duplicate.
