### ISSUE TITLE
A way to specify logfile or disable it

### ISSUE THREAD

**Issue by destitutus** [jupyter/nbgrader#997]
`nbgrader autograde` command, help commandline

```
--NbGrader.logfile=<Unicode>
    Default: '.nbgrader.log'
    Name of the logfile to log to.
```

```
--AutogradeApp.logfile=<Unicode>
    Default: '.nbgrader.log'
    Name of the logfile to log to.
```

according to help it should be something like `nbgrader autograde ps1 --student=student --force --AutogradeApp.logfile=.autograde.nbgrader.log --NbGrader.logfile=.autograde.nbgrader.log`

### Operating system

Ubunbu 14.04

### `nbgrader --version`

Python version 3.4.3 (default, Nov 28 2017, 16:41:13)
[GCC 4.8.4]
nbgrader version 0.5.4

### Expected behavior

`.autograde.nbgrader.log` created instead of `.nbgrader.log`

### Actual behavior

`.nbgrader.log` was created

### Steps to reproduce the behavior

run something like `nbgrader autograde ps1 --student=student --force --AutogradeApp.logfile=.autograde.nbgrader.log --NbGrader.logfile=.autograde.nbgrader.log`

**Comment by jhamrick** [comment]
Confirmed, setting the `NbGrader.logfile` config value doesn't seem to change the logfile that's used.

**Comment by rmjarvis** [comment]
+1 to requesting a fix for this.  

I'm finding it annoying that Jupyter keeps dropping these .nbgrader.log files everywhere I open a Jupyter session.  I tried setting `c.NbGrader.logfile` to a location in my root directory in `.jupyter/nbgrader_config.py`, but it doesn't work.

Even better would be to have an option to turn off nbgrader logging entirely if that's also on the table.

**Comment by jhamrick** [comment]
Yes, I agree it would be nice to additionally have a way to detect whether nbgrader itself is actually being used, and only create a logfile if it's actually necessary (though it's not obvious to me how to do this, unfortunately).

I think the best options in the near term are:

1. Have nbgrader by default log only to a single location (e.g. `~/Library/Jupyter/nbgrader.log`) so it doesn't by default create lots of different files.
2. Make sure the log path is actually configurable.

I'll try to get to both of these things soon.
