### ISSUE TITLE
Support for one instructor in charge of multiple courses

### ISSUE THREAD

**Issue by FranLucchini** [jupyter/nbgrader#998]
Hello, 

Recently our team started to use Nbgrader with JupyterHub. We are thinking of a future case where a single teacher or instructor will be in charge of multiple courses and we can't find a way of having one single account across all the courses, so the teacher can manage all assignments without having to use multiple accounts.

For example, we have two mock courses, course1 and course2, and we have instructor1 that manages both of them. We followed this information: [Example Use Case: One Class, Multiple Graders](https://nbgrader.readthedocs.io/en/latest/configuration/jupyterhub_config.html?highlight=multiple#example-use-case-multiple-classes) and we came to the conclusion that for the instructor to able to manage both courses the only way was to manually edit `nbgrader_config.py` located in his home directory. We edit: 

```python
c.Exchange.course_id = "course1"
c.CourseDirectory.root = '/JupyterHub/grader-course1/course1'
```
And we change course1 for course2. 

Is there a smarter way to do this? We could collaborate to make this feature if necessary :)

### Operating system 
Ubuntu 18.04

### `nbgrader --version`
```
Python version 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0]
nbgrader version 0.5.4
```

### `jupyterhub --version` (if used with JupyterHub)
0.8.1

### `jupyter notebook --version` 
5.5.0

**Comment by jhamrick** [comment]
I think what you're describing is possible if you follow the instructions for "Multiple Classes" on the page you linked to---you do need to create multiple JupyterHub services (one per class) but you should be able to access those services from the same user account assuming that account is listed under `c.JupyterHub.load_groups`. Or perhaps I am not quite understanding your use case?

**Comment by perllaghu** [comment]
There is a definite use-case here:
Jupyter Notebooks are provided as a central service, thus multiple classes/courses use a single instance (as opposed to a new instance is spun up for each course)

In this model, authentication is often provided via an LTI connection, and the role of the user is defined in an LTI parameter. In such a situation, it is inevitable that one `userid` will be an instructor for multiple courses.

This applies irrespective of the central service being supplied by the Department of Artificial Intelligent, the Faculty of Information Technology, the School of Hard Sciences, or the whole Institution.

"One Instructor, One Course" really only works if there's actually "One Jupyterhub, One Course"

**Comment by jhamrick** [comment]
For the "Multiple Classes" instructions I mentioned it is a single instance of JupyterHub (not one per course), but that JupyterHub instance runs multiple *services* of nbgrader (one per course). Multiple instructors for the same course just need to be mapped to the relevant nbgrader services in the `jupyterhub_config.py`.

This isn't really a nbgrader thing; it's purely done through JupyterHub: nbgrader is just a particular type of service that can be run through JupyterHub. Which users are allowed to access a particular instance of nbgrader is determined through the JupyterHub configuration.

**Comment by rkdarst** [comment]
I'm not doing exactly what you are trying, but it is related.   I think our view are similar because we both see users as the primary objects, not the hub or hub services. (for different reasons, I don't like the idea of a hub service running outside the control of any particular actual user account).  I solved the problem by having server spawn options for different courses, and then the `pre_spawn_hook` will mount a different `/course` directory depending on what is started.  This is sort of similar to @perllaghu's comment in #960 (https://github.com/jupyter/nbgrader/issues/960#issuecomment-427749776).

My use cases are described here:
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/174#issuecomment-410235452
https://github.com/jupyter/nbgrader/pull/1000#issuecomment-427664752

Related issues asking for similar things: #960, #961 maybe, maybe more.

It seems like a lot of us are thinking outside the previous vision and we could work together on these...

**Comment by sgvasquez** [comment]
Hello! I'm working with @FranLucchini with JHub and Nbgrader. The case we are currently working on is when a grader wants to create, release and collect assignments for two (or more) different courses he/she is in charge of. Currently in the Formgrader tab we are able to do actions on assignments on only one course, the one that is currently defined in nbgrader_config.py, inside the grader's home directory.

We'd like to make it so a grader can chose which course he/she can act on, preferable via browser, and that's what we are failing to see right now.

Is there any configuration we are misreading, or perhaps there is another option we have to enable?

Also, in the _Example Use Case: Multiple Classes_ it's specified that we need to write in the config file a root variable that points to the directory in where the course can be found. How do we do when we want to specify different paths for different courses?

Thanks a lot!

**Comment by jhamrick** [comment]
It sounds like there is a lot of interest in having the formgrader support multiple classes, so perhaps it is worth considering adding this feature---though it will be a substantial amount of work, as all of nbgrader's machinery currently makes a strong assumption that the course directory manages exactly one course. I unfortunately don't have the bandwidth at the moment to implement something like that, though if someone wants to try to take a stab at it I can give pointers 🙂 

In the meantime @sgvasquez there isn't a way to have the *same* formgrader work with multiple classes, though as described in the docs you mentioned you can run multiple formgraders (one per class) which the same instructor has access to. That instructor can access the formgrader for a particular class at the url `/services/<service-name>`, such as `/services/formgrader-course101` or `/services/formgrader-course123`.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyter-nbgrader-hackathon-topics/1040/1
